### ISSUE TITLE
Failing to parse nested structs (BigQuery)

### ISSUE THREAD

**Issue by defonzie** [sqlfluff/sqlfluff#1004]
## Expected Behaviour

No parsing errors for `SELECT STRUCT(STRUCT(1 AS b) AS a) AS foo` with BigQuery dialect. Using `STRUCT` inside of a function call also fails (e.g. `SELECT ARRAY_AGG(STRUCT(a AS a, b AS b)) FROM foo`).

## Observed Behaviour

`Found unparsable section: ' AS b'`

## Steps to Reproduce

http://sqlfluff-online.herokuapp.com/fluffed?sql=H4sIANTthmAC_wt29XF1DlEIDgkKdQ7RgFKGCo7BCkmaIDIRTKbl5_NyAQBx15-eKwAAAA%3D%3D&dialect=bigquery

## Version
0.5.2

## Configuration
```
dialect = bigquery
```

**Comment by barrywhart** [comment]
Just a thought... this seems similar to the `CAST()` function in SQL, which also uses `AS` syntax inside what otherwise resembles a normal function call.

https://cloud.google.com/bigquery/docs/reference/standard-sql/conversion_functions#cast

**Comment by defonzie** [comment]
I think this could be solved by allowing `TypelessStructSegment`  in the `FunctionContentsExpressionGrammar` as well as in the innermost `Sequence` of the `TypelessStructSegment` itself.

**Comment by barrywhart** [comment]
@defonzie: It sounds like you have looked at the dialect -- that's great! Do you think you might be interested in working on this issue?
