### ISSUE TITLE
Add support for files without an extension

### ISSUE THREAD

**Issue by yxslx** [sqlfluff/sqlfluff#1010]
Would it be possible to support files with no extension, looking through the config it seems you have to specify a list of file extensions to be linted.

**Comment by adam-tokarski** [comment]
@yxslx 
How should it work? With dedicated option or just include all files without extension but still ignoring these with existing but not matched one?
So for case with files `test.sql, test.ddl, test, test.xxx, test2.sql` it would process `test.sql, test.ddl, test, test2.sql`?

**Comment by alanmcruickshank** [comment]
I'm going to close this issue as stale. I've had a think through how this would be implemented and I don't think there's a good route without adding some potentially confusing complexity. If anyone has any good ideas on a good implementation of this - feel free to re-open with suggestions.
