### ISSUE TITLE
The Big Segment Refactor ™

### ISSUE THREAD

**Issue by alanmcruickshank** [sqlfluff/sqlfluff#1019]
This combines #897 & #1014.

Following from discussion betweem @barrywhart and @alanmcruickshank - this supports #642.

This tracks a big refactor which simplifies a chunk of the parser codebase. The following steps need to happen:
1. Refactor Lexer Configs so that Segments are only generated at the last minute, next to where position markers are enriched.
2. Refactor Position markers (and resolve #897) so that markers always have knowledge of source and template. Templated files are always generated, even if a string is passed to `.lex()`.
3. Fully implement segment factories and remove the `.make()` method used to dynamically create segments. Review `BaseSegment.is_type()` to make sure it still works with that in mind.

**Comment by pwildenhain** [comment]
Just have to say, I love the name of this issue 🤣

**Comment by barrywhart** [comment]
@alanmcruickshank: Can this one be closed now? Great work, BTW!

**Comment by alanmcruickshank** [comment]
Yep. I'm going to declare this done 👍 . You should be all good for the parallel work now.

**Comment by NiallRees** [comment]
💰💰💰
