### ISSUE TITLE
Add a little fun when the CLI passes?

### ISSUE THREAD

**Issue by nolanbconaway** [sqlfluff/sqlfluff#1043]
Black does this, and I like it a lot!

![image](https://user-images.githubusercontent.com/1770896/118029495-37276f00-b332-11eb-936d-84c2c72aaf2b.png)

Any reason we oughn't inject a little fun when the CLI passes?

**Comment by barrywhart** [comment]
Great idea! What characters should we use? I was trying to find a dandelion because fluff. 

One of these may work:
❃ ✾ ❁ ❊

We'd need other characters, too. Let's do this!!

**Comment by nolanbconaway** [comment]
Are emojis available? 🌷 🌹 🌷 🌹

**Comment by barrywhart** [comment]
I think anything that's available as a Unicode character is doable. So it's not completely open (I.e. arbitrary pictures), but there are lots of choices. Maybe around 4,000? (Don't ask how I know this!!)

**Comment by alanmcruickshank** [comment]
I think this site is great for browsing emojis: https://www.emojicopy.com/

My suggestions would be:
- sparkler: 🎇
- party popper: 🎉
- magic wand: 🪄 (seems poorly supported)
- cyclone: 🌀
- bright button: 🔆
- roll of paper: 🧻
- scroll: 📜
- soap: 🧼
- razor: 🪒
- sponge: 🧽

so far I think my favourites are [soap](https://emojipedia.org/soap/) and [scroll](https://emojipedia.org/scroll/) which seem to have reasonable cross platform support.

**Comment by barrywhart** [comment]
Also:
🛁 🚿 🧴 🪥  🪠

The plunger is probably off topic, but really makes me laugh. 🤣

**Comment by paigeb** [comment]
This discussion makes me think about proposing the addition of a “lint roller” emoji to Unicode, like [a colleague of mine did for yarn and thread](https://amberley.dev/blog/2020-09-16-how-do-new-emoji-happen/) 🧶🧵!

**Comment by nolanbconaway** [comment]
I'm using my ubuntu machine right now, and I think the platform support should definitely be considered 
![image](https://user-images.githubusercontent.com/1770896/118339311-7696bc80-b4e6-11eb-9f44-e76a2a12df7e.png)
