### ISSUE TITLE
Starting in 0.5.4, parser is apparently not setting the "type" field on identifier segments correctly

### ISSUE THREAD

**Issue by barrywhart** [sqlfluff/sqlfluff#1049]
-- If this is a parsing or linting issue, please include a minimal SQL example which reproduces the issue, along with the `sqlfluff parse` output, `sqlfluff lint` output and `sqlfluff fix` output when relevant. Finally, please add any labels that are related to the issue before submitting so that it can be addressed easily! --

## Expected Behaviour

No exceptions thrown during `sqlfluff fix`.

## Observed Behaviour

Many exceptions thrown, similar to this:
```
CRITICAL   [L020] Applying rule L020 threw an Exception: 'NoneType' object has no attribute 'raw' 
Traceback (most recent call last):
  File "/Users/bhart/dev/sqlfluff/src/sqlfluff/core/rules/base.py", line 309, in crawl
    templated_file=templated_file,
  File "/Users/bhart/dev/sqlfluff/src/sqlfluff/rules/L020.py", line 54, in _eval
    select_info = get_select_statement_info(segment, dialect)
  File "/Users/bhart/dev/sqlfluff/src/sqlfluff/core/rules/analysis/select.py", line 27, in get_select_statement_info
    segment, dialect
  File "/Users/bhart/dev/sqlfluff/src/sqlfluff/core/rules/analysis/select.py", line 116, in get_aliases_from_select
    aliases = fc.get_eventual_aliases()
  File "/Users/bhart/dev/sqlfluff/src/sqlfluff/dialects/dialect_ansi.py", line 1225, in get_eventual_aliases
    ref: AliasInfo = clause.get_eventual_alias()
  File "/Users/bhart/dev/sqlfluff/src/sqlfluff/dialects/dialect_ansi.py", line 929, in get_eventual_alias
    return AliasInfo(segment.raw, segment, True, self, alias_expression, ref)
```

## Steps to Reproduce

Follow the repro steps provided in #1024.

## Version
Include the output of `sqlfluff --version` along with your Python version

SQLFluff 0.5.5
Python 3.7.3

## Configuration
None

**Comment by barrywhart** [comment]
I think this is related to the recent parser refactoring, as the problem does not occur in 0.5.3. and earlier. I did some investigation and found that, at the point when the rules are called, some identifier segments have type `raw` rather than type `identifier`.

Below is debug output from the `get_eventual_alias()` function in `dialect_ansi.py`:

Latest release (0.5.5):
```
(Pdb) alias_expression.segments
(<KeywordSegment: ([L: 22, P: 29]) 'AS'>, <WhitespaceSegment: ([L: 22, P: 29]) ' '>, <CodeSegment: ([L: 22, P: 29]) 'tx'>)
(Pdb) [s.type for s in alias_expression.segments]
['keyword', 'whitespace', 'raw']
```

Version 0.5.3:
```
(Pdb) alias_expression.segments
(<AS_KeywordSegment: ([426](1, 22, 27)) 'AS'>, <whitespace_RawSegment: ([428](1, 22, 29)) ' '>, <naked_identifier_ReSegment: ([429](1, 22, 30)) 'tx'>)
(Pdb) [s.type for s in alias_expression.segments]
['keyword', 'whitespace', 'identifier']
```

Note the `'tx` segment has type `raw`. Interestingly, the output from `sqlfluff parse` looks correct:
* `tx` is listed as `identifier`
* The overall parse tree is identical between 0.5.3 and 0.5.5. (I used the command `sed 's/^.\{21\}//'` to remove the row/column number info, leaving just the YAML parse tree so I could compare the two with `diff`.)

**Comment by barrywhart** [comment]
@alanmcruickshank: Can you take a look at this? I did some triage, but I didn't know where in the lexer/parser the segment types are set, so debugging progress was pretty slow.

**Comment by alanmcruickshank** [comment]
The replacement of dynamic types means we should never _read_ `segment.type` anymore because it won't take into account the custom type. We should always use `segment.is_type()`.

**Comment by alanmcruickshank** [comment]
Confirmed that this is an issue. Working on it now.

**Comment by alanmcruickshank** [comment]
found the issue. Fix will be live soon.
