### ISSUE TITLE
In 0.5.6, setting `indented_joins` to `True` breaks parsing of table aliases

### ISSUE THREAD

**Issue by pwildenhain** [sqlfluff/sqlfluff#1068]
-- If this is a parsing or linting issue, please include a minimal SQL example which reproduces the issue, along with the `sqlfluff parse` output, `sqlfluff lint` output and `sqlfluff fix` output when relevant. Finally, please add any labels that are related to the issue before submitting so that it can be addressed easily! --

## Steps to Reproduce

`test.sql`
```sql
select
    field_1
from my_table as alias_1
```

```
$ sqlfluff lint test.sql
== [test.sql] FAIL
L:   3 | P:   1 |  PRS | Found unparsable section: 'from my_table as alias_1'
```

## Version
Include the output of `sqlfluff --version` along with your Python version
`sqlfluff, version 0.5.6`
## Configuration
```
[sqlfluff]
# Need to ignore templating until we can use the dbt templater
ignore = templating
exclude_rules = L003,L004,L046,L013,L022,L027,L031,L033,L034,L035,L036,L037,L039

[sqlfluff:templater:jinja:context]
target = 'dev'

[sqlfluff:indentation]
indented_joins = True

[sqlfluff:rules]
max_line_length = 115

[sqlfluff:rules:L010]
capitalisation_policy = lower

```

**Comment by barrywhart** [comment]
Fascinating bug! I did some tinkering to try and narrow down the issue. This setting in `.sqlfluff` is the key: if you remove this, the error does not occur:
```
[sqlfluff:indentation]
indented_joins = True
```

@alanmcruickshank: Could this be related to the big segment refactoring? I know that it involved some deep changes to the `Indent` and `Dedent` segments.

**Comment by alanmcruickshank** [comment]
I'll take a look - I think you're intuition is probably right.

**Comment by alanmcruickshank** [comment]
Oh man 🤦 . It's a stupid typo. PR coming shortly, just working out how to get a test case around it.
