### ISSUE TITLE
Get max line length down to 127

### ISSUE THREAD

**Issue by alanmcruickshank** [sqlfluff/sqlfluff#1076]
Triggered by #1072 

> psf/black's 88 chars per line is more modern than PEP8's meager 79.
> A personal favorite is 127 which allows reading code on GitHub's file viewer without requiring left/right scrolling.

To get us down to flake8 linting having a max line length of 127, I believe we only need to change ~17 lines. This would enable the codebase to be much more readable in side by side editors and in web consoles.

This would also be a great issue for new contributors.
- update the `max-line-length` in `tox.ini`.
- edit the offending lines so that all the tests and linting passes.

**Comment by dflss** [comment]
Hi all! If nobody else is working on it, I would be happy to give it a try :smiley:

**Comment by NiallRees** [comment]
Go for it @dflss !
