### ISSUE TITLE
PostgreSQL support for "WITH RECURSIVE" 

### ISSUE THREAD

**Issue by jdsada30** [sqlfluff/sqlfluff#1087]
-- If this is a parsing or linting issue, please include a minimal SQL example which reproduces the issue, along with the `sqlfluff parse` output, `sqlfluff lint` output and `sqlfluff fix` output when relevant. Finally, please add any labels that are related to the issue before submitting so that it can be addressed easily! --

## Expected Behaviour
I would expect statements with RECURSIVE modifier to be parsed by sqlfluff, as they are supported by PostgreSQL. 

## Observed Behaviour
> == [test.sql] FAIL
L:   1 | P:   1 |  PRS | Found unparsable section: 'WITH RECURSIVE t(n) AS (\n
                       | VALUES (1)\n...'
## Steps to Reproduce
Create a sql file with the following query:
>WITH RECURSIVE t(n) AS (
    VALUES (1)
  UNION ALL
    SELECT n+1 FROM t WHERE n < 100
)
SELECT sum(n) FROM t;

Lint the file with the following command(s) :
>sqlfluff lint test.sql --dialect postgres or sqlfluff lint test.sql
## Version
I am using sqlfluff version 0.5.6 and python version 3.8.5. 

This example comes from  the official [PostgreSQL documentation](https://www.postgresql.org/docs/9.1/queries-with.html). I found similar results when executing queries from Github Project [vertx-jooq](https://github.com/jklingsporn/vertx-jooq).

**Comment by bolajiwahab** [comment]
Fix by PR https://github.com/sqlfluff/sqlfluff/pull/1102

**Comment by bolajiwahab** [comment]
@jdsada30 Can you help close this issue since the fixing PR has been merged?
