### ISSUE TITLE
Add a (non-blocking) changelog change check for PR CI

### ISSUE THREAD

**Issue by nolanbconaway** [sqlfluff/sqlfluff#1094]
I always forget to update the changelog when i merge a PR, it's just easy to forget! We can help ourselves remember by adding a CI check that the changelog is in the changed files for each PR. There are very reasonable cases in which a changelog entry is not needed, so this would be an optional/non-blocking check that serves as a reminder.

LMK if you hate this idea!

**Comment by NiallRees** [comment]
I like!
