### ISSUE TITLE
Provide an opinionated .sqlfluff config

### ISSUE THREAD

**Issue by noel** [sqlfluff/sqlfluff#1116]
When starting out, users need a config that they can use.  Today's config file in the docs leans more to giving people options, but this can lead to checks that lead to inconsistencies between developers.

Example:
``` 
[sqlfluff:rules:L010]  # Keywords
capitalisation_policy = consistent
```

If used as defined, an organization could end up with one developer who prefers upper and another that prefers lower thus having inconsistency in the codebase.

I propose creating an opinionated config file where the above would instead be something like
```
[sqlfluff:rules:L010]  # Keywords
capitalisation_policy = upper
```

**Comment by noel** [comment]
Here's a starting point
[.sqlfluff config](https://gist.github.com/noel/6c590bf3654ca346bf2a97d5b81f4d8c)

**Comment by grippy** [comment]
👍  Maybe the cli could add a sub-command to walk you thru generating this config? Maybe it just asks the user to provide the `dialect` and `templater` options and then it spits out this opinionated config to the local directory.

**Comment by tunetheweb** [comment]
I’m going to close those. We have an opinionated config file. It may not be to everyone’s liking (that’s what opinionated means!) but I don’t think we should be maintaining both a “default” and a “this is what we really think you should be using”. It’s too confusing.

If we feel that strongly about some of the defaults we should change them as that is _the_ opinionated config file we provide.
