### ISSUE TITLE
weird "ValueError: Zero length string passed to ReSegment!?" error

### ISSUE THREAD

**Issue by Arshaku** [sqlfluff/sqlfluff#1124]
I have the following query with Jinja templating (actually my initial query was more complex, I just simplified it as much as possible for the bug report):

```
{% set some_condition %}TRUE{% endset %}

WITH cust AS
    (SELECT SNAPSHOT_DATE
    FROM DATAHUB.SNAPSHOT_DAILY
    WHERE {{some_condition}}
    )

SELECT DISTINCT cust.SNAPSHOT_DATE
FROM cust
```

and when running "sqlfluff lint ./addons.template.sql" it throws the following exception:
ValueError: Zero length string passed to ReSegment!?

The full stacktrace is attached:
[stacktrace.txt](https://github.com/sqlfluff/sqlfluff/files/6583612/stacktrace.txt)

## Observed Behaviour
What makes it very strange is that if I remove almost any of the parts of this query, it doesn't throw an exception anymore. 
For example, the following alternatives work just fine:

```
{% set some_condition %}TRUE{% endset %}

WITH cust AS
    (SELECT SNAPSHOT_DATE
    FROM DATAHUB.SNAPSHOT_DAILY
    )

SELECT DISTINCT cust.SNAPSHOT_DATE
FROM cust
```

```
{% set some_condition %}TRUE{% endset %}

WITH cust AS
    (SELECT SNAPSHOT_DATE
    FROM DATAHUB.SNAPSHOT_DAILY
    WHERE {{some_condition}}
    )
```

```
WITH cust AS
    (SELECT SNAPSHOT_DATE
    FROM DATAHUB.SNAPSHOT_DAILY
    WHERE {{some_condition}}
    )

SELECT DISTINCT cust.SNAPSHOT_DATE
FROM cust
```

```
{% set some_condition %}TRUE{% endset %}

WITH cust AS
    (SELECT SNAPSHOT_DATE
    FROM SNAPSHOT_DAILY
    WHERE {{some_condition}}
    )

SELECT DISTINCT cust.SNAPSHOT_DATE
FROM cust
```

## Version
sqlfluff, version 0.5.6
Python 3.8.8

## Configuration
I use the default configuration

**Comment by alanmcruickshank** [comment]
Very interesting bug - I'll pick this one up. The section of code which slices templated files has some heuristics in it which could behave strangely in some circumstances. This looks like a simple enough query that this shouldn't be one where that's an issue however - so something isn't working as planned.
