### ISSUE TITLE
Add Variable Creation and Setting to Bigquery Dialect

### ISSUE THREAD

**Issue by rileyrunnoe** [sqlfluff/sqlfluff#1127]
BigQuery now supports [scripting](https://cloud.google.com/bigquery/docs/reference/standard-sql/scripting) within its SQL.

Adding this functionality to segments will allow for the proper parsing of BigQuery procedural SQL.

(Note that these are different than User-Defined-Functions)

**Comment by rileyrunnoe** [comment]
Separating the `BEGIN` `END` scripting into a separate issue as it is used very similarly across dialects

**Comment by barrywhart** [comment]
@rileyrunnoe: Can this issue be closed? It looks like you have split it into multiple, separate issues.

**Comment by barrywhart** [comment]
Closing. Can reopen if this was a mistake.

**Comment by rileyrunnoe** [comment]
@barrywhart This wasn't split into another issue. This can be closed because this https://github.com/sqlfluff/sqlfluff/pull/1189 resolved the issue :)
