### ISSUE TITLE
L010 Error message is too generic

### ISSUE THREAD

**Issue by dmateusp** [sqlfluff/sqlfluff#1128]
The L010 rule on capitalisation of keywords always errors with `Inconsistent capitalisation of keywords.` which can be misleading if the configuration isn't `= consistent`

I think giving different error messages based on the configuration `["consistent", "upper", "lower", "capitalise"]` would be a lot more helpful.

This is probably a simple change that just requires a description being passed to https://github.com/sqlfluff/sqlfluff/blob/89aaab8f6724482e346e490e89b23776063ac19b/src/sqlfluff/rules/L010.py#L162

**Comment by zhongjiajie** [comment]
I volunteer to do this, could I?

**Comment by dmateusp** [comment]
for sure!! :)

**Comment by scrambldchannel** [comment]
I've been playing around with SQLFluff (thanks for the work so far!) 

I was curious about how rules work so took a look at this. Naively I can change the message given by passing a value for `description` to `LintResult` but couldn't really see an elegant way to dynamically do this in `_eval` such that it would work for the classes that inherit from L010 - i.e. I can pull something out of the `_target_elems` property but it seems like a bit of a hack. Is there are a more elegant way of doing this that I'm not seeing? I've opened a draft PR anyway so would welcome any feedback at your leisure.

Cheers
Alex

**Comment by dmateusp** [comment]
@scrambldchannel so I tried out your changes with the following file:

```sql
Select
    TruE As flag,
    col_a,
    my_fUNc() As teSt
From schema_a.table_a
```

and I'm getting the following output

```
== [lower.sql] FAIL
L:   2 | P:   5 | L010 | Keyword must be capitalised.
L:   2 | P:   5 | L040 | Null literal must be consistently upper case.
L:   4 | P:   5 | L030 | Function name must be consistently upper case.
L:   4 | P:  18 | L014 | Naked identifier must be consistently lower case.
All Finished 📜 🎉!
```

with my only config being `capitalisation_policy = capitalise`

so my understanding is that your PR already changes the behavior of the rules that inherit from L010 (L040, L030, L014) and the results are what would be expected. I think the PR just needs some updated tests and some new tests :)

Were you referring to something else I am not seeing?

**Comment by scrambldchannel** [comment]
Thanks Daniel, I can have a look at the tests. 

Looking at it again, I might need to think about the case where `pascal` is specified in the `cap_policy_opts` (but I need to look deeper into what this actually does)

**Comment by zhongjiajie** [comment]
Hi @scrambldchannel, are you still work on the PR https://github.com/sqlfluff/sqlfluff/pull/1173? I current have time to fix this issue
