### ISSUE TITLE
Add BEGIN and END Block Statements to ANSI Dialect

### ISSUE THREAD

**Issue by rileyrunnoe** [sqlfluff/sqlfluff#1169]
This issue grew out of [this issue](https://github.com/sqlfluff/sqlfluff/issues/1127) which was formerly add scripting to bigquery dialect. Due to the relevance of `BEGIN` and `END` across SQL dialects, I think it would be relevant to add these sort of block statements to the base dialect in order for other languages to inherit this functionality

- [PostgreSQL](https://www.postgresql.org/docs/9.1/plpgsql-structure.html) Documentation
- [MySQL](https://dev.mysql.com/doc/refman/8.0/en/begin-end.html)
- [BigQuery](https://cloud.google.com/bigquery/docs/reference/standard-sql/scripting#beginend)

I have been attempting to add this enhancement while developing for the above issue, but have been running into significant hurdles. The conversation around what would need to be implemented can be found on [this pr](https://github.com/sqlfluff/sqlfluff/pull/1163)

Namely, `BEGIN` and `END` will probably have difficulty behaving like a regular `StatementSegment` and may need their own sort of block functionality

**Comment by rileyrunnoe** [comment]
This is a related issue for mysql: https://github.com/sqlfluff/sqlfluff/issues/901

**Comment by alanmcruickshank** [comment]
I think this is now resolved, and as at writing `BEGIN` and `END` statements as supported in the `TransactionStatementSegment` in ansi.
