### ISSUE TITLE
Colored output doesn't play nicely with solarized dark theme

### ISSUE THREAD

**Issue by louis-vines** [sqlfluff/sqlfluff#1170]
I can't see the filenames on the output of sql fluff when using solarized dark theme

## Expected Behaviour
Output using dark terminal theme:
<img width="709" alt="image" src="https://user-images.githubusercontent.com/10738810/123290735-6ae8dd80-d509-11eb-8006-e91d7b27271b.png">

## Observed Behaviour
Output using solarized dark terminal theme:
<img width="721" alt="image" src="https://user-images.githubusercontent.com/10738810/123291073-b00d0f80-d509-11eb-888c-cf3bc89f1116.png">

## Steps to Reproduce
Run sqlfluff with solarized dark themed console

## Version
```
❯ sqlfluff --version
sqlfluff, version 0.6.0
```

## Configuration
Not applicable

**Comment by barrywhart** [comment]
Note that SQLFluff can't detect the color pallet of the terminal. We could consider adding a way to specify the colors (or color theme) you want. Note that the `--nocolor` option suppresses all colors from the output, so that's the best option for now.

**Comment by alanmcruickshank** [comment]
Given the suggestion above of using `--nocolor` and the lack of other developments on this issue. I'm going to close it as stale.
