### ISSUE TITLE
[teradata] qualify clause not parsing

### ISSUE THREAD

**Issue by eetu-h** [sqlfluff/sqlfluff#1184]
## Expected Behaviour

Teradata (and at least Snowflake) are supporting [qualify clause](https://docs.teradata.com/r/2_MC9vCtAJRlKle2Rpb0mA/1z5LI8ycTW55f53vLJ0WjQ) with ordered analytical functions. However sqlfluff is not parsing the qualify clause properly.

## Observed Behaviour

```
select
    id
    ,vlue
from mydb.mytable
qualify count(*) over (partition by id) > 1 
```
```
L:   4 | P:  39 |  PRS | Line 4, Position 35: Found unparsable section: '\nqualify count(*) over (partition by id...'
```

## Version

`sqlfluff, version 0.6.0`
`Python 3.8.8`

## Configuration
```
[sqlfluff]
dialect = teradata
templater = dbt
exclude_rules = L008,L009,L031,L034
output_line_length = 150

[sqlfluff:rules]
comma_style = leading
max_line_length = 150

[sqlfluff:indentation]
indented_joins = false
template_blocks_indent = false

[sqlfluff:rules:L003]
lint_templated_tokens = false

[sqlfluff:rules:L010]
capitalisation_policy = lower

[sqlfluff:rules:L014]
extended_capitalisation_policy = lower

[sqlfluff:rules:L030]
extended_capitalisation_policy = lower

[sqlfluff:rules:L040]
extended_capitalisation_policy = lower
```

**Comment by StijnZanders** [comment]
BigQuery has `QUALIFY` in Pre-GA as well (https://cloud.google.com/bigquery/docs/reference/standard-sql/query-syntax#qualify_clause), would be great if it could be added there as well
