### ISSUE TITLE
Jinja source alias instead of omitting it

### ISSUE THREAD

**Issue by tjirab** [sqlfluff/sqlfluff#1188]
### Current situation
Currently Jinja source aliases get purged. E.g. `{{ source('schema', 'table_x') }} as x` gets fixed as `{{ source('schema', 'table_x') }}`.

At the same time, column projections in the `SELECT` section get renamed from `table_x.column_1` to `database.schema.table_x.column_1` which actually breaks the SQL. So not sure if this should be labeled as bug or enhancement.
### Ideal situation
Ideally sqlfluff would accept table aliases defined by user or perhaps better use `table_x` (derived from Jinja `source()`) as table alias.

**Comment by barrywhart** [comment]
Can you please provide a test case for this to help us reproduce it?
* `.sql` file
* `.sqlfluff` file
* Expected result
* Actual result

**Comment by tunetheweb** [comment]
Yeah I can't repeat this. Fixing this:

```sql
SELECT
    1,
    {{ source('schema', 'table_x') }} as x
FROM
    table
```

Results in this - as expected:

```sql
SELECT
    1,
    {{ source('schema', 'table_x') }} AS x
FROM
    table
```

So need a full test case to investigate further.

**Comment by barrywhart** [comment]
I just closed a very similar (if not identical) issue earlier today. That one was from April. Are we fixing bugs without knowing about it? 😎

I'm pretty excited about the idea of fixing all the "corrupts SQL" bugs soon. 🤞🏽

**Comment by tunetheweb** [comment]
I'm using the "Awaiting Feedback" to periodically close old issues that we can't progress and where feedback was asked for and not supplied.

OP can reopen if they can supply us more details.
