### ISSUE TITLE
Edit/add new JSON schema to work with github actions

### ISSUE THREAD

**Issue by emily-hawkins** [sqlfluff/sqlfluff#1190]
relevant slack conversation: https://sqlfluff.slack.com/archives/C01V7UR2ARG/p1625599754011800

We're moving off of Jenkins onto Github Actions, and so I was starting to add our SQLFluff into github actions following the super helpful guides [here](https://github.com/sqlfluff/sqlfluff-github-actions/tree/main/menu_of_workflows)

I was able to get it run, but I noticed we were not getting any annotations on the PR itself. So to see the errors you have to go into the checks and find each line and file where the error occurs. Before, we had this set up in our jenkins job, so that when a SQLFluff error is found, it posts it on the PR on the file/line from the SQLFluff output. 

We are going to end up building something custom with our devops team for now, but it would be a great enhancement to update the JSON schema in SQLFluff and/or add an additional format output that matches the github actions annotations schema so more people could do this in the future without having to build something custom. (found [here](https://docs.github.com/en/rest/reference/checks#annotations-items) and [here](https://github.com/yuzutech/annotations-action) )

The current JSON output for SQLFluff looks like this 
```
[
  {
    "filepath": "dbt/models/admin/fact_dbt_runs.sql",
    "violations": [
      {
        "line_no": 7,
        "line_pos": 1,
        "code": "L010",
        "description": "Inconsistent capitalisation of keywords."
      }
    ]
  }
]
```

**Comment by dorzey** [comment]
It would be great to get this feedback in your PR. One thing we need to consider is that [vscode-sqlfluff](https://github.com/sqlfluff/vscode-sqlfluff) is dependent on the existing JSON output.

**Comment by barrywhart** [comment]
@emily-hawkins: I have a PR with a preliminary implementation of this: #1198. Would you be willing to do a real-world integration test of this in one of your projects, using the [annotation action](https://github.com/yuzutech/annotations-action) you linked to? It would be 💯 to test this "for real" before including it in a release.

If you can draft some documentation on how to use it, that would be really helpful too.
