### ISSUE TITLE
Option to print lint output in reverse order

### ISSUE THREAD

**Issue by jamiet-msm** [sqlfluff/sqlfluff#1197]
When running `sqlfluff lint` I like to start from the top of the list of recommendations and work my way down. However, that does mean that the item I want to address next (i.e. the thing at the top of the list) is off the top of my screen so I have to scroll in order to see it.

Hence, it would be really handy to print the output in reverse order, that would mean the thing I want to address first is at the bottom of the list and I wouldn't have to scroll in order to see it.

In the meantime I just pipe to head (`sqlfluff lint | head -20`) but I think I would prefer an option to see the output in reverse order.

Thanks in advance.

**Comment by jamiet-msm** [comment]
If this is something you'd be willing to accept a contribution for then let me know and I'll get to work on it.

**Comment by barrywhart** [comment]
Could you use the Linux `tac` command?

https://www.baeldung.com/linux/reverse-order-of-file-lines

**Comment by jamiet-msm** [comment]
Did not know about that. Will try it out, thx.

**Comment by barrywhart** [comment]
Closing because there's an easy solution that doesn't require SQLFluff changes.

**Comment by jamiet-msm** [comment]
@barrywhart Agreed. `tac` works fine.
