### ISSUE TITLE
BigQuery: CREATE [OR REPLACE] table OPTIONS ( description = 'desc' ) is not supported

### ISSUE THREAD

**Issue by tardyp** [sqlfluff/sqlfluff#1205]
## Expected Behaviour

in our big query process, we have a lot of following queries:

```
CREATE OR REPLACE TABLE foo
OPTIONS
  (description = 'copy of bar') AS (
    SELECT * from bar
    )
```
## Observed Behaviour

Following error
```
Found unparsable section: 'CREATE OR REPLACE TABLE foo\nOPTIONS\n (d...'
```

## Steps to Reproduce

http://online.sqlfluff.com/fluffed?sql=H4sIAELg7WAC_yWKOwqAMBAFeyF3eJ2fO1jEsIUQTEhyAX8BC12JNt5eg9XAzChHMhCMgyOrpSIE2WlCZBaFsaE3gxcFUC3rNaftvDc-0KKc-XzAEdOYyhrSo8oX4EmTCmgQE--5_rr-8AL24jT3awAAAA%3D%3D&dialect=bigquery

**Comment by barrywhart** [comment]
What dialect of SQL is this referring to?
