### ISSUE TITLE
dbt 0.20.0 raises: ImportError: cannot import name 'load_macro_manifest' from 'dbt.parser.manifest'

### ISSUE THREAD

**Issue by alanmcruickshank** [sqlfluff/sqlfluff#1218]
When upgrading to dbt 0.20.0, there's an import error in the dbt templater:

`ImportError: cannot import name 'load_macro_manifest' from 'dbt.parser.manifest'`

Checking the most recent version of that library ([here](https://github.com/dbt-labs/dbt/blob/develop/core/dbt/parser/manifest.py)) that function is indeed now missing. We should work out a replacement method to get what we need. I suspect we need to call `ManifestLoader.get_full_manifest()`.

**Comment by sdepablos** [comment]
@alanmcruickshank just to let you know I've been trying your PR in my repo with dbt 0.20 and so far so good.

**Comment by alanmcruickshank** [comment]
thanks @sdepablos - I'll merge my changes and release if you've tested them in the wild! :)
