### ISSUE TITLE
Snowflake dialect issues

### ISSUE THREAD

**Issue by damianslee** [sqlfluff/sqlfluff#1224]
CREATE ROLE IF NOT EXISTS ROLE-NAME-DASH;
SET THIS_ROLE=CURRENT_ROLE();
GRANT ROLE ROLE-NAME-DASH TO ROLE IDENTIFIER($THIS_ROLE);
CALL MyStoredProcedure(CURRENT_ROLE());
GRANT OWNERSHIP ON USER MYUSER TO ROLE SOME_ROLE;

## Expected Behaviour
1. object names with dashes are valid
2. SET variable is valid
3. referencing variable is valid $THIS_ROLE
4. CALL stored procedure is valid
5. changing ownership role on USER is valid.

## Observed Behaviour
== [test.sql] FAIL
L:   1 | P:  31 |  PRS | Line 1, Position 31: Found unparsable section:
                       | '-NAME-DASH'
L:   1 | P:  31 | L006 | Missing whitespace after -
L:   2 | P:   1 |  PRS | Line 2, Position 1: Found unparsable section: 'SET
                       | THIS_ROLE=CURRENT_ROLE()'
L:   3 | P:   1 |  PRS | Line 3, Position 1: Found unparsable section: 'GRANT
                       | ROLE ROLE-NAME-DASH TO ROLE IDENTI...'
L:   3 | P:  46 |  LXR | Unable to lex characters: '$THIS_ROLE...'
L:   4 | P:   1 |  PRS | Line 4, Position 1: Found unparsable section: 'CALL
                       | MyStoredProcedure(CURRENT_ROLE())'
L:   5 | P:   1 |  PRS | Line 5, Position 1: Found unparsable section: 'GRANT
                       | OWNERSHIP ON USER MYUSER TO ROLE S...'
All Finished 📜 🎉!

## Steps to Reproduce
sqlfluff lint --dialect snowflake test.sql

## Version
0.6.1
python 3.8

**Comment by dbeatty10** [comment]
This expected behavior is also reported in #996:
- SET variable is valid

**Comment by dbeatty10** [comment]
@damianslee can you add these 2 labels?
- [dialect](https://github.com/sqlfluff/sqlfluff/labels/dialect)
- [snowflake](https://github.com/sqlfluff/sqlfluff/labels/snowflake)

I don't think I have permission to add labels, or I would just do it myself.

**Comment by barrywhart** [comment]
I added the labels.

**Comment by barrywhart** [comment]
@damianslee: This may be more likely to be addressed if split into multiple GitHub issues. (One per item on the 5-item list.)

**Comment by tunetheweb** [comment]
@damianslee are you sure dashes are officially supported in Snowflake?

From here: https://docs.snowflake.com/en/sql-reference/identifiers-syntax.html

>Unquoted object identifiers:
> - Start with a letter (A-Z, a-z) or an underscore (“_”).
> - Contain only letters, underscores, decimal digits (0-9), and dollar signs (“$”).
> - Are stored and resolved as uppercase characters (e.g. id is stored and resolved as ID).

Think I have fixes for the rest of them.

**Comment by damianslee** [comment]
dashes are not supported.  i think some cases work.  best to not support dashes
