### ISSUE TITLE
Add sqlfluff fix -p flag

### ISSUE THREAD

**Issue by reidwil-jb** [sqlfluff/sqlfluff#1228]
-- Please add any additional labels that are related to the issue before submitting! --
Currently, both `lint` and `fix` calls support `--processes` while only `lint` has the abbreviated `-p` flag. Is there a specific reason the `fix` call does not have that shortened version?

If not, I have attached a PR to add the shortcut flag for the `fix` sqlfluff call.

**Comment by reidwil-jb** [comment]
https://github.com/sqlfluff/sqlfluff/pull/1229

**Comment by barrywhart** [comment]
PR merged, closing issue. Thanks for the contribution, @reidwil-jb!
