### ISSUE TITLE
Document segment/grammar inheritance and editing methods

### ISSUE THREAD

**Issue by NiallRees** [sqlfluff/sqlfluff#1235]

**Comment by tunetheweb** [comment]
I'm going to close this thanks to the wiki: https://github.com/sqlfluff/sqlfluff/wiki/Contributing-Dialect-Changes

Can always ahve more documentation, but think above, especially when coupled with more technical detail in https://docs.sqlfluff.com/en/latest/architecture.html provides a good basic grounding.
