### ISSUE TITLE
Look into using dbt CLI for templater vs relying on Python methods

### ISSUE THREAD

**Issue by NiallRees** [sqlfluff/sqlfluff#1237]
The Python API is [undocumented](https://docs.getdbt.com/docs/running-a-dbt-project/dbt-api) and prone to change in each new release (hence we have to keep patching SQLFluff). Can we achieve the same functionality using just CLI subprocess calls?

**Comment by pwildenhain** [comment]
Should this be closed in favor of #1236?

**Comment by barrywhart** [comment]
I no longer think this is feasible, given the work in #1788 (PR, in review but not yet merged), which improves the raw <---> templated mapping by monkeypatching Jinja to intercept calls from dbt.

Any thoughts, @NiallRees?

**Comment by NiallRees** [comment]
> I no longer think this is feasible, given the work in #1788 (PR, in review but not yet merged), which improves the raw <---> templated mapping by monkeypatching Jinja to intercept calls from dbt.
> 
> Any thoughts, @NiallRees?

Sounds good to me!
