### ISSUE TITLE
running sqlfluff fix command 2nd time still finds and fixes some identation issues

### ISSUE THREAD

**Issue by Arshaku** [sqlfluff/sqlfluff#1245]
when I run the _sqlfluff fix_ command on my sql file (with jinja templates in it), among other things it fixes some indentation/whitespace issues. So now I would expect the indentation is correct. But then if I run the _fix_ command again, it still fixes some more indentation issues (usually on lines it already changed the indentation during the previous run). 
Because of this issue I have to create a sophisticated python script which runs the _sqlfluff fix_ multiple times in a loop, every time checking if the files are changed and stop when  _sqlfluff fix_ doesn't find anything to fix anymore.

## Expected Behaviour
the _sqlfluff fix_ command to fix all the issues from one go / single run.

## Observed Behaviour
it requires multiple runs of the _fix_ command until it fixes all the issues in the file.

## Version
sqlfluff, version 0.6.2
Python 3.8.10

## Configuration
the default configuration

**Comment by barrywhart** [comment]
Can you provide an example `.sql` and `.sqlfluff` configuration file so we can reproduce this? Otherwise, we really can't make progress on addressing it.
