### ISSUE TITLE
Add the option to remove/change the emojis of the output

### ISSUE THREAD

**Issue by Arwiim** [sqlfluff/sqlfluff#1246]
It would be nice if we can have a option to change/modify/remove the emojis of the output.

![image](https://user-images.githubusercontent.com/53288078/128351980-c0a3874b-7e05-4197-92ff-4b2f036bd1fc.png)

**Comment by barrywhart** [comment]
@Arwiim: One possible implementation would be to extend this existing option to also suppress the emoji output:
```
  -n, --nocolor                   No color - if this is set then the output
                                  will be without ANSI color codes.
```

This existing option and your request seem similar -- in both cases, the intent is to get plain text output. What do you think?

Tagging @nolanbconaway, who was involved in the Slack conversation about this (in the #help channel).

**Comment by Arwiim** [comment]
Well it doesn't, the only think that -n do its removes the colors, but not the emojis
![image](https://user-images.githubusercontent.com/53288078/128365759-77b89ebb-ce8a-4af8-b1fe-1af746e40e39.png)
@nolanbconaway

**Comment by nolanbconaway** [comment]
Yep! i never set it up to be disabled on -n but ought to have!

**Comment by barrywhart** [comment]
@Arwiim: Right, I was discussing the design for a possible fix. This is **definitely not** the current behavior.

To clarify, I'm proposing we extend the behavior of an existing command-line option rather than adding a new one.

**Comment by Arwiim** [comment]
Thanks for the support! look forward to a new version with this corrected

**Comment by barrywhart** [comment]
Hey @nolanbconaway: I started work on this before I saw you'd assigned it to yourself. 😿 I'll go ahead and create a PR -- hope that's okay.

**Comment by nolanbconaway** [comment]
Lol ofc

**Comment by barrywhart** [comment]
Cool cool. I'm sorry about that! I made a list of a few issues to look at as the notifications were coming in. I also looked briefly at #1248, which looks slightly scary (templating + rules + busted fix). If I can get some advice from Alan, I might look into that one. 😬😰
