### ISSUE TITLE
L027 fails with EXTRACT(ISOYEAR/ISOWEEK

### ISSUE THREAD

**Issue by robertoash** [sqlfluff/sqlfluff#1258]
This code generates a fail on L027:

```
SELECT
    CONCAT(
        EXTRACT(ISOYEAR FROM ranking.available_delivery_dates),
        '-',
        EXTRACT(ISOWEEK FROM ranking.available_delivery_dates)
    ) AS year_week
FROM ranking
LEFT JOIN bad_experiences AS bad_xp
    ON bad_xp.geographical_area_id = ranking.geographical_area_id
LEFT JOIN occupation_percentage
    ON occupation_percentage.geographical_area_id = ranking.geographical_area_id
```

The fail is:
Unqualified reference 'ISOYEAR' found in select with more than one referenced table/view.

ISOYEAR is not a reference but a date part so I assume it shouldn't fail or is there something I'm missing?

**Comment by barrywhart** [comment]
What dialect are you using? Did you specify the dialect when you ran it? Can you provide your `.sqlfluff` file for reference?

**Comment by robertoash** [comment]
Sorry about this. Wasn't aware of the "dialect" option. Closing this issue
