### ISSUE TITLE
Fail on L027 when using aliases in GROUP BY/ORDER BY

### ISSUE THREAD

**Issue by robertoash** [sqlfluff/sqlfluff#1259]
Somewhat related to https://github.com/sqlfluff/sqlfluff/issues/400 but dealing with ORDER/GROUP BY.

BigQuery supports alias use in GROUP BY and ORDER BY. I'm getting a fail on L027 when GROUPING/ORDERING by an alias.

```
SELECT
    CONCAT(
        EXTRACT(ISOYEAR FROM ranking.available_delivery_dates), 
        '-',
        EXTRACT(ISOWEEK FROM ranking.available_delivery_dates) 
    ) AS year_week,
    ROUND(
        SUM(ranking.weighted_impact_score_geo_date),
        0
    ) AS weighted_impact_score_geo_date
FROM ranking
LEFT JOIN bad_experiences AS bad_xp
    ON bad_xp.geographical_area_id = ranking.geographical_area_id
LEFT JOIN occupation_percentage
    ON occupation_percentage.geographical_area_id = ranking.geographical_area_id
GROUP BY
    year_week
ORDER BY
    year_week DESC,
    weighted_impact_score_geo_date ASC
```

Is this intended?

**Comment by barrywhart** [comment]
Can you please supply some additional information? I think this is mentioned in the bug template. This will help us understand and reproduce the behavior you're seeing.
* Expected output
* Actual output
* Your `.sqlfluff` file

**Comment by robertoash** [comment]
I'm sorry about this. I wasn't aware of the "dialect" option. Closing this issue
