### ISSUE TITLE
Allow for DBT arguments in config

### ISSUE THREAD

**Issue by kamcdonough20** [sqlfluff/sqlfluff#1262]
The current DBT config assumes no arguments are passed on ```dbt run```, but many instances where the dbt-profile is configured to uses variables when building, such as for the database name. This prevents  sqlfluff from  being able to build the targets.

**Comment by barrywhart** [comment]
Can you provide more detail about what arguments should be supported, and link to the dbt docs on those arguments? We can't start work on this until we have these details.

**Comment by swtwsk** [comment]
I was just about to raise a similar issue, so I'll add my comment here instead :)

I guess @kamcdonough20 meant DBT's [vars](https://docs.getdbt.com/reference/dbt-jinja-functions/var). DBT allows usage of `var('variable_name')` in its Jinja templates and then substitutes them with variables passed as a yaml-encoded string using `--vars` in the CLI or listed in `dbt_project.yml`. So, e.g.:
```sql
# models/example_model.sql
select * from events where event_type = '{{ var("event_type") }}'
```
```bash
$ dbt run --vars "{\"event_type\":\"activation\"}"
```
yields
```sql
select * from events where event_type = "activation"
```
Similarly, one can use `var` in DBT's `profiles.yml`.

Currently, there is no way to pass those variables when using SQLFluff. Fixing this behaviour will probably require changes in `sqlfluff_templater_dbt.templater` (i.e., its `DbtConfigArgs`), CLI and/or SQLFluff config parser. 

---
[env_var](https://docs.getdbt.com/reference/dbt-jinja-functions/env_var) seems to be picked correctly. However, it makes sense as DBT templater reads those variables directly from `os.environ`.

**Comment by tcholewik** [comment]
@kamcdonough20 I encountered the same problem, and I am working on a patch for that.

Assuming that I understood correctly how dbt expects to receive these vars then I simply have to ask sqlfluff to read extra field in config.

Not really sure if anyone else is working on this as well.
