### ISSUE TITLE
Create dialect for MS SQL DB

### ISSUE THREAD

**Issue by tkachenkomaria244** [sqlfluff/sqlfluff#1282]
For parsing MS SQL DB sql scripts it seems to be useful to add special dialect.

For example, for table creation we have the following structure, which cannot be parsed with ANSI dialect (due to square brackets around schema, index, table, fields names and "GO", "CLUSTERED","UNCLUSTERED" keywords).
Similar issue with square brackets we have for scripts creation for views and indexes.

table1.sql:
"
CREATE TABLE [schema1].[table1] (
    [field1]                            DATE           NOT NULL,
    [field2]                              BIGINT         NOT NULL,
    [field3]                          BIGINT         NULL
);

GO
CREATE CLUSTERED INDEX [Cix_U_XID_YID]
    ON [schema1].[table1]([field1] ASC, [field2] ASC);
"

**Comment by jhaysODPS** [comment]
A full solution is still dependent on: https://github.com/sqlfluff/sqlfluff/issues/3852
