### ISSUE TITLE
Switch to squash gits commits on merge to main

### ISSUE THREAD

**Issue by tunetheweb** [sqlfluff/sqlfluff#1301]
I notice we do not squash commits on pull request merges.  I’m a big fan of squashing on merge for public repos like this for the following reasons:
- It keeps the git history cleaner, rather than riddled with hundred of “more fixes” or “review feedback” or “merge branch main” type commits. And rebasing is just a lot more painful way to do that.
- It gives a meaningful commit name (the PR title and the PR number) rather than random ones different contributors might pick.
- Each PR is a unit of work and the individual commits that made up that, while the PR was being worked on and review feedback was addressed are not. It’s rare we need to go back to any of those individual commits after merge.
- It is less embarrassing to have all your work in progress and millions of commits in the main branch forever more.
- It encourages people to commit frequently (which is good practice), rather than try to minimise the number of commits for when the merge happens.

What’s peoples thoughts in switching to Squash merges? It’s basically a change to the Settings->Options to the following:

![B8DD79A8-19BC-4924-99CA-B165185AB278](https://user-images.githubusercontent.com/10931297/129964951-10384f85-b8b6-4aa1-8ee9-c20f95b64c6f.jpeg)

**Comment by barrywhart** [comment]
Does this have any impact on the workflow for contributors, in the normal case or in other cases such as updating the PR with changes from `main‘, resolving merge conflicts, etc.?

Any thoughts or questions, @sqlfluff/sqlfluff-maintainers?

**Comment by tunetheweb** [comment]
Nope. Everything is exactly the same except when it’s merge it looks like it’s one big commit in the git history instead of multiple ones.

The only downside is that if someone did a lot of work and did want to dig out one particular commit (e.g. an old attempt at the fix that ultimately wasn’t used, but that they wanted to have another look at again to reuse that code for a different reason) then it won’t be in the `main` git history. It will be in the original branch but often people delete old branches after merge. But honestly how likely is that, and how easy would it even be to find that commit when there’s so much noise in the git history?

**Comment by barrywhart** [comment]
It sounds like a reasonable change to me. I would say I don't have a strong feeling one way or another. When I look back in the history, it usually involves one or both of:
* `git blame
* `git log -p` plus searching

I can see the second way might be streamlined since intermediate changes to files would no longer appear in the commit history.

Let's see what the other maintainers think.

**Comment by tunetheweb** [comment]
I tend to use the blame button in GitHub to see when a line was added/amended and that can get really noisy.

But happy to hear what others think and if there’s more advantages to the current method that I’m not aware of.

**Comment by tunetheweb** [comment]
Default changed and first merge completed with squash (#1308) with no issue.
