### ISSUE TITLE
`sqlfluff fix` mixes hanging and regular indents

### ISSUE THREAD

**Issue by nc-holodakg** [sqlfluff/sqlfluff#1310]
## Steps to Reproduce

Run `sqlfluff fix` on this code:
``` sql
select *
from foo
where a like 'a%'
  and b like 'b%'
  and c = false
```

## Expected Behaviour

Either one of these options:
``` sql
select *
from foo
where a like 'a%'
      and b like 'b%'
      and c = false
```
or
``` sql
select *
from foo
where a like 'a%'
    and b like 'b%'
    and c = false
```

## Observed Behaviour

`sqlfluff fix` produces this output, which looks worse than any of the alternatives:

``` sql
select *
from foo
where a like 'a%'
      and b like 'b%'
    and c = false
```

## Version
SQLFluff 0.6.3
Python 3.9.4

**Comment by barrywhart** [comment]
To better understand the behavior, I extended the test case with an additional line:
```
select *
from foo
where a like 'a%'
  and b like 'b%'
  and c like 'c%'
  and d like 'd%'
```

And got:
```
select *
from foo
where a like 'a%'
      and b like 'b%'
    and c like 'c%'
    and d like 'd%'
```

So the behavior is that hanging indent is only applied to the first line. Need to dig into why this is happening and make it consistent.
