### ISSUE TITLE
Lock our versions more?

### ISSUE THREAD

**Issue by tunetheweb** [sqlfluff/sqlfluff#1317]
Should we lock our versions more in [requirements.txt](https://github.com/sqlfluff/sqlfluff/blob/main/requirements.txt) and [requirements_dev.txt](https://github.com/sqlfluff/sqlfluff/blob/main/requirements_dev.txt)?

Currently we only lock some of them:

```
click>=7.1
colorama>=0.3
configparser
cached-property
# oyaml is like pyyaml but preserves orderings
oyaml
Jinja2
diff-cover>=2.5.0
# pathspec handles the .sqlfluffignore file
pathspec
pytest
tblib
appdirs
# dataclasses backport for python 3.6
dataclasses; python_version < '3.7'
chardet
types-chardet
toml
```

Can then use dependabot to automatically keep them up to date (see https://github.com/sqlfluff/sqlfluff-online/pull/27 as an example file).

**Pluses:**
- More consistency so don't need to ask people having problems what version they are running.
- More certainty of support across versions (i.e. we KNOW we support black version XXX because that's whats in out repo).
- Tests are run on pull requests from Dependabot to update dependencies so we only update if tests pass.
- Get a heads up on updates to our dependencies (why's everyhting being reformatted? Or yeah, I saw a PR saying black has a new version out).

**Negatives:**
- More PRs to approve and merge.
- Not everyone runs pip install regularly (though it is part of `tox`), so might not update dependencies locally anyway.

**Comment by barrywhart** [comment]
At work, we use pip-compile, so we have one "input" file with very little if any freezing, and another file with **everything** frozen, to avoid variation across installations.

Note that (IIRC) these .txt files don't affect what gets installed for users, only for developers.

**Comment by barrywhart** [comment]
If this package works as advertised, maybe we could add a "test" that runs it to verify the current virtualenv matches the requirements files. This would address the issue of people not running `pip install` regularly.

https://pypi.org/project/pip-check-reqs/

**Comment by alanmcruickshank** [comment]
I've always worried that because sqlfluff is a tool that people might use with other packages - that by locking too much we make it harder to play nice with other packages if we lock too specifically. Is that a valid concern?

**Comment by tunetheweb** [comment]
Not too familiar with Python ecosystem but having a quick read up on it, I think you might be right. I come more from a Node background where each dependency can have it's own versions if needed. Seems it's not the same for Python so should probably leave this as is.

Will close this then but feel free to reopen if anyone wants to discuss further.

**Comment by barrywhart** [comment]
This is actually possible. There are two different concepts in play:
* What package version(s) does `sqlfluff` request when it is installed on a user's system? This is configured in `setup.py`'s `install_requires` section [here](https://github.com/sqlfluff/sqlfluff/blob/main/setup.py#L90L115). We would leave this "as is".
* What package version(s) does a SQLFluff *contributor* install. This is configured in `requirements.txt` and `requirements_dev.txt`.

In some of our internal packages at work, we do something very much like this.

**Comment by tunetheweb** [comment]
OK but doesn't think kind of defeat the point if these get two separated from each?

A big part of the point was to be confident of what versions people were running. Knowing what the developers are running is only half the battle.

Currently if we only lock the `requirements.txt` and `requirements_dev.txt`, then a non-developer. who is still running SQLFluff 0.5.0 for whatever reason, can still get incompatible updates (cause we have a `>=` in `setup.py`) and they can raise an issue saying it's broken.

Plus I'm a little uncomfortable with developers and test suites being locked on one version, and then releasing for different versions to be used.

Also I'm not sure this is really a problem here. It's more just a best practice from the node world I'm more familiar with so thought I'd ask the question. It seems there's good reason not to lock it.

**Comment by barrywhart** [comment]
Alan is correct that you don't want to lock things too much for users, because the package may not co-exist nicely. It is certainly possible to lock things down _a little bit_ in `setup.py`. It's difficult to know how much is appropriate, though, because package maintainers often don't seem to follow semantic versioning. (Some packages increment the major version number frequently, even though in my experience, old code still works.)

Ok, I'll close it again.

If we notice that users are having issues due to incompatible packages, we can look at locking down `setup.py` a bit more.
