### ISSUE TITLE
lateral flatten group sqlfluff changes cause to not work

### ISSUE THREAD

**Issue by meoda** [sqlfluff/sqlfluff#1318]
_If this is a parsing or linting issue, please include a minimal SQL example which reproduces the issue, along with the `sqlfluff parse` output, `sqlfluff lint` output and `sqlfluff fix` output when relevant._

## Expected Behaviour

below to run works

```sql
with source_data as (
select key column_name
  , count(*)
from (
    select object_construct(a.*) x
    from {{ ref('src_test_file') }} a
), lateral flatten(x)
group by key
)
 select * from source_data 
```

## Observed Behaviour

sqlfluff parsing cause not to run (DBT)

```sql
with source_data as (
    select
        key as column_name,
        count(*)
    from (
        select object_construct(a.*) as x
        from {{ ref('src_test_file') }}
        ), lateral
    group by key
)

select * from source_data
```

## Steps to Reproduce
Run first set of code against a table (just counts columns/column name)
Either one below modifies so SQL doesn't run properly
`sqlfluff fix -f  (on file)`
or
`sqlfluff fix -f --dialect snowflake`

## Dialect
ansi
or
snowflake

## Version
0.6.2
0.6.4
Include the output of `sqlfluff --version` along with your Python version
```
$ sqlfluff --version
sqlfluff, version 0.6.4

$ python --version
Python 3.8.6
```

## Configuration

Include your SQLFluff configuration here

Using windows, did .exe install
 only found a /sqlfluff/config.iniconfig.ini
# Config file for SQLFluff, mostly for version info for now

```
[sqlfluff]
version=0.6.4
stable_version=0.6.4
```

**Comment by tunetheweb** [comment]
@meoda running the fix using `dialect snowflake` does not corrupt the SQL as far as I can see as the `flatten` key word is still there when I try it.

I agree it does with ANSI but I do not believe `lateral flatten` is valid ANSI syntax.

**Comment by meoda** [comment]
thank you.  I agree and will rewrite for future sqlfluff
