### ISSUE TITLE
Return non zero exit code on fix when there are lint violations

### ISSUE THREAD

**Issue by mvgijssel** [sqlfluff/sqlfluff#1340]
We use [lefthook](https://github.com/evilmartians/lefthook) in combination with a pre-commit git hook to fix and commit updated dbt models when committing changes to the repository. This works great with the only downside that `poetry run sqlfluff --fix` will return a 0 exit code when it's done fixing even though there are still unfixable lint violations. 

As an enhancement if would be great if sqlfluff could return a non zero exit code on fix when there are still unfixable linting violations.

**Comment by nolanbconaway** [comment]
I got this one unless someone faster wants it!

**Comment by tunetheweb** [comment]
> I got this one unless someone faster wants it!

Actually I started looking at this already and think I have a fix. Would appreciate a PR review though!
