### ISSUE TITLE
BigQuery Parameterized Queries

### ISSUE THREAD

**Issue by rileyrunnoe** [sqlfluff/sqlfluff#1342]
[BigQuery](https://cloud.google.com/bigquery/docs/parameterized-queries) allows for adding parameters to queries using the `@VAR_NAME` syntax.

I am hoping to add this to the bigquery language so that these queries can be parsed.

**Comment by tunetheweb** [comment]
Can you give an example query?

**Comment by rileyrunnoe** [comment]
```sql
SELECT 1
from x
where y = @z
```

Z is specified as a specific value with whatever SDK you are using to interact with BQ.
