### ISSUE TITLE
postgres dialect doesn't support comments on functions

### ISSUE THREAD

**Issue by miketheman** [sqlfluff/sqlfluff#1354]
This SQL:

```sql
COMMENT ON FUNCTION dummy() IS NULL;
```

raises:

```
sqlfluff.api.simple.APIParsingError: Found 1 issues while parsing string.
Line 2, Position 1: Found unparsable section: 'COMMENT ON FUNCTION dummy() IS NULL'
```

_Originally posted by @miketheman in https://github.com/sqlfluff/sqlfluff/pull/1347#discussion_r701998810_

**Comment by tunetheweb** [comment]
ExaSol has similar comments so should be easy enough to copy this across and add a test case if you (or anyone else!) would like to add.

**Comment by miketheman** [comment]
@tunetheweb Thanks for the pointer! Should I attempt to add this to the current code, or wait until #1347 makes it through to `main`?

**Comment by tunetheweb** [comment]
It’s merged now so work away!!

**Comment by miketheman** [comment]
Random question: If a fixture file is using CRLF line endings, is it desirable to convert that to LF only? I've found it helps to have an [`.editorconfig`](https://editorconfig.org/) file at the root of a project to help ensure consistent, and even [plug it into a pre-commit check](https://github.com/editorconfig-checker/editorconfig-checker.python#usage-with-the-pre-commit-git-hooks-framework). Happy to move this to a new issue if it's important enough!

**Comment by tunetheweb** [comment]
Yes! Big fan of `.editorconfig` files. We have `black` for the Python files but enforcing some standards on the `.rst`, `.md`, and `.sql` files would be good.

But let's pull, it into a separate issue.

**Comment by tunetheweb** [comment]
Raised #1356 for this.
