### ISSUE TITLE
Add a .editorconfig file

### ISSUE THREAD

**Issue by tunetheweb** [sqlfluff/sqlfluff#1356]
As discussed in https://github.com/sqlfluff/sqlfluff/issues/1354#issuecomment-913054119 we should add a `.editorconfig` file.

[Editorconfig](https://editorconfig.org/) is a file which many IDEs support (sometimes via plugins) which enforce consistent styling which can be applied automatically (e.g. tabs versus spaces, newlines at the bottom).

It is added by placing an `.editorconfig` file in the root directory with a format like the below:

```
# editorconfig.org
root = true

[*]
indent_style = space
end_of_line = lf
charset = utf-8
trim_trailing_whitespace = true
insert_final_newline = true

[*.{html,md,js,css,sql}]
indent_size = 2

[*.py]
indent_size = 4

[*.rst]
indent_size = 3
```

Any IDE that a contributor uses, that supports this, will automatically enforce these standards.

We already have `black` to enforce this consistency for our python files, but enforcing (some of?) this for `.md`, `.rst`, and `.sql` files would help bring consistency and avoid "nit"-ty feedback on PRs.

Some items to consider:
- What rules to enforce? For Python this should be obvious as can follow `black`'s convention but for others might not be as obvious.
- Tabs versus spaces - I presume spaces since `black` does this for Python files. Anyone fancy opening the argument or can we just go with that?
- Indentation spacing for no-Python files? Again `black` has set the standard to 4 spaces for Python, but often 2 spaces are used for JS and other files. Luckily `.editorconfig` supports setting this by file type (see above) if we want to use this. Also our .rst files seem to use 3 spaces so is that the convention for there?
- Spot checking a few files, to ensure that adding a small tweak to any of those file types doesn't result in a load of white space noise in PRs forevermore.
- Maybe cleaning up all the files that don't match that to avoid item above?
- Add as [a pre-commit hook](https://github.com/editorconfig-checker/editorconfig-checker.python#usage-with-the-pre-commit-git-hooks-framework)?
- Add documentation for contributors to tell them how to install any necessary plugins for popular IDEs?

**Comment by tunetheweb** [comment]
Maybe should leave the pre-commit hock out of this for now and keep it simple?

We don’t use one for black for example - though do enforce it during our checks. Maybe should have a [CI check for this](https://github.com/editorconfig/editorconfig/wiki/FAQ#my-files-are-not-automatically-reformatted-the-editorconfig-plugin-is-not-working) like we do for black?

**Comment by barrywhart** [comment]
We tried the editorconfig pre-commit hook a few months ago and had to remove it due to a bug. It insisted on "multiple of 4" indent even in situations that called for other levels, e.g. aligning arguments with the parentheses in multiline function calls.

**Comment by barrywhart** [comment]
+1 for using spaces, following existing conventions, and doing a one-time update of all existing files.
