### ISSUE TITLE
Add max_per_element kwarg to AnyNumberOf()

### ISSUE THREAD

**Issue by WittierDinosaur** [sqlfluff/sqlfluff#1368]
It'd be useful for some uses of `AnyNumberOf()` to have a `max_per_element` option. This would allow us to be more strict with some of our grammar definitions. Functions, for example:

```
CREATE FUNCTION my_function RETURNS int AS "" LANGUAGE plpgsql;
```
Would pass. while:
```
CREATE FUNCTION my_function RETURNS int AS "" LANGUAGE plpgsql LANGUAGE plpgsql;
```
Would fail.

**Comment by tunetheweb** [comment]
Yes! Or at least a `no_duplicates` boolean option if that's easier.

Ref: https://github.com/sqlfluff/sqlfluff/pull/1336#discussion_r699152260

**Comment by tunetheweb** [comment]
I think this is covered by `AnySetOf` added in #2326
