### ISSUE TITLE
Add support for Snowflake DML command COPY INTO 

### ISSUE THREAD

**Issue by armaandhull** [sqlfluff/sqlfluff#1397]
As mentioned in https://github.com/sqlfluff/sqlfluff/issues/1268#issuecomment-917463767, `COPY INTO` DML command for Snowflake is not yet supported by sqlfluff. This issue is about adding support for the same.

More information about `COPY INTO` can be found at https://docs.snowflake.com/en/sql-reference/sql/copy-into-table.html

**Comment by tunetheweb** [comment]
This is supported:

https://github.com/sqlfluff/sqlfluff/blob/89b1e9c35568b0d55de3af8165de99600969aab6/src/sqlfluff/dialects/dialect_snowflake.py#L935-L945

And we have test cases here: https://github.com/sqlfluff/sqlfluff/blob/main/test/fixtures/parser/snowflake/snowflake_copy_into.sql

I noticed in #1268 you were running 0.6.2 but COPY INTO was only added to Snowflake in 0.6.5.

Could you retry with a later version and reopen this issue with example SQL if it's still failing?
