### ISSUE TITLE
Remove circleci in our repo

### ISSUE THREAD

**Issue by zhongjiajie** [sqlfluff/sqlfluff#1399]
It seem that we do not use circleci anymore, so maybe we should remove the related between circleci and repo.
Unless all PR would failed cause circleci checklist faild, which it not good for reviewer and contributors

Here it's and example PR https://github.com/sqlfluff/sqlfluff/pull/1393 and screenshot

![image](https://user-images.githubusercontent.com/15820530/133190025-aec03a77-5f4d-44b2-8a8a-da295a82e15d.png)

**Comment by tunetheweb** [comment]
Did you get a chance to have a look yet @alanmcruickshank ? It’s quite creating confusion and noise so would be nice to resolve.

**Comment by tunetheweb** [comment]
Seems to be gone. Not sure whether cause we disabled it or CircleCI got bored of use not running tests.
