### ISSUE TITLE
Rules for Nesting Views

### ISSUE THREAD

**Issue by aidan-plenert-macdonald** [sqlfluff/sqlfluff#1417]
Having multiple layers of VIEW nesting can negatively impact the optimizer.

How could I make a rule that looks at multiple SQL files and detects if VIEWs are being overly nested?

**Comment by tunetheweb** [comment]
How would you know it's a VIEW and not a TABLE? Or do you want it to apply to both? Could you update your question with example SQL you want to detect maybe?

**Comment by tunetheweb** [comment]
Closing as not heard anything back. Can reopen if we get feedback.
