### ISSUE TITLE
Documentation is not clear on how to use pluggy to enable custom rules

### ISSUE THREAD

**Issue by rohithmiryala** [sqlfluff/sqlfluff#1429]
## Issue
The documentation doesn't mention how pluggy library works, so people who are not familiar with it will face difficulty in running the custom implemented rules.

## Suggested Improvement

It's better to mention in the [documentation](https://docs.sqlfluff.com/en/stable/developingplugins.html#few-things-to-note-about-plugins) that we should run `pip install -e .` inside the plugin folder to include the custom rules in linting.

**Comment by Aditya-Tripuraneni** [comment]
I would like to take on this issue. Could somebody assign it to me? I'd be glad to add the `pip instal -e` to the documentation where needed.
