### ISSUE TITLE
Indentation error on Jinja templated test case

### ISSUE THREAD

**Issue by tunetheweb** [sqlfluff/sqlfluff#1436]
As discussed in #1430 the test file [`test/fixtures/linter/autofix/ansi/016_index_error_with_jinja_if/after.sql`](https://github.com/sqlfluff/sqlfluff/blob/62687a79887205a0c877ccdd8bf18be44e39738e/test/fixtures/linter/autofix/ansi/016_index_error_with_jinja_if/after.sql) creates an unexpected dedent when fixed with rule L003

## Expected Behaviour

The `{{ product }}` line is not dedented, and in fact should be indented

## Observed Behaviour

The `{{ product }}` line is dedented

## Steps to Reproduce

Run this:
```
sqlfluff fix test/fixtures/linter/autofix/ansi/016_index_error_with_jinja_if/before.sql --rules L003 -f
```

Do a `git diff` and note this output:

```
 {% for product in products %}
 SELECT
-  brand,
-  country_code,
-  category,
-  name,
-  id
+    brand,
+    country_code,
+    category,
+    name,
+    id
 FROM
-  {{ product }}
+{{ product }}
```

The select clauses have been correct indented, but the from clause has been dedented instead of indented.

Not this does NOT happen if `product` is used instead of `{{ product }}` and also does not happen if `{% if not loop.last %} UNION ALL {% endif %}` is used instead of `{% if not loop.last -%} UNION ALL {%- endif %}`

## Dialect

ansi with jinja

## Version
Include the output of `sqlfluff --version` along with your Python version

SQLFluff version: `main` as of September 23 (commit hash b977d63a8552a7d60e9310ef5efceeedb2123361) (to be updated after #1430 is merged
Python version: 3.8

## Configuration

No config so all defaults.

**Comment by barrywhart** [comment]
Internally, this is very similar to #1438. There's an easy fix to just leave the indentation of `{{ product }}` as-is. I'd like to look a little deeper first to see about actually fixing the indentation (adding two spaces).

Also, even if we go with the simple fix, it'd be good to de-duplicate this code a bit, perhaps by adding a new method to `TemplatedFile`.

For now, here's a heavy "copy paste" diff (i.e. from #1443) that fixes the issue.
```
diff --git a/src/sqlfluff/rules/L003.py b/src/sqlfluff/rules/L003.py
index ca511274..4f8c268d 100644
--- a/src/sqlfluff/rules/L003.py
+++ b/src/sqlfluff/rules/L003.py
@@ -206,7 +206,7 @@ class Rule_L003(BaseRule):
             if key not in ("line_buffer", "indent_buffer")
         }

-    def _eval(self, segment, raw_stack, memory, **kwargs):
+    def _eval(self, segment, raw_stack, memory, templated_file, **kwargs):
         """Indentation not consistent with previous lines.

         To set the default tab size, set the `tab_space_size` value
@@ -395,6 +395,26 @@ class Rule_L003(BaseRule):
                         current_indent_buffer=this_line["indent_buffer"],
                         current_anchor=segment,
                     )
+
+                    deletion_slice = fixes[-1].anchor.pos_marker.source_slice
+
+                    # Check the raw source (before template expansion) immediately
+                    # following the whitespace we want to delete. Often, what looks
+                    # like trailing whitespace in rendered SQL is actually a line like:
+                    # "    {% for elem in elements %}\n", in which case the code is
+                    # fine -- it's not trailing whitespace from a source code
+                    # perspective.
+                    next_raw_slice = templated_file.raw_slices_spanning_source_slice(
+                        slice(deletion_slice.stop, deletion_slice.stop)
+                    )
+                    # If the next slice is literal, that means it's regular code, so
+                    # it's safe to delete the trailing whitespace. If it's anything
+                    # else, it's template code, so don't delete the whitespace because
+                    # it's not REALLY trailing whitespace in terms of the raw source
+                    # code.
+                    if next_raw_slice[0].slice_type != "literal":
+                        fixes = None
+
                     self.logger.debug(
                         "    !! Indentation does not match #%s. Fixes: %s", k, fixes
                     )
```
