### ISSUE TITLE
Unexpected exception on "too long" jinja-comment

### ISSUE THREAD

**Issue by courentin** [sqlfluff/sqlfluff#1439]
## Expected Behaviour

Successful run of `sqlfluff lint`

## Observed Behaviour

Exception raised on Rule L016 when having a jinja comment with more than 80 characters.

```python
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/sqlfluff/core/rules/base.py", line 302, in crawl
    res = self._eval(
  File "/usr/local/lib/python3.9/site-packages/sqlfluff/rules/L016.py", line 503, in _eval
    fixes = self._eval_line_for_breaks(this_line)
  File "/usr/local/lib/python3.9/site-packages/sqlfluff/rules/L016.py", line 266, in _eval_line_for_breaks
    raise ValueError("Is this possible?")  # pragma: no cover
ValueError: Is this possible?
== [a.sql] FAIL
L:   3 | P:  82 | L016 | Unexpected exception: Is this possible?; Could you open
                       | an issue at https://github.com/sqlfluff/sqlfluff/issues
                       | ? You can ignore this exception for now, by adding
                       | '--noqa: L016' at the end of line 3
L:   4 | P:   9 | L016 | Line is too long
```

## Steps to Reproduce

Lint this file:
```sql
SELECT *
{# comment #}
{# ........................................................................... #}
FROM table
```

## Dialect

ANSI

## Version
Include the output of `sqlfluff --version` along with your Python version

`sqlfluff, version 0.6.6`

## Configuration

Default config

**Comment by tunetheweb** [comment]
Open PR #1440 to resolve.

That will handle it properly in `lint`. However looks like we can't easily auto fix it using `fix`, but can at least exit gracefully then with an unfixable error.

**Comment by kieronellis** [comment]
Can this (i.e. long jinja comments like {#...#}) be ignored please? `ignore_comment_clauses = True` doesn't ignore these.

**Comment by tunetheweb** [comment]
I think that's a reasonable ask to honour `ignore_comment_clauses` for templated comments @kieronellis 

Could you raise a new issue for this, since this one is closed?
