### ISSUE TITLE
support SQLite dialect

### ISSUE THREAD

**Issue by tlgs** [sqlfluff/sqlfluff#1452]
SQLite is the the [most used](https://sqlite.org/mostdeployed.html) database engine in the world. I believe it would be a great addition to this project to support its dialect.

Following the discussion on #1450, it should be similar to `Postgres` with one difference being the `REGEXP` keyword.

**Comment by WittierDinosaur** [comment]
I think we should avoid cloning Postgres, as the language isn't an extension of it. We shold clone ANSI, and copy-paste the relevant functionality out of Postgres

**Comment by tunetheweb** [comment]
I chose to clone Postgres for this reason:

https://en.wikipedia.org/wiki/SQLite
> SQLite generally follows PostgreSQL syntax.
