### ISSUE TITLE
TSQL PIVOT/UNPIVOT parsing error

### ISSUE THREAD

**Issue by tkachenkomaria244** [sqlfluff/sqlfluff#1467]
PIVOT/UNPIVOT statements causes parsing error.
Syntax description: [from-using-pivot-and-unpivot](https://docs.microsoft.com/en-us/sql/t-sql/queries/from-using-pivot-and-unpivot?view=sql-server-ver15)

## Example
```sql
select 
	  tbl.column_name
	, [1] as Lvl_1 
	, [2] as Lvl_2
	, [3] as Lvl_3
from 
	table_name tbl
pivot
	(max(value) for rn in([1],[2],[3]) ) as pvt
```
parsing result:

```
[L:  7, P:  2]      |                from_expression:
[L:  7, P:  2]      |                    [META] indent:
[L:  7, P:  2]      |                    from_expression_element:
[L:  7, P:  2]      |                        table_expression:
[L:  7, P:  2]      |                            table_reference:
[L:  7, P:  2]      |                                identifier:                   'table_name'
[L:  7, P: 12]      |                        whitespace:                           ' '
[L:  7, P: 13]      |                        alias_expression:
[L:  7, P: 13]      |                            identifier:                       'tbl'
[L:  7, P: 16]      |                    newline:                                  '\n'
[L:  8, P:  1]      |                    [META] dedent:
[L:  8, P:  1]      |                unparsable:                                   !! Expected: 'Nothing...'
[L:  8, P:  1]      |                    raw:                                      'pivot'
[L:  8, P:  6]      |                    newline:                                  '\n'
```

## Expected Behaviour
No parsing errors, construction is parsed as special pivot segment

## Observed Behaviour
```
==== parsing violations ====
L:   8 | P:   1 |  PRS | Line 8, Position 1: Found unparsable section:
                       | 'pivot\n\t(max(value) for rn in([1],[2],[3]...'
```

## Dialect
`dialect = tsql`

## Version
`Python 3.9.6`
`sqlfluff, version 0.6.6`

**Comment by michael-the1** [comment]
We just hit this exact same bug yesterday, but in Snowflake instead! Good to see the PR for TSQL up already, not sure how much work it'll be to adapt to Snowflake too. I'll have a look at it today as well, though I'm not very familiar with the sqlfluff codebase.

**Comment by tunetheweb** [comment]
The code is very nice and friendly to work with and happy to help guide you through this. It's great to know how to add new syntax when you hit these types of issues.

However, I added PIVOT statement support to Snowflake in 6.5.0 (see #1353) so if you're on that version already then maybe we've missed some particular syntax. Could you open a new issue with an example of the the exact SQL being used and can discuss it there?

**Comment by michael-the1** [comment]
Yes, I'm able to reproduce the bug on 6.6.0. I'll open a new issue. Thanks for the help!
