### ISSUE TITLE
Fix `profiles_dir` override behavior

### ISSUE THREAD

**Issue by k-aranke** [sqlfluff/sqlfluff#1468]
According to the [DBT docs](https://docs.getdbt.com/dbt-cli/configure-your-profile#using-a-custom-profile-directory), the `DBT_PROFILES_DIR` environment variable overrides the default profiles directory.

However, in SQLFluff, the `PROFILES_DIR` environment variable **will not** take precedence over the `profiles_dir` configuration as illustrated in the code snippet below:

https://github.com/sqlfluff/sqlfluff/blob/28d1ca27ce6a9e5421f720c6bcb91f046285662c/src/sqlfluff/core/templaters/dbt.py#L178-L183

Here's my proposal to fix the problem (happy to write a PR):
1. Switch the order of arguments to the `or` clause above
2. Change the environment variable from `PROFILES_DIR` to `DBT_PROFILES_DIR` to remain consistent with DBT

Let me know what you think. Thanks!

**Comment by barrywhart** [comment]
I think this works correctly now in the latest dbt templater. See #2539, which explicitly tests the ability to specify the profiles directory using an environment variable.
