### ISSUE TITLE
PostgreSQL functions with SETOF does not parse

### ISSUE THREAD

**Issue by ErunamoJAZZ** [sqlfluff/sqlfluff#1520]
## Expected Behaviour
At least show internal lint issues

## Observed Behaviour
Can't parse the function because of the `setof`

## Steps to Reproduce
```
CREATE OR REPLACE FUNCTION public.postgres_setof_test()
 RETURNS SETOF text
 LANGUAGE sql
 STABLE STRICT
AS $function$
  select unnest(array['hi', 'test'])
$function$
;
```
sqlfluff can't parse showing a message
_Found unparsable section: 'CREATE OR REPLACE FUNCTION crw_public.po...'_

## Dialect
postgres

## Version
Python 3.8.10
sqlfluff, version 0.6.8

## Configuration
```
[sqlfluff]
dialect = postgres

[sqlfluff:rules]
tab_space_size = 2
```

**Comment by tunetheweb** [comment]
Fixed in #1522
