### ISSUE TITLE
Overly permissive `IfExpressionStatement` in T-SQL

### ISSUE THREAD

**Issue by tunetheweb** [sqlfluff/sqlfluff#1556]
#1469 introduced `IfExpressionStatement` to tsql dialect with the following syntax:

```py
    match_grammar = Sequence(
        OneOf(
            Sequence(Ref("IfNotExistsGrammar"), Ref("SelectStatementSegment")),
            Sequence(Ref("IfExistsGrammar"), Ref("SelectStatementSegment")),
            "IF",
            Ref("ExpressionSegment"),
        ),
        Ref("StatementSegment"),
        Sequence("ELSE", Ref("StatementSegment"), optional=True),
    )
```

However, because of the optional, this can match to the following:

```py
        Ref("ExpressionSegment"),
        Ref("StatementSegment"),
```

Which seems overly permissive. I noticed it matching some things it shouldn't.

@ericmuijs looks like you added, so what's your thoughts here?
@jpers36 interested if you have an opinion too.

**Comment by jpers36** [comment]
@tunetheweb IF/ELSE is next priority to fix on my list.  BEGIN/END is critical to the IF/ELSE fix since IF/ELSE relies so much on BEGIN/END as a wrapper; and IF/ELSE is the biggest blocker to rolling out SQLFluff to my team.
