### ISSUE TITLE
Code clean up questions

### ISSUE THREAD

**Issue by tunetheweb** [sqlfluff/sqlfluff#1575]
Some questions, while we've no queued PRs (or at least only a short queue!):

- [x] - Should we move `test/fixtures/parser/` folder to `test/fixtures/dialects` inline with how the code is stored? Raised as #1585 
- [x] - Should we switch dialect keywords from `dialect_keywords.py` to `keywords_dialect.py` so they're listed with the dialects? Raised as #1584

**Comment by barrywhart** [comment]
No opinion on the first. +1 on the second.

**Comment by alanmcruickshank** [comment]
+1 on the second.

I think +1 on the first, that does feel more useful and in line with the rest of the project. Also not strong views though 🤷  - happy either way.
