### ISSUE TITLE
DBT tests failing

### ISSUE THREAD

**Issue by jpers36** [sqlfluff/sqlfluff#1593]
DBT tests are failing on what appear to be unrelated PRs.

## Expected Behaviour

DBT tests run as normal.

## Observed Behaviour

Errors such as the following:

dbt018 create: /home/runner/work/sqlfluff/sqlfluff/.tox/dbt018
dbt018 installdeps: -Urrequirements.txt, -Urrequirements_dev.txt, requests, plugins/sqlfluff-plugin-example, -e., dbt==0.18.2, plugins/sqlfluff-templater-dbt
ERROR: invocation failed (exit code 1), logfile: /home/runner/work/sqlfluff/sqlfluff/.tox/dbt018/log/dbt018-1.log
================================== log start ===================================
Processing ./plugins/sqlfluff-plugin-example
  DEPRECATION: A future pip version will change local packages to be built in-place without first copying to a temporary directory. We recommend you use --use-feature=in-tree-build to test your packages with this new behavior before it becomes the default.
   pip 21.3 will remove support for this functionality. You can find discussion regarding this at https://github.com/pypa/pip/issues/7555.
Processing ./plugins/sqlfluff-templater-dbt
    ERROR: Command errored out with exit status 1:
     command: /home/runner/work/sqlfluff/sqlfluff/.tox/dbt018/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-84knc4ug/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-84knc4ug/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-pknnkhu1
         cwd: /tmp/pip-req-build-84knc4ug/
    Complete output (9 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-84knc4ug/setup.py", line 10, in <module>
        version = config.get("sqlfluff", "version")
      File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/configparser.py", line 781, in get
        d = self._unify_values(section, vars)
      File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/configparser.py", line 1149, in _unify_values
        raise NoSectionError(section) from None
    configparser.NoSectionError: No section: 'sqlfluff'
    ----------------------------------------
WARNING: Discarding file:///home/runner/work/sqlfluff/sqlfluff/plugins/sqlfluff-templater-dbt. Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

=================================== log end ====================================
ERROR: could not install deps [-Urrequirements.txt, -Urrequirements_dev.txt, requests, plugins/sqlfluff-plugin-example, -e., dbt==0.18.2, plugins/sqlfluff-templater-dbt]; v = InvocationError('/home/runner/work/sqlfluff/sqlfluff/.tox/dbt018/bin/python -m pip install -Urrequirements.txt -Urrequirements_dev.txt requests plugins/sqlfluff-plugin-example -e. dbt==0.18.2 plugins/sqlfluff-templater-dbt', 1)
___________________________________ summary ____________________________________
ERROR:   dbt018: could not install deps [-Urrequirements.txt, -Urrequirements_dev.txt, requests, plugins/sqlfluff-plugin-example, -e., dbt==0.18.2, plugins/sqlfluff-templater-dbt]; v = InvocationError('/home/runner/work/sqlfluff/sqlfluff/.tox/dbt018/bin/python -m pip install -Urrequirements.txt -Urrequirements_dev.txt requests plugins/sqlfluff-plugin-example -e. dbt==0.18.2 plugins/sqlfluff-templater-dbt', 1)

## Steps to Reproduce

Submit a pull request.

**Comment by tunetheweb** [comment]
Yes we're aware. #1583 will fix it but not quite ready to merge yet.

**Comment by tunetheweb** [comment]
Fixed now!
