### ISSUE TITLE
Handle dbt-plugin separation in super/mega linter packages

### ISSUE THREAD

**Issue by tunetheweb** [sqlfluff/sqlfluff#1600]
SQLFluff 0.7.0 will separate dbt to a separate `sqlfluff-templater-dbt` pip package. This is not installed by default any more so is an optional extra.

I'm aware of at least two linter packages that bundle SQLFluff in as a linter:
- [ ] - The [GitHub Super-Linter](https://github.com/github/super-linter) creates a Docker image of commonly used linters to allow people to use linters like SQLFluff from one easy source (it's how I discovered about this project btw). https://github.com/github/super-linter/issues/2051 https://github.com/github/super-linter/pull/2052
- [ ] - The [Mega-Linter](https://github.com/nvuillam/mega-linter) is a fork of the Github Super-Linter which does similar. https://github.com/nvuillam/mega-linter/issues/842 https://github.com/nvuillam/mega-linter/pull/861

I will raise issues with both these projects to include the `sqlfluff-templater-dbt` pip package by default from 0.7.0 so any DBT users using SQLFluff through these can continue to do so.

This issue is just a reference issue for me to refer those projects back to this.

**Comment by barrywhart** [comment]
No, pre-commit sets up its own private environment. It supports tools in most any language, and it manages those automatically. It's pretty slick!

**Comment by tunetheweb** [comment]
Closing as decided not to include the dbt templater as will need dbt packages installed too so not a good fit for those super/mega linters anyway.
