### ISSUE TITLE
PostgreSQL: Support SELECT INTO statement

### ISSUE THREAD

**Issue by JakubKryszczuk** [sqlfluff/sqlfluff#1606]
SQL Fluff doesn't support `SELECT INTO` statement ([docs](https://www.postgresql.org/docs/9.1/sql-selectinto.html)). `INTO` is transformed to alias of the last column in SELECT.  Disabling the rule L012 doesn't help.

Example query:
```
SELECT
    foo,
    bar
INTO baz
FROM qux;
```

## Expected Behaviour
```
SELECT
    foo,
    bar
INTO baz
FROM qux;
```

## Observed Behaviour
```
SELECT
    foo,
    bar
    AS into baz
FROM qux;
```

## Dialect

PostgreSQL

## Version
SQLFluff 0.6.2
Python 3.9

**Comment by tres1N** [comment]
Hi, i would like to work on this issue:)
