### ISSUE TITLE
[Question] How to deal with Dbt packages (in Jinja mode)?

### ISSUE THREAD

**Issue by CyberShadow** [sqlfluff/sqlfluff#1645]
SQLFluff seems to deal fairly well with Dbt macros in plain Jinja mode. The first significant obstacle that I've encountered is Dbt packages, which allow referencing macros declared elsewhere.

Even if the paths to files declaring macros added in other packages were to be added to SQLFluff's search path, it seems that currently SQLFluff doesn't have any mechanisms to deal with syntax which references them. E.g., if the Dbt package is called `utils`, a macro call would look like `{% utils.macro_name(...) %}`. SQLFluff fails parsing this with `Undefined jinja template variable: 'utils'`.

Would this be feasible to address somehow (other than using the full Dbt mode, which has its own set of challenges)?

**Comment by tunetheweb** [comment]
Can you dummy this in your `.sqlfluff` file? My understanding is that's one of the main difference's between Jinja and DBT in SQLFluff - jinja has no real concept of macros, except those dummied in `.sqlfluff`, whereas DBT pulls in the DBT ones.

**Comment by CyberShadow** [comment]
I don't think there is a way to do this for things like `x.y(...)` (where `x` is a package name).

**Comment by tunetheweb** [comment]
Ah you're right. And seems to be a core Jinja restriction, rather than a SQLFluff issue so not sure easily solved 😞 Unless it's hacked around by converting to `x_y(...)`. but seems a bit hacky.

**Comment by jpy-git** [comment]
Hi @CyberShadow, If you're still interested in being able to mock these dbt macros via Jinja, @Tonkonozhenko implemented the ability to do this sort of thing in #1976.

You can find the relevant details on library templating [here](https://docs.sqlfluff.com/en/stable/configuration.html#library-templating)

Basically you can just define a module called `utils` and have a mock function inside called `macro_name` and that can then be referenced via `{% utils.macro_name(...) %}`

Closing
