### ISSUE TITLE
TSQL L025 linter exception

### ISSUE THREAD

**Issue by jpers36** [sqlfluff/sqlfluff#1669]
```
SELECT 
	a
FROM b
```

## Expected Behaviour

This SQL should lint

## Observed Behaviour

CRITICAL   [L025] Applying rule L025 threw an Exception: _level_to_int() takes 1 positional argument but 2 were given
Traceback (most recent call last):
  File "C:\users\jpersons\source\repos\sqlfluff\src\sqlfluff\core\rules\base.py", line 304, in crawl
    res = self._eval(
  File "C:\users\jpersons\source\repos\sqlfluff\src\sqlfluff\rules\L020.py", line 109, in _eval
    return self._lint_references_and_aliases(
  File "C:\users\jpersons\source\repos\sqlfluff\src\sqlfluff\rules\L025.py", line 56, in _lint_references_and_aliases
    for tr in r.extract_possible_references(
  File "C:\users\jpersons\source\repos\sqlfluff\src\sqlfluff\dialects\dialect_ansi.py", line 681, in extract_possible_references
    level = self._level_to_int(level)
TypeError: _level_to_int() takes 1 positional argument but 2 were given
CRITICAL   [L026] Applying rule L026 threw an Exception: _level_to_int() takes 1 positional argument but 2 were given
Traceback (most recent call last):
  File "C:\users\jpersons\source\repos\sqlfluff\src\sqlfluff\core\rules\base.py", line 304, in crawl
    res = self._eval(
  File "C:\users\jpersons\source\repos\sqlfluff\src\sqlfluff\rules\L026.py", line 97, in _eval
    return super()._eval(segment, parent_stack, dialect, **kwargs)
  File "C:\users\jpersons\source\repos\sqlfluff\src\sqlfluff\rules\L020.py", line 109, in _eval
    return self._lint_references_and_aliases(
  File "C:\users\jpersons\source\repos\sqlfluff\src\sqlfluff\rules\L026.py", line 72, in _lint_references_and_aliases
    tbl_refs = r.extract_possible_references(level=r.ObjectReferenceLevel.TABLE)
  File "C:\users\jpersons\source\repos\sqlfluff\src\sqlfluff\dialects\dialect_ansi.py", line 681, in extract_possible_references
    level = self._level_to_int(level)
TypeError: _level_to_int() takes 1 positional argument but 2 were given
== [C:\Users\jpersons\Documents\LinterTest.sql] FAIL
L:   1 | P:   1 | L025 | Unexpected exception: _level_to_int() takes 1 positional
                       | argument but 2 were given; Could you open an issue at
                       | https://github.com/sqlfluff/sqlfluff/issues ? You can
                       | ignore this exception for now, by adding '--noqa: L025'
                       | at the end of line 1
L:   1 | P:   1 | L026 | Unexpected exception: _level_to_int() takes 1 positional
                       | argument but 2 were given; Could you open an issue at
                       | https://github.com/sqlfluff/sqlfluff/issues ? You can
                       | ignore this exception for now, by adding '--noqa: L026'
                       | at the end of line 1
L:   1 | P:   1 | L036 | Select targets should be on a new line unless there is
                       | only one select target.
L:   1 | P:   7 | L001 | Unnecessary trailing whitespace.
L:   2 | P:   1 | L004 | Incorrect indentation type found in file.
L:   3 | P:   6 | L009 | Files must end with a trailing newline.
All Finished!

## Steps to Reproduce

run lint on the above code

## Dialect

TSQL

## Version

most recent main (b186b538)
Python 3.9.6

## Configuration

vanilla

**Comment by tunetheweb** [comment]
It's this:

https://github.com/sqlfluff/sqlfluff/blob/42aa81e06d64754370f646b49901c887e3f61f59/src/sqlfluff/dialects/dialect_tsql.py#L401

Replacing that with the actual ANSI definition fixes it:

```py
    from typing import Union
    @staticmethod
    def _level_to_int(level: Union[ObjectReferenceLevel, int]) -> int:
        # If it's an ObjectReferenceLevel, get the value. Otherwise, assume it's
        # an int.
        level = getattr(level, "value", level)
        assert isinstance(level, int)
        return level
```

Wonder why those aren't equivalent?

Any Python people (@barrywhart / @alanmcruickshank ) know this?

**Comment by WittierDinosaur** [comment]
It hasn't been copied across as a static method. Methods defined in a class implicitly take `self` as their first argument.

**Comment by tunetheweb** [comment]
Thanks - that works!
