### ISSUE TITLE
Increase the usage of augmented assignment statements

### ISSUE THREAD

**Issue by elfring** [sqlfluff/sqlfluff#1685]
:eyes: Some source code analysis tools can help to find opportunities for improving software components.
:thought_balloon: I propose to [increase the usage of augmented assignment statements](https://docs.python.org/3/reference/simple_stmts.html#augmented-assignment-statements "Augmented assignment statements") accordingly.

Would you like to integrate anything from a transformation result which can be generated by a command like the following?
(:point_right: Please check also for questionable change suggestions because of an evolving search pattern.)
```
[Markus_Elfring@fedora lokal]$ perl -p -i.orig -0777 -e 's/^(?<indentation>\s+)(?<target>\S+)\s*=\s*\k<target>[ \t]*(?<operator>[+\-%&|^@]|\*\*?|\/\/?|<<|>>)/$+{indentation}$+{target} $+{operator}=/gm' $(find ~/Projekte/sqlfluff/lokal -name '*.py')
```

**Comment by tunetheweb** [comment]
Are you talking in our own source code? Or in the code we parse? Because very few SQL dialects AFAIK allow "+=" type operations ([T-SQL is one of the few AFAIK](https://docs.microsoft.com/en-us/sql/t-sql/language-elements/add-equals-transact-sql?view=sql-server-ver15))

**Comment by elfring** [comment]
:thought_balloon: I suggest to improve a few implementation details in the Python scripts of this development repository.

**Comment by barrywhart** [comment]
@elfring: Can you explain how this change would benefit users or maintainers of SQLFluff? I'm unsure how to justify asking contributors to work on this compared to other issues.

**Comment by elfring** [comment]
:thought_balloon: I suggest to take some information better into account [which was published also together with release notes for Python 2](https://docs.python.org/3/whatsnew/2.0.html#augmented-assignment "Augmented assignments").
How do you think about to support another bit of collateral evolution in such a software area? :thinking:

Would you find any change suggestions relevant which can be generated by the shown Perl command (for example)?

**Comment by tunetheweb** [comment]
Personally I don't see the value in switching to these. It's handy to have the syntax support for those that expect it and want to use this, but don't think it's going to have any material difference to make the effort worthwhile to convert existing code to this format.

Unless I'm missing something?

**Comment by elfring** [comment]
:crystal_ball: Under which circumstances will development interests grow also for [information from the release notes for Python 2](https://docs.python.org/3/whatsnew/2.0.html#augmented-assignment "Augmented assignments")?

-----

:thought_balloon: How will the support evolve for the application of compound (or combined) assignments in SQL software areas?

**Comment by tunetheweb** [comment]
When there’s clear benefits. What are the benefits of moving to this? And do the outweigh the effort?

**Comment by elfring** [comment]
Which explanations do you still miss from the referenced information sources?

**Comment by tunetheweb** [comment]
What are the benefits of moving to this for an existing code base?

**Comment by elfring** [comment]
:thought_balloon: I imagine that affected components can be adjusted another bit for more desirable software run time characteristics, can't they?

**Comment by tunetheweb** [comment]
So you're saying augmented assignments have clear and measurable performance improvements for those that have moved to them? Any case studies of that?

If this was true, and moving to them was easy I'd be all for it. But seems to me there is effort to search and replace, risk to ensure it's not broken anything (so more effort to manually review this).

Additionally it will fill out git history with a number of changes which, as I have said many times, you have not given any demonstrable any benefit for.

So I again ask: What are the benefits of moving to this? And do they outweigh the effort?

If we can't get clear answers on that then I think we should close this issue.

**Comment by elfring** [comment]
>So you're saying augmented assignments have clear and measurable performance improvements for those that have moved to them?

Can you accept the explanation from the Python documentation?

“…
In the augmented version, `x` is only evaluated once. Also, when possible, the actual operation is performed _in-place_, meaning that rather than creating a new object and assigning that to the target, the old object is modified instead.
…”

:thought_balloon: Do you accordingly expect positive effects for the software run time characteristics?


>Any case studies of that?

The usage of specific programming interfaces is growing in some areas, isn't it? :thinking:
Would you like to take another look at components (which I touched so far)?


>If this was true, and moving to them was easy I'd be all for it.

Some file transformation tools can help considerably.


>But seems to me there is effort to search and replace, and risk to ensure it's not broken anything (so more effort to manually review this).

There are the usual recurring concerns to consider (also for development approaches).

**Comment by elfring** [comment]
:thought_balloon: How will the chances evolve that the following change possibilities can support further constructive development considerations?

```diff
diff --git a/plugins/sqlfluff-templater-dbt/sqlfluff_templater_dbt/templater.py b/plugins/sqlfluff-templater-dbt/sqlfluff_templater_dbt/templater.py
index 8e27a8d9..8c76ce92 100644
--- a/plugins/sqlfluff-templater-dbt/sqlfluff_templater_dbt/templater.py
+++ b/plugins/sqlfluff-templater-dbt/sqlfluff_templater_dbt/templater.py
@@ -421,8 +421,8 @@ class DbtTemplater(JinjaTemplater):
         #    2. Append the count from #1 above to the node.raw_sql and
         #       compiled_sql objects, both of which have had the trailing
         #       newlines removed by the dbt-templater.
-        node.raw_sql = node.raw_sql + "\n" * n_trailing_newlines
-        compiled_sql = compiled_sql + "\n" * n_trailing_newlines
+        node.raw_sql += "\n" * n_trailing_newlines
+        compiled_sql += "\n" * n_trailing_newlines
 
         raw_sliced, sliced_file, templated_sql = self.slice_file(
             node.raw_sql,
diff --git a/src/sqlfluff/core/parser/grammar/base.py b/src/sqlfluff/core/parser/grammar/base.py
index d19587ad..eae4bb80 100644
--- a/src/sqlfluff/core/parser/grammar/base.py
+++ b/src/sqlfluff/core/parser/grammar/base.py
@@ -744,7 +744,7 @@ class BaseGrammar(Matchable):
                     )
                 new_elems = new_elems[:idx] + insert + new_elems[idx:]
             elif at is None:
-                new_elems = new_elems + insert
+                new_elems += insert
             else:
                 new_elems = new_elems[:at] + insert + new_elems[at:]
         if remove:
diff --git a/src/sqlfluff/rules/L003.py b/src/sqlfluff/rules/L003.py
index eae869ad..6bdf6773 100644
--- a/src/sqlfluff/rules/L003.py
+++ b/src/sqlfluff/rules/L003.py
@@ -344,7 +344,7 @@ class Rule_L003(BaseRule):
             return LintResult(memory=memory)
 
         if raw_stack and raw_stack[-1] is not context.segment:
-            raw_stack = raw_stack + (context.segment,)
+            raw_stack += (context.segment,)
         res = self._process_raw_stack(
             raw_stack,
             memory,
diff --git a/src/sqlfluff/rules/L035.py b/src/sqlfluff/rules/L035.py
index d75d811e..b4f23ba3 100644
--- a/src/sqlfluff/rules/L035.py
+++ b/src/sqlfluff/rules/L035.py
@@ -69,5 +69,5 @@ class Rule_L035(BaseRule):
                         fixes.append(
                             LintFix("delete", context.segment.segments[walk_idx])
                         )
-                        walk_idx = walk_idx - 1
+                        walk_idx -= 1
         return None
diff --git a/src/sqlfluff/rules/L036.py b/src/sqlfluff/rules/L036.py
index ed5533b8..80fddbf7 100644
--- a/src/sqlfluff/rules/L036.py
+++ b/src/sqlfluff/rules/L036.py
@@ -317,7 +317,7 @@ class Rule_L036(BaseRule):
                             idx += 1
 
             if copy_with_newline:
-                insert_buff = insert_buff + [NewlineSegment()]
+                insert_buff += [NewlineSegment()]
 
             fixes += [
                 # Insert the select_clause in place of the first newlin in the
diff --git a/src/sqlfluff/rules/L049.py b/src/sqlfluff/rules/L049.py
index b82a1edc..6b9e34d5 100644
--- a/src/sqlfluff/rules/L049.py
+++ b/src/sqlfluff/rules/L049.py
@@ -97,7 +97,7 @@ class Rule_L049(Rule_L006):
                         ] = [WhitespaceSegment()]
                         edit = whitespace_segment + edit
                     if self._missing_whitespace(next_seg, before=False):
-                        edit = edit + [WhitespaceSegment()]
+                        edit += [WhitespaceSegment()]
                     return LintResult(
                         anchor=operator,
                         fixes=[
```
