### ISSUE TITLE
TSQL: allow for nested comment blocks

### ISSUE THREAD

**Issue by jpers36** [sqlfluff/sqlfluff#1716]
TSQL allows for nested comment blocks:

https://docs.microsoft.com/en-us/sql/t-sql/language-elements/slash-star-comment-transact-sql?view=sql-server-ver15#remarks

For example:

```
/* Outer /* Inner */ Outer */
```

## Expected Behaviour

The above parses as one whole comment block

## Observed Behaviour

The above fails to parse since the lexer ends the comment block after the first ```*/```.

## Steps to Reproduce

See above

## Dialect

TSQL

## Version

Latest main (9041ed61)
Python 3.9.6

## Configuration

Vanilla

**Comment by jpy-git** [comment]
got a solution for this, will create a PR:

![image](https://user-images.githubusercontent.com/80432516/144485782-1d045d15-1331-4967-ade0-89c4e85a1ddb.png)

(If you look at the syntax highlighting it looks like vscode can't handle these comment blocks 😛 )
