### ISSUE TITLE
MySQL can't parse SELECT with "INTO OUTFILE"

### ISSUE THREAD

**Issue by serafin-tech** [sqlfluff/sqlfluff#1740]
## Observed Behaviour

Exact error message: CRITICAL   [L031] Applying rule L031 threw an Exception: Fixes must provide an anchor. 

## Steps to Reproduce

payload to generate the issue:
```
SELECT
  imie, nazwisko
FROM
  pracownicy
INTO OUTFILE '/tmp/outfile.txt';

```

command: `sqlfluff lint --dialect=mysql payload.sql`

## Dialect

mysql

## Version
```
$ python3 --version
Python 3.8.10
$ sqlfluff --version
sqlfluff, version 0.7.1
```

## Configuration

no specific config applied other than those in CLI above, fresh install, first linting and the issue occured

**Comment by barrywhart** [comment]
SQLFluff has a parse error on the test query. If I swap the `INTO OUTFILE` and the `FROM`, it parses and lints okay:
```
SELECT
  imie, nazwisko
INTO OUTFILE '/tmp/outfile.txt'
FROM
  pracownicy
```

This looks like a grammar issue, as the MySQL docs include examples with the `INTO OUTFILE` occurring before **or** after the `FROM`.

https://dev.mysql.com/doc/refman/8.0/en/select-into.html
