### ISSUE TITLE
New TSQL rule: don't create stored procedures with sp_ prefix

### ISSUE THREAD

**Issue by jpers36** [sqlfluff/sqlfluff#1745]
https://docs.microsoft.com/en-us/sql/t-sql/statements/create-procedure-transact-sql?view=sql-server-ver15#procedure_name

The sp_ prefix is used by Microsoft to identify system procedures.  Using the sp_ prefix affects performance slightly since SQL Server performs an unnecessary check against the system schema.  It could also break processes if there is a naming conflict.

We should be able to create a linter for TSQL that identifies and flags the creation of stored procedures with this issue.

Anti-pattern:
```
CREATE PROCEDURE dbo.sp_pull_data
AS
SELECT
    [ID],
    [DataDate],
    [CaseOutput]
FROM table1
```
Pattern:

```
dbo.pull_data
```
or
```
dbo.usp_pull_data
```

**Comment by jpy-git** [comment]
Think this would be pretty simple to implement codewise. 

@tunetheweb do we have any other examples of rules that apply to a single dialect?
