### ISSUE TITLE
New rule suggestion: identify and flag RIGHT JOINs

### ISSUE THREAD

**Issue by jpers36** [sqlfluff/sqlfluff#1749]
RIGHT JOINs can always be rewritten as LEFT JOINs.  I find LEFT JOINs to be far more intuitive, so at least for my projects I have a standard that RIGHT JOINs should not be used.  If the community as a whole disagrees, this enhancement request can be rejected.

Anti-pattern:
```
SELECT
    a.col1,
    b.col2
FROM a
RIGHT JOIN b ON a.keyval = b.keyval
```

Pattern:
```
SELECT
    a.col1,
    b.col2
FROM b
LEFT JOIN a ON a.keyval = b.keyval
```

**Comment by jpy-git** [comment]
Can definitely make a rule to highlight this as it's a common style guide rule. 

I would maybe question if this could be difficult to autofix outside of the simplest case shown above
e.g.
```SQL
SELECT
    foo.a
    bar.b
FROM foo
RIGHT JOIN (
<some really comlicated subquery>
) as bar
ON foo.a = bar.a
```
or
```SQL
SELECT
    foo.a
    bar.b
    baz.c
FROM foo
LEFT JOIN bar
    ON foo.a = bar.a
RIGHT JOIN baz
    ON foo.a = baz.a
```

Maybe just flag the linting error, as it's probably best for the user to reassess their JOINs if they're using right joins.
Happy to apply an autofix in the simple case if you think it best though?

**Comment by jpers36** [comment]
I agree that this would be difficult to auto-fix.  I'm expecting just a linting error.

**Comment by jpy-git** [comment]
Cool I'll pull that together 😄
