### ISSUE TITLE
Rule 001 Deleting dbt snapshot line

### ISSUE THREAD

**Issue by bdelamotte** [sqlfluff/sqlfluff#1771]
_If this is a parsing or linting issue, please include a minimal SQL example which reproduces the issue, along with the `sqlfluff parse` output, `sqlfluff lint` output and `sqlfluff fix` output when relevant._

## Expected Behaviour
Remove whitespace but keep the following line at the top of the dbt model:
`{% snapshot dim_aggregated_brand_hierarchy_snapshot %}`

## Observed Behaviour
sqlfluff fix is removing the snapshot line.

## Steps to Reproduce
- sqlfluff parse  snapshots/dim_aggregated_brand_hierarchy.sql 
- sqlfluff fix snapshots/dim_aggregated_brand_hierarchy.sql
- press y to fix

## Dialect
snowflake

## Version
sqlfluff, version 0.7.0
Python 3.8.11

## Configuration
```
[sqlfluff]
templater = dbt
dialect = snowflake
rules = L001, L009


[sqlfluff:templater:dbt]
project_dir = .
profiles_dir = ./config
profile = infomart
```

Output of parse, lint, before the sqlfluff fix, and after sqlfluff fix.
[sqlfluff_lint_output.txt](https://github.com/sqlfluff/sqlfluff/files/7428815/sqlfluff_lint_output.txt)
[sqlfluff_parse_output.txt](https://github.com/sqlfluff/sqlfluff/files/7428816/sqlfluff_parse_output.txt)
[dim_aggregated_brand_hierarchy_after_fix.sql.txt](https://github.com/sqlfluff/sqlfluff/files/7428818/dim_aggregated_brand_hierarchy_after_fix.sql.txt)
[dim_aggregated_brand_hierarchy.sql.txt](https://github.com/sqlfluff/sqlfluff/files/7428820/dim_aggregated_brand_hierarchy.sql.txt)

**Comment by barrywhart** [comment]
I tried to reproduce this. When I run `sqlfluff lint` on your file, I get the error:
```
dbt.exceptions.CompilationException: Compilation Error in model issue_1771 (models/issue_1771.sql)
  Encountered unknown tag 'snapshot'.
    line 1
      {% snapshot dim_aggregated_brand_hierarchy_snapshot %}
```

Can you provide more info on how to reproduce this?

**Comment by barrywhart** [comment]
I found the dbt [documentation](https://docs.getdbt.com/docs/building-a-dbt-project/snapshots/#example) on snapshots.

**Comment by barrywhart** [comment]
I managed to reproduce this issue with a slightly modified SQL file (added a `target_schema` parameter). Note that the SQL file **must** be in the `snapshots/` directory in order for dbt to successfully compile it.
```
{% snapshot dim_aggregated_brand_hierarchy_snapshot %}

{{
    config(
      strategy='check',
      unique_key='aggregated_brand_hierarchy_id',
     target_schema='snapshots',
      check_cols='all'
    )
}}

select   
    aggregated_brand_hierarchy_id,
    pepsi_hierarchy_id,
    finance_hierarchy_id,
    aggregated_brand_lvl3,
    aggregated_brand_lvl2,
    aggregated_brand_lvl1, 
    brand_deck_name,
    is_in_slide

from {{ ref('dim_aggregated_brand_hierarchy') }}

{% endsnapshot %}
```

**Comment by barrywhart** [comment]
I did some preliminary investigation to inspect the output of the dbt compile step -- i.e., in `DbtTemplater.process()`, what is the value of `compiled_sql` before `sqlfluff fix` processes it. The `snapshot` line is **already blank** at that point. 

I'm still not sure this explains why it gets lost in the "fix" result, though. After all, SQLFluff preserves other kinds of templating such as `{% if %}` blocks. It appears that `{% snapshot %}` is some sort of dbt extension to Jinja.

Anyway, some progress...

**Comment by barrywhart** [comment]
I'm trying to determine where dbt processes and removes the `{% snapshot %}` open and close tags. I'm setting some breakpoints in both SQLFluff and the dbt source code. The 🐇 🕳️ goes pretty deep...

Here's a stack trace where I'm looking now:
```
-> fnames, config=self.config, formatter=self.linter.formatter
  /Users/bhart/dev/sqlfluff/plugins/sqlfluff-templater-dbt/sqlfluff_templater_dbt/templater.py(255)sequence_files()
-> for key, node in self.dbt_manifest.nodes.items():
  /Users/bhart/.pyenv/versions/3.7.9/envs/sqlfluff-3.7.9/lib/python3.7/site-packages/cached_property.py(36)__get__()
-> value = obj.__dict__[self.func.__name__] = self.func(obj)
  /Users/bhart/dev/sqlfluff/plugins/sqlfluff-templater-dbt/sqlfluff_templater_dbt/templater.py(140)dbt_manifest()
-> self.dbt_manifest = loader.load()
  /Users/bhart/.pyenv/versions/3.7.9/envs/sqlfluff-3.7.9/lib/python3.7/site-packages/dbt/parser/manifest.py(301)load()
-> parser_types
  /Users/bhart/.pyenv/versions/3.7.9/envs/sqlfluff-3.7.9/lib/python3.7/site-packages/dbt/parser/manifest.py(407)parse_project()
-> parser.parse_file(block)
  /Users/bhart/.pyenv/versions/3.7.9/envs/sqlfluff-3.7.9/lib/python3.7/site-packages/dbt/parser/snapshots.py(82)parse_file()
-> self.parse_node(block)
> /Users/bhart/.pyenv/versions/3.7.9/envs/sqlfluff-3.7.9/lib/python3.7/site-packages/dbt/parser/base.py(377)parse_node()
-> config: ContextConfig = self.initial_config(fqn)
```

Below, in `dbt.parser.base.parse_node()`, I'm looking at the file contents a couple of different wants. Note that `block.contents` is missing the `{% snapshot %}` open and close tags, but `block.file.contents` has them.

```
(Pdb) type(block)
<class 'dbt.parser.search.BlockContents'>
(Pdb) type(block.file)
<class 'dbt.contracts.files.SourceFile'>
(Pdb) block.contents
"\n\n{% if True %}\n-- 1. Save my comment, please\n{% endif %}\n\n{% if False %}\n-- 2. Save my comment, please\n{% endif %}\n\n{{\n    config(\n      strategy='check',\n      unique_key='c1',\n      target_schema='snapshots',\n      check_cols='all'\n    )\n}}\n\nselect\n    c1\nfrom\n    foo\n\n"
(Pdb) block.file.contents
"{% snapshot dim_aggregated_brand_hierarchy_snapshot %}\n\n{% if True %}\n-- 1. Save my comment, please\n{% endif %}\n\n{% if False %}\n-- 2. Save my comment, please\n{% endif %}\n\n{{\n    config(\n      strategy='check',\n      unique_key='c1',\n      target_schema='snapshots',\n      check_cols='all'\n    )\n}}\n\nselect\n    c1\nfrom\n    foo\n\n{% endsnapshot %}"
```

**Comment by barrywhart** [comment]
dbt has several custom Jinja tags, including the following (possibly others):
* `snapshot`
* `materialization`
* `test`

When Jinja parses one of these custom tags, it creates an instance of dbt's `BlockTag` class, defined [here](https://github.com/dbt-labs/dbt-core/blob/main/core/dbt/clients/_jinja_blocks.py).

In SQLFluff's dbt templater, we monkeypatch Jinja to intercept calls to `jinja2.Environment.from_string()`. Later in `sqlfluff.core.templaters.slicers.tracer.JinjaTracer._slice_template()`, we call `self.env.lex(self.raw_str)` to parse the raw code.

**Comment by barrywhart** [comment]
It's not yet clear to me that dbt actually renders a template containing `{% snapshot %}` and other custom tags. I found a class `BlockIterator` in the same file that defines `BlockTag`. That class defines a `find_blocks()` function, beginning with the following lines:
```
    def find_blocks(self, allowed_blocks=None, collect_raw_data=True):
        """Find all top-level blocks in the data."""
        if allowed_blocks is None:
            allowed_blocks = {'snapshot', 'macro', 'materialization', 'docs'}
```

It appears dbt _may be_ using a similar technique of calling Jinja's `lex()` function to extract tokens from the raw source, then doing its own custom processing to extract the code inside `{% snapshot %}` and other blocks.

Next steps:
* Understand what dbt is doing.
* Determine if we can (should) leverage this directly or create our own similar code. The risk of using it directly is that it'll be too brittle and dependent on specific versions of dbt.

**Comment by bdelamotte** [comment]
Thank you @barrywhart  for looking into this.

**Comment by barrywhart** [comment]
🙏🏽😊
