### ISSUE TITLE
Lint/fix macro files separately 

### ISSUE THREAD

**Issue by jranks123** [sqlfluff/sqlfluff#1779]
We love SQLFluff on our team, but we've found it is extremely slow on files that contain lots of macro calls.

I think this is because it lints any macros called from a model as part of the linting process. This seems unnecessary - why not lint them separately? If the macro is in a separate file, and I don't make a change to that file, I don't want the overheads of having to lint it, especially as macro linting is so slow in SQLFluff.

This is sadly preventing us from adding SQLFluff as a build step in our CI/CD

**Comment by barrywhart** [comment]
Can you provide an example file? Also, can you provide some timing information? "Extremely slow" may mean very different things to different people. As written, this issue may not be something anyone can work on.

FWIW, PR #1744 was merged recently, and it speeds up the parser, so it may help with your issue.

**Comment by barrywhart** [comment]
No feedback after 2 1/2 months. Closing.
