### ISSUE TITLE
New rule: COALESCE instead of CASE/IF when possible

### ISSUE THREAD

**Issue by iajoiner** [sqlfluff/sqlfluff#1797]
In all dialects that have `COALESCE` code such as `CASE WHEN num_cats IS NULL THEN 0 ELSE num_cats END` are bad practices because they are very long and need to be simplified as `COALESCE(num_cats, 0)` which is much shorter and a lot more readable.

**Comment by tunetheweb** [comment]
Is this different to [Rule_L043](https://docs.sqlfluff.com/en/stable/rules.html#sqlfluff.core.rules.Rule_L043)?

**Comment by iajoiner** [comment]
@tunetheweb Yes. Here CASE does not necessarily actually return a boolean. However we may expand the scope of L043 to include it.

**Comment by jpy-git** [comment]
Looking into this, agree it should be a refinement of L043
