### ISSUE TITLE
New rule: database & schema restrictions

### ISSUE THREAD

**Issue by iajoiner** [sqlfluff/sqlfluff#1800]
_Note: This is for general enhancements to the project. Please use the Bug report template instead to raise parsing/linting/syntax issues for existing supported dialects_
At some companies different databases & schemas serve different purposes. Some are secure. Others aren’t. Some are sandboxes not fit for production while others are for production. In order not to misuse data source it is a good idea to allow projects to prohibit usage of (or limit usage to) certain databases & schemas in their `.sqlfluff` file.

**Comment by tunetheweb** [comment]
@iajoiner you can remove the template text to make the issues more readable. I've edited them out of your current issues and raised #1792 to avoid this issue in future.

**Comment by tunetheweb** [comment]
@alanmcruickshank here's another example as discussed in https://github.com/sqlfluff/sqlfluff/issues/361#issuecomment-955778171
