### ISSUE TITLE
L049 also flags `UPDATE foo SET foo = NULL`

### ISSUE THREAD

**Issue by BarnabyShearer** [sqlfluff/sqlfluff#1801]
The new `Comparisons with NULL should use "IS" or "IS NOT"` rule is applying to the SET clause of UPDATE queries where `= NULL` is required.

**Comment by tunetheweb** [comment]
This was fixed in #1791 which will be included in the next release. If you could confirm you’re not seeing this when using the `main` branch that would be good.

**Comment by BarnabyShearer** [comment]
Sorry I checked open bugs but not closed; this is indeed fixed thank you very much.
