### ISSUE TITLE
GROUPS/USER Query Errors in Redshift

### ISSUE THREAD

**Issue by tdstark** [sqlfluff/sqlfluff#1805]
Currently, any queries which CREATE/ALTER USER/GROUP permissions in Redshift throw errors. These will likely need to be added to the Redshift dialect.

## Expected Behaviour
The following four queries throw errors:
`CREATE USER test CREATEUSER PASSWORD :TEST_PASSWORD;`
`CREATE GROUP test_group;`
`ALTER GROUP test_group ADD USER new_user;`
`ALTER USER power_user WITH SYSLOG ACCESS UNRESTRICTED;`

## Observed Behaviour
Each one of these statements throws errors.

## Steps to Reproduce
Run `sqlfluff lint` while pointing at a .sql script with the aformentioned queries.

## Dialect
Redshift

## Version
`v0.7.1`

## Configuration
Default configuration

**Comment by tunetheweb** [comment]
This is a great first issue for anyone looking to start contributing to SQLFluff: https://github.com/sqlfluff/sqlfluff/wiki/Contributing-Dialect-Changes
