### ISSUE TITLE
Should all rules be enabled by default?

### ISSUE THREAD

**Issue by tunetheweb** [sqlfluff/sqlfluff#1812]
Some thoughts from [another thread](https://github.com/sqlfluff/sqlfluff/issues/1687#issuecomment-946158751), that I think are worth pulling into it's own issue for discussion:

> I'm in two minds about disabling rules by default.
> 
> On one hand, there's some rules I disagree with (this being one, but also L028, L031, L032, L034, L035, L037, and L043) and think I'm probably not alone with some of those, and usually defaults should be the sensible options used by most.
> 
> On the other hand, having them all on by default, makes you look at a rule, evaluate it, and then decide if it's one for you or not - that is, it's an explicit decision to turn it off. I think that would happen less if we turned them off by default - i.e. people wouldn't evaluate whether to turn it on, and instead would ignore the non-default rules unless it was something they felt strongly about and wanted to enforce. And maybe that's OK? But maybe that's also a missed opportunity to look at these rules and see if you should be using them? L031 makes a lot of sense for small databases. Just not convinced it scales well.
> 
> And the other issue is, that the impression I get, is that some of the users don't realise it's OK to turn off rules. Most linters (flake8/black being the exception!) need customising to your preferences.

**Comment by pwildenhain** [comment]
Could we potentially get the best of both worlds here? Where we have only the most stable, most common sense rules enabled by default, but provide some sort of flag that allows users to run *all* the rules e.g. `--run-all-rules` so they could see for themselves the difference between the "default" and "all" and decide which rules they want to whitelist.

I know we've also discussed in past issues (#201) on having severity levels for our lints. These conversations feel like they are circling around the same concept/problem

**Comment by WittierDinosaur** [comment]
I think while we're in Beta we can still change this kind of behaviour, as long as it's announced and in the release notes. Also, separately, we are at 50/ 51 rules now. While we're in Beta, maybe we should start grouping them. eg. C01, C02, for core, D01,D02 for dialect dependant, T01, T02, for templaters, etc

**Comment by WittierDinosaur** [comment]
As long as we don't use the LXX namespace, we can also keep back-compatible aliases for them

**Comment by jpy-git** [comment]
I like @WittierDinosaur's idea of starting to group rules by the rule name prefix (C01, T03, etc.). 

I think if we were to do that then we could adjust the include/exclude rule options in the CLI/config to accept globs (or regex):
e.g.
```console
sqlfluff lint test.sql --rules C*
``` 
to just include core rules
or
```console
sqlfluff lint test.sql --exclude-rules T*
```
to include all rules except template rules

That way we can ship with all rules enabled in order to encourage more people to write good quality SQL, but still make it super simple for people to just enable the core rules in the config by either using the CLI examples above or in the config:
```ini
[sqlfluff]
rules = C*
```

**Comment by jpy-git** [comment]
was looking through old issues and noticed what I described above was also requested in #1445

**Comment by barrywhart** [comment]
Let's use the rule groupings defined in #811 to determine which rules to enable by default. I.e., I suggest by default, we only enable "core" rules.

**Comment by alanmcruickshank** [comment]
I think the intent of this rule is now resolved with rule reorg, grouping and disabling L031 by default.
