### ISSUE TITLE
DISTKEY/SORTKEY are unparseable in Redshift

### ISSUE THREAD

**Issue by tdstark** [sqlfluff/sqlfluff#1845]
## Expected Behaviour
Queries like the following ought to be parsable by the Redshift dialect:
```
CREATE TABLE table1
  (
  	column_1 INT,
  	column_2 VARCHAR(5)
  )
  DISTKEY (column_1)
  SORTKEY (column_1);
```
## Observed Behaviour
The aforementioned query is unparsable. This is likely due to the fact that `DISTKEY` and `SORTKEY` are not part of the Postgres dialect. These will need to be added to the Redshift dialect.

## Dialect
Redshift

## Version
`0.8.0`

## Configuration
Default

**Comment by WittierDinosaur** [comment]
Fixed by #1855
