### ISSUE TITLE
linting errors inconsistent in different os  environments (windows vs code/linux ec2/gitlab docker)

### ISSUE THREAD

**Issue by jnicoles1** [sqlfluff/sqlfluff#1847]
we are using latest version of sqlfluff and dbt :
errors on local (windows) are not consistent with ci pipeline ,
in local we don't see any errors but in ci we errors mostly L003 ,
and tested the code on linux machine - and the errors are different than both local and ci.

## Observed Behaviour
Linting errors on windows and Linux (gitlab ci ) are not consistent 
## Steps to Reproduce
Any sql file with 20-30 lines of code with joins, test the sqlfluff lint on windows vs code , and verify the same code in any linux machine

## Dialect
postgres
## Version
0.7.1
Include the output of `sqlfluff --version` along with your Python version

## Configuration
```
Include your SQLFluff configuration here
```

**Comment by tunetheweb** [comment]
I'm afraid there isn't enough information here for us to be able to help. It sounds to me like a file or newline encoding error, rather than necessarily something with SQLFluff. But if we have a minimal, reproducible, example then can look further into it.

**Comment by DimitriSam** [comment]
We have encountered the same issue with SQLFluff where its behavior differs between local environments and continuous integration (CI), specifically with respect to rule L003. Despite fixing all violations of the rule in our local environment, we have observed that the GitHub workflow can still flag violations that we did not see when running locally.

**Comment by sadeka4** [comment]
We have experienced the same problem for the L02 rule; the behavior is inconsistent across various CI environments. In one environment, it passes successfully whereas fails with errors in another one. Tried to reproduce the errors in our local environment; however, failed to do that. Any thoughts?

**Comment by manug25** [comment]
I am also facing the same issue for LT02 and CV10. It runs fine on local machine (mac m3 machine) but failing on the CI (Ubuntu latest 24.02).

**Comment by rhasenack** [comment]
Same here. I get different results in local development (mac m4), DBT Cloud IDE and DBT CI linting. 
All are running the same sqlfluff version

**Comment by stefiivanova** [comment]
Same here. Locally runs without error but not in CI jobs.

**Comment by maddypat** [comment]
Also experiencing this, specifically with indentation rules (L002, L003, L004) -- CI gets different results than local.

**Comment by jcpsantiago** [comment]
+1 with indentation rules.

**Comment by alexscott-ff** [comment]
+1 with exact same file and config locally (mac) and in CI (ubuntu). CI fails linting with an indentation error (relating to jinja syntax in dbt templater).
