### ISSUE TITLE
Formatting for executing stored procedures

### ISSUE THREAD

**Issue by fdw** [sqlfluff/sqlfluff#1861]
In T-SQL, a stored procedure can be called with
```sql
exec <name>
  @param1 = 'value'
  @param2 = 'value'
```

I could not find any rule in sqlfluff regarding such formatting. Would it be possible to force indentation for the parameters, for example?

**Comment by tunetheweb** [comment]
You need to include INDENT/DEDENT in the grammar.

I've added this to #2439
