### ISSUE TITLE
Order of application of rules affects computability

### ISSUE THREAD

**Issue by Gregory108** [sqlfluff/sqlfluff#1881]
When `SELECT` is uppercase and following `distinct` is lowercase AND the line is long enough to trigger carrying over, SQLFluff puts capitalised `DISTINCT` before carried-over `SELECT`. This breaks SQL syntaxis. 

I believe this is due to 3 Rules being applied simultaneously on the source text, rather than sequentially one after another:
1. Rule_L010 (Inconsistent capitalisation of keywords)
2. Rule_L016 (Line is too long) - the threshold to trigger it is between 49 and 87, so, probably, 60?
3. Rule_L041 (SELECT clause modifiers such as DISTINCT must be on the same line as SELECT.)

Thus the 3rd rule puts capitalised `DISTINCT` on the same line where `SELECT` was (but it is not there anymore).

Request:
```
SELECT
        *
    FROM
        `project_name.schema_name.table1`
    WHERE
        long_varname_to_trigger_Rule_L016_id in (SELECT distinct id FROM `project_name.schema_name.table2` WHERE deletedat IS NULL)
```

## Expected Behaviour
```
SELECT
        *
    FROM
        `project_name.schema_name.table1`
    WHERE
         long_varname_to_trigger_Rule_L016_id IN (SELECT DISTINCT
              id 
            FROM `project_name.schema_name.table2` WHERE deletedat IS NULL
         )
```

## Observed Behaviour
```
SELECT
    *
FROM
    `project_name.schema_name.table1`
WHERE
    long_varname_to_trigger_Rule_L016_id IN ( DISTINCT
        SELECT
            id
        FROM `project_name.schema_name.table2` WHERE deletedat IS NULL
    )
```

## Steps to Reproduce
Use the request above. Substitute `project_name.schema_name.table1/2` with any tables, available in your environment (and use corresponding variable names, but the 6th line of the request should stay long (>60 symbols)

## Dialect
- Jinja SQL in VSCode
- Standard SQL in BigQuery
- SQLFluff is not yet [configured for dbt specifics](https://docs.sqlfluff.com/en/stable/configuration.html?highlight=dbt#dbt-project-configuration)

## Version
- sqlfluff, version 0.7.1 and version 0.8.1 checked
- Python 3.8.9

## Configuration
Standard "vanilla" configuration, no tweaks of rules, no configuration files

**Comment by WittierDinosaur** [comment]
Ah - that's weird. Can you make a minimum viable example (ideally without Jinja), and we'll look into it

**Comment by barrywhart** [comment]
I'm testing with:
```
SELECT
        *
    FROM
        {{ source('src', 'table1') }}
    WHERE
        long_varname_to_trigger_Rule_L016_id in (SELECT distinct id FROM {{ source('src', 'table1') }} WHERE deletedat IS NULL)
```

**Comment by barrywhart** [comment]
I reproduced this issue using just two rules. This is my `.sqlfluff` file:
```
[sqlfluff]
dialect = bigquery
templater = dbt
rules = L016,L041
```

**Comment by barrywhart** [comment]
I reproduced it without using templating:
```
SELECT
        *
    FROM
        superverylongtablenamereallyreally1
    WHERE
        long_varname_to_trigger_Rule_L016_id in (SELECT distinct id FROM superverylongtablenamereallyreally2 WHERE deletedat IS NULL)
```

**Comment by barrywhart** [comment]
@Gregory108: I have a PR that fixes this: #1904. Great bug report, thanks!

**Comment by Gregory108** [comment]
@barrywhart Wow! A super quick and impressive resolution! Thank you so much!

**Comment by barrywhart** [comment]
No problem! You can thank the Atlanta Falcons. Once they fell behind 14-3 today, I needed a distraction. 🤣
