### ISSUE TITLE
sqlfluff cannot pass extract(dow from date)

### ISSUE THREAD

**Issue by cristianying** [sqlfluff/sqlfluff#1886]
## Expected Behaviour
be able to pass:
extract(dow from date)
## Observed Behaviour
failed to recognize dow as a non field
![image](https://user-images.githubusercontent.com/37324199/141391345-34908f88-ef39-4ef2-b0d7-26dd9f6cfe10.png)

## Steps to Reproduce
try to run sqlfluff on queries that contain extract(dow from date)
## Dialect
snowflake
## Version
Include the output of `sqlfluff --version` along with your Python version
sqlfluff --version     
sqlfluff, version 0.8.1

## Configuration
```
Include your SQLFluff configuration here
```

**Comment by DawidJanczak** [comment]
Just to expand a bit this also affects PostgreSQL. An example:
```
SELECT
  d.a,
  weekdays.day
FROM
  GENERATE_SERIES(CURRENT_DATE, CURRENT_DATE + INTERVAL '1000 days', '1 day') AS d(a)
LEFT JOIN GENERATE_SERIES(1, 7) AS weekdays(day)
  ON (EXTRACT(isodow FROM d.a))::integer = weekdays.day
```

Sqlfluff output:
```== [test.sql] FAIL                                                                                                     
L:   7 | P:  15 | L027 | Unqualified reference 'isodow' found in select with more
                       | than one referenced table/view.
All Finished 📜 🎉!

```

**Comment by jpy-git** [comment]
postgres part of this has been done
