### ISSUE TITLE
requires.io shows as "not found"

### ISSUE THREAD

**Issue by jpy-git** [sqlfluff/sqlfluff#1891]
Not sure who manages this:
![image](https://user-images.githubusercontent.com/80432516/141522865-ce61e5da-7d86-4fdc-9db7-1c4d2294f1ee.png)

Low prio, but nice to fix.

**Comment by barrywhart** [comment]
Can you explain this in more detail? What is requires.io, what does it mean that it says "requirements not found", and what work would be required to fix it?

**Comment by tunetheweb** [comment]
It’s the badge on the main README of this repo.

I looked into it before and saw other complaining and thought it had broken for everyone but found some repos where it worked. Couldn’t figure it out. Thought it might be related to the `main`/`master` change.

Think we should just remove it from the README. It looks poor that it’s broken.

**Comment by jpy-git** [comment]
@barrywhart Apologies should have been more clear!
As @tunetheweb says it's one of the badges on the README. 

I'm not overly familiar `requires.io` but from what I can see it checks that requirements files are using latest dependency packages, which for us isn't too relevant as we don't have any upper limit on our requirements.

Agree that we should probably just remove the badge as it makes it look as if somethings broken, even though it's not really used. I'll create a PR 👍

**Comment by tunetheweb** [comment]
Oh is that why it’s failing? The wildcards in the requirements.txt? That makes sense.

I did ask about this before in https://github.com/sqlfluff/sqlfluff/issues/1317 and due to the fact we offer an API we didn’t want to make our dependencies too strict to impact any dependent projects.
