### ISSUE TITLE
Format nested SQL statements

### ISSUE THREAD

**Issue by fdw** [sqlfluff/sqlfluff#1920]
I sometimes need to build dynamic SQL queries in SQL, so that I have to define queries first as a variable that will later be executed. For example (in TSQL):
```sql
declare @sql = 'select * from ' + @otherVariable + ' where column=1';
execute sp_executesql @sql
```

I'm not even sure this is possible, but if sqlfluff could also parse, check and format the query in `@sql`, that would be quite awesome!

**Comment by tunetheweb** [comment]
I'm curious as why you need to format it if you're just passing the SQL to the database? Are you wanting to format your code? What would that look like for above example?

**Comment by fdw** [comment]
The nested SQL is part of a larger SQL file that I need to maintain. I would like to automatically format all these files and have a similar format even for the nested statement so that it's easier to maintain.
Also, it's even harder to find errors in the nested statements, so if sqlfluff could do that, that would be a huge bonus!

**Comment by jpy-git** [comment]
@fdw Surely Jinja/dbt is a better approach to creating templated code, and they're already supported by the project?

Using templating is going to be much more readable than string concatenation.

**Comment by tunetheweb** [comment]
Plus one to @jpy-git 's suggestion.

I'm still not sure what you expect the formatted SQL to look like?

Like this?:

```sql
declare @sql = '
  select *
  from
' + @otherVariable + '
  where column=1
';
execute sp_executesql @sql

**Comment by fdw** [comment]
> Surely Jinja/dbt/sqlalchemy is a better approach to creating templated code, and they're already supported by the project?

Wish it were so, but I don't have anything available but SQL.
Basically, the task is to write a procedure where the table name is passed as a parameter. In TSQL, there is no other way to do that dynamically apart from the string concatenation here.
I'm not much of a fan, either 😉

> I'm still not sure what you expect the formatted SQL to look like?

My main goal is that it looks identical everywhere. Right now, no-one keeps me from formatting it differently each and every time I have to do something like this. The concrete formatting is not important (as long as it is sensible, f.e. not everything in one long line).

If that is out of scope for sqlfluff, I totally understand - it is hopefully quite rare. Still, I wanted to ask 🙂

**Comment by tunetheweb** [comment]
Well if not using a recognised templater, then the best I can suggest for consistency is somehow extracting the full SQL in a script and calling SQLFluff (either via the Python API on the command line), on the full SQL after variable subsitution and showing an error if it doesn't mean your style guide (e.g. lowercase `select` instead of `SELECT`). Have that part of a commit hook or CI to alert developers committing "bad code".

I think anything else beyond that really is out of scope I'm afraid.

**Comment by fdw** [comment]
Fair enough. Then thanks for your time and effort 🙂
