### ISSUE TITLE
Add chardet to setup.py installation requirements

### ISSUE THREAD

**Issue by MarkBird** [sqlfluff/sqlfluff#1925]
## Expected Behaviour

Able to run sqlfluff after `pip install sqlfluff==0.8.1`

## Observed Behaviour
```
import chardet
ModuleNotFoundError: No module named 'chardet'
```

## Steps to Reproduce

`pip install sqlfluff==0.8.1` on a system that doesn't have `chardet` installed.

## Version
sqlfluff version 0.8.1
python version 3.6.2

**Comment by jpy-git** [comment]
Good spot, I'll add this and there's a new release coming soon so hopefully should be able to get it in by then
