### ISSUE TITLE
Parsing issues with Spark trim command for both/leading/trailing

### ISSUE THREAD

**Issue by anzelpwj** [sqlfluff/sqlfluff#1935]
Spark SQL has a `TRIM` function for trimming strings: https://spark.apache.org/docs/3.0.0/api/sql/index.html#trim. I'm running into parsing issues around these (initially prompted by a `BOTH FROM` command).

## Expected Behaviour

From the link above, we have the following example strings (which should all parse):

```sql
> SELECT trim('    SparkSQL   ');
 SparkSQL
> SELECT trim(BOTH FROM '    SparkSQL   ');
 SparkSQL
> SELECT trim(LEADING FROM '    SparkSQL   ');
 SparkSQL
> SELECT trim(TRAILING FROM '    SparkSQL   ');
     SparkSQL
> SELECT trim('SL' FROM 'SSparkSQLS');
 parkSQ
> SELECT trim(BOTH 'SL' FROM 'SSparkSQLS');
 parkSQ
> SELECT trim(LEADING 'SL' FROM 'SSparkSQLS');
 parkSQLS
> SELECT trim(TRAILING 'SL' FROM 'SSparkSQLS');
 SSparkSQ
```

## Observed Behaviour

Running each of these into `echo "X" | sqlfluff parse --dialect spark3 -` and looking for parsing errors:
- `SELECT trim('    SparkSQL   ');` succeeds
- `SELECT trim(BOTH FROM '    SparkSQL   ');` fails
- `SELECT trim(LEADING FROM '    SparkSQL   ');` fails
- `SELECT trim(TRAILING FROM '    SparkSQL   ');` fails
- `SELECT trim('SL' FROM 'SSparkSQLS');` succeeds
- `SELECT trim(BOTH 'SL' FROM 'SSparkSQLS');` fails
- `SELECT trim(LEADING 'SL' FROM 'SSparkSQLS');` fails
- `SELECT trim(TRAILING 'SL' FROM 'SSparkSQLS');` fails

## Steps to Reproduce

See above.

## Dialect

Spark3

## Version

```
python==3.9.7
sqlfluff==0.8.2
```

## Configuration

Default

**Comment by PhilippLange** [comment]
AFAIK Spark SQL is the ANSI complaint syntax for TRIM.
Hence this should be implemented in the ANSI dialect.
Could someone add the ANSI label?
Will give this a try.

**Comment by tunetheweb** [comment]
It does parse in ANSI but incorrectly:

```
[L:  1, P:  8]      |                        function_name:
[L:  1, P:  8]      |                            function_name_identifier:         'trim'
[L:  1, P: 12]      |                        bracketed:
[L:  1, P: 12]      |                            start_bracket:                    '('
[L:  1, P: 13]      |                            [META] indent:
[L:  1, P: 13]      |                            expression:
[L:  1, P: 13]      |                                column_reference:
[L:  1, P: 13]      |                                    identifier:               'BOTH'
[L:  1, P: 17]      |                            whitespace:                       ' '
[L:  1, P: 18]      |                            keyword:                          'FROM'
[L:  1, P: 22]      |                            whitespace:                       ' '
[L:  1, P: 23]      |                            expression:
[L:  1, P: 23]      |                                literal:                      "'    SparkSQL   '"
```

That shouldn't be a column reference.
