### ISSUE TITLE
Postgres: DROP TYPE [IF EXISTS] foo [CASCADE] unsupported

### ISSUE THREAD

**Issue by davidandreoletti** [sqlfluff/sqlfluff#1937]
# Expected Behaviour

The code snippet is parsed successfully.

# Observed Behaviour

PRS error

`PRS	1 / 1	Line 1, Position 1: Found unparsable section: 'DROP TYPE IF EXISTS foo CASCADE'`

# Steps to Reproduce

Parse this with postgres dialect:

`DROP TYPE IF EXISTS foo CASCADE;`

# Configuration

- Command: `echo "DROP TYPE IF EXISTS foo CASCADE" | sqlfluff lint --dialect=postgres -`
- SQLfluff 0.8.1
- Python 3.9.x

**Comment by jpy-git** [comment]
@davidandreoletti FYI this has already been fixed in #1870 and will be in release 0.8.2

1st case below is 0.8.1, 2nd is current master:
![image](https://user-images.githubusercontent.com/80432516/142599103-158da6ab-f876-457e-9c62-532286ae5cff.png)

So we can close this issue 👍

**Comment by davidandreoletti** [comment]
> @davidandreoletti FYI this has already been fixed in #1870 and will be in release 0.8.2
> 
> 
> 
> 1st case below is 0.8.1, 2nd is current master:
> 
> ![image](https://user-images.githubusercontent.com/80432516/142599103-158da6ab-f876-457e-9c62-532286ae5cff.png)
> 
> 
> 
> So we can close this issue 👍 

Super. Thx!
