### ISSUE TITLE
How to disable a rule via the config?

### ISSUE THREAD

**Issue by yb66** [sqlfluff/sqlfluff#1938]
## URL or Command Line Option with the issue being reported

The documentation does not include something like "How to disable a rule". There is [Ignoring line ranges](https://docs.sqlfluff.com/en/stable/rules.html#ignoring-line-ranges) and within the configuration of some rules there are things like `force_enable` but nothing about *how to do that in the config*. Or at least, nothing *obvious* (I'm a new user, if things are to be found then they need to be obvious).

I've done site searches of the docs and scoured them but not found this.

Is it `exclude_rules`? I found it while writing this. There's a line hidden in [CLI Arguments](https://docs.sqlfluff.com/en/stable/configuration.html#cli-arguments). I guess it's that.

## Issue/Suggested Improvement

Give at least one example, preferably in a section with an appropriate title, of how to disable a rule *within the .sqlfluff config*, and make it *very clear*. For all I know, one of the lines in the [default config](https://docs.sqlfluff.com/en/stable/configuration.html#default-configuration) is disabling a rule but how would I know? It's almost a hundred lines long and the only candidate has a "None" next to it.

Regards,
iain

**Comment by jpy-git** [comment]
@yb66 this already exists in the configuration section of the documentation:
![image](https://user-images.githubusercontent.com/80432516/142600111-a40a420d-3a5c-4167-ab84-f1f25728812f.png)

I think the `Configuration` page is a sensible place to put it. That section does quite clearly state that the config file is an alternative place to put command line options, so the place to look would be the `CLI Reference` page or just do `sqlfluff lint --help` if you want to understand what options you have?

On the default config point, I think `exclude_rules=None` is pretty clear that no rules are disabled by default.

No harm in creating a PR if you think you have a clearer layout though?

**Comment by tunetheweb** [comment]
I think a link to that section from the rules page would help make this clearer:

Somewhere around this section: https://docs.sqlfluff.com/en/stable/rules.html#inline-ignoring-errors

**Comment by jpy-git** [comment]
@tunetheweb ahh, those `Inline Ignoring Errors` and `Ignoring line ranges` are duplicated in the configuration page. 
I can see why this could be confusing to someone looking at the rules page as put those sections there implies you would expect the rest of the config info there.
I would propose remove those two sections from the rules page and then replace it with the link to the `CLI Arguments` section in `Configuration`. That way the user has one clear place to look for config info.

**Comment by tunetheweb** [comment]
Hmmm.... I'm in two minds.

In general I don't like duplicating content (they're bound to get out of sync - as this has shown).

But on the other hand I think it is useful to have this on the rules page. Yes we could link, but it is handy to have it directly there (I certainly use the one on the rules page more as always forget the syntax and usually on that page when I want to implement an inline override).

Maybe this is one of the rare occasions where duplicating is OK?

Or maybe should have a common template that we can pull into both pages to avoid it getting out of sync? I think that's relatively easy with out doc solution.

**Comment by jpy-git** [comment]
Yeah that's fair enough, I have always just defaulted to the `Configuration` page.

In that case I think the template solution in both pages seems a sensible approach.

I think the template section would cover basic examples of:
- including/excluding rules via CLI
- including/excluding rules via config
- ignoring individual lines/line ranges
- changing a config options for a couple rules.

It can be fairly simple examples (more of a quickstart) and then in the `Rules Reference` page we can refer them to the `Configuration` page for more detailed info on config files, dbt/jinja options, default config, etc.

**Comment by tunetheweb** [comment]
This was added to https://docs.sqlfluff.com/en/latest/configuration.html#enabling-and-disabling-rules in #2291
