### ISSUE TITLE
Rules should be able to use memory without explicitly returning a LintResult with a memory parameter

### ISSUE THREAD

**Issue by barrywhart** [sqlfluff/sqlfluff#1943]
Now that the rules take a `RuleContext` object with a `memory`, it seems annoying and unnecessary to require a rule to return `LintResult(memory=` in order to use the memory feature. Could we simply allow them to modify the `memory` property directly?

**Comment by alanmcruickshank** [comment]
@barrywhart - with the way we're going on crawling, I think the use of the `memory` parameter is getting less and less required at all. Should I close this issue?

**Comment by barrywhart** [comment]
Sounds good. I assume you're referring to the flexible crawling behavior and thus no longer having to split the linting/fixing logic across separate calls to `_eval()`?
