### ISSUE TITLE
sqlfluff lint produces expected output but sqlfluff fix produces errors

### ISSUE THREAD

**Issue by aa0910** [sqlfluff/sqlfluff#1953]
Type Error

This probably occurs because of dbt_utils.surrogate_key

Gives the type error for following rules:
 
TypeError: 'NoneType' object is not iterable

Rules:
L039 - unnecessary whitespace
L044 - unknown number of result columns
L003 - indentation

## Dialect
bigquery

## Version
Sqlfluff version - 0.7.1
Python version - 3.9.8

## Configuration
```
[sqlfluff]
verbose = 0
nocolor = False
dialect = bigquery
templater = dbt
rules = None
exclude_rules = None
recurse = 0
output_line_length = 80
runaway_limit = 10
ignore_templated_areas = True
encoding = autodetect
# Comma separated list of file extensions to lint.

# NB: This config will only apply in the root folder.
sql_file_exts = .sql,.sql.j2,.dml,.ddl

[sqlfluff:indentation]
indented_joins = False
indented_using_on = True
template_blocks_indent = True

[sqlfluff:templater]
unwrap_wrapped_queries = True

[sqlfluff:templater:jinja]
apply_dbt_builtins = True


[sqlfluff:templater:jinja:macros]
# Macros provided as builtins for dbt projects
dbt_ref = {% macro ref(model_ref) %}{{model_ref}}{% endmacro %}
dbt_source = {% macro source(source_name, table) %}{{source_name}}_{{table}}{% endmacro %}
dbt_config = {% macro config() %}{% for k in kwargs %}{% endfor %}{% endmacro %}
dbt_var = {% macro var(variable, default='') %}item{% endmacro %}
dbt_is_incremental = {% macro is_incremental() %}True{% endmacro %}

# Some rules can be configured directly from the config common to other rules.
[sqlfluff:rules]
tab_space_size = 4
max_line_length = 80
indent_unit = space
comma_style = trailing
allow_scalar = True
single_table_references = consistent
unquoted_identifiers_policy = all

# Some rules have their own specific config.
[sqlfluff:rules:L007]  # Keywords
operator_new_lines = after

[sqlfluff:rules:L010]  # Keywords
capitalisation_policy = consistent

[sqlfluff:rules:L011]  # Aliasing
aliasing = explicit

[sqlfluff:rules:L012]  # Aliasing
aliasing = explicit

[sqlfluff:rules:L014]  # Unquoted identifiers
extended_capitalisation_policy = consistent

[sqlfluff:rules:L016]
ignore_comment_lines = False

[sqlfluff:rules:L026]
force_enable = False

[sqlfluff:rules:L028]
force_enable = False

[sqlfluff:rules:L029]  # Keyword identifiers
unquoted_identifiers_policy = aliases
quoted_identifiers_policy = none

[sqlfluff:rules:L030]  # Function names
capitalisation_policy = consistent

[sqlfluff:rules:L038]
select_clause_trailing_comma = forbid

[sqlfluff:rules:L040]  # Null & Boolean Literals
capitalisation_policy = consistent

[sqlfluff:rules:L042]
# By default, allow subqueries in from clauses, but not join clauses.
forbid_subquery_in = join

[sqlfluff:rules:L047]  # Consistent syntax to count all rows
prefer_count_1 = False
prefer_count_0 = False
```

**Comment by tunetheweb** [comment]
No screenshot is included. Also better to include the actual SQL than a screenshot to save someone having to retype it.

**Comment by aa0910** [comment]
> No screenshot is included. Also better to include the actual SQL than a screenshot to save someone having to retype it.

Here is a code that would generate these errors:

One fix for L003 not applied, it will re-cause the same error
One fix for L039 not applied, it will re-cause the same error
Applying rule L044 threw an exception: 'NoneType' object is not iterable
```

with base_data as (
    select *
    from {{ ref('targets_data') }}
)

, pivot as (
    select
      date_trunc(month_detail, month) 
            as month_detail
    , target_area
    , target_theater
    , null as target_industry_info
    , target_sales_team
    , target_sales_sub_team
      , 'Value'
            as target_name    
      , sum(target_value)
            as target_num
      , null
            as target_deno

    from base_data
    where target_name = 'Value'
    {{ dbt_utils.group_by( n = 7 ) }}
)

select
    *
    , {{ dbt_utils.surrogate_key([
      'month_detail'
    , 'target_theater'
    , 'target_area'
    , 'target_industry_info'
    , 'target_sales_team'
    , 'target_sales_sub_team'
    , 'target_name'
  ]) }} as surrogate_key

from pivot
```

**Comment by jpy-git** [comment]
@aa0910 I can see that you're using sqlfluff 0.7.1, I know a lot of work has been done on the dbt templater since then so out of curiosity would you be able to retry with 0.8.2 and confirm if you're still seeing the issue?

**Comment by aa0910** [comment]
> @aa0910 I can see that you're using sqlfluff 0.7.1, I know a lot of work has been done on the dbt templater since then so out of curiosity would you be able to retry with 0.8.2 and confirm if you're still seeing the issue?

Thank you Joseph, just a quick question on the same, how do i updrage my sqlfluff. I tried to upgrade using multiple ways but it still shows my version as 0.7.1. Can you please help me with the command to upgrade. Appreciate your help.

**Comment by jpy-git** [comment]
sure thing, @aa0910. The easiest way to upgrade is `pip install --upgrade sqlfluff` (you may need to replace `pip` with whatever you usually use to install things e.g. `pip3` or `python3 -m pip`)

**Comment by aa0910** [comment]
> sure thing, @aa0910. The easiest way to upgrade is `pip install --upgrade sqlfluff` (you may need to replace `pip` with whatever you usually use to install things e.g. `pip3` or `python3 -m pip`)

@jpy-git the version upgrade for sqlfluff did not resolve this issue. Did anything work for you regarding this issue? Appreciate any help!

**Comment by barrywhart** [comment]
@aa0910: I am having technical issues and am unable to reproduce this on my system (M1 Mac, Python 3.9, dbt 1.0.0).

Can you please provide complete logging output from the failure? That will help us track down the issue. (You can enable logging output by adding the option `-vvvv` to your `sqlfluff lint` or `sqlfluff fix` command.
