### ISSUE TITLE
TSQL: add <table_option> in CREATE TABLE 

### ISSUE THREAD

**Issue by tkachenkomaria244** [sqlfluff/sqlfluff#1954]
TSQL Dialect. Add possibility to parse <table_option> block in CREATE TABLE statement according to [create-table-transact-sql](https://docs.microsoft.com/en-us/sql/t-sql/statements/create-table-transact-sql?view=sql-server-ver15)

**Comment by tkachenkomaria244** [comment]
I'll take care of it

**Comment by tkachenkomaria244** [comment]
> 

Sorry, I've no chance to close it in the nearest future.

**Comment by RoBal42** [comment]
Is there any possibility for solving this issue in the near future? 
We are working with temporal tables (as in #3542 ) and it would be nice if those would be supported.

**Comment by barrywhart** [comment]
@RoBal42: Dialect changes are pretty easy, often a good first issue for new contributors. Care to give it a go?

**Comment by RoBal42** [comment]
We already looked into that, but couldn't really get to the core. If we manage to solve this we will try to share our solution, but I am not sure if we have the capacity for that.
