### ISSUE TITLE
Nuisance: L052 (require_final_semicolon = True) does not reliably add `;` if L009 is on and EOF line does not exist already

### ISSUE THREAD

**Issue by Gregory108** [sqlfluff/sqlfluff#1978]
If:
- Rule 009 is not excluded (default)
- There is no single trailing newline (as rule 009 requires)
- Rule 052 parameter `require_final_semicolon = True` (not default)

Then `sqlfluff fix` adds newline, but does not add a semicolon (`;`).

Related experiments:
- Value of another 052's parameter `semicolon_newline = True/False` does not affect the mechanics
- While ```[sqlfluff] exclude_rules = L009``` makes `;` appear always as expected

## Query
```
SELECT
    a
FROM foo
```

## Expected Behaviour
```
SELECT a
FROM foo;

```

## Observed Behaviour
```
SELECT a,
FROM foo

```

## Steps to Reproduce
I believe any setup will have such error if 
```
[sqlfluff:rules:L052] 
require_final_semicolon = True
```
added to the `.sqlfluff`

## Dialect
- bigquery

## Version
- sqlfluff, version 0.8.2

## Configuration
```
[sqlfluff]
templater = jinja
dialect = bigquery
# exclude_rules = L009

[sqlfluff:rules:L052] 
require_final_semicolon = True
```

**Comment by Gregory108** [comment]
@barrywhart 
May have the same nature as my previous [Issue](https://github.com/sqlfluff/sqlfluff/issues/1881)

**Comment by jpy-git** [comment]
Will look into this, not sure it's related to the other issue

**Comment by jpy-git** [comment]
cool, I think I've found the fix for this. Similar to @barrywhart's final comment in #1808. Will pull together a PR

**Comment by Gregory108** [comment]
@jpy-git Cool! Thanks!
