### ISSUE TITLE
TSQL: PRS error: add possibility to parse MERGE statement

### ISSUE THREAD

**Issue by tkachenkomaria244** [sqlfluff/sqlfluff#1982]
Please add possibility to parse MERGE statement in TSQL dialect.
[merge-transact-sql](https://docs.microsoft.com/ru-ru/sql/t-sql/statements/merge-transact-sql?view=sql-server-ver15)

I see MERGE has been implemented already in Exasol and Snowflake dialects of SQLFluff. 
But MERGE  was not included in ANSI base dialect for some reason, although MERGE is in ANSI standard:
[Merge_(SQL)](https://en.wikipedia.org/wiki/Merge_(SQL))

Script example:
```
merge 
	schema1.table1 dst
using
	schema1.table1 src
on
	src.rn = 1
	and dst.e_date_to is null
	and dst.cc_id = src.cc_id
when matched
	then update
		set
			dst.l_id = src.l_id
			, dst.e_date_to = src.e_date_from;
```

**Comment by tkachenkomaria244** [comment]
I can try to add MERGE into TSQL but need an advise about ANSI dialect.
@barrywhart is it needed to add MERGE to ANSi also?

**Comment by barrywhart** [comment]
I think it's okay to add it to TSQL instead.

We can move it to ANSI later if it seems useful to do so.

**Comment by tkachenkomaria244** [comment]
test code: `with source_data as 
				(
					select
						cc_id     
						, cc_name  
                                                , cc_description

					from 
						DW.sch1.tbl1
					where 
						e_date_to is null
						and l_id >= dd 
						and l_id <= dd
				)
				merge 
					DM.sch1.tbl2 dst
				using 
					source_data src
				on
					src.cc_id = dst.cc_id
				when 
					matched 
						then
							update 
								set
									dst.cc_name = src.cc_name
									, dst.cc_description = src.cc_description
				when 
					not matched 
						then 
							insert 
							(
								cc_id     
								, cc_name  
								, cc_description
							)
							values 
							(
								cc_id     
								, cc_name  
								, cc_description
							);`
