### ISSUE TITLE
Placeholder-templating documentation: incorrect example with config group name and param_regex 

### ISSUE THREAD

**Issue by tkachenkomaria244** [sqlfluff/sqlfluff#1996]
For documentation about [placeholder-templating](https://docs.sqlfluff.com/en/stable/configuration.html#placeholder-templating) I suggest the following fixes/improvements:
1. Improvement: it would be usefull to add some statement about nessesity to turn on templating with `templater = placeholder` because it is not obvious for first-time users:
```
[sqlfluff]
templater = placeholder
```
2. Fix issue: I've got an error (see below) when I tried to follow documentation about [placeholder-templating](https://docs.sqlfluff.com/en/stable/configuration.html#placeholder-templating)
in part of 
"
In case you need a parameter style different from the ones above, you can pass a custom regex.
```
[sqlfluff:templater:placeholder:context]
param_regex='__(?P<param_name>[\w_]+)__'
my_name='john'
```
the named parameter param_name will be used as the key to replace, if missing, the parameter is assumed to be positional and numbers are used insead.
"
**Variant 1 - with error**
.sqlfluff configuration:
```
[sqlfluff:templater:placeholder:context]
param_regex = '\$\{(?P<param_name>[\w_]+)\}'
V_LOAD_ID = '1111'
```
```
  File "d:\sqlfluff\sqlfluff-main\src\sqlfluff\core\templaters\placeholder.py", line 94, in get_context
    raise ValueError(
ValueError: No param_regex nor param_style was provided to the placeholder templater!
```
Variant with `sqlfluff:templater:placeholder` seems to be recognized by templater but cannot get correctly param_regex for parsing:
**Variant 2 - with error**
.sqlfluff configuration:
```
[sqlfluff:templater:placeholder]
param_regex = '\$\{(?P<param_name>[\w_]+)\}'
V_LOAD_ID = '1111'
```
```
==== parsing violations ====
L:  10 | P:   8 |  LXR | Unable to lex characters: '${V_LOAD_I...'
```
**Variant 3 - working variant is in my case:** 
.sqlfluff configuration:
```
[sqlfluff:templater:placeholder]
param_regex = \$\{(?P<param_name>[\w_]+)\}
V_LOAD_ID = '1111'
```

**Comment by jpy-git** [comment]
@tkachenkomaria244 Thanks for spotting this, I think you're correct here.

looking in the code `param_regex` should be under:
`[sqlfluff:templater:placeholder]`

and the reason why variant 2 fails but 3 works is because in a config file the quotes are interpreted as literal, so your compiled regex was like r"'\$\{(?P<param_name>[\w_]+)\}'" (with the single quotes included). 

Agree the docs are misleading so will pull together an update now 👍
