### ISSUE TITLE
Implement fix rule for comparison operators with space inside

### ISSUE THREAD

**Issue by tkachenkomaria244** [sqlfluff/sqlfluff#1997]
TSQL and Oracle (ANSI dialect) allow having comparison operators written with spaces inside (such as ">  =", "<    =").
Please add a possibility in SQLFluff to fix such cases and remove these whitespaces inside, i.e. to fix from "> =" to ">=".

## Dialect
TSQL, ANSI

**Comment by jpy-git** [comment]
@barrywhart 
thinking about this PR further, do you think it would be worth introducing a `comparison_operator_reference` segment (like we have for `column_reference`) to better group these space separated comparison operators?

current:
![image](https://user-images.githubusercontent.com/80432516/143864617-7dff3647-018f-4b21-bd2b-803802ddad50.png)

suggested change would be something like:
```
expression:
    column_reference:
        identifier:                       'b'
    whitespace:                           ' '
    comparison_operator_reference:
        comparison_operator:                  '!'
        whitespace:                           ' '
        comparison_operator:                  '>'
    whitespace:                           ' '
    literal:                              '2'
```

Reason being any rules that rely on placement of comparison operators (as mentioned in #1965) can refer to `comparison_operator_reference`. It can contain a method to give the combination of underlying comparison operators to save every rule having to reimplement logic to find out the type of operator.

Additionally it would make the rule proposed in this issue easy to implement:
- locate `comparison_operator_reference` (`context.segment` in this case)
- if more than one child segment flag as "whitespace in comparison operators"
- fix is then something like delete all bar one of the child segments and edit the remaining one to be the combined symbol segment.
```python
fixes = []
fixes.extend([LintFix("delete", s) for s in context.segment.segments[1:]])
fixes.append(LintFix("edit", context.segment.segments[0], context.segment.<method_on_comparison_operator_reference_to_get_combined_segment>())
```
- fixed parse looks like:
```
expression:
    column_reference:
        identifier:                       'b'
    whitespace:                           ' '
    comparison_operator_reference:
        comparison_operator:                  '!>'
    whitespace:                           ' '
    literal:                              '2'
```

**Comment by jpy-git** [comment]
Also given that this also applies to oracle it makes sense to move this to ansi

**Comment by barrywhart** [comment]
+1 for creating a "grouping" type for comparisons. I wouldn't use the term "reference", though, since that implies it's referring to some external thing such as a table or column. Perhaps `comparison_operator_segment` or `comparison_condition`?

**Comment by jpy-git** [comment]
`comparison_operator_segment` makes sense, i think the `comparison_condition` sounds like it implies that the whole expression is included 👍

**Comment by swanderz** [comment]
TSQL user confirming that as part of migrating to 0.9.0, we now get rule L006 failures for instances of `!=` and `>=` when there's no space between

```sql
SELECT DISTINCT CountryNo
FROM {{ ref('vwFinanceCompanyCode') }}
WHERE CountryNo != '81'
```

```
== [/home/vsts/work/1/s/models/finance/PRsourcing/AvaCountries.sql] FAIL
L:   3 | P:  17 | L006 | Missing whitespace after !
L:   3 | P:  18 | L006 | Missing whitespace before =
```

**Comment by jpy-git** [comment]
Assigning this to myself as I need to do a general tidy up of the multi-character operators to fix @swanderz issue above plus a similar issue I'm encountering building out the MySQL expressions.

Will add the operator spacing fix to L039

**Comment by jpy-git** [comment]
Realise this unintentionally got closed by the PR to fix comparison operator grammar. Reopening to address the actual rule fix! 😄
