### ISSUE TITLE
L052 - Add option for newline semicolon just for multiline queries

### ISSUE THREAD

**Issue by WittierDinosaur** [sqlfluff/sqlfluff#2013]
We use newline'd semicolons, but only for multiline queries. A config option for this would be great.

Eg.
```
SELECT foo FROM bar;
```

But also:
```
SELECT foo
FROM bar
;
```

**Comment by jpy-git** [comment]
Where would you propose adding the newline for something like

```sql
with cte as (
    select a from b
)

select * from cte
```

**Comment by WittierDinosaur** [comment]
Under it. It'd just be useful for the multiline gang if there was a config option for snapping inline to single line queries only

**Comment by jpy-git** [comment]
makes sense, just checking 😄 Do you know if we have a method of reliably determining the which lines belong to the current query? My first thought would be find the parent StatementSegment and check if it spans multiple lines, but not sure if that also applies to tsql?

**Comment by jpy-git** [comment]
@WittierDinosaur got this working well now 👍 On my point above, looking at the grammar I think we should be fine to use the parent StatementSegment for all dialects including tsql. tsql basically just wraps the optionally wraps StatementSegment in begin/end blocks but that doesn't impact this logic.

In terms of config I propose we change the current `semicolon_newline` option to `multiline_newline` and it works as we described here. I think most people will want the semi_colon on the same line for one line segments so it makes sense to redefine the option to be "Should semi-colons be placed on a new line after the multi-line statements?" 😄
