### ISSUE TITLE
L052 - Same line semicolon snaps it onto comments

### ISSUE THREAD

**Issue by WittierDinosaur** [sqlfluff/sqlfluff#2014]
## Expected Behaviour

sqlfluff fix
before:
```
SELECT a
FROM b --comment
;
```

after:
```
SELECT a
FROM b; --comment
```

## Observed Behaviour

after:
```
SELECT a 
FROM b --comment;
```

## Steps to Reproduce

sqlfluff fix the before block

## Dialect

ansi

## Version
0.8.2

## Configuration
Default - but crucially L052 `semicolon_newline = False`

**Comment by jpy-git** [comment]
Will take a look, I think I was just snapping to the last non-whitespace/newline so just need to update to also ignore comments

**Comment by WittierDinosaur** [comment]
I think there's an is_code property that should help
