### ISSUE TITLE
L034 triggers in queries without wildcards

### ISSUE THREAD

**Issue by tekumara** [sqlfluff/sqlfluff#2049]
## Expected Behaviour
The sql has no wildcards so I wasn't expecting L034

## Observed Behaviour
```
L:   1 | P:   1 | L034 | Use wildcards then simple targets before calculations
                       | and aggregates in select statements.
```

## Steps to Reproduce
_test.sql_
```
SELECT 1 AS dv_keyid,
       MIN(t.runid) AS dv_runid,
       MIN(t.dv_distkey) AS dv_distkey,
       t.id
FROM t


```
## Version
sqlfluff, version 0.8.2
python 3.9

## Configuration

Default out-of-the-box config.

**Comment by jpy-git** [comment]
@tekumara this is not a bug. The rule states "Use wildcards then simple targets before calculations and aggregates in select statements." This means when ordering your columns in this query, simple targets (1, t.id) need to come before the aggregate functions (MIN). (If your query had a wildcard it would come at the start)

i.e.
```sql
SELECT
    1 AS dv_keyid,
    t.id,
    MIN(t.runid) AS dv_runid,
    MIN(t.dv_distkey) AS dv_distkey
FROM t
```

(https://docs.sqlfluff.com/en/stable/rules.html#:~:text=class%20Rule_L034(code%2C%20description%2C%20**kwargs))

**Comment by tekumara** [comment]
Ah gotcha, thanks for the explanation. I read the subject of the sentence as being wildcards, not order of columns in general.
