### ISSUE TITLE
Simple API: parse command

### ISSUE THREAD

**Issue by jpy-git** [sqlfluff/sqlfluff#2062]
So the purpose of the Simple API is to provide a clear way for users to interact with sqlfluff via code.

In the case of the `lint` and `fix` commands the action of the functions are pretty well defined, however, for the `parse` command we return a ParsedString named tuple.
There's nothing strictly wrong with this per se, but was just wondering if there was a discussion to be had around whether this is currently providing users with too much access to the sqlfluff internals (as shown below) rather than a more well defined API?

![image](https://user-images.githubusercontent.com/80432516/144944061-dd5229ba-5a02-44f8-8372-285f023c443e.png)

**Comment by jpy-git** [comment]
@tunetheweb @barrywhart this was one of the things that would be good to clarify before we consider any 1.0.0 release?

**Comment by tunetheweb** [comment]
It’s an interesting question. In general we try to keep the internals away from the Simple API so it has a stable API not subject to most interns changes.

However parse by definition needs to return the parse tree. Well it doesn’t it could just return true or false, but that would really make it very limited. Then again maybe that should be all the Simple API covers?

Have you any suggestions what else to return? A JSON object version of the parse tree? Something else? But even then some internals would be return (e.g. the `type` of each object).

Any other thoughts?

**Comment by barrywhart** [comment]
The parser tests use a YAML version of the parse tree, and YAML is basically the same as JSON. I agree we should be returning fairly simple data rather than SQLFluff-specific types. (I didn't know about `parse()`, and now I'm a little bit horrified. 😱)

**Comment by jpy-git** [comment]
Yeah I think the JSON suggestion sounds best to me too. As @barrywhart said, I know we have the code to convert the parse tree to yaml and there's also the stringify method as well which encodes the tree for the CLI output. So I think encoding the parse tree into JSON via a similar jsonify method would be ideal. We may already have something similar so I'll check, but if not I don't think it would be too hard to implement 😄

**Comment by tunetheweb** [comment]
I think we do have a JSON output format from the command line parse option.

**Comment by jpy-git** [comment]
I believe the JSON from the command line is only the linting results rather than the parse tree.

**Comment by tunetheweb** [comment]
Also available for parse: https://docs.sqlfluff.com/en/stable/cli.html#sqlfluff-parse

> `-f, --format <format>`
> What format to return the parse result in.
> 
> Options
>   human | json | yaml

**Comment by jpy-git** [comment]
Nice, we have this `to_records` method on the tree which I'm pretty sure is perfect right? 😄 
![image](https://user-images.githubusercontent.com/80432516/145491784-a17e7c6f-d208-407e-b7e8-08b167a2536d.png)

**Comment by tunetheweb** [comment]
Nice!

**Comment by jpy-git** [comment]
Will create the PR 👍
