### ISSUE TITLE
DBT Plugin: Reference dbt profiles.yml from home directory

### ISSUE THREAD

**Issue by csimonsson** [sqlfluff/sqlfluff#2063]
Would it be possible to configure the dbt plugin to read the profile.yml file using the relative path from the home directory to enable all users share the same .sqlfluff file?

Or maybe there is a better way to configure sqlfluff for a team with mixed OS setup, both macos and windows?

```
[sqlfluff:templater:dbt]
project_dir = my_project/
profiles_dir = <home>/.dbt/
profile = my_profile
```

**Comment by barrywhart** [comment]
From SQLFluff Slack:
>I think that setting is optional -- if you omit it, I think it looks in the default location for your OS.

Christian Simonson  1 hour ago
>Oh, that's working, thanks! 

Thus, no code change required. PR #2070 updates the documentation to mention that the `profiles_dir` setting is optional.
