### ISSUE TITLE
Docker: dbt templater plug-in

### ISSUE THREAD

**Issue by jpy-git** [sqlfluff/sqlfluff#2102]
As part of release 0.9.0 we are releasing an Official Docker image on DockerHub for SQLFluff.

Initially this will not include the dbt plugin and it's dependencies, therefore, this issue is to be used to facilitate discussions around how to best implement a Docker image including dbt capabilities.

Initial Discussions can be found in #2097.

Main points of discussion are around do we:
a) Have a single SQLFluff image containing both sqlfluff and the dbt templater.
b) Separate sqlfluff  and sqlfluff + dbt templater images in separate docker repos.
c) Separate sqlfluff and sqlfluff + dbt templater images in using tags in the sqlfluff/sqlfluff docker repo.

Personally I would lean towards `c)` as we would could have a docker image for the sqlfluff + dbt templater image that inherits from the sqlfluff image in the build step to avoid unnecessary duplication of work and still allow for people to just use the sqlfluff only image.  Using tags in the same repo is useful as it means we only have one set of keys in the CI pipeline and there's only one README to maintain.

My main question around tagging (that applies to all options) is what permutations of SQLFluff and dbt would we want to offer for the image? For just SQLFluff it's pretty simple as we just give the package version, but for sqlfluff + dbt do we want to build and tag all possible combinations of sqlfluff version and dbt version (i.e. sqlfluff 0.8.2 + dbt 0.19.2, sqlfluff 0.8.2 + dbt 0.21.3, sqlfluff 0.9.0 + dbt 1.0.0, etc...) or would we only offer a few to avoid things getting unwieldy?

**Comment by jpy-git** [comment]
@tunetheweb @barrywhart @alanmcruickshank feel free to add any further thoughts on the dbt templater docker image here

**Comment by tunetheweb** [comment]
I think there’s a genuine question as to whether we need a Docket image including the dbt templater at all?

The primary usage of the SQLFluff Docker image is for those that don’t want the the hassle of dealing with a Python environment, as I understand it. For example a T-SQL developer that doesn’t use Python at all, but wants to lint or fix their SQL.

Dbt is a Python package as I understand it. So will all people using dbt have Python installed anyway? Or if they use Docker will they build their own Docker image with the exact versions and packages they need.

So do we even need a dbt Docker image?

I’m not a dbt user, and have only used Docker on rare occasions so genuinely interested to here what users of this want, and if there’s demand for this.

**Comment by jpy-git** [comment]
@tunetheweb I agree the subset of people using SQLFluff + dbt via docker is likely pretty small.

I also think your point on building their own image is valid as well. The purpose of the SQLFluff image atm is to provide a blackbox implementation of SQLFluff for users to use without having to worry about setting up python or to use within containerized setups (e.g. Kubernetes/Fargate).

If someone were to want to use sqlfluff + dbt in Docker image I would envision it being more for containerized development (i.e. consistent dev environment across a team) in which case, as you said, they would likely have their own Dockerfile/docker-compose.yml and sqlfluff would just be included as one of the many other dependencies in the project but not it's own standalone image 👍

**Comment by jpy-git** [comment]
Looks like there's not much interest in this and as described above we don't think this is needed so closing
