### ISSUE TITLE
postgres: Implement explicit datatypes

### ISSUE THREAD

**Issue by kayman-mk** [sqlfluff/sqlfluff#2109]
## Expected Behaviour
SqlFluff should post an error message if the `create table` statement has a column definition using `datetime` as data type. The Postgres dialect has no such data type.

## Observed Behaviour
No error message shown.

## Steps to Reproduce
Use the following Sql:
```sql
create table a(
  b datetime not null
);
```

## Dialect
Postgres

## Version
- SqlFluff 0.8.2
- Python 3.9.7
 

## Configuration
No config at all.

**Comment by jpy-git** [comment]
@kayman-mk referring [here](https://github.com/sqlfluff/sqlfluff/blob/8ccb55943d539278840296bcca9a6aad9baec670/src/sqlfluff/dialects/dialect_ansi.py#L299) in `dialect_ansi.py` there are no specific datatypes implemented for any of SQLFluff. 

so even something like this will still parse:
![image](https://user-images.githubusercontent.com/80432516/145849595-b55260de-72fc-4b66-a269-48a05f43a73e.png)

Reading the TODO comment this looks like we're temporarily allowing anything there as a datatype to get it parsing for all dialects. If we were to implement this with more explicit data types (which is totally doable) we should fully implement all explicit data types for the dialect (we can start with just postgres).

**Comment by jpy-git** [comment]
Here's a complete list of data types that will need adding: https://www.postgresql.org/docs/14/datatype.html

**Comment by kayman-mk** [comment]
Oh yes, we should. The ticket is a reminder for me. Had no time to implement it ad hoc.

**Comment by jpy-git** [comment]
Nice, you can pick this up when you get time 😄
