### ISSUE TITLE
Redshift create external tables and schemas

### ISSUE THREAD

**Issue by NiklasMolin** [sqlfluff/sqlfluff#2145]
## Expected Behaviour
```
CREATE EXTERNAL TABLE spectrum.partitioned_lineitem
PARTITIONED BY (l_shipdate, l_shipmode)
STORED AS parquet
LOCATION 'S3://mybucket/cetas/partitioned_lineitem/'
AS SELECT l_orderkey, l_shipmode, l_shipdate, l_partkey FROM local_table;```
```
```
create external schema spectrum_schema
from data catalog
database 'sampledb'
region 'us-west-2' 
iam_role 'arn:aws:iam::123456789012:role/MySpectrumRole';
````

## Observed Behaviour
They examples should be parsable

## Steps to Reproduce
Run sqlfluff over any example sql including any of the statements.
## Dialect
redshift
## Version
sqlfluff, version 0.8.2
python 3.7

## Configuration
Default

**Comment by NiklasMolin** [comment]
@tunetheweb really sorry. Guessing you closed it because I manage to create it without the description. Adding it now, could we reopen? Or did you have another reason for closing it?

**Comment by tunetheweb** [comment]
Nope that was reason. Thought it had been opened in error to be honest!

**Comment by tinder-albertyue** [comment]
Attempted to add the `create external table` parsing over at https://github.com/sqlfluff/sqlfluff/pull/2229
