### ISSUE TITLE
Postgres - Parsing failure for function names starting with _

### ISSUE THREAD

**Issue by kevinmarsh** [sqlfluff/sqlfluff#2146]
## Expected Behaviour

Similar to issue #1742, in Postgres the function's `name` in a `CREATE FUNCTION...` can start with an underscore

## Observed Behaviour

```
PRS | 1 / 1 | Line 1, Position 1: Found unparsable section: 'CREATE FUNCTION _add(integer, integer) R...'
```

## Steps to Reproduce

```sql 
CREATE FUNCTION _add(integer, integer) RETURNS integer
    AS 'select $1 + $2;'
    LANGUAGE SQL
```

## Dialect

Postgres

## Version

```
sqlfluff, version 0.8.2
Python 3.9.9
Postgres 13.3
```

**Comment by jpy-git** [comment]
@kevinmarsh, makes sense looks like the PR #1765 that resolved #1742 didn't update the `FunctionNameIdentifierSegment`: https://github.com/sqlfluff/sqlfluff/blob/1ad0cebb1ddf72b65725b23bee59568523065523/src/sqlfluff/dialects/dialect_ansi.py#L296

Should be a fairly quick fix to override the ANSI `FunctionNameIdentifierSegment` in Postgres in the same way that #1765 did for `ParameterNameSegment`.

lmk if you'd rather I pick it up 👌
