### ISSUE TITLE
L057 incompatible with BigQuery

### ISSUE THREAD

**Issue by tunetheweb** [sqlfluff/sqlfluff#2150]
In L057 we added a rule to check for non-alphanumeric characters in identifiers.

Either the parser, or this rule needs some tweaking for BigQuery.

Most dialects create parse trees like this for table references:

```
echo "SELECT a FROM schema1.table1" | sqlfluff parse  - 
...
[L:  1, P: 15]      |                        table_expression:
[L:  1, P: 15]      |                            table_reference:
[L:  1, P: 15]      |                                identifier:                   'schema1'
[L:  1, P: 22]      |                                dot:                          '.'
[L:  1, P: 23]      |                                identifier:                   'table1'
...
```

So rule L057 makes sense.

For BigQuery table_references are enclosed in a backticks and can also have a star at the end, either way this is parsed as a single identifier:

```
% echo 'SELECT a FROM `user.schema.table1_*`' | sqlfluff parse --dialect bigquery -
[L:  1, P: 15]      |                            table_reference:
[L:  1, P: 15]      |                                identifier:                   '`user.schema.table1_*`'
```

This causes L057 to fail for, basically, every BigQuery query making the rule useless.

There's a number of options to resolve this:
1. Disable this rule for BigQuery dialect. There's precedence here for other rules but it's a bit of a blunt instrument and the rule could be useful.
2. Update BigQuery grammar to parse table references better using the dot sequence
3. Strip dots and final stars from BigQuery table references (_note: edited from initial comment, following further investigations below_).

I'm veering on option 3 as the simplest as it will also cover the final star, though possibly option 2 is the better solution for the dots.

Any thoughts here?

## Expected Behaviour

L057 should only flag unexpected non-alphanumeric

## Observed Behaviour

L057 fails for all BigQuery queries referencing a real table.

## Steps to Reproduce

As per above

## Version
Include the output of `sqlfluff --version` along with your Python version.
If you are using dbt then please additionally include the dbt version.

0.9.0

## Configuration

Standard config, except setting dialect to BigQuery

**Comment by jpy-git** [comment]
@tunetheweb I'm pretty sure the quotes already get stripped in the rule so it'll just be the star. I think the approach is just allow alphanumeric + star for bigquery 👍

Is it just the star that's extra?

**Comment by tunetheweb** [comment]
Actually it looks like it does handle the back ticks as quotes, so it's just the star that's the problem.

**Comment by tunetheweb** [comment]
Jinx!

**Comment by tunetheweb** [comment]
It's also the dots in the table references. PR coming up...

**Comment by terzieff** [comment]
Hm, @tunetheweb, it looks to me that the backticks might still be a problem. At least for me for a query that looks like
```
FROM `xxx.yyy.zzz` oo
LEFT JOIN `xxx.yyy.vvv` shp ON shp.order_id = oo.id
```
I get fails like this:
```
L:  31 | P:   6 | L057 | Do not use special characters in identifiers.
L:  32 | P:  11 | L057 | Do not use special characters in identifiers.
```

Do you know if I'm doing something wrong? I'm using version 0.13.1. I tried adding the below to the config file, but it didn't change anything.
```[tool.sqlfluff.rules.L057]
additional_allowed_characters = "`"```

**Comment by tunetheweb** [comment]
I'm not able to repeat this:

```
(.venv) barry@Barrys-MacBook sqlfluff % more test.sql
SELECT
    oo.col1,
    shp.col2
FROM `xxx.yyy.zzz` oo
LEFT JOIN `xxx.yyy.vvv` shp ON shp.order_id = oo.id
(.venv) barry@Barrys-MacBook sqlfluff % sqlfluff lint --dialect bigquery test.sql --rules L057
All Finished 📜 🎉!
```

**Comment by tunetheweb** [comment]
Are you definitely using BigQuery dialect?

**Comment by terzieff** [comment]
Ah, so it's something to do with the dashes we use in project names, try running on a query like
```
SELECT
  oo.id,
  shp.id
FROM `cw-prd-data-0001.orders.orders` oo
LEFT JOIN `cw-prd-data-0001.shipping.packages` shp ON shp.order_id = oo.id
```

**Comment by tunetheweb** [comment]
Yes those are special chars 

This works for me:

```
(.venv) barry@Barrys-MacBook sqlfluff % more .sqlfluff
[sqlfluff]
dialect = bigquery

[sqlfluff:rules:L057]
additional_allowed_characters = "-"
(.venv) barry@Barrys-MacBook sqlfluff % more test.sql
SELECT
  oo.id,
  shp.id
FROM `cw-prd-data-0001.orders.orders` oo
LEFT JOIN `cw-prd-data-0001.shipping.packages` shp ON shp.order_id = oo.id
(.venv) barry@Barrys-MacBook sqlfluff % sqlfluff lint --rules L057 test.sql
All Finished 📜 🎉!
```

**Comment by terzieff** [comment]
Ah, great, thanks a lot! The character position in the fail message was pointing me to the backticks and I didn't think about the dashes at all 🙈

**Comment by tunetheweb** [comment]
Ah yes. The character position is for the identifier that's wrong, not the letter in that identifier (as would need multiple positions in above example). Bad luck that your identifier started with another non-alphanumeric which confused you.
