### ISSUE TITLE
Snowflake: Parse create table statement with `organization` as column causes unparsable exception

### ISSUE THREAD

**Issue by wong-codaio** [sqlfluff/sqlfluff#2164]
Snowflake: Using `organization` as column name in a `CREATE TABLE` statement causes runtime exception when parsing.

## Expected Behaviour

SQLFluff parse runs without issues.

## Observed Behaviour

Unparsable section found:
```
(.venv) ~/code/sqlfluff (main) $ sqlfluff parse sample.sql --dialect snowflake
[L:  1, P:  1]      |file:
[L:  1, P:  1]      |    statement:
[L:  1, P:  1]      |        create_table_statement:
[L:  1, P:  1]      |            keyword:                                          'CREATE'
[L:  1, P:  7]      |            whitespace:                                       ' '
[L:  1, P:  8]      |            keyword:                                          'TABLE'
[L:  1, P: 13]      |            whitespace:                                       ' '
[L:  1, P: 14]      |            keyword:                                          'IF'
[L:  1, P: 16]      |            whitespace:                                       ' '
[L:  1, P: 17]      |            keyword:                                          'NOT'
[L:  1, P: 20]      |            whitespace:                                       ' '
[L:  1, P: 21]      |            keyword:                                          'EXISTS'
[L:  1, P: 27]      |            whitespace:                                       ' '
[L:  1, P: 28]      |            table_reference:
[L:  1, P: 28]      |                identifier:                                   'table_name'
[L:  1, P: 38]      |        unparsable:                                           !! Expected: 'Nothing...'
[L:  1, P: 38]      |            whitespace:                                       ' '
[L:  1, P: 39]      |            bracketed:
[L:  1, P: 39]      |                start_bracket:                                '('
[L:  1, P: 40]      |                newline:                                      '\n'
[L:  2, P:  1]      |                whitespace:                                   '  '
[L:  2, P:  3]      |                raw:                                          'organization'
[L:  2, P: 15]      |                whitespace:                                   ' '
[L:  2, P: 16]      |                raw:                                          'VARCHAR'
[L:  2, P: 23]      |                newline:                                      '\n'
[L:  3, P:  1]      |                end_bracket:                                  ')'
[L:  3, P:  2]      |    statement_terminator:                                     ';'
[L:  3, P:  3]      |    newline:                                                  '\n'

==== parsing violations ====
L:   1 | P:  38 |  PRS | Line 1, Position 38: Found unparsable section: ' (\n organization
                       | VARCHAR\n)'
```

## Steps to Reproduce

1. Create a file with the following content:
```
CREATE TABLE IF NOT EXISTS table_name (
  organization VARCHAR
);
```
2. Run `sqlfluff parse <file> --dialect snowflake`

## Dialect

Snowflake

## Version

SQLFluff - v0.9.0
```
(.venv) ~/code/sqlfluff (main) $ sqlfluff --version
sqlfluff, version 0.9.0
```

Python 3.9.9
```
(.venv) ~/code/sqlfluff (main) $ python --version
Python 3.9.9
```

## Configuration

Default except setting `--dialect snowflake`

**Comment by tunetheweb** [comment]
Organization is a semi-reserved word in Snowflake https://docs.snowflake.com/en/sql-reference/reserved-keywords.html

But we don't really have that concept in SQLFluff so have it down as a full reserved word, meaning it can't be used in a column name.

Since the reservation seems kind of light:
> Cannot be used as an identifier in a SHOW command (e.g. ‘SHOW … IN <identifier>’).
we should probably just removed it from our reserved word list and pretend it isn\t a reserved word at all.

**Comment by wong-codaio** [comment]
> But we don't really have that concept in SQLFluff so have it down as a full reserved word, meaning it can't be used in a column name.

Right - Should the failure be triggered by a linting rule, rather than failing parsing?

**Comment by tunetheweb** [comment]
Checking of reserved words currently happens as part of parsing. It's basically invalid SQL that can't be parsed if you use a reserved word.

It's a good question if if _should_ just accept this as part of parsing, and have a separate linting rule to ensure reserved words aren't used as identifiers,  but that's not the way it currently works.

**Comment by jpy-git** [comment]
Just put it as a non_reserved_keyword

**Comment by BorePlusPlus** [comment]
There seems to be a few issues regarding reserved words in Snowflake lately. For example #1927 and #2165

**Comment by jpy-git** [comment]
@BorePlusPlus that's because Snowflake doesn't have a well defined list of Reserved vs Non-reserved keywords (https://docs.snowflake.com/en/sql-reference/reserved-keywords.html) so they were likely initially conservatively placed in reserved_keywords.

If you're interested in contributing you can fix this very easily by moving the responsible words from `snowflake_reserved_keywords` to `snowflake_unreserved_keywords` in `src/sqlfluff/dialects/dialect_snowflake_keywords.py` and then submitting a PR.

**Comment by BorePlusPlus** [comment]
I see you already started a task @jpy-git, but hit an obstacle. I'd like to help, but not sure how.
