### ISSUE TITLE
New dialect: AWS Athena

### ISSUE THREAD

**Issue by juhoautio** [sqlfluff/sqlfluff#2168]
Is there interest in adding a dialect for [AWS Athena](https://docs.aws.amazon.com/athena/latest/ug/ddl-sql-reference.html)?

As a workaround one can get somewhere by applying hive dialect on Athena queries, but it's not perfect.

So, probably a lot of code could be borrowed from hive dialect implementation.

For DML queries Athena dialect is basically a subset of Presto. But SQLFluff doesn't currently support Presto dialect either.

**Comment by jpy-git** [comment]
Sounds cool, the more dialects the merrier 👍 

@barrywhart @tunetheweb out of curiosity do we have threshold of syntax coverage for adding a new dialect to the project?
i.e. doesn't make sense to merge a new dialect in if it only has 2 statements added since users would likely get confused that it doesn't match the actual syntax, but obviously its also unreasonable to expect everything in the initial PR.

**Comment by barrywhart** [comment]
I'm not aware of anything. Perhaps we could merge the PR but not add the dialect to the docs.

**Comment by tunetheweb** [comment]
> i.e. doesn't make sense to merge a new dialect in if it only has 2 statements added since users would likely get confused that it doesn't match the actual syntax, but obviously its also unreasonable to expect everything in the initial PR.

My personal preference is to get started even with one statement. Adding a dialect is a bit more intimidating than adding a statement. Once it's added, even with only a little difference than a current dialect, I think it's more likely we'll get some more contributions. So no minimum for me — quite the reverse, I'd rather contributors did NOT hold up adding until they felt they had enough.

**Comment by jpy-git** [comment]
makes sense, was just checking 👍

**Comment by barrywhart** [comment]
If I understand correctly, AWS Athena basically _is_ Presto, so if we do this, I recommend calling the dialect `presto` rather than `athena`.

**Comment by juhoautio** [comment]
I would say that Athena deserves its own dialect.

As it reads in [SQL Reference for Amazon Athena](https://docs.aws.amazon.com/athena/latest/ug/ddl-sql-reference.html):

> With some exceptions, Athena DDL is based on HiveQL DDL. Athena DML is based on Presto 0.172 for engine version 1 and Presto 0.217 for engine version 2.

So Athena dialect would share a lot with Presto dialect, but not everything. It also shares a lot with Hive.

**Comment by mrshu** [comment]
Suppose one would like to take a shot at putting together a quick Athena (or Presto for that matter) dialect. Where would it be best to start?

**Comment by tunetheweb** [comment]
> Suppose one would like to take a shot at putting together a quick Athena (or Presto for that matter) dialect. Where would it be best to start?

Have a look at #2293 where we added Oracle with one `COMMENT ON` statement only. Should do similar here, where you set it up, and add one difference from the base dialect (ANSI?).

Also worth reading having a read of https://github.com/sqlfluff/sqlfluff/wiki/Contributing-Dialect-Changes as a beginners guide to how work.
