### ISSUE TITLE
ALTER GROUP statements are unparsable

### ISSUE THREAD

**Issue by tdstark** [sqlfluff/sqlfluff#2186]
The following statement is unparsable:
`ALTER GROUP test_group ADD USER "test.user";`

## Expected Behaviour
The aforementioned statement should be parsable.

## Observed Behaviour
The aforementioned statement is not parsable.

## Dialect
ANSI/Redshift

## Version
`0.9.0`

## Configuration
Default configuration

**Comment by jpy-git** [comment]
@tdstark when I originally made the PR to add this statement the docs weren't very clear as to whether or not the user/groups could be quoted: https://docs.aws.amazon.com/redshift/latest/dg/r_ALTER_GROUP.html

Could you quickly confirm for me if the group name can also be quoted please?
```sql
ALTER GROUP "test.group" ADD USER "test.user";
```

**Comment by tdstark** [comment]
> @tdstark when I originally made the PR to add this statement the docs weren't very clear as to whether or not the user/groups could be quoted: https://docs.aws.amazon.com/redshift/latest/dg/r_ALTER_GROUP.html
> 
> Could you quickly confirm for me if the group name can also be quoted please?
> 
> ```sql
> ALTER GROUP "test.group" ADD USER "test.user";
> ```

I ran a quick test and users and groups can both be quoted. I think it's as easy as changing `NakedIdentifierSegment` to `ObjectReferenceSegment`.

**Comment by jpy-git** [comment]
@tdstark makes sense, you want to take it? (happy to do it if not 😄)

**Comment by tdstark** [comment]
> @tdstark makes sense, you want to take it? (happy to do it if not 😄)

I've got it!

**Comment by jpy-git** [comment]
This was fixed by @tdstark s PR #2188 💪 

Closing
