### ISSUE TITLE
TSQL: dialect-specific FunctionContentsGrammar

### ISSUE THREAD

**Issue by jpers36** [sqlfluff/sqlfluff#2200]
## Expected Behaviour

TSQL has a dialect-specific FunctionContentsGrammar.

## Observed Behaviour

TSQL relies on an ANSI-defined grammar which does not fully represent TSQL's functionality.

## Dialect

TSQL

**Comment by tunetheweb** [comment]
This was added in #2170 (which was before this issue?!?).

If that's not sufficient, then need more details on what the exact ask is
