### ISSUE TITLE
New Dialect: Vertica

### ISSUE THREAD

**Issue by klyusba** [sqlfluff/sqlfluff#2219]
Vertica is popular enterprise-level DBMS with columnar storage. Vertica has simple dialect with a few features over ANSI SQL.
Thanks

**Comment by tunetheweb** [comment]
Alway happy to take on new dialects @klyusba but IMHO these are best added by people who use that dialect, understand its differences, and have access to an instance to check syntax. Would you be up for submitting a PR to add this dialect? You could base it on #1453 where we added SQLite with only a small change from ANSI. Then you can grow the dialect as needs be in future PRs.
