### ISSUE TITLE
Confusing config path behavior

### ISSUE THREAD

**Issue by jacopofar** [sqlfluff/sqlfluff#2225]
I'm not sure whether this is a documentation issue or a bug.

I'm trying to parse a query using a custom config with some placeholders defined. I want to do it programmatically but for the moment I try to get it to work as a CLI operation.

I want to use SQLFluff to parse SQL files from other projects, so it's essential for me to specify a configuration for the whole "scanning project" and not different ones for different projects.

## URL or Command Line Option with the issue being reported

   sqlfluff parse --config sqlfluff_config.toml /absolute/path_to_a.sql

## Issue/Suggested Improvement

The error I get says:

        WARNING    Attempt to set templater to placeholder failed. Using jinja templater. Templater cannot be set in a .sqlfluff file in a subdirectory of the current working directory. It can be set in a .sqlfluff in the current working directory. See Nesting section of the docs for more details. 

I have three issues with this:

* The [nesting section of the doc](https://docs.sqlfluff.com/en/stable/configuration.html?highlight=sqlfluff#nesting) reports that the file should be called `sqlfluff` and be in the current working directory, but the error is saying it should be called `.sqlfluff`, which one is the correct one?

* The file is in my workdir, not in a subdirectory of it but the error says it is not. I tried both an arbitraty name, sqlfluff and .sqlfluff but it stays the same.

* The warning is shown at the beginning but then sqlfluff keeps running, which makes it hard to spot the error (I didn't even see at the beginning because the parse output was too long). I think stopping after showing the error would be a less surprising default behavior, since the user probably set a config to have it used anyways.

**Comment by alanmcruickshank** [comment]
I think the problem here is only that you're trying to set the `templater`. Can you share the config file for this issue?

**Comment by jacopofar** [comment]
For what I remember my goal at the time was to use the templater for placeholder replacements that was just merged to parse some query, using the latest version of sqlfluff I see no warning and eventually I used a different approach.

My template contains this:

```
[sqlfluff:templater:placeholder]
param_style=colon
user_ids='(1,2,3)'
```
the query file is in the postgres dialect and in the form

```SQL

SELECT * FROM users WHERE id IN :user_ids
```
I get an error:

    ==== parsing violations ====
    L:   8 | P:  32 |  PRS | Line 8, Position 32:  Found unparsable section: ' IN
                           | :user_ids'

from which I suspect it's not picking up the templater config.

I'm not using it at the moment, and this code was built for a 0.x version, if this is a deprecated usage the issue can be closed

**Comment by alanmcruickshank** [comment]
I'm going to close this issue as I think it's been resolved.
