### ISSUE TITLE
Create a Docker Compose environment to help SQLFluff developers run the dbt templater tests locally

### ISSUE THREAD

**Issue by barrywhart** [sqlfluff/sqlfluff#2248]
PR #2230 updates the dbt tests to require a Postgres server and a database connection.

This is currently not possible on M1 Macs due to the inavailability of the `psycopg2` database driver package not yet being available. Even on other platforms, requiring a database to be set up can be onerous -- what if you can't get the right version? Or what if you already have Postgres installed and are using it for something else and the passwords don't match, etc. etc.?

Let's create a `docker-compose.yml` for the dbt tests consisting of the configured postgres instance image and the python image with sqlfluff and dbt dependencies installed (both images amd64). That way we can just `docker compose up` our dbt dev environment which would make contributing to the dbt side of the project a lot easier for anyone. I prefer the more traditional approach with the main package, but the complexity for dbt development seems a good fit.

Relevant docs if you're not familiar: https://docs.docker.com/compose/
(disclaimer: this is not anything to do with official sqlfluff docker image, just using docker as a dev environment)

**Comment by barrywhart** [comment]
I have a messy but working Docker Compose dev environment set up for my local SQLFluff development. I'm happy to work on this ticket or share the files I have so far. (Not uploading them now, because it's kind of a big, sprawling mess that would need some tidying before sharing.)

**Comment by jpy-git** [comment]
Thanks @barrywhart would def be great to get this setup 😄 Feel free to create a draft PR when you're happy with sharing your starting point and we can take a look 👍

**Comment by jpy-git** [comment]
Going to keep this open so we can add to ideas/improvements to this as we test out the new environment 👍

**Comment by barrywhart** [comment]
@jpy-git: I'm going to close this. We can open new issues as we come up with other ideas. Mostly, the new environment is working well for me. The only nuisance I'm seeing is the need to manually edit these files to change the hostname:

* plugins/sqlfluff-templater-dbt/test/fixtures/dbt/profiles_yml/profiles.yml
* plugins/sqlfluff-templater-dbt/test/fixtures/dbt/profiles_yml_fail/profiles.yml
