### ISSUE TITLE
Underscores in doc examples

### ISSUE THREAD

**Issue by jpy-git** [sqlfluff/sqlfluff#2266]
Not sure what's introduced this but there's underscores in the rules reference doc examples?
![image](https://user-images.githubusercontent.com/80432516/148700612-b896f049-6773-4ecf-a907-773a94fb027a.png)

**Comment by tunetheweb** [comment]
I don’t see them in Safari on my phone. Can you try a different browsers/incognito mode?

**Comment by jpy-git** [comment]
@tunetheweb so that first image is using Brave Browser. I have dark mode on so the underscores stand out.

If I use Safari (without dark mode) the underscores are also still there (more obvious when you highlight):
![image](https://user-images.githubusercontent.com/80432516/148700876-f941d6b1-7220-4888-a74d-cd1356d043df.png)

**Comment by jpy-git** [comment]
I can also see them on Chrome on my phone

**Comment by tunetheweb** [comment]
Interesting. Can you flick through through the versions in the bottom right widget to see when it was introduced?

**Comment by tunetheweb** [comment]
Looks like 0.9.1 to me. Can just make them out with an extreme zoom in.

**Comment by jpy-git** [comment]
Yeah 0.9.0 looks fine to me
![image](https://user-images.githubusercontent.com/80432516/148701007-8930b1fa-505f-4e5c-80c3-3335df86e99b.png)

**Comment by jpy-git** [comment]
This bit of the docs is handled by autodoc so looking at potential PRs:
#2241 - Updated just the docstring in `src/sqlfluff/core/rules/__init__.py` so doesn't seem likely.
#2234 - Seems a bit more likely, but I do remember building the docs and not seeing anything weird 🤔

**Comment by jpy-git** [comment]
Although given that it also affects all the autodoc code blocks, not just the  rule ones, maybe there's been some update to one of the Sphinx dependencies that's not working right
![image](https://user-images.githubusercontent.com/80432516/148701259-4a1ce8c8-b0d5-45ba-b294-6521ab6ccb25.png)

**Comment by tunetheweb** [comment]
It's coming from pygments style sheet:

![image](https://user-images.githubusercontent.com/10931297/148701317-ff39b4b6-2dde-4b19-987b-00d419f02dc8.png)

Not familiar with this library though but trying to figure it out...

**Comment by tunetheweb** [comment]
Found it: looks like it's fixed already in 2.11.2: https://github.com/pygments/pygments/issues/2020

Any of the @sqlfluff/sqlfluff-maintainers know if it's possible to restart/redeploy the docs.sqlfuff.com site without a release?

**Comment by tunetheweb** [comment]
So turns out our default alabaster theme is also setting that, so still seeing this even with pygments 2.11.2. However it's only since pygments started applying the `w` class that this is visible (hence why we didn't see it before).

Will try and raise an issue with alabaster but looks like it's not maintained much anymore so will also raise a PR to override this to fix it short term.

**Comment by tunetheweb** [comment]
https://github.com/bitprophet/alabaster/pull/188
