### ISSUE TITLE
L052: Auto-fix appended extra `semicolon` in `CREATE TABLE` statement when `multiline_newline` is `True`

### ISSUE THREAD

**Issue by wong-codaio** [sqlfluff/sqlfluff#2268]
## Expected Behaviour

* Auto-fix of L052 should move `;` at the end of `CREATE TABLE` statement to the next line when `multiline_newline = True`.

## Observed Behaviour

* Auto-fix printed the following when `sqlfluff fix` is executed:
```
==== finding fixable violations ====
WARNING    Loop limit on fixes reached [10].
== [sample.sql] FAIL
L:   3 | P:   2 | L052 | Statements must end with a semi-colon.
==== fixing violations ====
1 fixable linting violations found
```
* Auto-fix for L052 did not move `;` to the next line.
* Auto-fix for L052 appended multiple `;` after the `CREATE TABLE` statement.

## Steps to Reproduce

1. Create `sample.sql` with the following content:
```
CREATE TABLE my_table (
    id INTEGER
);
```
2. Override L052 to force semi colon of multi-line statement to be on the new line with the following override: (You can create a `.sqlfluff` with the content below.)
```
[sqlfluff:rules:L052]
multiline_newline = True
```
3. Run `sqlfluff fix sample.sql -f`

## Dialect

Ansi (Default - Not specific to any dialect.)

## Version

```
(.venv) ~/code/sqlfluff (main) $ sqlfluff fix sample.sql
(.venv) ~/code/sqlfluff (main) $ sqlfluff --version
sqlfluff, version 0.9.1
(.venv) ~/code/sqlfluff (main) $ python --version
Python 3.9.9
```

## Configuration
* Override L052 to force multiline statement's semicolon to always be in a new line.
```
[sqlfluff:rules:L052]
multiline_newline = True
```

## Output of `sqlfluff fix`

```
(.venv) ~/code/sqlfluff (main) $ sqlfluff fix sample.sql
==== finding fixable violations ====
WARNING    Loop limit on fixes reached [10].
== [sample.sql] FAIL
L:   3 | P:   2 | L052 | Statements must end with a semi-colon.
==== fixing violations ====
1 fixable linting violations found
Are you sure you wish to attempt to fix these? [Y/n] ...
Attempting fixes...
Persisting Changes...
== [sample.sql] PASS
Done. Please check your files to confirm.
All Finished 📜 🎉!
(.venv) ~/code/sqlfluff (main) $
```

**Comment by barrywhart** [comment]
@jpy-git: Interested in looking at this one? It relates to L052, which you added recently.
