### ISSUE TITLE
Do we need the Implementation section of the Rules doc page?

### ISSUE THREAD

**Issue by tunetheweb** [sqlfluff/sqlfluff#2286]
## URL or Command Line Option with the issue being reported

https://docs.sqlfluff.com/en/stable/rules.html#implementation

## Issue/Suggested Improvement

The Implementation section seems to list a lot of the internals of the rules. It's wedged between the rules themselves, and the information on how to ignore certain rules - both of which are more aimed at end users than SQLFluff rules developers.

I actually though the Implementation section was an error, and went back a few versions to see when it was incorrectly included. But looks like it has always been there.

Should the Implementation be on a separate page?
Or perhaps move the ignore section up to beneath the rules so the top of the page is for users, and the bottom has more detail for developers?

**Comment by barrywhart** [comment]
I agree with moving it to a different page for developers, not users.

**Comment by jpy-git** [comment]
Agree it can be moved 👍
