### ISSUE TITLE
Missing configuration documentation in rule L054

### ISSUE THREAD

**Issue by tomasfarias** [sqlfluff/sqlfluff#2287]
Despite having a configuration keyword (`group_by_and_order_by_style`), Rule L054 is missing configuration documentation whereas other rules, like L057, do have it.

## URL or Command Line Option with the issue being reported

https://docs.sqlfluff.com/en/stable/rules.html#sqlfluff.core.rules.Rule_L054

## Issue/Suggested Improvement

Seems like the issue would be fixed by decorating [`Rule_L054`](https://github.com/sqlfluff/sqlfluff/blob/main/src/sqlfluff/rules/L054.py#L7) with [`document_configuration`](https://github.com/sqlfluff/sqlfluff/blob/main/src/sqlfluff/core/rules/doc_decorators.py#L21), as the configuration keyword is already present in [config_info.py](https://github.com/sqlfluff/sqlfluff/blob/main/src/sqlfluff/core/rules/config_info.py#L120).

I can submit a PR if this is indeed the case.

## Offtopic question

Would it be worth it to create an issue raising the need for having L054 enforce a consistent style within `GROUP BY` and `ORDER BY` clauses, but **not** across them, or is this something that has already been discussed and rejected before?

Thanks!

**Comment by tunetheweb** [comment]
> Seems like the issue would be fixed by decorating [`Rule_L054`](https://github.com/sqlfluff/sqlfluff/blob/main/src/sqlfluff/rules/L054.py#L7) with [`document_configuration`](https://github.com/sqlfluff/sqlfluff/blob/main/src/sqlfluff/core/rules/doc_decorators.py#L21), as the configuration keyword is already present in [config_info.py](https://github.com/sqlfluff/sqlfluff/blob/main/src/sqlfluff/core/rules/config_info.py#L120).

Yup it's exactly that - good spot. Adding that fixes it:

![image](https://user-images.githubusercontent.com/10931297/149005405-12ffaa50-82a5-40f0-a2bb-f949f2151565.png)

Wanna open a PR?

I wonder if there's some test we could put in to flag this in future?

> Would it be worth it to create an issue raising the need for having L054 enforce a consistent style within `GROUP BY` and `ORDER BY` clauses, but **not** across them, or is this something that has already been discussed and rejected before?

It should be doing it **across** them too. See this test case for example:

https://github.com/sqlfluff/sqlfluff/blob/faf16d06ecf6ba0d19cb5ab0c029f73383d5dc2d/test/fixtures/rules/std_rule_cases/L054.yml#L87-L97

Do you have an example where it doesn't do this?

**Comment by tomasfarias** [comment]
> Wanna open a PR?

Just opened a quick PR.

> I wonder if there's some test we could put in to flag this in future?

Perhaps we can:
* If the class has a non-empty `config_keywords`:
  * Check `class.__doc__` for the existence of a `"* Configuration"` substring.
  * Check `class.__doc__` for the existence of a substring for each config keyword.
  * Fail test if any of the previous 2 checks failed, pass otherwise.
* If empty `config_keywords`: pass.

> It should be doing it across them too. See this test case for example:
> Do you have an example where it doesn't do this?

I didn't express myself correctly, yes the rule is checking across `GROUP BY`s and `ORDER BY`s. I intended to ask if we had considered adding a configuration value to check within clauses and not across them.

Or perhaps separating the rule into two: one for `GROUP BY` clauses, another one for `ORDER BY`, kind of how L030 checks for inconsistent capitalization for functions and L010 does so for keywords.
