### ISSUE TITLE
Add example to parse one file in test/fixtures/dialects/...

### ISSUE THREAD

**Issue by kayman-mk** [sqlfluff/sqlfluff#2313]
## URL or Command Line Option with the issue being reported
https://github.com/sqlfluff/sqlfluff/blob/main/CONTRIBUTING.md

## Issue/Suggested Improvement
Would be nice to have an example in the CONTRIBUTING.md on how to parse a single file of the test fixture sql. This would make my life a little bit easier as it is much faster than to generate all test fixtures and check the corresponding yml file.

I have found a description on how to run a single test case but I have no clue on how to parse an sql file if I have changed Sqlfluff and want to validate my changes against some fixtures.

**Comment by tunetheweb** [comment]
As the test files are write in SQL just run it like you would a normal SQL file instead of through an test suite command:

```
sqlfluff parse test/fixture/ansi/example.sql
```

Add a `—dialect` option if not ansi.

Note this will NOT generate the yml file but will tell you if it parsed or not and allow you to check the parse tree.

**Comment by kayman-mk** [comment]
@tunetheweb But this will use the installed version of Sqlfluff and not the one I changed locally, won't it?

**Comment by tunetheweb** [comment]
If you “activate’ you local venv it will use that. Though someone’s just raised #2314 to suggest that is done differently when using tox so keep an eye on that issue if doing that. Wasn’t aware it was different myself.

**Comment by kayman-mk** [comment]
Oh no, things can be so simple. Thanks!
#2314 was created by me ;-)

**Comment by tunetheweb** [comment]
Oops. Shouldn’t answer issues on my phone! 😁
