### ISSUE TITLE
"standard" output format

### ISSUE THREAD

**Issue by RRikor** [sqlfluff/sqlfluff#2331]
I'm having trouble integrating this program into my Neovim. Most of the linters have an output format that looks like `file-path:line:column: message`

There are format option specified, but that does not output similar results. Is there an option/config possibility I missed somewhere to get output like this? If not, this could be a nice enhancement.

**Comment by barrywhart** [comment]
One possible workaround: Could you try using `sqlfluff lint --format github-annotation`, then transforming the output (perhaps using `jq`)?

https://stedolan.github.io/jq/manual/

**Comment by RRikor** [comment]
I'll give something like that a try, thanks!
