### ISSUE TITLE
Support raiserror in TSQL

### ISSUE THREAD

**Issue by fdw** [sqlfluff/sqlfluff#2367]
T-SQL has a [raiserror](https://docs.microsoft.com/en-us/sql/t-sql/language-elements/raiserror-transact-sql?view=sql-server-ver15) statement that doesn't seem to be parsed by `sqlfluff`.

**Comment by fdw** [comment]
Do you have any hint how to implement this? So far, I have only found that the keyword already exists, but I don't have any idea where to add it to the grammar.

**Comment by tunetheweb** [comment]
This seems to be the basic syntax for a very simple RAISERROR statement:

```py
@tsql_dialect.segment()
class RaiserrorStatementSegment(BaseSegment):
    """RAISERROR statement.

    https://docs.microsoft.com/en-us/sql/t-sql/language-elements/raiserror-transact-sql?view=sql-server-ver15
    """

    type = "raiserror_statement"
    match_grammar = Sequence(
        "RAISERROR",
        Bracketed(
            Delimited(
                Ref("NumericLiteralSegment"),
                OneOf(Ref("NumericLiteralSegment"), Ref("QualifiedNumericLiteralSegment")),
                OneOf(Ref("NumericLiteralSegment"), Ref("QualifiedNumericLiteralSegment")),
                Ref("QuotedLiteralSegment"),
            ),
        ),
    )
```

And then add `RaiserrorStatementSegment` to `class StatementSegment`.

Might be good to create an `OptionallyQualifiedNumericLiteralSegment` (surprised we haven't got one of those already!) to avoid repeating the `OneOf(Ref("NumericLiteralSegment"), Ref("QualifiedNumericLiteralSegment"))` bit

Then you can expand this statement with everything else `RAISERROR` supports.
