### ISSUE TITLE
return does not need a parameter

### ISSUE THREAD

**Issue by fdw** [sqlfluff/sqlfluff#2370]
At least in T-SQL, `return` does not require a parameter: https://docs.microsoft.com/en-us/sql/t-sql/language-elements/return-transact-sql?view=sql-server-ver15

## Expected Behaviour
```sql
return;
```
can be parsed

## Observed Behaviour
parsing fails

## Steps to Reproduce
1. Use `return` without a paramter somewhere.
2. Run `sqlfluff parse` on it

## Dialect
T-SQL

## Version
```
sqlfluff, version 0.9.1
Python 3.10.1
```

## Configuration
```
[sqlfluff]
dialect = tsql
```

**Comment by jpy-git** [comment]
@fdw if you want to fix this one it should be a very quick PR. Just change `Ref("ExpressionSegment"),` to `Ref("ExpressionSegment", optional=True),` here:  
https://github.com/sqlfluff/sqlfluff/blob/d974cdaa1c49090fa1460c10d2b9d9ae69cd5fb8/src/sqlfluff/dialects/dialect_tsql.py#L1443-L1452

**Comment by tunetheweb** [comment]
> @fdw if you want to fix this one it should be a very quick PR. Just change...

And add a test case 😁

More info: https://github.com/sqlfluff/sqlfluff/wiki/Contributing-Dialect-Changes

**Comment by fdw** [comment]
I think I might try my hand at this, when I have some time. Thank you! 🙂

**Comment by RishiKumarRay** [comment]
Can i raise a PR , by just changing it to this as you said Ref("ExpressionSegment", optional=True),? One thing is it compulsory to add test case, Because I won't be able to do it .

**Comment by jpy-git** [comment]
@RishiKumarRay adding the test case is compulsory.
