### ISSUE TITLE
tsql: Should be able to parse stored procedure declarations with default values for parameters

### ISSUE THREAD

**Issue by fdw** [sqlfluff/sqlfluff#2372]
At least in T-SQL, you can define default values for a stored procedure's parameters (https://docs.microsoft.com/en-us/sql/relational-databases/stored-procedures/specify-parameters?view=sql-server-ver15#specifying-parameter-data-types). It would be nice if `sqlfluff` could parse and maybe even format them.

**Comment by barrywhart** [comment]
Can you provide an example SQL that you'd like SQLFluff to be able to parse?

**Comment by fdw** [comment]
Sure:
```sql
create or alter procedure name
  @param1 nvarchar(10) = 'test',
  @param2 int = 21
as begin
  return 1;
end
```
