### ISSUE TITLE
Snowflake issue parsing statement with COLUMN as an identifier

### ISSUE THREAD

**Issue by alvare16** [sqlfluff/sqlfluff#2375]
Trying to create a boolean in this way: 
` coalesce(a.column like '%"attribute":{"name":"something"%', false) as is_column`

## Expected Behaviour
The expected behavior would be for sqlfluff to lint my model and show me any lint errors that might exist.

## Observed Behaviour
sqlfluff returns a value error like:
`ValueError: unmatched '{' in format spec`

## Steps to Reproduce
Add a '{' characterwhile trying to match a pattern in a column.

## Dialect
Snowflake

## Version

sqlfluff, version 0.9.1
Python 3.7.4
dbt installed version: 0.21.0

## Configuration
```
[sqlfluff]
verbose = 0
nocolor = False
dialect = snowflake
templater = dbt
exclude_rules = L009, L011, L021, L029, L031, L033, L034, L041, L042, L044, L047, L050, L054
# link to the rule docs https://docs.sqlfluff.com/en/stable/rules.html
recurse = 0
output_line_length = 110
runaway_limit = 10
ignore_templated_areas = True
encoding = autodetect
# Comma separated list of file extensions to lint.

# NB: This config will only apply in the root folder.
sql_file_exts = .sql,.sql.j2,.dml,.ddl

[sqlfluff:indentation]
indented_joins = False
indented_using_on = false
template_blocks_indent = True

[sqlfluff:templater]
unwrap_wrapped_queries = True

[sqlfluff:templater:dbt]
apply_dbt_builtins = True

# Some rules can be configured directly from the config common to other rules.
[sqlfluff:rules]
tab_space_size = 4
max_line_length = 110
indent_unit = tab
comma_style = trailing
allow_scalar = False
single_table_references = consistent
unquoted_identifiers_policy = all

# Some rules have their own specific config.
[sqlfluff:rules:L007]  # Keywords
operator_new_lines = after

[sqlfluff:rules:L010]  # Keywords
capitalisation_policy = lower

[sqlfluff:rules:L012]  # Aliasing
aliasing = explicit

[sqlfluff:rules:L014]  # Unquoted identifiers
extended_capitalisation_policy = lower

[sqlfluff:rules:L016]
ignore_comment_lines = False

[sqlfluff:rules:L026]
force_enable = False

[sqlfluff:rules:L028]
force_enable = True

[sqlfluff:rules:L029]  # Keyword identifiers
unquoted_identifiers_policy = aliases

[sqlfluff:rules:L030]  # Function names
capitalisation_policy = lower

[sqlfluff:rules:L038]
select_clause_trailing_comma = forbid

[sqlfluff:rules:L040]  # Null & Boolean Literals
capitalisation_policy = lower
```

**Comment by tunetheweb** [comment]
It's not the `{`. This works fine for example:

```sql
SELECT a AS '%"attribute":{"name":"something"%'
FROM table1
```

It's the fact our Snowflake definition doesn't like a column name to be called `column` as that's a reserved word. This works fine:

```sql
SELECT coalesce(a.colum like '%"attribute":{"name":"something"%', false) as is_column
FROM table1 a
```

The Snowflake [keyword documentation](https://docs.snowflake.com/en/sql-reference/reserved-keywords.html) says this is a reserved word:

![image](https://user-images.githubusercontent.com/10931297/150394522-df984706-007a-47b0-a11f-c77124c451a1.png)

Is that's not the case, and the documentation is wrong, then we can easily move it to the `snowflake_unreserved_keywords` instead and then it parses fine.

**Comment by jpy-git** [comment]
@tunetheweb if it is then it's not fully unreserved:
![image](https://user-images.githubusercontent.com/80432516/150396464-45900673-adc9-4a82-9d3b-5c81d2e0aaea.png)

Sounds like a similar situation to what we had for `TABLE` in postgres the other day: https://github.com/sqlfluff/sqlfluff/issues/2306#issuecomment-1015517744

Happy for them to made unreserved if it doesn't introduce new parsing issues

**Comment by tunetheweb** [comment]
Raised this: https://github.com/sqlfluff/sqlfluff/pull/2376 so let's see. It's not reserved in ANSI so doubt it'll cause an issue.
