### ISSUE TITLE
Code coverage has dropped below 100% (again)

### ISSUE THREAD

**Issue by tunetheweb** [sqlfluff/sqlfluff#2420]
## Expected Behaviour

PRs should complete with 100% coverage and no loss in coverage.

This makes it easier to identify loss in coverage and avoids rounding errors leading to apparent loss in coverage when this is not due to that PR

`noqa` should be used when we're happy for code not to have coverage to keep us at 100%

## Observed Behaviour

We're at 99.93%

@barrywhart it looks like it was due to one of your PRs, and your follow up fix did not fully recover all the missing coverage:

![image](https://user-images.githubusercontent.com/10931297/150638718-eb6ea56b-80d5-4a65-89db-b40254d68a91.png)

I didn't notice when I merged that fix, as it did increase coverage so the CodeCov test passed (because the previous PR was merged in error without waiting for that to complete)

It's complaining that [templaters/slicers/heuristic.py](https://github.com/sqlfluff/sqlfluff/blob/main/src/sqlfluff/core/templaters/slicers/heuristic.py) is missing quite a bit of coverage:

![image](https://user-images.githubusercontent.com/10931297/150638789-c0aa0242-1656-403f-873e-980e049f2921.png)

![image](https://user-images.githubusercontent.com/10931297/150638780-daa818bd-c027-4485-947d-49d5f8686296.png)

Is this code still needed?
If so can it either be covered by a test or `noqa`?
If not can it be removed?

@alanmcruickshank can we _please_ make this a mandatory test to prevent regressions like this in future?

**Comment by barrywhart** [comment]
This file is not used anymore. It was essentially replaced by `JinjaTracer`. I had left it in place for some time, worried that `JinjaTracer` may have some big, hidden flaw and we'd need to revive this or fall back to it in some cases. I think I'll just remove it, since this is becoming troublesome. We can dig it out of the git history if we ever need to. Hope not! 🤞
