### ISSUE TITLE
COPY INTO from a stage in Snowflake throws list index out of range error

### ISSUE THREAD

**Issue by erevear** [sqlfluff/sqlfluff#2432]
## Expected Behaviour
Running rules 20,27, and 40 should check against the code for related issues and pass/fail based on code. This was the behavior in version 0.9.0
Problem seems related to COPY INTO as this issue doesn't occur on SELECT statements

## Observed Behaviour
Following errors:

L:   1 | P:   1 | L044 | Unexpected exception: list index out of range; Could you
                       | open an issue at
                       | https://github.com/sqlfluff/sqlfluff/issues ? You can
                       | ignore this exception for now, by adding '--noqa: L044'
                       | at the end of line 1
L:   9 | P:   5 | L020 | Unexpected exception: list index out of range; Could you
                       | open an issue at
                       | https://github.com/sqlfluff/sqlfluff/issues ? You can
                       | ignore this exception for now, by adding '--noqa: L020'
                       | at the end of line 9
L:   9 | P:   5 | L027 | Unexpected exception: list index out of range; Could you
                       | open an issue at
                       | https://github.com/sqlfluff/sqlfluff/issues ? You can
                       | ignore this exception for now, by adding '--noqa: L027'
                       | at the end of line 9

## Steps to Reproduce
Run sqlfluff lint on following SQL with rules 27, 44, and 20:
```
COPY INTO MY_TABLE (
                    COLUMN1
                  , COLUMN2
                  , COLUMN3


)
FROM (
    SELECT
            COLUMNA AS COLUMN1
            , COLUMNB AS COLUMN2
            , COLUMNC AS COLUMN3




    FROM @STG.MY_STAGE
)
FILE_FORMAT = (TYPE = JSON STRIP_OUTER_ARRAY = TRUE)
FORCE = TRUE
;
```

## Dialect
snowflake
## Version

sqlfluff version 0.9.1
python version 3.9
## Configuration
```
Include your SQLFluff configuration here
```

**Comment by tunetheweb** [comment]
Good news is that this was fixed in #2320 and now parses correctly in `main` branch. We've working on a 0.9.2 release (probably for Monday) which will include this fix.
