### ISSUE TITLE
T-SQL: INSERT INTO table EXECUTE

### ISSUE THREAD

**Issue by fdw** [sqlfluff/sqlfluff#2444]
T-SQL supports the syntax `INSERT INTO <table> EXECUTE <stored_procedure>` to insert the results of a stored procedure into a table.
(https://docs.microsoft.com/en-us/sql/t-sql/statements/insert-transact-sql?view=sql-server-ver15#syntax)

Postgres and MySQL don't seem support it or something similar.

**Comment by tunetheweb** [comment]
I _think_ this should be a simple matter of changing this line of `InsertStatementSegment`

https://github.com/sqlfluff/sqlfluff/blob/c8f495f74c06a4daae7c0a9c3e5909e3f61b8d2a/src/sqlfluff/dialects/dialect_tsql.py#L524

to:

```py
        OneOf(Ref("SelectableGrammar"), Ref("ExecuteScriptSegment")),
```

And adding a test case.

**Comment by fdw** [comment]
Thanks very much for the hint 🙂
