### ISSUE TITLE
T-SQL: Support @@rowcount

### ISSUE THREAD

**Issue by fdw** [sqlfluff/sqlfluff#2445]
In T-SQL, there are the (undeclared) variables `@@rowcount` and `@@rowcount_big` that `sqlfluff` doesn't yet recognize. (https://docs.microsoft.com/en-us/sql/t-sql/functions/rowcount-transact-sql?view=sql-server-ver15)

**Comment by tunetheweb** [comment]
The simplest answer would be to update this regex to allow for one `@`'s or two `@`'s at the beginning:

https://github.com/sqlfluff/sqlfluff/blob/c50b58918759fc2871fbcf7d68b77b1487c42cc4/src/sqlfluff/dialects/dialect_tsql.py#L189-L191

That would mean however that procedures/functions could use double `@`'s for their params which is not valid (I presume?). The other alternative would be to define a `SystemParameterNameSegment` and only insert that where it's allowed (`LiteralGrammar` only maybe?)
