### ISSUE TITLE
Support SOQL & SOSL dialects (Salesforce)

### ISSUE THREAD

**Issue by nvuillam** [sqlfluff/sqlfluff#2465]
Salesforce's SOQL and SOSL linting and autofixing by sqlfluff would have a huge impact on 3 millions developers in Salesforce ecosystem :)

https://developer.salesforce.com/docs/atlas.en-us.soql_sosl.meta/soql_sosl/sforce_api_calls_soql_sosl_intro.htm

Would you consider supporting them ?

I could contribute obviously :)

Note: most of SOQL / SOSL calls are directly implemented within Apex code (apex is Salesforce Platform java-like back-end language), would it be compliant with sqlfluff ?

Best regards

**Comment by tunetheweb** [comment]
Looks to me like SOQL could be added with relative ease, but would need someone who uses it/understands it to do that if you're up for that?

SQLFluff has a core ANSI dialect that provides the main SQL syntax, then individual dialects can override, or add to that "core" syntax for their own individual tweaks.

So first step would be to add the `soql` dialect with maybe one or two statements where it's different than ANSI. Here's an example PR where we added basic Oracle support recently to give you an idea: https://github.com/sqlfluff/sqlfluff/pull/2293.

Then just expand the syntax more and more to have a good level of coverage. This is where a real user of the syntax is invaluable as they'll have a set of queries to test on to see what dialect changes need to be added. Here's some info on that: https://github.com/sqlfluff/sqlfluff/wiki/Contributing-Dialect-Changes.

SOSL looks a bit different from SQL so maybe not a great fit. Saying that, other dialects have their own procedure language extensions, some of which have been at least partially implemented here. So possible, but I would start with SOQL and see how that goes first.

**Comment by nvuillam** [comment]
I (sadly) play with SOQL everyday, so yes I could provide inputs :)

SOSL is less used and could be let aside :)

**Comment by PLBMR** [comment]
@tunetheweb @nvuillam I use SOQL in my current job, and I could help with building out the dialect. Want to split this ticket up into SOQL/SOSL dialect support, and assign SOQL to me? I can spike on the major distinctions from ANSI.

**Comment by greg-finley** [comment]
Here's a [random article](https://skyvia.com/blog/soql-vs-sql-best-practices-to-query-salesforce-database#differences-soql-sql) about the differences.

Two SOQL things jump to mind that aren't parseable in ANSI:

1. `WHERE CreatedDate = LAST_N_DAYS:30` (`Found unparsable section: ':30'`).
2. `SELECT Account.Name FROM Contact` (`Reference 'Account.Name' refers to table/view not found`)

Fixing those should be enough of a start to the dialect. There are SQL things not possible in SOQL (`SELECT *`, `JOIN`), but we could get just tolerate them to begin with.

**Comment by tunetheweb** [comment]
FYI, here's the latest PR that added a new dialect (Db2): https://github.com/sqlfluff/sqlfluff/pull/3231

This gives some indication of what's needed to set it up as a dialect, and can then start adding new syntax/overrides to support differences from our ANSI dialect.

**Comment by greg-finley** [comment]
I just learned that SOQL doesn't end its statements with semicolons.

For anyone who knows SOQL more: can you put multiple queries in the same "file"? If so, how are they delimited (new lines?)? Like here's a test file of SQLs that each end in semicolons; how to do the same for SOQL? https://github.com/sqlfluff/sqlfluff/blob/main/test/fixtures/dialects/mysql/create_user.sql

**Comment by nvuillam** [comment]
@greg-finley I've never seen multiple SOQL queries in a single file
The use case seems to write a request in a .soql file and execute it using sfdx, for example

`sfdx force:data:soql:query -q "SELECT Name FROM Account"`

- There is no command to run multiple SOQL requests
- Bulk data is managed with JSON/CSV files so there are no scripts with a big list of INSERT (one line per record) like we can see with pure SQL
