### ISSUE TITLE
T-SQL: CREATE FUNCTION needs parentheses even if there are no parameters

### ISSUE THREAD

**Issue by fdw** [sqlfluff/sqlfluff#2472]
## Expected Behaviour
```sql
create or alter function test() returns int as
begin
  return 2;
end
```
is correct T-SQL and should work.

## Observed Behaviour
`sqlfluff` cannot parse the statement, as it either expect at least one parameter in the parentheses, or no parantheses at all (which is not valid T-SQL).

## Steps to Reproduce
See above

## Dialect
T-SQL

## Version
Latest `sqlfluff` from git
Python 3.10.1

## Configuration
```
[sqlfluff]
dialect = tsql
```

**Comment by tunetheweb** [comment]
Imagine this should be a matter of changing this:

```py
    # Function parameter list
    match_grammar = OptionallyBracketed(
        Ref("FunctionParameterGrammar"),
        AnyNumberOf(
            Ref("CommaSegment"),
            Ref("FunctionParameterGrammar"),
        ),
    )
```

to something like this:

```py
    # Function parameter list
    match_grammar = OptionallyBracketed(
        Sequence(
            Ref("FunctionParameterGrammar"),
            AnyNumberOf(
                Ref("CommaSegment"),
                Ref("FunctionParameterGrammar"),
            ),
            optional=True,
        ),
    )
```

**Comment by fdw** [comment]
I was at first irritated about the *optionally* bracketed as functions in T0SQL must always have parentheses. But it seems that the same class is also used for stored procedures, where the must not be parentheses.

So, I'm wondering whether it makes sense to split that into `FuncionParameterList` and `ProcedureParameterList`, as it currently allows incorrect SQL. What do you think?

**Comment by tunetheweb** [comment]
SGTM!
