### ISSUE TITLE
Possible issue with Coverage 6.3

### ISSUE THREAD

**Issue by tunetheweb** [sqlfluff/sqlfluff#2483]
## Expected Behaviour

CI should run and be reasonably stable

## Observed Behaviour

CI has been very unstable this evening, particularly for python 3.7. Looks like coverage 6.3 was released with some changes here, and did see some coverage error messages. I frooze it at 6.2 in #2479 and CI completed first time, despite not working one any open PRs for ages.

## Steps to Reproduce

Unfreeze coverage in requirements_dev.txt and run tests on Python 3.7. I can't get that set up on my local machine to confirm, but seems to be the case in CI.

## Dialect

All

## Version

0.9.2

## Configuration
Default

**Comment by tunetheweb** [comment]
I raised this: https://github.com/nedbat/coveragepy/issues/1310

We'll stay on 6.2 and see if more stable.

If anyone has any idea how to get a minimal repo to give to them then let me know!

**Comment by barrywhart** [comment]
I looked at the linked issue in the coveragepy repo, and there's active discussion on it. It sounds like they've seen similar issues elsewhere. 🤞

**Comment by tunetheweb** [comment]
Yup I'm keeping an eye on it, and tested one branch for them (but didn't fix it). Will leave this issue open to remind us to unpin it, if it gets resolved (at which point we might want to set minimum version number - pity you can't say != 6.3, but don't think you can do that).

**Comment by barrywhart** [comment]
Actually, you _can_ specify `!=`. https://www.python.org/dev/peps/pep-0440/#version-exclusion

The link provides an example and explanation.

**Comment by barrywhart** [comment]
I see that coverage 6.3.1 was released a couple months ago, and it says it fixed some of the deadlocks they were seeing. Do we know if that version fixes our issues?

https://github.com/nedbat/coveragepy/blob/master/CHANGES.rst#version-631--2022-02-01

**Comment by tunetheweb** [comment]
Nope. Hence why https://github.com/nedbat/coveragepy/issues/1310 is still open.

**Comment by tunetheweb** [comment]
Fixed in coverage 6.4: https://github.com/nedbat/coveragepy/issues/1310
