### ISSUE TITLE
Add `inline_comment_prefixes="#"` to configparser

### ISSUE THREAD

**Issue by its-gazza** [sqlfluff/sqlfluff#2493]
Currently sqlfluff reads in configuration files via `configparser.ConfigParser(**kw)` ([Reference](https://github.com/sqlfluff/sqlfluff/blob/7fbc8768a64590c1555c2d91d7bfb3e4741aebea/src/sqlfluff/core/config.py#L201)).

This causes issue when users put in comments after the line. For example: 

```ini
[sqlfluff]
dialect = teradata  # Some comment
```

will return `KeyError: 'teradata. # Some comment'`.

This can be resolved by adding the `inline_comment_prefixes="#"` option in `configparser.ConfigParser`.

Happy to create a PR for this.

**Comment by jpy-git** [comment]
@its-gazza While it seems like a cool idea, my gut feeling is Python doesn't make it default behaviour for a reason.

Consider someone using one of the templater features and they want a variable/macro/placeholder to contain a `#`:
*./test.cfg*
```
[sqlfluff:templater:jinja:context]
my_str='I am a #string not a #comment'
```

No inline comment:
*./test.py*
```python
>>> from configparser import ConfigParser
>>> cfg = ConfigParser()
>>> cfg.read("./test.cfg")
>>> cfg.get("sqlfluff:templater:jinja:context", "my_str")
"'I am a #string not a #comment'"
```

With inline comment:
*./test.py*
```python
>>> from configparser import ConfigParser
>>> cfg = ConfigParser(inline_comment_prefixes="#")
>>> cfg.read("./test.cfg")
>>> cfg.get("sqlfluff:templater:jinja:context", "my_str")
"'I am a"
```

**Comment by jpy-git** [comment]
So any solution would need to be able to handle that case.

N.B. You can always add comments above or below the relevant line:
```
[sqlfluff]
# Some comment
dialect = teradata 
```

**Comment by its-gazza** [comment]
I agree. The other reason I was requesting this feature is it'll look better in the `exclude_rules` section.

For example:

```ini
[sqlfluff]
exclude_rules = 
    L001,  # Unnecessary trailing whitespace
    L002,  # Mixed Tabs and Spaces in single whitespace
```

Looks better than

```ini
[sqlfluff]
exclude_rules = 
    # Unnecessary trailing whitespace
    L001,
    # Mixed Tabs and Spaces in single whitespace
    L002,
```

But i see your point, happy for this to be closed.

**Comment by tunetheweb** [comment]
I still like this change as don't think it's obvious this CAN'T be used - especially as it CAN be used on the group lines (e.g. `[sqlfluff]`).

Is there anyway to exclude # from quoted strings? And also insist at least one space  before the `#` for inline comments?

**Comment by its-gazza** [comment]
We could do it via regex, regex101 [here](https://regex101.com/r/RtjzKo/1).

In Python we could do something like:

```python
>>> from configparser import ConfigParser
>>> import re
>>> 
>>> regex = re.compile(r"(?!\")\W{2}#.*?$", re.MULTILINE)
>>> 
>>> cfg = ConfigParser()
>>> cfg.read("./setup.cfg")
['./setup.cfg']
>>> 
>>> print(f"Original: {cfg['sqlfluff']['test']}")
Original: "This is a # comment"
>>> print(f"Replaced: {re.sub(regex, '', cfg['sqlfluff']['test'])}")
Replaced: "This is a # comment"
>>> 
>>> print(f"Original: {cfg['sqlfluff']['test1']}")
Original: "This is a comment"  # Something
>>> print(f"Replaced: {re.sub(regex, '', cfg['sqlfluff']['test1'])}")
Replaced: "This is a comment"
>>> 
>>> print(f"Original: {cfg['sqlfluff']['rules']}")
Original: 
L001,  # Something
L002,  # Something
>>> print(f"Replaced: {re.sub(regex, '', cfg['sqlfluff']['rules'])}")
Replaced: 
L001,
L002,"
```

**Comment by jpy-git** [comment]
But when it comes to templating there's no reason the hash needs to be enclosed in quotes
```cfg
[sqlfluff:templater:jinja:context]
mysql=SELECT foo FROM bar; # I am a MySQL comment that should be included in template
```
^ That whole line could be subbed into a jinja template, but the regex would pick that up as a config comment.

My preference would be to just stick with the current approach of having comments on their own line since it allows freedom to template whatever the user wants and doesn't introduce any inconsistency between which config lines can have inline comments and which can't.

**Comment by tunetheweb** [comment]
Fair point. But an alternative POV is it _might be good_ to remove such comments to prevent issue. The comments don’t have any benefit (except in the config!) as they are only for SQLFluff.

Consider this SQL, which uses your templated code:

```sql
SELECT *
FROM table1
WHERE col1 IN {{ mysql }} AND col2 = true
```

Then again, an alternative is you might want a `#` for some other reason than comments and you wouldn’t want them stripped out:

```
mysql=SELECT foo FROM bar WHERE code like ‘%#%’
```

So can’t have both 🤷Unless you also introduce some escape sequence support too. And that’s probably more complicated than we want.

Anyway, my main concern was someone using a comment and not realising it wouldn’t be stripped out. But rereading the original post, I see it does cause a syntax error (though the one at the beginning of this comment won’t) so I’m not as pushed to have this after all. So I’m OK closing this.
