### ISSUE TITLE
Drop support for older dbt versions (<= 0.19.*)

### ISSUE THREAD

**Issue by barrywhart** [sqlfluff/sqlfluff#2514]
Some of the recent package dependency challenges with Black (#2512) make me think we should drop support for older dbt versions (i.e. prior to dbt 1.0.0). IIUC, there's very little usage of older versions now. Dropping support for these older versions will clean up the code and significantly reduce SQLFluff's "surface area" for version conflicts.

**Comment by alanmcruickshank** [comment]
I'm not sure I understand the link - does dbt have a dependency on black? I can't see one: https://github.com/dbt-labs/dbt-core/blob/main/core/setup.py.

If there is a direct link, then I feel like we shouldn't be tied to the version of black which dbt requires - but I'm also suprised that dbt has any dependency on black in the first place - it isn't a library which it imports.

**Comment by barrywhart** [comment]
It doesn't depend on Black. I think dbt depends on an old version of typing-extensions, which conflicts with the version Black wants. We could probably untangle this and get it working, but I think there's also a question how much effort we'd want to put into supporting older versions of dbt, anyway: it likely benefits very few users and will likely cause more than its share of future issues.

**Comment by alanmcruickshank** [comment]
As per discussion in the maintainers meeting today, let's drop support for dbt <= 0.19.*. That should free up any historic dependency on black and allow us to upgrade black within our dependencies.

We should also remove/simplify any of the current if statements in the dbt templater which have special routes for those dbt versions (which should actually strip out quite a lot of old code).
