### ISSUE TITLE
Create String Constant Segment for Postgres DIalect

### ISSUE THREAD

**Issue by PLBMR** [sqlfluff/sqlfluff#2516]
In our Postgres Dialect, A String Constant (defined [here](https://www.postgresql.org/docs/9.3/sql-syntax-lexical.html) in 4.1.2.1-4) can be represented in our grammar using the following:

```py
                OneOf(
                    Ref("QuotedLiteralSegment"),
                    Ref("DollarQuotedLiteralSegment"),
                ),
```

To best modularize and maintain string constants in our parser, it might make sense for us to:
1. Create a `StringConstantSegment` class in our Postgres Dialect that has a `match_grammar` that is defined as above.
2. Refactor implicit references to string constants in our Postgres Dialect to explicit references to the `StringConstantSegment` class.

_Originally posted by @tunetheweb in https://github.com/sqlfluff/sqlfluff/pull/2511#pullrequestreview-867061366_

**Comment by jpy-git** [comment]
I don't think we need a new `StringConstantSegment`.
`DollarQuotedLiteralSegment` is really just another type of `QuotedLiteralSegment` that can be used in the same places and therefore we should just move the it into the contents of `QuotedLiteralSegment` like we already do for `unicode_single_quote` and `escaped_single_quote`:
https://github.com/sqlfluff/sqlfluff/blob/d3c9855b5f41b403bd9e2b062236215706510379/src/sqlfluff/dialects/dialect_postgres.py#L239-L273

That way anywhere `QuotedLiteralSegment` is used in ANSI/Postgres will then allow DollarQuotedLiteralSegments

**Comment by tunetheweb** [comment]
Added that change in #2526
