### ISSUE TITLE
Less strict click version

### ISSUE THREAD

**Issue by NiklasMolin** [sqlfluff/sqlfluff#2543]
From what I get the pinned click requirement >= 8.0.0 was added to support autocompletion of the cli. Could that be made optional  and the version requirement be lowered. It makes it difficult for us to combine in env with other old apps. It might be an edge case, I don't know but we get hit by it through and old airflow -> flask version.  

Get that it's not the intention by we and I would assume at a lot of other users prefer to have sqlfluff as a lib and used in other cli's or apps.

**Comment by tunetheweb** [comment]
I think that's a fair ask, since it's an optional extra. Does seem to be [causing other issues too](https://github.com/megalinter/megalinter/issues/1224).
