### ISSUE TITLE
BigQuery dialect "replace" appears to support invalid syntax and have trouble with a final trailing comma

### ISSUE THREAD

**Issue by elyobo** [sqlfluff/sqlfluff#2549]
BigQuery's `SELECT REPLACE()` syntax was causing a PRS error for me. Looking at the [underlying dialect implementation](https://github.com/sqlfluff/sqlfluff/blob/f0af9aa4c31ea348aba844057ce3a0aa52802321/src/sqlfluff/dialects/dialect_bigquery.py#L532) it seems to be attempting to support a replace syntax without parentheses that as far as I can see (from docs and trying it out) that BigQuery itself does not support.

![image](https://user-images.githubusercontent.com/407806/152333595-6e2f55d9-fe11-4281-b784-1268ce776a5f.png)

Amending the rule to be more like the rather similar `SELECT EXCEPT()` syntax locally resolves my PRS error.

```python
@bigquery_dialect.segment()                                                    
class ReplaceClauseSegment(BaseSegment):                                       
    """SELECT REPLACE clause."""                                               
                                                                               
    type = "select_replace_clause"                                             
    match_grammar = Sequence(                                                  
        "REPLACE",                                                             
        Bracketed(                                                             
            Delimited(                                                         
                # Not *really* a select target element. It behaves exactly     
                # the same way however.                                        
                Ref("SelectClauseElementSegment"),                             
                delimiter=Ref("CommaSegment"),                                 
            )                                                                  
        ),                                                                     
    )                                                                          
```

Happy to open a PR to make this change if I'm not doing something wildly wrong here.

**Comment by tunetheweb** [comment]
Can you give an example query? In the code snippet you've given above you can see it needs `"REPLACE" Bracketed(..)`

Also the following example SQL [from the BigQuery docs](https://cloud.google.com/bigquery/docs/reference/standard-sql/string_functions#replace) parses:

```sql
WITH desserts AS
  (SELECT 'apple pie' as dessert
  UNION ALL
  SELECT 'blackberry pie' as dessert
  UNION ALL
  SELECT 'cherry pie' as dessert)

SELECT
  REPLACE (dessert, 'pie', 'cobbler') as example
FROM desserts;
```

**Comment by tunetheweb** [comment]
Also [Select replace](https://cloud.google.com/bigquery/docs/reference/standard-sql/query-syntax#select_replace) example syntax also parses:

```sql
WITH orders AS
  (SELECT 5 as order_id,
  "sprocket" as item_name,
  200 as quantity)
SELECT * REPLACE ("widget" AS item_name)
FROM orders;
```

**Comment by elyobo** [comment]
Thanks for the super quick response!

Your example is the `REPLACE()` function, not the `SELECT REPLACE` clause, sorry if that was unclear - I highlighted it in the syntax screenshot. I agree that it needs the `SELECT REPLACE` bracketed but if you follow the link to the dialect it's doing a `OneOf` with an unbracketed version which doesn't exist in BQ as far as I can tell.

I was just trying to pin down the specific problematic syntax and think I've spotted it; a `SELECT REPLACE` with a trailing comma triggers the problem.

This triggers a PRS problem.
 
```sql
SELECT foo.* REPLACE(foo AS bar),
FROM foo
```

These do not.

```sql
SELECT
  foo.* REPLACE(foo AS bar),
  blarg,
FROM foo
```
```sql
SELECT foo.* REPLACE(foo AS bar)
FROM foo
```

**Comment by elyobo** [comment]
Worth noting that the current version _does_ parse this, but probably should not - BigQuery complains "Syntax error: Expected "(" but got identifier "foo" at [1:22]". The proposed update also makes this a PRS error for sqlfluff.

```sql
SELECT foo.* REPLACE foo AS bar
FROM foo
```

**Comment by tunetheweb** [comment]
Cool. Happy to take the PR.

> Edit: all parse fine with my proposed change to drop the OneOf, although I don't really understand why :)

Tried looking into this.

I think it's basically another instance of #2427 , so when there's a few parsing options, Delimited gets greedy, and then it doesn't try the un-greedy option (cause it has the second un-bracketed clause to try instead).

Anyway, your suggestion is right way to go to avoid this.
