### ISSUE TITLE
Update L016 to optionally ignore long COMMENT lines as well

### ISSUE THREAD

**Issue by srjonemed** [sqlfluff/sqlfluff#2554]
For example:
```
CREATE OR REPLACE TABLE mytable (
    col1 NUMBER COMMENT 'col1 comment',
    col2 BOOLEAN COMMENT 'very long comment line, exceeding max_line_length...',
    col3 NUMBER COMMENT 'col3 comment'
)

```
sqlfluff-fix throws `L016 | Line is too long` error assuming the col2 comment exceeds max_line_length setting.

Setting `ignore_comment_lines` to True also doesn't help.
Updating each of the offending lines with --noqa directive might not be scalable where there are 100s of files involved.

**Comment by niconoe-** [comment]
This is definitly something I would like to have too, and I can spend some time in trying to make it.

Only question that I have is "how to name this configuration?". I'm thinking about `ignore_too_long_description`. I don't want to use `comment` to not confuse people between "business comment" like the usage above (that can be used for field or table comments) and "sql comment" which will be ignored by the parser when executing the query (`-- ` or `# ` or `/* ... */`).

In the meantime, I'll work on it with a temporary name.

**Comment by niconoe-** [comment]
I think I miss some information like the type and the name of possible segments that are considered as literal comments for field or for table. But, my idea was to add a condition right after these lines:

https://github.com/sqlfluff/sqlfluff/blob/main/src/sqlfluff/rules/L016.py#L469-L471

Something like

```python
            if ignore_too_long_description and this_line[-1].type == "?<the_expected_segment_type_for_field/table_comment>?":
                return None
```

Also, this needs to be added on this block as we might have a too long column with a trailing inline comment:

https://github.com/sqlfluff/sqlfluff/blob/main/src/sqlfluff/rules/L016.py#L537-L540

What do you think about?

**Comment by srjonemed** [comment]
Given that we already have a `ignore_comment_lines`, how about `ignore_inline_column_comments`? I'm hoping we're planning on only ignoring L016 on offending lines and still apply other rules on those lines (other words, not completely ignore the offending lines).

**Comment by tunetheweb** [comment]
I had a look at this and it's pretty tricky! L016 currently looks at the segments after it sees a new line, so doesn't have the full parse tree so can't see a comment literal being part of a `comment_clause`. So it's gonna be tricky...

Alternative might be to automatically add a `--noqa: L016` comment to the end of the line nut that feels a little hacky. And might interfere with other `noqa`'s a user might have added.

@barrywhart 's having a look at L016 for another issue so he might have some better ideas depending on what he discovers during that work...

**Comment by barrywhart** [comment]
See PR #2589. I named the new option `ignore_comment_clause` because some dialects implement comment clauses on things besides columns.

**Comment by srjonemed** [comment]
Awesome, thanks! What release would #2589 be available from?

**Comment by barrywhart** [comment]
It'll be in 0.10.0, which will likely be released by the end of this week.

**Comment by srjonemed** [comment]
Thanks!

**Comment by niconoe-** [comment]
That is awesome! Thank you very much for this feature!
