### ISSUE TITLE
Treat keywords and datatypes separately for L010

### ISSUE THREAD

**Issue by jonyscathe** [sqlfluff/sqlfluff#2556]
It is fairly common in postgresql to use uppercase for keywords and lowercase for data types.

This is how all of the postgresql.org documentation examples are crafted (i.e., see examples section here https://www.postgresql.org/docs/14/sql-createtable.html) and it seems a bit odd to not be able to match the capitilisation policy that postgres use.

I assume it would be a fairly minor change to be able to treat keywords and datatypes as two separate lists.
Possibly just as a separate capitalisation_policy option, or maybe have a new rule config of datatype_capitilisation_policy with options of ['match_keywords', 'consistent', 'upper', 'lower', 'capitalise'] with a default of match_keywords which would just have datatype_capitilisation_policy equal capitalisation_policy so that it wouldn't break anyone's current config setup.

**Comment by tunetheweb** [comment]
I think a better way of doing this is to have a separate rule as that's what we do for Function Names (L030) and boolean/null literals (L040), whether keywords or not. This is also easier after we added some exclude functionality in #2913
