### ISSUE TITLE
case/when statements are breaking the L039 rule

### ISSUE THREAD

**Issue by dehjli85** [sqlfluff/sqlfluff#2585]
## Expected Behaviour
Would expect the linter to appropriately indent case statements

## Observed Behaviour
Fails L039, and when using the auto-fixer, comes up with less than desirable fixes

## Steps to Reproduce
```
select
    b,
    case
        when a = 1 then 'yes'
        else 'no'
    end as c
from table1

```
Notice that lines 5 and 6 throw linting errors for L039 rule.
When using the fix command, its results in this:

```
select
    b,
    case
        when a = 1 then 'yes'
 else 'no'
 end as c
from table1
```

Notice a single space before the `else` and `end` instead of alignment with the `when` and `case`, respectively. This was not throwing an error with version 0.8.2

## Dialect
postgresql

## Version
0.9.4

**Comment by tunetheweb** [comment]
This has been fixed in #2526 which will be in 0.9.5, hopefully released in next week or so.
