### ISSUE TITLE
L025 triggers when table alias is used in FROM clause

### ISSUE THREAD

**Issue by rpr-ableton** [sqlfluff/sqlfluff#2613]
When running sqlfluff lint --rules L025 on the following SQL statement:

```sql
SELECT
    tbl1.col1 AS col1
    , tbl3.col4 AS col4
FROM
    tbl1 AS tbl1
    JOIN tbl2 AS tbl2 ON (tbl2.col2 = tbl1.col2)
    JOIN tbl3 AS tbl3 ON (tbl3.col3 = tbl2.col3)
;
```

The following error shows up: `L:   6 | P:  18 | L025 | Alias 'tbl2' is never used in SELECT statement.`

This doesn't make sense since sometimes you need intermediate tables in a series of JOINs :sweat_smile:

## Dialect
Happens in ansi, redshift and probably all other flavors.

## Version

sqlfluff 0.10.0
python 3.9

## Configuration
None, just running `sqlfluff lint --rules L025`

**Comment by barrywhart** [comment]
@elyobo: Yes, please create a separate issue.

**Comment by barrywhart** [comment]
I found a simple explanation for the issue. It will also be a simple fix. SQL does not require parentheses around the `ON` expression, and the rule actually doesn't support them, i.e. if parentheses are used, the join expression is not processed. I confirmed this by removing the parentheses. I will update the rule to handle parentheses.
