### ISSUE TITLE
TSQL: Raiserror needs to handle variables

### ISSUE THREAD

**Issue by fdw** [sqlfluff/sqlfluff#2695]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### Description

`raiserror` currently cannot be parsed if it gets variables (like `@severity`) as parameters.

### Use case

Variables should not be a problem.

### Dialect

T-SQL

### Are you willing to work on and submit a PR to address the issue?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by jpers36** [comment]
@fdw which version of SQLFluff did you test on?  I updated TSQL's RAISERROR recently enough that it's not in the latest release.

**Comment by fdw** [comment]
I just updated to the latest `main`, but the problem persists :( Could it be that it doesn't accept variables as parameters yet?

**Comment by jpers36** [comment]
@fdw can you post a snippet of code that's failing?
