### ISSUE TITLE
TSQL: Support cursors

### ISSUE THREAD

**Issue by fdw** [sqlfluff/sqlfluff#2696]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### Description

T-SQL (and maybe others) support cursors for iterative handling.

For example:
```sql
declare @id nvarchar(2);
declare <name> cursor forward_only read_only
for select id from <table>;

open <name>;
fetch next from <name> into @id;

close <name>;
deallocate <name>;
```

See [declare cursor](https://docs.microsoft.com/en-us/sql/t-sql/language-elements/declare-cursor-transact-sql?view=sql-server-ver15), [open](https://docs.microsoft.com/en-us/sql/t-sql/language-elements/open-transact-sql?view=sql-server-ver15), [fetch](https://docs.microsoft.com/en-us/sql/t-sql/language-elements/fetch-transact-sql?view=sql-server-ver15), [close](https://docs.microsoft.com/en-us/sql/t-sql/language-elements/close-transact-sql?view=sql-server-ver15), [deallocate](https://docs.microsoft.com/en-us/sql/t-sql/language-elements/close-transact-sql?view=sql-server-ver15)

### Use case

Parsing should succeed

### Dialect

T-SQL

### Are you willing to work on and submit a PR to address the issue?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by fdw** [comment]
Would it be enough to just add `segment`s and `grammar`s to enable parsing, or do you want more functionality?

**Comment by tunetheweb** [comment]
I think just getting it to parse is sufficient rather than checking anything futher.

Though obviously should have test cases for it.
