### ISSUE TITLE
Support multiple dialects in config.

### ISSUE THREAD

**Issue by shicholas** [sqlfluff/sqlfluff#2754]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### Description

We have a ETL repository that uses multiple flavors of SQL. We would like the ability to specify multiple dialects in a `.sqlfluff` file. For instance:

```
[sqlfluff]
templater = jinja
dialect = postgres
sql_file_exts = .sql

[sqlfluff:dialect:teradata]
sql_file_exts = teradata.sql
```

With this config, a file like `schema.sql` would be interpreted with the `postgres` dialect and a file like `etl.teradata.sql` would be interpreted with the `teradata` dialect.

### Use case

running `sqlfluff fix .` should pick up on the appropriate dialect based on the file extension.

### Dialect

n/a, this is config for all.

### Are you willing to work on and submit a PR to address the issue?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by shicholas** [comment]
If the project authors can send me an ideal config, I can write the code from there, thanks!

**Comment by tunetheweb** [comment]
@shicholas are your SQL files in different folders? Or mixed?

Because if it’s the former you could for this:

1. Have a sql/.sqlfluff file with your common config
2. Have a sql/postgres/.sqfluff setting that dialect which will be used for all sql files in that directory
3. Have a sql/teradata/.sqfluff setting that dialect which will be used for all sql files in that directory

**Comment by tunetheweb** [comment]
@shicholas do you think this is still needed? Or is the suggested option sufficient?

**Comment by shicholas** [comment]
It would be nice to have it, but the suggested option is sufficient. I'm happy to submit a PR if you'd like to introduce this into the library. Thanks

**Comment by barrywhart** [comment]
I'm going to close this issue since it's not needed. I'm reluctant to add unnecessary features at this time, while we're trying to reach a stable 1.0.
