### ISSUE TITLE
sqlfluff can not properly parse snowflake string functions like regex

### ISSUE THREAD

**Issue by vicsteiner** [sqlfluff/sqlfluff#2776]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### What Happened

Using sqlfluff 0.10.1.

Trying to parse a Snowflake query containing  string functions like REGEXP raises an APIParsingError.

### Expected Behaviour

The query to be parsed correctly.

### Observed Behaviour

```
---------------------------------------------------------------------------
APIParsingError                           Traceback (most recent call last)
Input In [3], in <module>
----> 1 sqlfluff.parse(query, dialect="snowflake")

File ~/.virtualenvs/base_venv/lib/python3.9/site-packages/sqlfluff/api/simple.py:169, in parse(sql, dialect, config_path)
    167 # If we encounter any parsing errors, raise them in a combined issue.
    168 if parsed.violations:
--> 169     raise APIParsingError(parsed.violations)
    170 # Return a JSON representation of the parse tree.
    171 if parsed.tree is None:  # pragma: no cover

APIParsingError: Found 1 issues while parsing string.
Line 4, Position 8: Found unparsable section: " regexp 'San* [fF].*'"
```

### How to reproduce

```
import sqlfluff

query = """
select v
from strings
where v regexp 'San* [fF].*'
order by v;
"""

sqlfluff.parse(query, dialect="snowflake")
```

### Dialect

snowflake

### Version

0.10.1

### Configuration

standard

### Are you willing to work on and submit a PR to address the issue?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by jpy-git** [comment]
Will fix this now

**Comment by vicsteiner** [comment]
Wow super fast! Thanks for that!
