### ISSUE TITLE
Enhancements to generate_parse_fixture_yml.py command

### ISSUE THREAD

**Issue by tunetheweb** [sqlfluff/sqlfluff#2844]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### Description

This takes a while to run and is only going to take longer as test coverage gets more and more comprehensive.

Could we add parallel ability?

Could we add ability to only generate for one file or folder so when making dialect changes you don't need to needlessly generate all the other dialects too (CI will protect us if someone incorrectly thinks they don't need to regenerate it all).

### Use case

Will make developing dialect improvements easier

### Dialect

All

### Are you willing to work on and submit a PR to address the issue?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by tunetheweb** [comment]
@barrywhart / @OTooleMichael think one of you could look at this as more your area of expertise? You'd forever have my gratitude in return! 😉

**Comment by OTooleMichael** [comment]
I can prolly have a go. How slow are they at the moment. I think I Ran this last week and it was fine

**Comment by tunetheweb** [comment]
Need to persuade the wife to let me buy an M1 (or M2?) Max 😁

Takes a good 5-10 mins for me on my aging Mac. Which, when I only really need one generated is a bit much.

**Comment by barrywhart** [comment]
The script is already parallel. See [these lines](https://github.com/sqlfluff/sqlfluff/blob/main/test/generate_parse_fixture_yml.py#L55L57).

**Comment by barrywhart** [comment]
Letting you specify a directory  is a good idea. 👍

**Comment by tunetheweb** [comment]
Just did some timing there (single runs, with terminal mostly in the foreground but lots of apps in the background):

It took 4 mins 19 seconds for me to run it in default mode (I have 4 cores btw, well 2 and 2 v)
```
% date; python test/generate_parse_fixture_yml.py; date
Fri 11 Mar 2022 21:29:33 GMT
Fri 11 Mar 2022 21:33:52 GMT
```

Hard coded some other values for number of cores and got following run times (again just a single run so not that scientific) shows much worse times - including reverting back to default of 4 cores!:

cores | run time
----|----
1| 8 mins 03 seconds
2| 7 mins 03 seconds
3| 8 mins 02 seconds
4| 8 mins 06 seconds (way more than above!)

Admittedly was doing more on the laptop for those runs, but still shows the pain this is (for me at least). Especially as, as I say, it's wasting most of the time regenerating YAMLs for dialects I have not touched.

Also doesn't really appear that multi-processing is helping me. Probably cause all the other stuff I have running on this little thing.

Always knew my Mac was under powered (it's my secondary machine and I bought it for portability) but think it's time to upgrade it when the new Air comes out later this year!

<img width="698" alt="image" src="https://user-images.githubusercontent.com/10931297/157975397-567b848d-59dc-4fc9-aa90-8f3e6d1df66e.png">

**Comment by barrywhart** [comment]
I've got an M1. It's fast and has great battery life. Occasionally there are things I can't run or have to build from source. (This is also why I use the Docker environment for dbt templater development.)

**Comment by tunetheweb** [comment]
How long does it take to run out of interest?

**Comment by barrywhart** [comment]
Just over 23 seconds. It's a Macbook Pro, 16GB RAM, 8 cores (4 performance and 4 efficiency).

**Comment by tunetheweb** [comment]
🤯

I was expecting it to be a good bit faster but was not expecting that!!! Man I need to upgrade!

**Comment by barrywhart** [comment]
@OTooleMichael, @tunetheweb: Can this issue be closed now?

**Comment by tunetheweb** [comment]
Yup. @OTooleMichael if you add "Closed XXXX" or "Fixes XXXX" to the PR it's auto closed when PR is merged. But I feel bad with that minor gripe for this amazing improvement for me! :-)

**Comment by OTooleMichael** [comment]
Sure - I thought it was just the ref, but obviously that make more sense
