### ISSUE TITLE
Parse unesting semi structured data + timestamp conversion

### ISSUE THREAD

**Issue by Olaktal** [sqlfluff/sqlfluff#2861]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### What Happened

Hello !

After few months, I finally re-prioritize SQLfluff in my Todo 🎉 
We have json data that we flatten thanks to new Redshift [SUPER column](https://docs.aws.amazon.com/redshift/latest/dg/query-super.html)
Here is one of our SQL query (we use DBT)
```
WITH raw_data AS (
    SELECT
        status,
        created,
        start,
        "end",
        received_date,
        lfdomain,
        lfprocesstimestamp,
        deletedat,
        expungedat,
        id AS resource_id,
        JSON_PARSE(meta) AS meta,
        JSON_PARSE(identifier) AS identifier
    FROM datalake_staging.appointment
    WHERE received_date BETWEEN '1970-01-01' AND '2022-01-01'
),

extension_extraction AS (
    SELECT
        raw_data_tmp.resource_id::INT AS extension_extraction_resource_id,
        raw_data_tmp.meta."versionId"::INT AS version_id,
        MAX(CASE WHEN extension_array.url = 'http://lifen.fr/fhir/StructureDefinition/Resource/Extension/DatabaseReference' THEN extension_array."valueReference".reference END)::VARCHAR AS database_reference
    FROM raw_data AS raw_data_tmp
    LEFT JOIN raw_data_tmp.meta.extension AS extension_array ON TRUE
    GROUP BY 1, 2
)

SELECT
    raw_data.status::VARCHAR AS status,
    raw_data.start::TIMESTAMPTZ AT TIME ZONE 'UTC' AS started_at,
    raw_data."end"::TIMESTAMPTZ AT TIME ZONE 'UTC' AS ended_at,
    raw_data.created::TIMESTAMPTZ AT TIME ZONE 'UTC' AS created_at,
    raw_data.identifier[0].value::VARCHAR AS communication_request_fhir_reference_origin,
    extension_extraction.database_reference
FROM raw_data
LEFT JOIN extension_extraction ON extension_extraction.extension_extraction_resource_id = raw_data.resource_id AND extension_extraction.version_id = raw_data.meta."versionId"
```

```
poetry run sqlfluff lint appointment.sql --dialect redshift
```

And the lint result is

```
L:  31 | P:  22 | L031 | Avoid aliases in from clauses and join conditions.
L:  32 | P:  46 | L031 | Avoid aliases in from clauses and join conditions.
L:  38 | P:  33 | L012 | Implicit/explicit aliasing of columns.
L:  38 | P:  33 | L014 | Unquoted identifiers must be consistently lower case.
L:  38 | P:  33 | L029 | Keywords should not be used as identifiers.
L:  38 | P:  35 |  PRS | Line 43, Position 35: Found unparsable section: " TIME
                       | ZONE 'UTC' AS started_at"
L:  39 | P:  33 | L012 | Implicit/explicit aliasing of columns.
L:  39 | P:  33 | L014 | Unquoted identifiers must be consistently lower case.
L:  39 | P:  33 | L029 | Keywords should not be used as identifiers.
L:  39 | P:  35 |  PRS | Line 44, Position 35: Found unparsable section: " TIME
                       | ZONE 'UTC' AS ended_at"
L:  40 | P:  35 | L012 | Implicit/explicit aliasing of columns.
L:  40 | P:  35 | L014 | Unquoted identifiers must be consistently lower case.
L:  40 | P:  35 | L029 | Keywords should not be used as identifiers.
L:  40 | P:  37 |  PRS | Line 45, Position 37: Found unparsable section: " TIME
                       | ZONE 'UTC' AS created_at"
```

### Expected Behaviour

It should not have any error

### Observed Behaviour

Well the first 2 errors (`L031`) doesn't make sense since it is the way we need to write the query in order to flatten data (look at [this part of the doc](https://docs.aws.amazon.com/redshift/latest/dg/query-super.html#unnest), we need to set aliases)

For the rest, it seems it simply doesn't recognize the `AT TIME ZONE 'UTC'` part. Can you fix this for the redshift dialect ?

Thanks !

### How to reproduce

Create a .sql with the SQL code and execute the command line above

### Dialect

redshift

### Version

sqlfluff, version 0.11.0

### Configuration

`.sqlfluff`
```
[sqlfluff]
templater = dbt

[sqlfluff:rules]
tab_space_size = 4
max_line_length = 800

[sqlfluff:rules:L059]
ignore_words = versionId,valueReference

[sqlfluff:templater:jinja]
apply_dbt_builtins = True

[sqlfluff:templater:dbt]
project_dir = workflow/queries/dbt
library_path = dbt_utils
```

### Are you willing to work on and submit a PR to address the issue?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by tunetheweb** [comment]
> For the record, I already mention timestamp error 6 month ago and [the solution was to use postgres dialect](https://github.com/sqlfluff/sqlfluff/issues/1155) but I can't use it since it generate others errors.

That’s not strictly the case. That issue was about adding it to Postgres. It was done and the issue closed. You then asked why it wasn’t working and I pointed out you weren’t using Postgres that this functionality was added for. At no point did you mention you needed it for Redshift (I thought you were using ANSI to be honest). Now we know that, we can look to add this to Redshift.

> About aliases due to unesting json, I [found this issue](https://github.com/sqlfluff/sqlfluff/issues/1672) but the rule L031 was excluded, is this my only option to solve this problem ? Since it might concern a lot of people, maybe it is a better idea to solve it definitely ?

This is a complicated one and one Redshift user has made some contributions to make progress on it but it’s not fully solved yet. We are happy to take further contributions on it if you or anyone else wishes to contribute. Personally I don’t find rule L031 that useful and I exclude it so it’s definitely not the highest priority for me personally. I would advise excluding that rule.

**Comment by tunetheweb** [comment]
With #2863 the only linting errors for your SQL with your config are:

```
% sqlfluff lint test.sql --dialect redshift                    
% sqlfluff lint test.sql --dialect redshift
== [test.sql] FAIL                                                                                                                                                                                                                     
L:  24 | P:  22 | L031 | Avoid aliases in from clauses and join conditions.
L:  25 | P:  46 | L031 | Avoid aliases in from clauses and join conditions.
All Finished 📜 🎉!
```

I believe the two L031 errors are valid errors as the rule is implemented.

I don't know if this is valid Redshift, but that is what the rule wants you to use?:

```sql
extension_extraction AS (
    SELECT
        raw_data.resource_id::INT AS extension_extraction_resource_id,
        raw_data.meta."versionId"::INT AS version_id,
        MAX(CASE WHEN raw_data_tmp.meta.extension.url = 'http://lifen.fr/fhir/StructureDefinition/Resource/Extension/DatabaseReference' THEN raw_data.meta.extension."valueReference".reference END)::VARCHAR AS database_reference
    FROM raw_data
    LEFT JOIN raw_data_tmp.meta.extension AS extension_array ON TRUE
    GROUP BY 1, 2
)
```

As I say I (and many others!), disagree with rule L031, so if you don't need it, then turn it off.

**Comment by PLBMR** [comment]
> This is a complicated one and one Redshift user has made some contributions to make progress on it but it’s not fully solved yet

Hey @Olaktal ! I'm that Redshift user. I've been making incremental progress towards fully supporting the `SUPER` data type in the Redshift dialect. I've implemented support for `SUPER` types in column references (#2564 ), and I'm working on introducing support for `SUPER` types in table references (#2567 ). It's a pretty complex problem because `SUPER` types are ambiguously referenced in syntax (often misinterpreted as column aliases), and we need to build out a lot of redshift-specific rule exceptions that account for that ambiguity.

The `L031` issue you've identified is particularly interesting. This query involves joining a table with a nested field in that table. This is pretty advanced use of SUPER types; I wasn't even aware this was possible in the Redshift spec.

Can you make an extra issue for the part of the query that was incorrectly flagged by L031? I can fix it some time over the next month.

**Comment by Olaktal** [comment]
@tunetheweb you are my hero ! You fixed it so fast :) 
Can't wait for the release :) 

@PLBMR I created [this dedicated issue](https://github.com/sqlfluff/sqlfluff/issues/2865) if you want to try to fix it sometime :) 

Thanks both of you :)
