### ISSUE TITLE
PIVOT and UNPIVOT redshift 

### ISSUE THREAD

**Issue by troyschuetrumpf-elation** [sqlfluff/sqlfluff#2875]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### Description

Redshift recently added support for PIVOT and UNPIVOT, these are not recognised by SQLFluff and so result in a parsing error. 

https://aws.amazon.com/about-aws/whats-new/2022/02/amazon-redshift-support-pivot-unpivot-sql-operators/

### Use case

Redshift dialect support for PIVOT and UNPIVOT

### Dialect

Redshfit 

### Are you willing to work on and submit a PR to address the issue?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by PLBMR** [comment]
I'll take this on over the weekend.
