### ISSUE TITLE
Make sqlfluff-templater-dbt an optional dependency

### ISSUE THREAD

**Issue by PhilippLange** [sqlfluff/sqlfluff#2883]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### Description

I've been fiddeling around a bit with dbt + sqlfluff.
Since the plugin sqlfluff-templater-dbt is necessary, I was wondering if it would make sense to add sqlfluff-templater-dbt as an optional dependency to sqlfluff.

Implementation would be as simple as adding this to setup.cfg:
```yaml
extras_require =
  dbt=sqlfluff-templater-dbt
```

WDYT?

### Use case

syntactic sugar

Do this:
```console
pip install sqlfluff[dbt]
```

Instead of this:
```console
pip install sqlfluff-templater-dbt
```

### Dialect

all

### Are you willing to work on and submit a PR to address the issue?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by barrywhart** [comment]
This may be okay, but I want to note that the reverse is already true (templater depends on SQLFluff). I'm wondering if a circular dependency like this will cause issues with installation or other tools.

**Comment by PhilippLange** [comment]
I'm quite sure this won't cause any issues. However this feature might be unnecessary. Should I close this?

**Comment by barrywhart** [comment]
I think we should close it. I understand why you're asking, but I feel like it would confuse people. Confused people create issues, and since the maintainers are volunteers, we want to minimize support issues so we can focus on bug fixes and enhancements.
