### ISSUE TITLE
Make a more sensible public API

### ISSUE THREAD

**Issue by alanmcruickshank** [sqlfluff/sqlfluff#289]
For projects like dbt (https://github.com/fishtown-analytics/dbt) and for suggestions like https://github.com/kgpayne/sqlfluff/issues/1 I think sqlfluff should present some level of reliable public API. This is a placeholder for that.

I think this might be a sensible target for the next major release.

Comments, thoughts and suggestions welcome!

**Comment by barrywhart** [comment]
We've been looking at using SQLFluff purely as a SQL parser, to extract table dependency information from the SQL we execute. (This is used to automatically generate diagrams.) For now, we're using regex instead, but hope to use SQLFluff once it has more thorough BigQuery parsing. I'd be happy to share bits of this code or review any proposed API.

**Comment by alanmcruickshank** [comment]
I want to do this too, mostly to help the team avoid circular dependencies. @barrywhart are you able to post the kind of output you get from your regex solution at the moment? Your use case may be a good starting point.

**Comment by barrywhart** [comment]
Sure! To make sure I understand, you want to see an example record? I'll get that tomorrow. The most important parts are the output table and a list of input tables.

**Comment by barrywhart** [comment]
I'll just go ahead and share the whole Python module for this -- it includes both the original, SQLFluff-based code (currently commented out), as well as the regex-based code we're using as a workaround.

This code is focused on table dependencies, but now that we've added SQLFluff support for machine-learning models (BigQueryML), I've been thinking whether we might do something similar for ML models (dependency information, etc.).

See the `print` call at the bottom -- that's where the actual JSON output is created. Here's some basic documentation for the fields:
* These fields are generated by parsing the query with SQLFluff or regex:
  *  `source_tables`: List of input tables
  * `documentation`: Optional, free-form text with human-readable documentation on the table. This is typically generated by parsing any comment at the top of the SQL query. Basically reusing the Python "docstring" concept in SQL
* These other fields are provided by the caller or user
  * `destination_table`: Output table for the query or job
  * `field_info`: Optional, list of field name/field type pairs for the destination table
  *  `num_rows`: Optional, number of rows (a.k.a. records) in the destination table
  * `created_by`: Optional, free-form text info on how the table was created (e.g. `bigquery`, `dataflow`)

```
import json
import re

FluffConfig = None

try:
    from sqlfluff.config import FluffConfig
    from sqlfluff.parser import FileSegment, ParseContext  # pragma: no py2 cover
except ImportError:  # pragma: no py3 cover
    # sqlfluff is not available on Python 2
    pass


#def _find_tables(ast, stack):  # pragma: no py2 cover
    """
    Given a SQL abstract syntax tree in tuple format, as returned by SQLFluff,
    find and yield all the table names.
    :param ast: Abstract syntax tree
    :param stack: "Stack" of parent node types
    :return: str

    Example value for ast:

    ('file',
     (('statement',
       (('select_statement',
         (('select_clause',
           (('keyword', 'SELECT'),
            ('select_target_element',
             (('object_reference', (('naked_identifier', 'user_id'),)),)))),
          ('from_clause',
           (('keyword', 'FROM'),
            ('table_expression',
             (('object_reference',
               (('quoted_identifier',
                 '`database.schema.benchmark_user_map`'),)),)))),
          ('where_clause',
           (('keyword', 'WHERE'),
            ('expression',
             (('object_reference', (('naked_identifier', 'list_id'),)),
              ('keyword', 'IS'),
              ('keyword', 'NULL'))))))),)),))
    """
    # TODO: Re-enable this code when we're ready to use SQLFluff for SQL
    #  analysis.
    # Context: As of April 2020, SQLFluff is still in alpha, and in some cases
    # it fails to parse valid BigQuery SQL. Barry is continuing to test it, find
    # new issues, and test the fixes. We'll know when it's finally ready by
    # continuing to test updated versions against our production SQL.
    # if isinstance(ast[0], str):
    #     if isinstance(ast[1], tuple):
    #         # Interior node
    #         for table in _find_tables(ast[1], stack + [ast[0]]):
    #             yield table
    #     else:
    #         # Leaf node
    #         if ast[0] == 'quoted_identifier' and ast[1].startswith('`') and \
    #                 ast[1].endswith('`') and 'table_expression' in stack:
    #             yield ast[1][1:-1]
    # else:
    #     # Interior node
    #     for node in ast:
    #         for table in _find_tables(node, stack):
    #             yield table


#def _dfs(ast):  # pragma: no py2 cover
    """
    Do a DFS traversal of 'ast', returning a flat tuple.
    Given a SQL abstract syntax tree in tuple format, as returned by SQLFluff,
    do a depth-first search traversal of that tree.
    :param ast: tuple Abstract syntax tree
    :return: tuple

    ('file',
     (('statement',
       (('select_statement',
         (('newline', '\n'),
          ('whitespace', '        '),
          ('raw', '-- This constraint checks that'),
          ('newline', '\n'),
          ('whitespace', '        '),
          ('raw', '-- blah blah foo bar.'),
          ('newline', '\n'),
          ('whitespace', '        '),
          ('select_clause',
           (('keyword', 'SELECT'),
            ('newline', '\n'),
            ('whitespace', '            '),
            ('select_target_element',
             (('object_reference', (('naked_identifier', 'total_rows'),)),)))),
          ('newline', '\n'),
          ('whitespace', '        '),
          ('from_clause',
           (('keyword', 'FROM'),
            ('whitespace', ' '),
            ('table_expression',
             (('object_reference',
               (('quoted_identifier',
                 '`database.schema.benchmark_summaries`'),)),)),
            ('newline', '\n'),
            ('whitespace', '    '))))),)),))
    """
    # TODO: Re-enable this code when we're ready to use SQLFluff for SQL
    #  analysis.
    # if isinstance(ast[0], str):
    #     if isinstance(ast[1], tuple):
    #         # Interior node
    #         for node in _dfs(ast[1]):
    #             yield node
    #     else:
    #         # Leaf node
    #         yield ast
    # else:
    #     # Interior node
    #     for node in ast:
    #         for table in _dfs(node):
    #             yield table


# TODO: Re-enable this code when we're ready to use SQLFluff for SQL
#  analysis.
# def _find_first_comment(ast):  # pragma: no py2 cover
#     nodes = list(_dfs(ast))
#     result = []
#     for node in nodes:
#         if node[0] == 'raw':
#             comment_text = re.search(r'--\s*(.*)', node[1]).group(1)
#             result.append(comment_text)
#         elif result and node[0] not in {'whitespace', 'newline'}:
#             break
#     return ' '.join(result)


# TODO: Re-enable this code when we're ready to use SQLFluff for SQL
#  analysis.
# def _parse_sql(sql, code_only=False):  # pragma: no py2 cover
#     config = FluffConfig(overrides=dict(dialect='bigquery'))
#     context = ParseContext.from_config(config)
#     fs, _ = FileSegment.from_raw(sql, config=config)
#     fs.parse(parse_context=context)
#     ast = fs.to_tuple(code_only=code_only, show_raw=True)
#     return ast


def parse_sql_query_tables(sql, project):
    """
    Given a SQL query, return the tables it reads from.
    :param sql: str
    :param project: GCP project (in case not provided in query)
    :return: list
    """
    result = []
    if FluffConfig is not None:  # pragma: no py2 cover
    # Derp, the SQLFluff parser can't handle some BigQuery syntax yet.
    #     ast = _parse_sql(sql, code_only=True)
    #     for table in _find_tables(ast, []):
    #         parts = table.split('.')
    #         if len(parts) < 3:
    #             parts = [project] + parts
    #         result.append('.'.join(parts))
        temp_result = re.findall(r'`[A-Za-z0-9_\-\.]+`', sql)
        temp_result = [t[1:-1] for t in temp_result]
        for table in temp_result:
            parts = table.split('.')
            if len(parts) < 3:
                parts = [project] + parts
            result.append('.'.join(parts))
    return result


def parse_sql_docstring(sql):
    if FluffConfig is not None:  # pragma: no py2 cover
        # Derp, the SQLFluff parser can't handle some BigQuery syntax yet.
        # ast = _parse_sql(sql)
        # return _find_first_comment(ast)
        result = []
        for line in sql.split('\n'):
            m = re.search(r'--\s*(.*)', line)
            if m:
                result.append(m.group(1))
            elif result and not line.strip():
                # Once we have comments, stop on blank line.
                break
            elif line.strip():
                # Always stop on non-blank, non-comment line.
                break
        return ' '.join(result)
    else:
        return None


def log_table_dependency(
        full_dest_table_name, source_tables, field_info, num_rows, created_by,
        documentation
):
    """Log dependency information about a table being created"""
    print("table_dependency: {}".format(json.dumps({
        "created_by": created_by,
        "destination_table": full_dest_table_name,
        "source_tables": source_tables,
        "field_info": field_info,
        "num_rows": num_rows,
        "documentation": documentation,
    })))

```

**Comment by alanmcruickshank** [comment]
I think the combination of #501 and #504 gets us about as far as I intended to take this for 0.4.0.

Can I do a quick poll on whether we've covered the functionality that people expected, or whether there's anything else major that we'd like to target for 0.4.0? @barrywhart @pwildenhain @nolanbconaway @kgpayne

I'm also option to suggestions for *future* features which might not go into 0.4.0 but are natural extensions of this which we should target for future releases.

**Comment by nolanbconaway** [comment]
The public api has realized all that I could dream of!

**Comment by barrywhart** [comment]
Maybe not 4.0, but my two top wishlist items are still:
* Address slow performance on files with lots of issues (there had been some progress, but it has regressed)
* We had a tricky parsing issue a few months back trying to add UDF support to BigQuery.

These issues have caused me to hold off including SQLFluff as a standard part of every data science project at my employer.

Think we could address one or both of these soon?

**Comment by alanmcruickshank** [comment]
> Think we could address one or both of these soon?

I've got ideas to address both, I'll see if I can put together prototypes to demonstrate over the next few weeks.

When I posed the question, I was thinking specifically about the API being exposed. Any more feedback on that in particular?

**Comment by barrywhart** [comment]
Not much to add, except to +1 your idea about making it easy to distinguish various kinds of object names. In BigQuery, I'm aware of:
* project
* dataset
* column
* BigQuery ML model

I wonder what this looks like for other data stores, and if we may need custom logic for some data stores to extract and identify the pieces, based on things like delimiters, separators, etc.

**Comment by alanmcruickshank** [comment]
I'm going to close this issue - I think the main things we wanted to hit with the first version have been hit with 0.4.0. Further development should probably be part of a new issue 👍
