### ISSUE TITLE
Make L003 easier to fix and understand.

### ISSUE THREAD

**Issue by alanmcruickshank** [sqlfluff/sqlfluff#2892]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### Description

Recently working on https://github.com/brooklyn-data/dbt_artifacts, I got hit with with this: 
![image](https://user-images.githubusercontent.com/4670904/159170846-df1d0d95-5926-4f98-a38f-f5d6e28324ab.png)

Because of the mixture of indents and templating I don't think it's immediately obvious what the indentation *should* be and I don't think it's immediately clear from the error message.

I suggest that warnings from this rule should say something like. "Expected n indents more/less". That way it's much clearer what the user should do differently.

### Dialect

This was in the snowflake dialect, but I think the point is generally applicable.

### Are you willing to work on and submit a PR to address the issue?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by barrywhart** [comment]
@alanmcruickshank: @OTooleMichael has done a lot of work to refactor and improve L003 recently. His work is mostly complete, and he's in the middle of testing it (mainly looking into failures of some tricky existing test cases for the dbt templater. You should coordinate with him on this.)

**Comment by OTooleMichael** [comment]
I started on a V1,  which accidentally changed too much  in one go.

This however is Running and a solid clean up.

https://github.com/sqlfluff/sqlfluff/pull/2884

**Comment by OTooleMichael** [comment]
On the specifics of the Error messages how about all error messages are the same
`Expected i indentations found j [compared to L0X]` ?

**Comment by alanmcruickshank** [comment]
> On the specifics of the Error messages how about all error messages are the same
> `Expected i indentations found j [compared to L0X]` ?

I think that's a good suggestion. If we wanted to be really overkill, then `Expected i indentations, found j [compared to k on L0X]` might be even more explicit.

**Comment by OTooleMichael** [comment]
I thought about the on line X - but I think that is covered as standard by the way the Lints are all done. No need to have it in the lint error desc

**Comment by alanmcruickshank** [comment]
Yeah I guess L003 should only compare to lines that are valid, and so you can always just _look_ at the comparison line to understand how much indent to add.

**Comment by OTooleMichael** [comment]
Sorry I misread. I thought you meant the line number of the error'd line.

**Comment by tunetheweb** [comment]
I think this can be closed now @OTooleMichael / @alanmcruickshank ? Feel free to reopen if I've misunderstood.
