### ISSUE TITLE
Applying rule L042 threw an Exception: 'CTEDefinitionSegment' object has no attribute 'get_identifier' 

### ISSUE THREAD

**Issue by SamuelBucheliZ** [sqlfluff/sqlfluff#2898]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### What Happened

When running sqlfluff 0.11.1 on the following code
```
INSERT INTO target_table (target_column)
SELECT table1.column1
FROM table1
INNER JOIN (
    SELECT table2.join_column
    FROM table2
) AS temp3
ON table1.join_column = temp3.join_column
```
the process fails with 
```
Applying rule L042 threw an Exception: 'CTEDefinitionSegment' object has no attribute 'get_identifier'
```

Note: The SQL above is a simplified example, so it does not make much sense as it is, but it is the minimal example I could come up with to reproduce the error (the original SQL which led to the discovery is much more complex and makes more sense).

### Expected Behaviour

sqlfluff does not throw any unexpected exceptions.

### Observed Behaviour

Running
```
% sqlfluff lint --dialect redshift test.sql
```
gives the following output
```
CRITICAL   [L042] Applying rule L042 threw an Exception: 'CTEDefinitionSegment' object has no attribute 'get_identifier' 
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.9/site-packages/sqlfluff/core/rules/base.py", line 535, in crawl
    res = self._eval(context=context)
  File "/opt/homebrew/lib/python3.9/site-packages/sqlfluff/rules/L042.py", line 114, in _eval
    return _calculate_fixes(
  File "/opt/homebrew/lib/python3.9/site-packages/sqlfluff/rules/L042.py", line 180, in _calculate_fixes
    if ctes.has_duplicate_aliases() or is_recursive:
  File "/opt/homebrew/lib/python3.9/site-packages/sqlfluff/rules/L042.py", line 267, in has_duplicate_aliases
    used_names = self.list_used_names()
  File "/opt/homebrew/lib/python3.9/site-packages/sqlfluff/rules/L042.py", line 258, in list_used_names
    id_seg = cte.get_identifier()
AttributeError: 'CTEDefinitionSegment' object has no attribute 'get_identifier'
== [test.sql] FAIL                                                              
L:   2 | P:   1 | L042 | Unexpected exception: 'CTEDefinitionSegment' object has
                       | no attribute 'get_identifier'; Could you open an issue
                       | at https://github.com/sqlfluff/sqlfluff/issues ? You can
                       | ignore this exception for now, by adding '-- noqa: L042'
                       | at the end of line 2
All Finished 📜 🎉!
```

### How to reproduce

With sqlfluff 0.11.1, run
```
sqlfluff lint --dialect redshift test.sql
```
where `test.sql` is
```
INSERT INTO target_table (target_column)
SELECT table1.column1
FROM table1
INNER JOIN (
    SELECT table2.join_column
    FROM table2
) AS temp3
ON table1.join_column = temp3.join_column
```

### Dialect

redshift

### Version

0.11.1, as per
```
% sqlfluff --version
sqlfluff, version 0.11.1
```

### Configuration

No additional/specific configuration used (sqlfluff was used directly after installing it with `pip install sqlfluff`).

### Are you willing to work on and submit a PR to address the issue?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by barrywhart** [comment]
Thanks for the bug report! Looks like an easy fix. It was working correctly on ANSI dialect, just needed to reorganize the code a bit so it works for other dialects as well.
