### ISSUE TITLE
Postgres: "insert into ... on conflict ..." not supported

### ISSUE THREAD

**Issue by loafofpiecrust** [sqlfluff/sqlfluff#2904]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### What Happened

I wanted to auto-fix issues with my SQL files that use Postgres upsert functionality, which is the `on conflict ...` syntax. This is detailed on [the Postgres docs for INSERT](https://www.postgresql.org/docs/9.5/sql-insert.html), under the "ON CONFLICT clause" section. sqlfluff failed to parse this, so was unable to auto-fix lint warnings.

### Expected Behaviour

I expected sqlfluff to parse `on conflict` syntax, and thus be able to fix issues in SQL files using it. There are two variants of the syntax that I know of: `on conflict do nothing` and `on conflict do update ...` (which uses standard update syntax).

### Observed Behaviour

Relevant output from `sqlfluff lint`:
```
L:   2 | P:  36 |  PRS | Line 2, Position 63: Found unparsable section: '\nON
                       | CONFLICT DO NOTHING'
```

### How to reproduce

Run `sqlfluff lint` against this file:
```sql
INSERT INTO document (id, title)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
```

### Dialect

Postgres

### Version

```
sqlfluff, version 0.11.1
```

### Configuration

```ini
[sqlfluff]
dialect = postgres
templater = placeholder
exclude_rules = L031, L057, L027

[sqlfluff:indentation]
indented_joins = True

[sqlfluff:rules]
tab_space_size = 2
max_line_length = 90

[sqlfluff:rules:L010]
capitalisation_policy = lower

[sqlfluff:rules:L030]
capitalisation_policy = lower

[sqlfluff:templater:placeholder]
param_style = numeric_dollar
1 = 'one'
2 = 'two'
3 = 'three'
4 = 'four'
5 = 'five'
6 = 'six'
7 = 'seven'
8 = 'eight'
9 = 'nine'
10 = 'ten'
11 = 'eleven'
```

### Are you willing to work on and submit a PR to address the issue?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by tunetheweb** [comment]
Looks like this was recognised and there's a TODO in the code for this:

https://github.com/sqlfluff/sqlfluff/blob/305159ea643baf6b4744b98c3566613754b2f659/src/sqlfluff/dialects/dialect_postgres.py#L3242

The `DO NOTHING` would be very simple to add, but the `DO UPDATE` looks a little more involved (presumably why it's been left as a TODO!), so would be good for someone with Postgres access and knowledge to take this on.

**Comment by jmc-bbk** [comment]
I might try this one. If there's no immediate urgency, I'm happy to give it a go this week.
