### ISSUE TITLE
How to call sqlfluff from another python wrapper

### ISSUE THREAD

**Issue by rayamoh** [sqlfluff/sqlfluff#2950]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### Issue/Suggested Improvement

Would like to invoke sqlfluff in another python program and create output in a format compatible to Codeclimate spec and integrate Python wrapper in Gitlab pipelines

Please suggest any documentation or way to achieve this. Thanks!

### Are you willing to work on and submit a PR to address the issue?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by tunetheweb** [comment]
Use the Simple API: https://docs.sqlfluff.com/en/stable/api.html

**Comment by tunetheweb** [comment]
Going to close this as believe that should answer your question. Feel free to reopen, or open a new issue if it doesn't.

**Comment by rayamoh** [comment]
Thank you. Is there any way to pass .sql file as input to api? If str parm is the only option , all sql commands in .sql file should be combined and passed as str?

**Comment by tunetheweb** [comment]
Yes you need to read the file and pass it’s entire contents as a string.
