### ISSUE TITLE
Core enhancement: Improve consistency across dialects, and predictabiilty in handling structures

### ISSUE THREAD

**Issue by barrywhart** [sqlfluff/sqlfluff#2977]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### Description

From a discussion between @alanmcruickshank and @barrywhart [here](https://github.com/sqlfluff/sqlfluff/pull/2831#discussion_r840817983):
>There are a lot of places where we could be more consistent dialects, and more predictable in handling structures. I'm thinking of doing something to try and highlight issues like that.
>I did a bit of work in that area recently -- requiring that if a subdialect replaces a parent dialect's segment definition, the type must remain the same. It would be good to keep improving in this area. Automated internal quality checks are great at preventing bugs. 🙌

The recent work mentioned above was in `src/sqlfluff/core/dialects/base.py` in #2942.

### Dialect

n/a

### Are you willing to work on and submit a PR to address the issue?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by alanmcruickshank** [comment]
I've done a bit of a scan for options in this space and I'm actually not sure what else I would do here 🤔 .

I'm going to close this for now.
