### ISSUE TITLE
Added sqlfluff formatting and linting to null-ls

### ISSUE THREAD

**Issue by KingMichaelPark** [sqlfluff/sqlfluff#2990]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### Description

This isn't a feature request as I have already done it, but wanted to make the project aware that there is a plugin in neovim that I have added the linting and formatting to called `null-ls`

[formatter](https://github.com/jose-elias-alvarez/null-ls.nvim/blob/main/lua/null-ls/builtins/formatting/sqlfluff.lua)
[linting](https://github.com/jose-elias-alvarez/null-ls.nvim/blob/main/lua/null-ls/builtins/diagnostics/sqlfluff.lua)

Just wanted to let you know in case a feature request comes for neovim. (As you already maintain a vs code plugin)  

### Dialect

N/A

### Are you willing to work on and submit a PR to address the issue?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by tunetheweb** [comment]
Thanks for lettings us know @KingMichaelPark !

And for doing the work to add that.
