### ISSUE TITLE
BigQuery: Trailing comma in columns of `CREATE TABLE` statement is unparsable

### ISSUE THREAD

**Issue by dmohns** [sqlfluff/sqlfluff#3011]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### What Happened

A BigQuery `CREATE TABLE` statement that has a trailing comma after the last column yields unparsable error. However, it perfectly valid BigQuery SQL.

### Expected Behaviour

SQLFluff can parse this BigQuery specific.

### Observed Behaviour

```
Line 1, Position 1: Found unparsable section: 'CREATE TABLE (
    col1 STRING,
)'
```

### How to reproduce

```sql
CREATE TABLE (
    col1 STRING,
)
```

https://online.sqlfluff.com/fluffed?sql=H4sIAMxkTGIC_3MOcnUMcVUIcXTycVXQ4OVSAILk_BxDheCQIE8_dx1eLk0A3ISaliMAAAA%3D&dialect=bigquery

### Dialect

BigQuery

### Version

0.11.2 -> webversion

### Configuration

default

### Are you willing to work on and submit a PR to address the issue?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by tunetheweb** [comment]
This is easily fixed by adding `allow_trailing=True` in the CreateTableStatementSegment:

```py
        # Column list
        Sequence(
            Bracketed(
                Delimited(
                    OneOf(
                        Ref("TableConstraintSegment"),
                        Ref("ColumnDefinitionSegment"),
                    ),
                    allow_trailing=True,
                )
            ),
```

I agree we should enhance L038 to also cover this. Maybe with a separate config option (`create_table_colons_trailing_comma`?).
