### ISSUE TITLE
BigQuery: `WEEK(<WEEKDAY>)` as `date_part` can triggered L027

### ISSUE THREAD

**Issue by dmohns** [sqlfluff/sqlfluff#3020]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### What Happened

Using `WEEK(<WEEKDAY>)` as `date_part` can trigger L027. Which is valid as per https://cloud.google.com/bigquery/docs/reference/standard-sql/date_functions#date_trunc for example.

For example 

```sql
WITH prep_1 AS (SELECT DATE('2017-11-25') AS some_date),

prep_2 AS ((SELECT DATE('2017-11-05') AS some_date)
)

SELECT
    prep_1.some_date AS prep_1_original,
    prep_2.some_date AS prep_2_original,
    DATE_TRUNC(prep_1.some_date, WEEK(monday)) AS prep_1_truncated,
    DATE_TRUNC(prep_2.some_date, WEEK(monday)) AS prep_2_truncated
FROM prep_1
FULL OUTER JOIN prep_2
    ON TRUE;
```

### Expected Behaviour

SQLFluff should understand `monday` as a date part not a column reference. (And in fact ask me to capitalise it)

### Observed Behaviour

L027

### How to reproduce

https://online.sqlfluff.com/fluffed?sql=H4sIAIVyTWIC_4WOzQqCQBRG9wPzDnenAxo6EC1aiU1kmQM64lIkJYT8wWzR2-eolJjR7O6953zfRI44QN1kdWyCFYAaMJfZAnaWYKpCDXOjm6ZO1wqR13tVZHGatBnRMMKo12ivLXvGl4cRkeZAYwTdG8pXb0YKwy6umvyal8lNm5B0gaRzUn4jFn7o2eo8XoOIsZNaVGWaPAmZtLXNo7x0RPojhP4PoZ8QjPY-P4_Z3RC6LvBQMB-O3PFGfCjiHnQ1bIvRC9vXxziOAQAA&dialect=bigquery

### Dialect

bigquery

### Version

0.11.2 -> webversion

### Configuration

default

### Are you willing to work on and submit a PR to address the issue?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by tunetheweb** [comment]
Should be fixed in #3021
