### ISSUE TITLE
Linter - Make the way that it steps through the parse tree smarter

### ISSUE THREAD

**Issue by WittierDinosaur** [sqlfluff/sqlfluff#3036]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### Description

The objects in the the parse tree have information about their child elements. As such, we could make it so the parser only steps into branches of the parse tree that have element types that it's concerned with. 

### Use case

-

### Dialect

-

### Are you willing to work on and submit a PR to address the issue?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by barrywhart** [comment]
This is a promising idea. Think we could gather some real-world data to help confirm this before starting the work? One possibility: across a number of slow files, measure the time spent per rule. Can we confirm that it's spending significant time in rules that don't target the segment types found in the file?

**Comment by alanmcruickshank** [comment]
I think this was resolved in #3717
