### ISSUE TITLE
Linter - Some rules deal with file structure, and have no need to step through the entire tree

### ISSUE THREAD

**Issue by WittierDinosaur** [sqlfluff/sqlfluff#3037]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### Description

Any highly specific rules should take trivial amounts of time to run, such as ones that address the end of the file

### Use case

-

### Dialect

-

### Are you willing to work on and submit a PR to address the issue?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by barrywhart** [comment]
L009 and L050 look like good initial candidates for this. Are you aware of any others? (I could figure this out from the code, but there are lots of rules to study!)

@WittierDinosaur @tunetheweb @alanmcruickshank
