### ISSUE TITLE
Failure in python templating with non existing variables

### ISSUE THREAD

**Issue by andbul** [sqlfluff/sqlfluff#3040]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### What Happened

Hi, I have sql files with python templating in my project.  Example 
```
SELECT  col1, col2, col3 
FROM {input_table}.foo_table 
where dt = {dt_nodash}
```

And I decided to use  SqlFluff for linting and formating code in files. But when I've run:
`sqlfluff fix --dialect sparksql --templater python my_unformatted_file.sql`
sqlfluff produced next exception
`sqlfluff.core.errors.SQLTemplaterError: Failure in Python templating: ‘input_table’. Have you configured your variables?`

I've tried to use `--templater raw` option but in that case sqlfluff  in `sqlfluff parse ..` produces parse err
```
==== parsing violations ====
L: 2| P:   5 |  PRS | Line 117, Position 5: Found unparsable section: ‘from
                       | {input_table}'
```

and in `sqlfluff fix ....` 

```
==== no fixable linting violations found ====
All Finished!
  [nnn unfixable linting violations found]
```

The problem is that template fields will be inserted later in runtime (when airflow will run job)  from environment and in "format" phase in my build process i actually don't know the content of variables. So my question is do sqlfluff has some ignore configs for not configured variables?  How to get around this problem?

### Expected Behaviour

Sql file is correctly formating ignoring non existing variables

### Observed Behaviour

Error in parse and fix. Unfixable linting violations found

### How to reproduce

# some_file.sql
`SELECT  col1, col2, col3 FROM {input_table}.foo_table where dt = {dt_nodash}`

execute with default config

`sqlfluff parse --dialect sparksql --templater python some_file.sql`

or

`sqlfluff fix --dialect sparksql --templater python some_file.sql`

### Dialect

sparksql

### Version

0.11.2

### Configuration

default config

### Are you willing to work on and submit a PR to address the issue?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by tunetheweb** [comment]
SQLFluff expects you to provide dummy values for all templated code in your config file. These are substituted in (much like Airflow would do) to make proper SQL, which it can understand, and then lint.

You can read more about how to do that here: https://docs.sqlfluff.com/en/stable/configuration.html#jinja-templating-configuration. As you are using the `python` templater you need to put this in a `sqlfluff:templater:python` section:

```
[sqlfluff:templater:python:context]
input_table =my_table
```

I'll close this issue now, but feel free to reopen it if this doesn't answer your question.

**Comment by andbul** [comment]
But, I don't need to make such dummy variables for substitution. Users in our project write sql python-templated scripts without declaring default variables and values. Is there a way to skip substitution phase and parse sql as is? If no, maybe I could help to improve sqlfluff and make PR for some `ignore_` flag?

**Comment by tunetheweb** [comment]
> Hi @tunetheweb , but, I don't need to make such dummy variables for substitution. Users in our project write sql python-templated scripts without declaring default variables and values.

Yes but your airflow job will do that substitution before the Database runs that SQL. Until it does that it is not SQL.

> Is there a way to skip substitution phase and parse sql as is? If no, maybe I could help to improve sqlfluff and make PR for some ignore_ flag?

You can ignore parsing errors with `--noqa: PRS` on those lines (or on the project as a whole), however this will cause SQLFluff to not be able to fully understand the SQL, and so will not pick up linting errors properly, and will also (deliberately) not allow `fix` to run on the file at all.

Ultimately SQLFluff is a SQL linter and what you are passing is not SQL.

SQLFluff has the ability to define these dummy variables, once, in your config and then they can be used in any of your SQL files, so it can understand the typical SQL that is produced by your pipeline. Without that it cannot do it's job.

**Comment by mrcool4** [comment]
Hi My Sql code has '~' which is causing parsing errors. We use ~xyz~ as a placeholder that gets replaced during the runtime. Is there a way to customise param_style?
