### ISSUE TITLE
BigQuery: Add support for `SAFE.` prefix in function calls w.r.t L014

### ISSUE THREAD

**Issue by dmohns** [sqlfluff/sqlfluff#3047]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### What Happened

Using BigQuery `SAFE.` prefix seems to confuse SQLFluff and trigger L014 in weird fashions.

For example:

```sql
SELECT
    TRUE AS col1,
    SAFE.SUBSTR('foo', 0, -2) AS col2;
```

```
Unquoted identifiers must be consistently lower case.
```

Auto Fix:
```sql
SELECT
    TRUE AS col1,
    safe.SUBSTR('foo', 0, -2) AS col2;
```

Note the lower case `safe`.

At the same time, taking this SQL

```sql
SELECT SAFE.SUBSTR('foo', 0, -2) AS col2;
```

```
Unquoted identifiers must be consistently upper case.
```

Auto Fix:
```sql
SELECT SAFE.SUBSTR('foo', 0, -2) AS COL2;
```

Note upper case `COL2`.

### Expected Behaviour

`SAFE.` should be understood as function prefix and behave the same way like function as far as capitalisation is concerned. E.g. `SAFE.FUNCTION` or `safe.function`. In either case SQLFluff should not change column aliases as part of L014.

### Observed Behaviour

Inconsistent behaviour as described above.

### How to reproduce

Enter SQL from above and run `sqlfluff fix`

### Dialect

bigquery

### Version

0.12.0 -> webversion

### Configuration

default

### Are you willing to work on and submit a PR to address the issue?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by tunetheweb** [comment]
Fixed in #3048. In meantime you can add `SAFE` to the list of `ignore_words` for L014 in your sqlfluff config.
