### ISSUE TITLE
Fixing L025 results into invalid SQL

### ISSUE THREAD

**Issue by enote-kane** [sqlfluff/sqlfluff#3051]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### What Happened

When using only the table (or type) alias (no explicit column), then error `L025` is (somewhat understandably) raised.

When applying `sqlfluff fix`, the resulting SQL becomes invalid.

Referencing complete tables or other types with an alias is completely desired in PostgreSQL (and necessary, if you have functions taking custom types or table row types).

### Expected Behaviour

Either no L025 error (for dialect `postgres`) or a working fix.

In the test case presented here, a fix _would_ be possible by introducing an auto-generated explicit column, but that - of course - won't work for table row types or any other composite types that have been defined outside the current file.

### Observed Behaviour

PostgreSQL now throws:
```
ERROR:  column "status_name" does not exist
LINE 6:     'values', json_agg(status_name)
                               ^
```
db<>fiddle: https://dbfiddle.uk/?rdbms=postgres_14&fiddle=54a1d72ef276f9e79de3657c37c367d4

### How to reproduce

1. Start with the following file:
    ```sql
    CREATE TYPE my_enum AS ENUM ('new', 'open', 'closed');

    SELECT json_build_object(
        'name', 'ticket_status',
        'type', 'enum',
        'values', json_agg(status_name)
    )
    FROM unnest(enum_range(NULL::my_enum)) AS status_name;
    ```
2. Execute `sqlfluff fix ...`
3. Try to execute the "fixed" SQL file

### Dialect

postgres

### Version

sqlfluff, version 0.12.0

### Configuration

default (option `--dialect postgres` given to command line invocations)

### Are you willing to work on and submit a PR to address the issue?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by enote-kane** [comment]
For single-column results, PostgreSQL seems to name the only column the same as the table alias:
```sql
EXPLAIN (COSTS OFF, VERBOSE) SELECT my_oid FROM pg_catalog.pg_group, unnest(pg_group.grolist) AS my_oid;
```

Output:
```
 Nested Loop
   Output: my_oid.my_oid <<< here it goes
   ->  Seq Scan on pg_catalog.pg_authid
         Output: pg_authid.oid, pg_authid.rolname, pg_authid.rolsuper, pg_authid.rolinherit, pg_authid.rolcreaterole, pg_authid.rolcreatedb, pg_authid.rolcanlogin, pg_authid.rolreplication, pg_authid.rolbypassrls, pg_authid.rolconnlimit, pg_authid.rolpassword, pg_authid.rolvaliduntil
         Filter: (NOT pg_authid.rolcanlogin)
   ->  Function Scan on pg_catalog.unnest my_oid
         Output: my_oid.my_oid
         Function Call: unnest((SubPlan 1))
         SubPlan 1
           ->  Seq Scan on pg_catalog.pg_auth_members
                 Output: pg_auth_members.member
                 Filter: (pg_auth_members.roleid = pg_authid.oid)
(12 rows)
```
...but I was unable to find any official statement on this behavior in the docs, so it might change at some point (although unlikely).

However, as there is no way to verify that the alias actually references a single-column set, this specific behavior cannot be assumed.

**Comment by tunetheweb** [comment]
BigQuery has this too and we have a way of treating `UNNEST` aliases as column aliases instead of table aliases. Will open a PR to do the same for Postgres.
