### ISSUE TITLE
L052 + Jinja: Autofix breaks templated SQL if `;` is outside the template

### ISSUE THREAD

**Issue by dmohns** [sqlfluff/sqlfluff#3079]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### What Happened

I ran into a weird case where the autofix of `L052` produces an invalid SQL. Arguably the SQL template in this example is not very well written, but I don't think broken SQL as result of autofix should be acceptable.

### Expected Behaviour

The result of autofix should be a valid SQL.

### Observed Behaviour

```sql
{% set some_variable = (1 == 1) %}

{% if some_variable %}
SELECT 1;{% else %}
SELECT 2
{% endif %}
;
```

Which is broken as `SELECT 1;;` fails when running.

### How to reproduce

```sql
{% set some_variable = (1 == 1) %}

{% if some_variable %}
SELECT 1
{% else %}
SELECT 2
{% endif %}
;
```

https://online.sqlfluff.com/fluffed?sql=H4sIAO2EVmIC_6tWVShOLVEozs9NjS9LLMpMTMpJVbBV0DBUsLVVMNRUUK3l5eLlqlZVyExDUwSSCXb1cXUOUTAEq0jNKUYRNYKI5qUAtYKErQHzPtgYbAAAAA%3D%3D&dialect=ansi

### Dialect

ansi

### Version

0.12 -> webversion

### Configuration

default

### Are you willing to work on and submit a PR to address the issue?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by barrywhart** [comment]
I think the underlying issue is that SQLFluff doesn't respect the fact that code inside a Jinja block (`if` or `for`) is special. While it "knows" not to move code in or out of areas with template substititions e.g. (`{{ blahblah }}`), it treats literal code inside these blocks as normal, literal code.
