### ISSUE TITLE
`indented_using_on` not applying to `MERGE INTO ... USING ... ON` statements

### ISSUE THREAD

**Issue by dmohns** [sqlfluff/sqlfluff#3091]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### What Happened

The `ON` part of an `MERGE INTO ... USING ... ON` statement is not affected by `indented_using_on` setting. Although the documentation of `indented_using_on` is about JOINs, I think it could be expanded to cover this as well.

However, I guess this case is not 100% clear, as it can be argued that in the `MERGE` case, the `ON` statement is conceptionally more close to a `WHERE` in JOINs.

So, looking for opinions here whether this case should be covered by `indented_using_on` or leave like it is.

### Expected Behaviour

```sql
MERGE INTO t
USING u
    ON t.a = u.b
WHEN MATCHED THEN
    UPDATE SET a = 1
```

### Observed Behaviour

```sql
MERGE INTO t
USING u
ON t.a = u.b
WHEN MATCHED THEN
    UPDATE SET a = 1
```

### How to reproduce

https://online.sqlfluff.com/fluffed?sql=H4sIAJI8V2IC__N1DXJ3VfD0C_FXKOHlCg329HNXKOXl8vdTKNFLVLBVKNVL4uUK93D1U_B1DHH2cHVRCAFyeLkUgCA0wMUxxFUh2DVEAaTUkJcLAK3540pOAAAA&dialect=ansi

### Dialect

ansi

### Version

0.12.0 -> webversion

### Configuration

default, i.e. `indented_using_on = True`

### Are you willing to work on and submit a PR to address the issue?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by tunetheweb** [comment]
Makes sense to me. Should be a simple matter of replacing this:

https://github.com/sqlfluff/sqlfluff/blob/4bc2916bf87b260744ba77d2d6a6f5ed407a2ba8/src/sqlfluff/dialects/dialect_ansi.py#L2338

with this:

```py
Conditional(Indent, indented_using_on=False),
Ref("JoinOnConditionSegment"),
Conditional(Dedent, indented_using_on=False),
```

And then writing a n L003.yml test case.
