### ISSUE TITLE
Snowflake VALUES construct not fully supported

### ISSUE THREAD

**Issue by Dikootje** [sqlfluff/sqlfluff#3103]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### What Happened

Some of our sql scripts have an unparsable section due to the use of the VALUES() contruct. 

### Expected Behaviour

I expect both statements in the following script to parse: 
```
select * from (values (1, 'one'), (2, 'two'), (3, 'three'));

select * from values (1, 'one'), (2, 'two'), (3, 'three');
```

### Observed Behaviour

The first statement in the file causes no issues. 
The second statement, without the extra set of parenthensis causes triggers the unparsable section part. 

### How to reproduce

Create tests.sql with the following content:
```
select * from (values (1, 'one'), (2, 'two'), (3, 'three'));

select * from values (1, 'one'), (2, 'two'), (3, 'three');
```
Then run sqlfluff lint --dialect snowflake tests.sql

### Dialect

Snowflake

### Version

sqlfluff, version 0.11.2
and 
sqlfluff, version 0.12.0

### Configuration

N/A

### Are you willing to work on and submit a PR to address the issue?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by tunetheweb** [comment]
This is easy enough to fix with this change:

```
diff --git a/src/sqlfluff/dialects/dialect_snowflake.py b/src/sqlfluff/dialects/dialect_snowflake.py
index 189f0a96..18d5660d 100644
--- a/src/sqlfluff/dialects/dialect_snowflake.py
+++ b/src/sqlfluff/dialects/dialect_snowflake.py
@@ -2928,7 +2928,7 @@ class TableExpressionSegment(ansi.TableExpressionSegment):
         Ref("TableReferenceSegment"),
         # Nested Selects
         Bracketed(Ref("SelectableGrammar")),
-        # Values clause?
+        Ref("ValuesClauseSegment"),
         Ref("StagePath"),
     )
```

However, I don't see this syntax specified in https://docs.snowflake.com/en/sql-reference/constructs/values.html

Do you have any docs reference to ensure this is definitely valid Snowflake syntax?

**Comment by Dikootje** [comment]
I can't find it in the docs, however I can assure you that it will run on Snowflake.

The syntax on the INSERT documentation seems to refer more to the format mentioned above without the extra set of parenthesis. But I didn't test this yet, since it's not a construct we use.

**Comment by Dikootje** [comment]
Just to show both ways are working fine: 
![image](https://user-images.githubusercontent.com/5430309/164460893-1e3384fa-60b2-4cc6-8a61-4aa444b62ac5.png)
