### ISSUE TITLE
Templated areas not being ignored as expected, L003

### ISSUE THREAD

**Issue by NiallRees** [sqlfluff/sqlfluff#3125]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### What Happened

I have a dbt model configured as:

```
select *
from {{ limit_dataset('table', '_fivetran_synced') }}
```

Compiled:
```
select *
from 


(select * from table where _fivetran_synced >= dateadd('day', -1, current_timestamp()))



```

Running SQLFluff lint:
```
tox -e lint -- models/model.sql
lint create: /Users/niall.woodward/dbt/.tox/lint
lint installdeps: dbt-snowflake~=1.0.0, sqlfluff-templater-dbt
lint installed: agate==1.6.3,appdirs==1.4.4,asn1crypto==1.5.1,attrs==21.4.0,Babel==2.9.1,certifi==2021.10.8,cffi==1.15.0,chardet==4.0.0,charset-normalizer==2.0.12,click==8.1.2,colorama==0.4.4,cryptography==3.4.8,dbt-core==1.0.4,dbt-extractor==0.4.1,dbt-snowflake==1.0.1,diff-cover==6.5.0,future==0.18.2,hologram==0.0.14,idna==3.3,importlib-metadata==4.11.3,iniconfig==1.1.1,isodate==0.6.1,Jinja2==2.11.3,jinja2-simple-tags==0.3.1,jsonschema==3.1.1,keyring==23.5.0,leather==0.3.4,Logbook==1.5.3,MarkupSafe==2.0.1,mashumaro==2.9,minimal-snowplow-tracker==0.0.2,msgpack==1.0.3,networkx==2.8,oscrypto==1.3.0,packaging==21.3,parsedatetime==2.4,pathspec==0.9.0,pluggy==1.0.0,py==1.11.0,pycparser==2.21,pycryptodomex==3.14.1,Pygments==2.11.2,PyJWT==2.3.0,pyOpenSSL==21.0.0,pyparsing==3.0.8,pyrsistent==0.18.1,pytest==7.1.1,python-dateutil==2.8.2,python-slugify==6.1.1,pytimeparse==1.1.8,pytz==2022.1,PyYAML==6.0,regex==2022.3.15,requests==2.27.1,six==1.16.0,snowflake-connector-python==2.7.6,sqlfluff==0.12.0,sqlfluff-templater-dbt==0.12.0,sqlparse==0.4.2,tblib==1.7.0,text-unidecode==1.3,toml==0.10.2,tomli==2.0.1,tqdm==4.64.0,typing-extensions==3.10.0.2,urllib3==1.26.9,Werkzeug==2.1.1,zipp==3.8.0
lint run-test-pre: PYTHONHASHSEED='3855145386'
lint run-test: commands[0] | sqlfluff lint models/model.sql --ignore parsing
=== [dbt templater] Sorting Nodes...
=== [dbt templater] Compiling dbt project...
=== [dbt templater] Project Compiled.
== [models/model.sql] FAIL
L:   2 | P:   6 | L003 | Expected 1 indentations, found 0 [compared to line 02]
All Finished 📜 🎉!
```

### Expected Behaviour

No lint error

### Observed Behaviour

Incorrect lint error

### How to reproduce

see above

### Dialect

Snowflake

### Version

sqlfluff==0.12.0

### Configuration

[sqlfluff]
dialect = snowflake
templater = dbt
rules = L001,L003,L004,L005,L006,L007,L008,L010,L011,L012,L014,L015,L017,L018,L021,L022,L023,L025,L027,L028,L030,L035,L036,L037,L039,L040,L041,L042,L045,L046,L048,L051,L055

[sqlfluff:rules:L003]
indent_unit = space
tab_space_size = 2

[sqlfluff:rules:L004]
indent_unit = space
tab_space_size = 2

[sqlfluff:rules:L010]
capitalisation_policy = lower

[sqlfluff:rules:L014]
capitalisation_policy = lower

[sqlfluff:rules:L028]
single_table_references = unqualified

[sqlfluff:rules:L030]
capitalisation_policy = lower

[sqlfluff:rules:L040]
capitalisation_policy = lower

[sqlfluff:rules:L042]
forbid_subquery_in = both

### Are you willing to work on and submit a PR to address the issue?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by barrywhart** [comment]
Using this as a test case (so I don't have to involve dbt):
```
select *
from {{ "\n\nmy_table" }}
```

**Comment by NiallRees** [comment]
Nice thank you @barrywhart
