### ISSUE TITLE
L003: Jinja directive outside of SELECT interfers with Jinja conditionals inside 

### ISSUE THREAD

**Issue by dmohns** [sqlfluff/sqlfluff#3133]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### What Happened

Linting the following SQL produces unexpected results:

```sql
{% set test = (1 == 1) %}

SELECT *
FROM table_1
WHERE TRUE
{% if test %}
AND TRUE
{% endif %}
```

### Expected Behaviour

```sql
{% set test = (1 == 1) %}

SELECT *
FROM table_1
WHERE TRUE
    {% if test %}
        AND TRUE
    {% endif %}
```

This is based on the result of: https://online.sqlfluff.com/fluffed?sql=H4sIACcmYWIC_wt29XF1DlHQ4uVyC_L3VShJTMpJjTfk5Qr3cA1yVQgJCnXl5apWVchMU9AwVLC1VTDUVFCt5eVy9HNBSKbmpQDlQcIAJZvHVk4AAAA%3D&dialect=ansi

```sql
SELECT *
FROM table_1
WHERE TRUE
{% if (1 == 1) %}
AND TRUE
{% endif %}
```

produces

```sql
SELECT *
FROM table_1
WHERE TRUE
    {% if (1 == 1) %}
        AND TRUE
    {% endif %}
```

### Observed Behaviour

```sql
{% set test = (1 == 1) %}

SELECT *
FROM table_1
WHERE TRUE
    {% if test %}
    AND TRUE
{% endif %}
```

Note the odd placement of `{% endif %}`

### How to reproduce

https://online.sqlfluff.com/fluffed?sql=H4sIAHYmYWIC_6tWVShOLVEoSS0uUbBV0DBUsLVVMNRUUK3l5eLlCnb1cXUOUdDi5XIL8vdVKElMykmNN-TlCvdwDXJVCAkKdeXlqlZVyEyD6AdpcvRzQUik5qUA5VRrASwShStlAAAA&dialect=ansi

### Dialect

ansi

### Version

0.12.0 -> webversion

### Configuration

default

### Are you willing to work on and submit a PR to address the issue?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by alanmcruickshank** [comment]
This is resolved in #3942 . On that branch the query is fixed to:

```sql
{% set test = (1 == 1) %}

SELECT *
FROM table_1
WHERE
    TRUE
    {% if test %}
        AND TRUE
    {% endif %}
```
