### ISSUE TITLE
TSQL: Support try_convert

### ISSUE THREAD

**Issue by fdw** [sqlfluff/sqlfluff#3134]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### Description

T-SQL has a built-in method `try_convert`: https://docs.microsoft.com/en-us/sql/t-sql/functions/try-convert-transact-sql?view=sql-server-ver15

### Use case

The method is recognized in the parser

### Dialect

T-SQL

### Are you willing to work on and submit a PR to address the issue?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by tunetheweb** [comment]
What happens if you try to use it now? Parse Error? Parses successfully not incorrectly? Something else?
