### ISSUE TITLE
TSQL: Insert with table hints

### ISSUE THREAD

**Issue by fdw** [sqlfluff/sqlfluff#3135]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### Description

In T-SQL, `insert` (and others) can have so-called table hints, for example:
```sql
insert into tableName with(tablock)...
```

Currently, `sqlfluff` does not understand this

### Dialect

T-SQL

### Are you willing to work on and submit a PR to address the issue?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by tunetheweb** [comment]
Could you use the `bug` template for missing dialect like this? We consider it a bug, and that template asks for more info (e.g. SQL, config, SQLFluff version...etc).

**Comment by fdw** [comment]
Sure, sorry! :)
