### ISSUE TITLE
Hive: Support back quote 

### ISSUE THREAD

**Issue by barunpuri** [sqlfluff/sqlfluff#3138]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### What Happened

sqlfluff currently can't handle for backquote(`) as an identifier or literal So if SQL uses backquote, this makes an error. 

### Expected Behaviour

sqlfluff supports parsing backquoted identifiers or literals

### Observed Behaviour

hql with backquote
```
WITH test AS (
    SELECT '123' AS `timestamp` 
)
SELECT `timestamp` FROM test
```
sqlfluff returns
<img width="673" alt="Screen Shot 2022-04-21 at 8 35 53 PM" src="https://user-images.githubusercontent.com/12489812/164449814-da9edfa7-38b9-4ffc-b3a6-b7b68a4084d9.png">

ref. https://cwiki.apache.org/confluence/display/Hive/Configuration+Properties#ConfigurationProperties-hive.support.quoted.identifiers

### How to reproduce

- Add `back_quote` to `QuotedLiteralSegment`
- Update `SingleQuotedIdentifierSegment` as one of `single_quote` and `back_quote`

ref. https://github.com/barunpuri/sqlfluff/commit/851ce3e48767a2d6c18fae1654354d848ae30242

### Dialect

hive

### Version

sqlfluff, version 0.12.0
python 3.7.10

### Configuration

[sqlfluff]
dialect = hive
sql_file_exts = .sql,.hql
exclude_rules = L025,L031
templater = raw

[sqlfluff:indentation]
indented_using_on = true
template_blocks_indent = false

[sqlfluff:templater:jinja:context]
a=a

[sqlfluff:templater:python: context]
a=a

[sqlfluff:rules]
tab_space_size = 4
max_line_length = 132
indent_unit = space
comma_style = trailing
allow_scalar = True
single_table_references = unqualified
unquoted_identifiers_policy = all

[sqlfluff:rules:L010]
capitalisation_policy = upper

[sqlfluff:rules:L014]
extended_capitalisation_policy = lower
ignore_words = None

[sqlfluff:rules:L016]
ignore_comment_lines = True
ignore_comment_clauses = True

[sqlfluff:rules:L022]
comma_style = trailing

[sqlfluff:rules:L030]
extended_capitalisation_policy = upper
ignore_words = None

[sqlfluff:rules:L031]
force_enable = False

[sqlfluff:rules:L040]
capitalisation_policy = upper
ignore_words = None

[sqlfluff:rules:L042]
forbid_subquery_in = join

[sqlfluff:rules:L051]
fully_qualify_join_types = both

[sqlfluff:rules:L054]
group_by_and_order_by_style = explicit

[sqlfluff:rules:L063]
extended_capitalisation_policy = upper
ignore_words = None

### Are you willing to work on and submit a PR to address the issue?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by tunetheweb** [comment]
BigQuery uses this btw:= and SQLFluff supports it in that:

```py
bigquery_dialect.replace(
    QuotedIdentifierSegment=NamedParser(
        "back_quote",
        CodeSegment,
        name="quoted_identifier",
        type="identifier",
        trim_chars=("`",),
    ),
```

This replaces the `double_quote` version of that from ANSI dialect.

But then it also allows Double Quotes in literals:

```py
bigquery_dialect.add(
    DoubleQuotedLiteralSegment=NamedParser(
        "double_quote",
        CodeSegment,
        name="quoted_literal",
        type="literal",
        trim_chars=('"',),
    ),

...

    # Add three elements to the ansi LiteralGrammar
    LiteralGrammar=ansi_dialect.get_grammar("LiteralGrammar").copy(
        insert=[
            Ref("DoubleQuotedLiteralSegment"),
            Ref("LiteralCoercionSegment"),
            Ref("ParameterizedSegment"),
        ]
    ),
```

So should be easy enough to do the same in Hive.
