### ISSUE TITLE
TSQL GOTO Labels (:) not parseable

### ISSUE THREAD

**Issue by edmoren** [sqlfluff/sqlfluff#3148]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### What Happened

While testing the newest version of the linter, `sqlfluff==0.12.0`, I encountered a crash on a label statement in a stored procedure.

[GOTO Label Documentation](https://docs.microsoft.com/en-us/sql/t-sql/language-elements/goto-transact-sql?view=sql-server-ver15)

Basic Syntax looks like this: 
```
DECLARE @Counter int;  
SET @Counter = 1;  
WHILE @Counter < 10  
BEGIN   
    SELECT @Counter  
    SET @Counter = @Counter + 1  
    IF @Counter = 4 GOTO Branch_One --Jumps to the first branch.  
    IF @Counter = 5 GOTO Branch_Two  --This will never execute.  
END  
Branch_One:  
    SELECT 'Jumping To Branch One.'  
    GOTO Branch_Three; --This will prevent Branch_Two from executing.  
Branch_Two:  
    SELECT 'Jumping To Branch Two.'  
Branch_Three:  
    SELECT 'Jumping To Branch Three.';
```

Specifically this issue is related to the label definition. `Branch_One:` in the example above.

### Expected Behaviour

Would expect this to be parseable in order to work with `GOTO` syntax. 

### Observed Behaviour

A parser error occurs, in terminal the error looks like this: 
```
L:   7 | P:   1 |  PRS | Line 7, Position 1: Found unparsable section: 'CREATE PROCEDURE                                           | [dbo].[foo]\n\t\t@in_wh_id...' 
```

### How to reproduce

[parse.txt](https://github.com/sqlfluff/sqlfluff/files/8535996/parse.txt)
[sample.txt](https://github.com/sqlfluff/sqlfluff/files/8535997/sample.txt)
[sqlfluff.txt](https://github.com/sqlfluff/sqlfluff/files/8535998/sqlfluff.txt)

Download the following files. 
* sample.txt 
* sqlfluff.txt
* parse.txt

Convert `sample.txt` into `sample.sql`.
Convert `sqlfluff.txt` into `.sqlfluff`.
Note, `parse.txt` included for example purposes.

Run the following command. I am on a windows machine, some modification may be needed to work on a unix system. 
`sqlfluff parse ./sample.sql --config ./.sqlfluff`

### Dialect

`tsql`

### Version

`sqlfluff==0.12.0`

### Configuration

```
[sqlfluff]
dialect = tsql

[sqlfluff:indentation]
indented_joins = false
indented_using_on = true

[sqlfluff:rules]
indent_unit = tab
tab_space_size = 4
operator_new_lines = after
capitalisation_policy = upper
aliasing = explicit
allow_scalar = True
extended_capitalisation_policy = consistent
ignore_comment_clauses = True
ignore_comment_lines = True
max_line_length = 120
comma_style = leading
single_table_references = consistent
select_clause_trailing_comma = forbid
prefer_count_1 = True
multiline_newline = True
require_final_semicolon = True
allow_space_in_identifier = True
quoted_identifiers_policy = all
unquoted_identifiers_policy = all
exclude_rules = L025, L031, L061
```

### Are you willing to work on and submit a PR to address the issue?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by tunetheweb** [comment]
This was fixed in #2949 and will be include a the next release (maybe today!)
