### ISSUE TITLE
Hive: Support for LATERAL VIEW clause

### ISSUE THREAD

**Issue by barunpuri** [sqlfluff/sqlfluff#3161]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### What Happened

sqlfluff currently can't handle for `LATERAL VIEW`. So if SQL uses `LATERAL VIEW`, this makes an error.

### Expected Behaviour

sqlfluff supports parsing `LATERAL VIEW`

### Observed Behaviour

hql with `LATERAL VIEW`
```
SELECT pageid, adid
FROM pageAds
LATERAL VIEW explode(adid_list) adTable AS adid;
```

sqlfluff returns 
<img width="697" alt="Screen Shot 2022-04-23 at 1 46 00 PM" src="https://user-images.githubusercontent.com/12489812/164878077-2c0e3968-4416-4113-bdf2-efa040fc5d4c.png">

ref. https://cwiki.apache.org/confluence/display/hive/languagemanual+lateralview

### How to reproduce

after #3160
Create `LateralViewClauseSegment` class referenced by sparksql with using UDTF
https://github.com/sqlfluff/sqlfluff/blob/ddc3200009f49f90575d1ed6a107f81710302311/src/sqlfluff/dialects/dialect_sparksql.py#L1613-L1639

### Dialect

hive

### Version

sqlfluff, version 0.13.0
Python 3.7.10

### Configuration

```
[sqlfluff]
dialect = hive
sql_file_exts = .sql,.hql
exclude_rules = L025,L031
templater = raw

[sqlfluff:indentation]
indented_using_on = true
template_blocks_indent = false

[sqlfluff:templater:jinja:context]
a=a

[sqlfluff:templater:python: context]
a=a

[sqlfluff:rules]
tab_space_size = 4
max_line_length = 132
indent_unit = space
comma_style = trailing
allow_scalar = True
single_table_references = unqualified
unquoted_identifiers_policy = all

[sqlfluff:rules:L010]
capitalisation_policy = upper

[sqlfluff:rules:L014]
extended_capitalisation_policy = lower
ignore_words = None

[sqlfluff:rules:L016]
ignore_comment_lines = True
ignore_comment_clauses = True

[sqlfluff:rules:L022]
comma_style = trailing

[sqlfluff:rules:L030]
extended_capitalisation_policy = upper
ignore_words = None

[sqlfluff:rules:L031]
force_enable = False

[sqlfluff:rules:L040]
capitalisation_policy = upper
ignore_words = None

[sqlfluff:rules:L042]
forbid_subquery_in = join

[sqlfluff:rules:L051]
fully_qualify_join_types = both

[sqlfluff:rules:L054]
group_by_and_order_by_style = explicit

[sqlfluff:rules:L063]
extended_capitalisation_policy = upper
ignore_words = None
```

### Are you willing to work on and submit a PR to address the issue?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by tunetheweb** [comment]
Note our sparksql dialect has this (search for `LateralViewClauseSegment`) so maybe a good one to base this one. And should try to be consistent on type (i.e. use `type = "lateral_view_clause"`) between sparksql and hive.
