### ISSUE TITLE
Snowflake - Unparsable array casting SQL

### ISSUE THREAD

**Issue by WittierDinosaur** [sqlfluff/sqlfluff#3176]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### What Happened

```
CREATE OR REPLACE TABLE foo.foo AS
	SELECT raw:foo::array[0]::string  as channel
	FROM foo.bar
	;
```
The index of the array is unparsable.

### Expected Behaviour

-

### Observed Behaviour

-

### How to reproduce

-

### Dialect

Snowflake

### Version

0.13.0

### Configuration

-

### Are you willing to work on and submit a PR to address the issue?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by vholmer** [comment]
Hi, this is affecting me as well. As long as I have "::ARRAY[0]" in my SQL sqlfluff says that it's unparseable even though I've put "dialect = snowflake".

**Comment by vholmer** [comment]
Oh, I forgot to mention: my current workaround is to simply do

```SQL
GET(column::ARRAY, 0) AS alias
```

instead of

```SQL
myColumn::ARRAY[0] AS alias
```

This makes the code parseable for sqlfluff.
