### ISSUE TITLE
Snowflake: Support COPY INTO <location>

### ISSUE THREAD

**Issue by WittierDinosaur** [sqlfluff/sqlfluff#3184]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### Description

We currently don't support COPY INTO <location>
https://docs.snowflake.com/en/sql-reference/sql/copy-into-location.html

### Dialect

Snowflake

### Are you willing to work on and submit a PR to address the issue?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by jmc-bbk** [comment]
I think this may be resolved by #3293 . Can you check @WittierDinosaur ?

I assume you were looking at a similar unparsable bit of code to me. Now that I've fixed a bug with file formats, looks like `COPY INTO` sections parse.

**Comment by jmc-bbk** [comment]
For example:

```
CREATE OR REPLACE PIPE bar.bar.bar
    AUTO_INGEST = TRUE
    AWS_SNS_TOPIC='topic'
    AS
COPY INTO foo.foo.foo
    FROM (
      SELECT
        METADATA$FILENAME
        , $1
        , $2
        , $3
      FROM @foo.bar.baz
    )
    ON_ERROR = 'skip_file'
    FILE_FORMAT = baz.bar.foo
;
```

will parse following 3293.

**Comment by mroy-seedbox** [comment]
This is still causing an issue for us in version `3.2.2`:
![image](https://github.com/user-attachments/assets/f355a84a-8f59-4c58-87c5-73068a354dcc)

I think maybe the `@` is throwing it off. Or maybe there's just no support for `COPY INTO <location>`. 🤷‍♂️
