### ISSUE TITLE
TSQL: Cannot parse `exists` with `union`

### ISSUE THREAD

**Issue by fdw** [sqlfluff/sqlfluff#3197]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### What Happened

I'm trying to parse a file with something like this: `if exists (select * from #a union all select * from #b)`.

### Expected Behaviour

This can be parsed and linted.

### Observed Behaviour

This line leads to a parsing error. Without the union (only doing `if exists (select * from #a)` or `if exists (select * from #b)`) it works.

### How to reproduce

See above

### Dialect

T-SQL

### Version

Latest `main`

### Configuration

Nothing relevant

### Are you willing to work on and submit a PR to address the issue?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by tunetheweb** [comment]
`if exists (select * from #a union all select * from #b)` is not a complete SQL statement, but looks like this can be fixed by replacing this:

https://github.com/sqlfluff/sqlfluff/blob/656a958146e9d415a39e77da7a063cd304fd56d3/src/sqlfluff/dialects/dialect_ansi.py#L1715

with
```py
Sequence("EXISTS", Bracketed(Ref("SelectableGrammar"))),
```
