### ISSUE TITLE
regex.Match AttributeError: module 'regex' has no attribute 'Match'

### ISSUE THREAD

**Issue by zmtnda** [sqlfluff/sqlfluff#3207]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### What Happened

after I updated to latest version, and run the command
`sqlfluff --version`
give me the error
`AttributeError: module 'regex' has no attribute 'Match'`

### Expected Behaviour

should output

`sqlfluff, version 0.13.0`

### Observed Behaviour

the trace of the error ...
File "/Users/user/anaconda3/envs/myenv/lib/python3.8/site-packages/sqlfluff/core/templaters/slicers/tracer.py", line 418, in JinjaAnalyzer
    self, m_open: regex.Match, m_close: regex.Match, tag_contents: List[str]
AttributeError: module 'regex' has no attribute 'Match'

### How to reproduce

run 
>sqlfluff --version

### Dialect

default: ansi

### Version

0.13.0

### Configuration

default

### Are you willing to work on and submit a PR to address the issue?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by tunetheweb** [comment]
Sounds like you have a really old version of `regex` installed.

Suggest you look at your Python dependencies and maybe do a fresh install?

Unfortunately this is not something to do with SQLFluff as far as aI can tell so closing this.

**Comment by metov** [comment]
>this is not something to do with SQLFluff
