### ISSUE TITLE
BigQuery: Missing date `PART` for `EXTRACT` (timestamp variation)

### ISSUE THREAD

**Issue by dmohns** [sqlfluff/sqlfluff#3208]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### What Happened

The BigQuery `EXTRACT` function supports different `part` parameters depending on whether it's called on a DATE, DATETIME or TIMESTAMP.

See

- https://cloud.google.com/bigquery/docs/reference/standard-sql/date_functions#extract
- https://cloud.google.com/bigquery/docs/reference/standard-sql/datetime_functions#extract
- https://cloud.google.com/bigquery/docs/reference/standard-sql/timestamp_functions#extract

Currently, in the TIMESTAMP variant of the function not all `part` are supported, see example below.

### Expected Behaviour

`EXTRACT` is fully supported in all variants.

### Observed Behaviour

```
Found unparsable section: '(DATE FROM TIMESTAMP_SECONDS(1651135778)...'
```

### How to reproduce

```sql
SELECT EXTRACT(DATE FROM TIMESTAMP_SECONDS(1651135778))
```

https://online.sqlfluff.com/fluffed?sql=H4sIAPJVamIC_wt29XF1DlFwjQgJcnQO0XBxDHFVcAvy91UI8fR1DQ5x9A2ID3Z19vdzCdYwNDM1NDQ2NTe30NQEACOQ5Jc3AAAA&dialect=bigquery

### Dialect

bigquery

### Version

0.13.0 -> webversion

### Configuration

default

### Are you willing to work on and submit a PR to address the issue?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by tunetheweb** [comment]
Weirdly that's not listed as valid BigQuery syntax [in their docs](https://cloud.google.com/bigquery/docs/reference/standard-sql/date_functions#extract), but tested it and agree it works. Have raised an issue with their docs.

Also raised #3209 to add this, for `EXTRACT` function only as, as per #2283 including this as a general date_part causes issues.
