### ISSUE TITLE
TSQL: `for xml path` is fixed incorrectly

### ISSUE THREAD

**Issue by fdw** [sqlfluff/sqlfluff#3219]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### What Happened

Original sql:
```
select blah for xml path('root')
```

When calling `sqlfluff fix`, it should stay the same. However, the single quotes around `root` are removed, resulting in the broken SQL
```
select blah for xml path(root)
```

I assume this is because `'root'` is parsed as a `SingleQuotedIdentifierSegment`. However, I don't know what the right would be. `QuotedLiteralSegment`?

### Expected Behaviour

see above

### Observed Behaviour

see above

### How to reproduce

see above

### Dialect

T-SQL

### Version

Latest main

### Configuration

Nothing relevant

### Are you willing to work on and submit a PR to address the issue?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by WittierDinosaur** [comment]
Yeah, QuotedLiteralSegment would work 👍
