### ISSUE TITLE
Tests don't run with tox

### ISSUE THREAD

**Issue by fdw** [sqlfluff/sqlfluff#3271]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### What Happened

I tried to test my changes with `tox -e py310`, but it results in an error:
```
.tox/py310/lib/python3.10/site-packages/sqlfluff/core/rules/base.py:1083: in register
    "all" in cls.groups
E   AttributeError: type object 'Rule_Example_L001' has no attribute 'groups'

The above exception was the direct cause of the following exception:
test/core/linter_test.py:410: in <module>
    dummy_rule_codes = [r.code for r in Linter().get_ruleset()]
.tox/py310/lib/python3.10/site-packages/sqlfluff/core/linter/linter.py:95: in get_ruleset
    rs = get_ruleset()
.tox/py310/lib/python3.10/site-packages/sqlfluff/core/rules/__init__.py:42: in get_ruleset
    std_rules = _load_standard_rules()
.tox/py310/lib/python3.10/site-packages/sqlfluff/core/rules/__init__.py:35: in _load_standard_rules
    std_rule_set.register(rule)
.tox/py310/lib/python3.10/site-packages/sqlfluff/core/rules/base.py:1088: in register
    raise AttributeError(
E   AttributeError: Rule 'Example_L001' doesn't belong to any rule groups. All rules must belong to at least one group
```

### Expected Behaviour

The tests work

### Observed Behaviour

It fails with the above error

### How to reproduce

On latest `main`, call `tox -e py310`.

### Dialect

n/a

### Version

Latest `main`

### Configuration

n/a

### Are you willing to work on and submit a PR to address the issue?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by tunetheweb** [comment]
To me this is a `tox` issue not a SQLFluff one to be honest.

**Comment by jmc-bbk** [comment]
I'm now getting this on main branch with `sqlfluff lint test.sql` - my environment is a bit of a mess. But thought I would flag in case there's anything else going on.

**Comment by jmc-bbk** [comment]
Fixed by deleting my repo and reinstalling a fresh (deleting `.tox` didn't work). Unsure what was up.
