### ISSUE TITLE
Doc typo "vales"

### ISSUE THREAD

**Issue by mdahlman** [sqlfluff/sqlfluff#3299]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### Issue/Suggested Improvement

I'm referring to this file:
docs/source/configuration.rst

Current:
will be used to overwrite any vales read from earlier files.

Fixed:
will be used to overwrite any values read from earlier files.

### Are you willing to work on and submit a PR to address the issue?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by tunetheweb** [comment]
Would love a PR for this as seems simple.

FYI, next time feel free to jump straight to PR for simple fixes like this rather than raising an issue.
