### ISSUE TITLE
Support FOR...IN syntax in BigQuery

### ISSUE THREAD

**Issue by ohyan** [sqlfluff/sqlfluff#3316]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### Description

We would like to use `FOR...IN`  in BigQuery but now it is not support in SQLFluff and it will generate a PRS error such as
```
L: 18 | P: 4 | PRS | Line 18, Position 4: Found unparsable section: ' FOR'
```

ref: https://cloud.google.com/bigquery/docs/reference/standard-sql/procedural-language#for-in

### Use case
generally
```
FOR loop_variable_name IN (table_expression)
DO
  sql_expression_list
END FOR;
```

example1:
```
FOR record IN
  (SELECT word, word_count
   FROM bigquery-public-data.samples.shakespeare
   LIMIT 5)
DO
  SELECT record.word, record.word_count;
END FOR;
```

example2:
```
FOR user IN (
    SELECT
        group,
	count(*) as count
    FROM `database.user`
)
DO
	ASSERT (COUNT > 0)
END FOR;
```

### Dialect

BigQuery

### Are you willing to work on and submit a PR to address the issue?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by tunetheweb** [comment]
Note your second example has two errors:
1. `group` is a reserved word so can't be used as an identifier
2. `ASSERT` statement needs to be ended in a semi-colon.

Confirmed this on BigQuery.
