### ISSUE TITLE
Support dbt var() macro

### ISSUE THREAD

**Issue by alanmcruickshank** [sqlfluff/sqlfluff#333]
As per https://docs.getdbt.com/docs/writing-code-in-dbt/jinja-context/var/.

**Comment by alanmcruickshank** [comment]
Initial implementation suggestion for this would just be to render the name of the `var` as the result. This means we can be independent of what that variable is and still parse *most* queries.

**Comment by pwildenhain** [comment]
@alanmcruickshank do you still think we should do this? Or just direct people to use the new `dbt` templater?

**Comment by alanmcruickshank** [comment]
> Or just direct people to use the new dbt templater?

We should do exactly that 😄
