### ISSUE TITLE
Handle SQL Embedded in Python (and other languages') Strings

### ISSUE THREAD

**Issue by ijoseph** [sqlfluff/sqlfluff#3331]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### Description

It's common practice to embed multiline SQL statements in Python files, as evidenced by the popularity of the [`python-string-sql`](https://marketplace.visualstudio.com/items?itemName=ptweir.python-string-sql) add-on. 

It would be very useful for us to add sqlfluff as a linter to our repository (using `pre-commit`) to detect/ auto-fix these SQL embedded in strings. 

#### Example
A file `tmp.py` with this:
```python
EXAMPLE = """
SELECT 
name FROM foo;
"""
```
is ignored by `sqlfluff fix`

> ```bash
> sqlfluff fix  tmp.py
> ==== finding fixable violations ====
> ==== no fixable linting violations found ====
> All Finished 📜 🎉! 
> ```

however the corresponding raw SQL file is fixed (when the extension is changed to `sql`), of course. 

### Use case

Pull request / pre-commit linters are able to run SQLFluff on embedded SQL strings and make appropriate changes/ warnings. 

### Dialect

N/A although Snowflake would be helpful 

### Are you willing to work on and submit a PR to address the issue?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

Vaguely related to https://github.com/sqlfluff/sqlfluff/issues/1010 in that `.py` files are ignored now completely due to extension, although simply changing extension doesn't suffice (and even if it did would be too inconvenient of a workaround at repository-scale linting)

**Comment by tunetheweb** [comment]
I'm not sure this is something SQLFluff would want to take on (or even how it would know whether a string in the middle of other code is SQL or not).

To me the best way of implementing this, would be for the code, to call the [Simple API](https://docs.sqlfluff.com/en/stable/api.html).

**Comment by barrywhart** [comment]
I agree with @tunetheweb. I think it'd be more appropriate to look at implementing this as a separate package that **uses** SQLFluff.

**Comment by ijoseph** [comment]
Makes sense -- seems tricky to detect an SQL string, and this requirement that `python-string-sql` uses to hack around this is probably not worth it:

> Insert `--sql`, `--beginsql`, or --`begin-sql` at the beginning of the part of the string you would like highlighted and a semicolon, `--endsql`, or `--end-sql` at the end of the highlighted section.

We decided that a better approach is to just split our SQL out into its own file and then load them into the Python modules. 

Feel free to WNF this.

**Comment by tunetheweb** [comment]
Closing this as will not fix
