### ISSUE TITLE
Disable the safeties on `fix`

### ISSUE THREAD

**Issue by alanmcruickshank** [sqlfluff/sqlfluff#334]
>  `The fix option is only available in combination with --rules. This is for your own safety!`
> I appreciate the concern, but git takes care of my safety needs, and while evaluating sqlfluff it would be really useful to see what it wants our SQL to be.

We should consider removing the requirement to specify rules on the `fix` command if it's hindering people trying the tool. This feature may just be a relic of when the `fix` routines were less reliable.

@barrywhart - thoughts?

**Comment by barrywhart** [comment]
I like having this as an option, definitely. Otherwise, I end up customizing the "fix" command I run based on the lint output.

It would be cool if the default were to fix everything. You could exclude rules if you want, or if you _include_v rules, you get _only_ those.

**Comment by barrywhart** [comment]
Maybe `fix` could use the same (or similar) "exclude" setting (in `.sqlfluff`) that `lint`uses.

**Comment by jml** [comment]
Hi! I wrote the original comment. 

I kind of beat this drum a lot, but I think what might be better is an explicit `fmt` command (like `go fmt`, `terraform fmt`, etc). Then the user expectations are that this will change my code, but only in low-risk ways that won't change semantics. 

Then `fix` can be reserved for more avant garde changes.

**Comment by barrywhart** [comment]
Related to the above, the "black" formatting package for Python code has a clever way to guarantee it doesn't make any unsafe changes: it builds an abstract syntax tree of the code before and after reformatting it, and it verifies that the two are identical.

That could be cool here as well, both for safety and for determining which rules are in the `fmt` versus `fix` category.

For a bit of info on black and this self verification feature, see here: https://github.com/psf/black/blob/master/README.md#note-this-is-a-beta-product.

**Comment by pwildenhain** [comment]
I would also _love_ to automatically apply a lot of rules. I think that `fix` has proven trustworthy for me, though I also see the value in a `fmt` command. Either way, I would love to have something like this.

**Comment by pwildenhain** [comment]
@alanmcruickshank Do you think we're in a good spot to disable the safeties on `fix`? I can't imagine it's that complex to turn this off -- I'm willing to give it a go if you still think this is a good idea

**Comment by pwildenhain** [comment]
I didn't know about the `--no-safety` flag until today! Should we consider this issue closed if all it takes is adding `--no-safety` to apply all the fixes? I figure if it's good enough for #434 then it's good enough for here.

Or do we really believe that the default should be fixing all the rules?
