### ISSUE TITLE
Postgres: select targets are optional but SQLFluff does not support this

### ISSUE THREAD

**Issue by booqoffsky** [sqlfluff/sqlfluff#3365]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### What Happened

There is a special insert request that checks for the presence of a row before inserting, so as not to increase the primary key counter. However, sqlfluff cannot parse it.

### Expected Behaviour

Working without parsing errors.

### Observed Behaviour

```
L:   6 | P:   1 |  PRS | Line 6, Position 1: Found unparsable section: 'SELECT'
L:   6 | P:   8 | L003 | Expected 1 indentations, found 0 [compared to line 05]
L:   8 | P:   2 |  PRS | Line 8, Position 2: Found unparsable section: '\nON
                       | CONFLICT DO NOTHING'
```

### How to reproduce

1) Create an `insert.sql` file:
```
INSERT INTO megatable (megacolumn)
SELECT * FROM (
    VALUES ( 'megavalue' )
) AS tmp (megacolumn)
WHERE NOT EXISTS (
SELECT FROM megatable AS mt
    WHERE mt.megacolumn = tmp.megacolumn
)
ON CONFLICT DO NOTHING;

```
2) Run `sqlfluff lint --dialect postgres insert.sql`

### Dialect

postgres

### Version

sqlfluff, version 0.13.1

### Configuration

[sqlfluff]
exclude_rules = L031

[sqlfluff:rules:L010]
capitalisation_policy = upper

[sqlfluff:rules:L011]
aliasing = explicit

### Are you willing to work on and submit a PR to address the issue?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by tunetheweb** [comment]
Is this valid SQL:

```sql
SELECT FROM megatable
```

Don't you have to specify some columns (or `*`) in the select statement? Once you do that it parses.

This parses btw:

```sql
INSERT INTO megatable (megacolumn)
(
    SELECT * FROM (
        VALUES ( 'megavalue' )
    ) AS tmp (megacolumn)
    WHERE NOT EXISTS (
    SELECT 1 FROM megatable AS mt
        WHERE mt.megacolumn = tmp.megacolumn
    )
)
ON CONFLICT DO NOTHING;
```

**Comment by booqoffsky** [comment]
Thanks for the sample query that can be parsed. I will use it.

fyi:
> Is this valid SQL: SELECT FROM megatable

Yes, this is valid SQL, here is another usage example: https://stackoverflow.com/a/11892796/8650784

**Comment by tunetheweb** [comment]
> Some other RDBMS don't allow an empty SELECT list on principal.

I agree with this principal! 😁

Even `SELECT 1 FROM megatable` would be preferably IMHO and presumably the same cost.
