### ISSUE TITLE
sparksql dialect to support aggregate function syntax (a.k.a. reduce)

### ISSUE THREAD

**Issue by juhoautio** [sqlfluff/sqlfluff#3373]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### What Happened

Syntax parsing is not implemented for the [aggregate function](https://spark.apache.org/docs/latest/api/sql/index.html#aggregate) of spark sql. Could it be added?

Examples of the syntax:

```sql
> SELECT aggregate(array(1, 2, 3), 0, (acc, x) -> acc + x);
 6
> SELECT aggregate(array(1, 2, 3), 0, (acc, x) -> acc + x, acc -> acc * 10);
 60
```

Could there also be an _alias_ `reduce`->`aggregate`? The [Databricks SQL](https://docs.databricks.com/sql/language-manual/functions/reduce.html) extension has it, so it would be convenient if sqlfluff also supports it. Would that be ok, or does sqlfluff try to exactly & only match the open source version of sparksql?

Examples from Databricks SQL:
```sql
> SELECT reduce(array(1, 2, 3), 0, (acc, x) -> acc + x);
 6
> SELECT reduce(array(1, 2, 3), 0, (acc, x) -> acc + x, acc -> acc * 10);
 60

> SELECT reduce(array(1, 2, 3, 4),
                named_struct('sum', 0, 'cnt', 0),
                (acc, x) -> named_struct('sum', acc.sum + x, 'cnt', acc.cnt + 1),
                acc -> acc.sum / acc.cnt) AS avg
 2.5
```

Currently sqlfluff fails parsing for this type of syntax, for example:
```
L:   1 | P:  61 |  PRS | Line 1, Position 61: Found unparsable section: '-> s +
```

----

One more thing: In sparksql dialect the keyword REDUCE is included:
https://github.com/sqlfluff/sqlfluff/blob/a1385c1d759b9a7ef099d6b842de78b393bf149c/src/sqlfluff/dialects/dialect_sparksql_keywords.py#L205
Does a keyword like this have a different meaning vs. same word appearing as a function name? I suppose this doesn't matter though. To be noted, there is no reserved keyword for AGGREGATE so I presume it is simply interpreted & allowed as a function name, which can be anything?

### Expected Behaviour

aggregate syntax is supported

### Observed Behaviour

aggregate syntax fails with parsing error

### How to reproduce

(examples in the "what happened" section)

### Dialect

- aggregate: sparksql
- reduce: not open source spark sql, only the proprietary [Databricks SQL](https://docs.databricks.com/sql/language-manual/functions/reduce.html).

### Version

sqlfluff, version 0.13.1

### Configuration

-

### Are you willing to work on and submit a PR to address the issue?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by mdahlman** [comment]
"I presume it is simply interpreted & allowed as a function name, which can be anything?"
You are correct. In your first example `reduce` and `array` parse as function names. Their presence or absence from reserved words don't matter here.

So I think the heart of the issue is different. The bug should get retitled to something like this:
"sparksql dialect to support '->' symbol"

To start with, it doesn't even lex. (SQLFluff doesn't recognize it as a symbol.) Adding that would be easy. But I'm not sure how to best parse it after that.

@tunetheweb, can you point to any sort of parallel example of handling something like that?

**Comment by tunetheweb** [comment]
I see some examples from postgres:

<img width="323" alt="image" src="https://user-images.githubusercontent.com/10931297/169348323-605b6284-6481-44d4-a184-6e6231690efe.png">

But really to build up the parse grammar need to know what this symbol means. I don't know what it is to be honest.

Any docs you can point us at @juhoautio ?

To be honest, this is why it's good to have people who use the dialect to implement their improvements - particularly for dialect-specific stuff like this. They might know some nuances, or be able to test some things on their instances, than non-users like the rest of us won't be able to.

**Comment by tunetheweb** [comment]
Ah sorry, I’m missed that the doc link in the original issue had the arrow syntax in it.

**Comment by mdahlman** [comment]
It seems to me that the last link is useful. Perhaps this is the core issue:
"sparksql dialect to support lambda expressions using ARROW '->' symbol"

From that link, these are the 2 constructions:
    | identifier ARROW expression                                                              #lambda
    | LEFT_PAREN identifier (COMMA identifier)+ RIGHT_PAREN ARROW expression                   #lambda

I still don't have a good guess about the level of difficulty here.

**Comment by deugene** [comment]
Any news on this? There are lots of lambda functions available in spark/databricks dialect. I cannot imagine how databricks dialect might be usable with sqlfluff without the support of '->' symbol. We use Postgres dialect with databricks SQL files as a workaround, but this approach has a lot of downsides for obvious reasons.

**Comment by barrywhart** [comment]
We always welcome new contributors. All the developers are volunteers, often with their own priorities.

**Comment by juhoautio** [comment]
@deugene FYI I've opened a PR that implements this

**Comment by barrywhart** [comment]
Kudos to @juhoautio for implementing this.
