### ISSUE TITLE
Unexpected exception "TypeGaurd: Segement Must exist Must exist"

### ISSUE THREAD

**Issue by jasper-eljakim** [sqlfluff/sqlfluff#3392]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### What Happened

Executed `sqlfluff lint` but it gave an exception

```
➜ sqlfluff lint file.sql --dialect mysql
CRITICAL   [L049] Applying rule L049 threw an Exception: TypeGaurd: Segement Must exist Must exist                                                                                                                                        
Traceback (most recent call last):
  File "/home/jasper/.local/lib/python3.8/site-packages/sqlfluff/core/rules/base.py", line 644, in crawl
    res = self._eval(context=context)
  File "/home/jasper/.local/lib/python3.8/site-packages/sqlfluff/rules/L049.py", line 82, in _eval
    assert sub_seg, "TypeGaurd: Segement Must exist Must exist"
AssertionError: TypeGaurd: Segement Must exist Must exist
== [file.sql] FAIL                                                                                                                                
L:   1 | P:   1 | L049 | Unexpected exception: TypeGaurd: Segement Must exist
                       | Must exist; Could you open an issue at
                       | https://github.com/sqlfluff/sqlfluff/issues ? You can
                       | ignore this exception for now, by adding '-- noqa: L049'
                       | at the end of line 1
L:   1 | P:  11 |  PRS | Line 1, Position 11: Found unparsable section: '(SELECT
                       | id FROM table WHERE field = TRUE...'
All Finished 📜 🎉!
```

### Expected Behaviour

No exception but maybe errors or warnings on the line when needed

### Observed Behaviour

The program died where it should not have.

### How to reproduce

My file contained multiple lines, but died on the first one:

```sql
SET @id = (SELECT id FROM table WHERE field = TRUE LIMIT 1);

UPDATE other_table SET foreign_key = @id WHERE foreign_key IS NULL;
```

### Dialect

mysql

### Version

➜  sqlfluff --version
sqlfluff, version 0.13.2
➜  python --version
Python 3.8.10

### Configuration

the default config

### Are you willing to work on and submit a PR to address the issue?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by mdahlman** [comment]
I see what's going. First, `table` is a reserved keyword in MySQL. So your set statement should instead be something like this single statement to avoid that unrelated complication:
```SET @id = (SELECT id FROM table1 WHERE field = TRUE LIMIT 1);```

Next, the linting error is an effect of a parsing error.

So this test identifies the initial problem:
```echo "SET @id = (SELECT id FROM table1 WHERE field = TRUE LIMIT 1);" | sqlfluff parse --dialect mysql -
--or even this more minimal version:
echo "SET @id = (SELECT 1);" | sqlfluff parse --dialect mysql -
```

This is a one-line fix in the MySQL dialect. I'm going to investigate now.
