### ISSUE TITLE
[postgres] Support for CREATE TYPE

### ISSUE THREAD

**Issue by ancoron** [sqlfluff/sqlfluff#341]
Please add support for `CREATE TYPE` in PostgreSQL dialect.
* https://www.postgresql.org/docs/current/sql-createtype.html

Simple example:
```sql
CREATE TYPE my_enum AS ENUM ('value');
```

**Comment by alanmcruickshank** [comment]
Yep. Good postgres feature we should add.

We should make sure whatever is added to the postgres dialect for this doesn't filter through to the snowflake dialect which depends on this as this isn't supported there.
