### ISSUE TITLE
Exit 0 when there are only unfixable violations

### ISSUE THREAD

**Issue by soares7vinicius** [sqlfluff/sqlfluff#3415]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### Description

Is there a way of setting SQLFLuff to return exit code 0 when there are just unfixable violations?
I'm facing a problem when using it inside a pre-commit hook and it never lets me do commit because the hook always returns 1.

<img width="567" alt="image" src="https://user-images.githubusercontent.com/12590152/171512309-092e5dff-9b4e-4b85-8852-2e59132c2918.png">

### Dialect

bigquery with dbt templater

### Are you willing to work on and submit a PR to address the issue?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by tunetheweb** [comment]
My advice here is to do one of the following (if decreasing order of preference):
1. Disable the rule if you don’t want to check for this issue.
2. Manually fix the problematic code.
3. `noqa` the problematic code if you want to ignore this particular instance in this particular SQL file.
4. Force commit using `--no-verify` if you don’t want to do any of the above for now.

To (incorrectly!) return a 0 exit code when there are issues, seems counterintuitive to the point of linking code with the rules you’ve set up to me.
