### ISSUE TITLE
[postgres] Support CREATE SCHEMA

### ISSUE THREAD

**Issue by ancoron** [sqlfluff/sqlfluff#342]
Please support `CREATE SCHEMA` for the PostgreSQL dialect:
* https://www.postgresql.org/docs/current/sql-createschema.html

Simple failing example:
```sql
CREATE SCHEMA api;
```

Common use-cases:
* logical tenant separation
* [PostgREST](http://postgrest.org/en/v7.0.0/tutorials/tut0.html#step-4-create-database-for-api)

**Comment by alanmcruickshank** [comment]
Yep. I think this should actually be implemented as a more general case of `CREATE <object>` which I think could cover `CREATE SCHEMA` but also `CREATE WAREHOUSE` and `CREATE DATABASE` (for snowflake users) and potentially event `CREATE ROLE` , `CREATE USER` or `CREATE GROUP` unless any of them have significant other functionality that we need to add.

**Comment by alanmcruickshank** [comment]
This was addressed in #772 . I'm going to close this issue.
