### ISSUE TITLE
Allow config for L036 to allow wildcard on same line

### ISSUE THREAD

**Issue by tunetheweb** [sqlfluff/sqlfluff#3425]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### Description

#3422 corrected a bug L036 to match the docs. However this is a change in behaviour so think we should make it configurable to work as it used to.

### Use case

Allow people to continue to use L036 as they used to.

### Dialect

All

### Are you willing to work on and submit a PR to address the issue?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by barrywhart** [comment]
@tunetheweb: Any suggestions for what to call this setting?

**Comment by barrywhart** [comment]
One possibility: `wildcard_policy` with possible values:
* `single`
* `multiple`

**Comment by tunetheweb** [comment]
`treat_wildcard_as_single_item`? Defaulting to `false`?

**Comment by tunetheweb** [comment]
Your suggestion works too.
