### ISSUE TITLE
[postgres] Support schema-qualified column data type

### ISSUE THREAD

**Issue by ancoron** [sqlfluff/sqlfluff#343]
All objects in PostgreSQL may be schema-qualified to ensure addressing a specific version, should an object with the same name exist in a schema that might be searched first.

In case of column data types, this fails:
```sql
CREATE TABLE counters (
    my_type public.MY_TYPE
);
```
...with:
```
== [db/test.sql] FAIL
L:   1 | P:   1 |  PRS | Found unparsable section: 'CREATE TABLE counters (\n
                       | my_type publ...'
```

**Comment by alanmcruickshank** [comment]
Interesting! I wasn't aware of this capability.

Are you aware of whether this exists in any other common dialects or whether we should address this as strictly a postgres feature?

(My assumption is most of the other issues you've raised would be part of the root ansi dialect, but this might be the exception).

**Comment by ancoron** [comment]
AFAICT, this should be possible for any dialect that supports multiple schemas or namespaces inside a single database. At least [SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/statements/create-table-transact-sql?view=sql-server-ver15) (look for `<data_type>` definition) also supports this.

**Comment by barrywhart** [comment]
AFAICT, it is not supported by:
* [MySQL](https://dev.mysql.com/doc/refman/8.0/en/create-table.html): See `column_definition`
* [BigQuery](https://cloud.google.com/bigquery/docs/reference/standard-sql/data-definition-language#column_name_and_column_schema)
* [Snowflake](https://docs.snowflake.com/en/sql-reference/sql/create-table.html)
