### ISSUE TITLE
[postgres] Support Postgres dollar quoting ($$)

### ISSUE THREAD

**Issue by ancoron** [sqlfluff/sqlfluff#347]
Please support parsing of `CREATE FUNCTION` in PostgreSQL dialect:
* https://www.postgresql.org/docs/current/sql-createfunction.html

Simple failing example:
```sql
CREATE FUNCTION add(integer, integer) RETURNS integer
    AS 'select $1 + $2;'
    LANGUAGE SQL
    IMMUTABLE
    RETURNS NULL ON NULL INPUT;
```

...results into:
```
== [db/test.sql] FAIL
L:   1 | P:   1 |  PRS | Found unparsable section: 'CREATE FUNCTION add(integer,
                       | integer) RE...'
```

**Comment by alanmcruickshank** [comment]
There's a PR in progress for this one already #325. I'm hoping this should be sorted soon.

**Comment by barrywhart** [comment]
PR #325 took a while to get working, but it is ready for review now. @ancoron, would you like to test or review the PR to see if it meets your needs? I think it is close, i.e. this works okay:

```
CREATE FUNCTION add(integer, integer) RETURNS integer
    AS 'select $1 + $2;'
    LANGUAGE SQL;
```

But I think we'll need some additional Postgres-specific dialect enhancements to support the additional syntax:
```
    IMMUTABLE
    RETURNS NULL ON NULL INPUT
```

**Comment by osvenskan** [comment]
Perhaps this should be its own issue, but it would be nice to support Postgres  dollar quoting which is a pretty common technique for delimiting function definitions --
```
CREATE FUNCTION foo(integer, integer) RETURNS integer
    AS $$ select $1 + $2; $$
    LANGUAGE SQL;
```

https://www.postgresql.org/docs/current/sql-syntax-lexical.html#SQL-SYNTAX-DOLLAR-QUOTING

**Comment by jankatins** [comment]
We use that '$$' quoting extensively, also as $anychars$<here the string>$anychars$" to make it even easier to do stuff like 

```
CREATE FUNCTION foo(integer, integer) RETURNS TEXT
    AS $f$
BEGIN
   EXECUTE $exec$SELECT $s$I'm a String with "double" and 'single' quotes in it...$s$;$exec$; 
END
 $f$   LANGUAGE 'plpgsql';
```
(didn't check if this compiles, but the quote/dollar pattern is what we use...)

**Comment by barrywhart** [comment]
I'll change the title of this issue to reflect the new goal.
