### ISSUE TITLE
[postgres] Support CREATE ROLE

### ISSUE THREAD

**Issue by ancoron** [sqlfluff/sqlfluff#349]
Please support `CREATE ROLE` in the PostgreSQL dialect:
* https://www.postgresql.org/docs/current/sql-createrole.html

Simple failing example:
```sql
CREATE ROLE web_anon nologin;
```
...results into:
```
== [db/test.sql] FAIL
L:   1 | P:   1 |  PRS | Found unparsable section: 'CREATE ROLE web_anon nologin'
```

**Comment by alanmcruickshank** [comment]
Yep - `CREATE ROLE` hasn't been touched yet. This needs adding. I think this would be good to tackle at the same time as #350.
