### ISSUE TITLE
Is any batch mode option to skip questions ?

### ISSUE THREAD

**Issue by borgogelli** [sqlfluff/sqlfluff#3530]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### What Happened

After a few errors, sqlfluff prints the following question: "Parsing errors were found and the dialect is set to 'ansi'. Have you configured the dialect correctly?"
This is definitely a problem for a non-interactive environment such as a CI pipeline.

### Expected Behaviour

It would be useful a cli option to skip every interactive input requests

### Observed Behaviour

(see above)

### How to reproduce

Can be reproduced with any sql file full of errrors. :-)

### Dialect

ansi

### Version

version 1.0.0

### Configuration

(no configuration)

### Are you willing to work on and submit a PR to address the issue?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by tunetheweb** [comment]
That's not an interactive request/question, but an error. There is no expectation (or even way) to respond to that on the command line, other than by fixing your SQL (or raising an issue here if it's correct SQL but SQLFluff is unable to parse it when it should).

You can ignore parsing errors with `--ignore parsing` but that means the SQL is not being linted and sqlfluff will also exit 0, which is probably not what you want.

Also are you sure you should be using the `ansi` dialect and there is not a better one for your needs?

**Comment by borgogelli** [comment]
@tunetheweb you're right there aren't any interactive questions and my Jenkins pipeline stop because I have missed to indicate the sql file and sqlstuff starts linting all the files in path.

`sqlfluff lint --verbose --dialect ansi --disable_progress_bar`

![image](https://user-images.githubusercontent.com/7045594/176877456-d6d67f9a-0456-42f4-bd2d-4f58e3a9d89c.png)

Strange behaviour but It could be caused by other files on my file system path. So I close the issue.
Thank you very much.

PS: I use the ansi dialect because I adopt Firebird dbms for my project
