### ISSUE TITLE
Automatically skip linting files over a certain size

### ISSUE THREAD

**Issue by barrywhart** [sqlfluff/sqlfluff#3537]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### Description

SQLFluff `lint` and `fix` commands should do an up-front file size check, and if it's longer than X, just print a message saying, "we're skipping this file". Code editors sometimes do this, and SQLFluff should, too. This avoids confusing users, who frequently try to lint large files and then report an issue saying SQLFluff is hanging.

We should make the limit variable, perhaps defaulting it to 500 or 1,000 lines.

### Use case

n/a

### Dialect

n/a

### Are you willing to work on and submit a PR to address the issue?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by fmms** [comment]
@barrywhart maybe it would make sense to add a timeout instead?

To my understanding it is not really the lines of a file that make sqlfluff slow.

I have CREATE TABLE statements with 1000 rows. Those are linted quickly.
It seems to be the query complexity.

I would be happy to have a --maximum-seconds-per-file parameter that skips a file if the fixing process took longer than e.g. 60 seconds ...

**Comment by barrywhart** [comment]
We could look into it, but timeouts are not gracefully supported for in-process code, only for network calls. I have in one case used some ugly code that simulated pressing Control-C after a certain amount of time. 🤢😳

**Comment by fmms** [comment]
As there is the —processes option I assumed there is some control thread kicking of the parallelism that could abort the process on one file. 
i just believe most/all people just are afraid of too long execution when either formatting lots of files or in ci/cd scenarios ..

**Comment by alanmcruickshank** [comment]
> @barrywhart maybe it would make sense to add a timeout instead?

I agree timeout would be better, but only viable in the case that someone is running with the parallel (`-p`) option. We could *also* add that option too for users who wanted more control?

**Comment by alanmcruickshank** [comment]
I'm happy to pick this one up - I might actually aim for a _character_ limit rather than a _line_ limit because that's a) slightly easier and b) more representative of complexity.
