### ISSUE TITLE
Add `"INTEGER"` to `PrimitiveTypeSegment` for Sparksql

### ISSUE THREAD

**Issue by ciwassano** [sqlfluff/sqlfluff#3554]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### Description

Add "INTEGER" to the match_grammar list. Sparksql also supports integer.
https://github.com/sqlfluff/sqlfluff/blob/dc22a21c01173a356f9e3c220068ba1c785867f9/src/sqlfluff/dialects/dialect_sparksql.py#L641

### Dialect

sparksql

### Are you willing to work on and submit a PR to address the issue?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by greg-finley** [comment]
Closed by https://github.com/sqlfluff/sqlfluff/pull/3624
