### ISSUE TITLE
sparksql: Add support for `qualify` statement 

### ISSUE THREAD

**Issue by eetu-h** [sqlfluff/sqlfluff#3555]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### Description

Databricks supports [qualify clause](https://docs.databricks.com/sql/language-manual/sql-ref-syntax-qry-select-qualify.html) with ordered analytical functions. However sqlfluff w/ sparksql dialect is not parsing the qualify clause properly.

```sql
select 'a' as my_field
from testdb.testtable
qualify sum(1) over (partition by my_field) > 0
```

```
L:   1 | P:   1 |  PRS | Line 3, Position 9: Found unparsable section: 'sum(1) over (partition by my_field) > 0'
L:   3 | P:   3 | L011 | Implicit/explicit aliasing of table.
L:   3 | P:   3 | L025 | Alias 'qualify' is never used in SELECT statement.
L:   3 | P:   3 | L029 | Keywords should not be used as identifiers.
```

```
[sqlfluff]
dialect = sparksql
```

### Dialect

sparksql (databricks)

### Are you willing to work on and submit a PR to address the issue?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by tunetheweb** [comment]
Can copy the `QualifyClauseSegment` from a few other dialects that support this. Maybe we should add to ANSI dialect since it's common to quite a few dialects?
