### ISSUE TITLE
Per file dialect selection

### ISSUE THREAD

**Issue by Clepech** [sqlfluff/sqlfluff#3559]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### Description

Allow dialect selection per sql file.

The dialect could be declared as a header comment in each file, For example:

```sql
-- sqlfluff dialect : postgres

SELECT * FROM table
```

This declaration will override general configuration

### Use case

We run sqlfluff on a repo containing many SQL files with different dialects. Our current use is to set sqlfluff (as a pre-commit) with the most used dialect and ignore other dialects. This request aims to run sqlfluff on currently ignored files.

### Dialect

All dialect

### Are you willing to work on and submit a PR to address the issue?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by tunetheweb** [comment]
Best practice would surely be to separate the files into different folders?:

- `sql/postgres/`
- `sql/bigquery/`

Within eaxch folder you could have a `.sqlfluff` file that sets the dialect and, at the top level, `sql` folder you could have a common `.sqlfluff` with the rest of the config.

**Comment by anneadb** [comment]
This feature would be useful for my team as well: We have a lot of data processing pipelines that have stages in multiple separate database systems. It would not make sense to have subfolders depending on the dialect for each pipeline. Plus, then we would need to copy paste the .sqlfluff configuration file into each folder instead of defining it for an entire project.

**Comment by tunetheweb** [comment]
> Plus, then we would need to copy paste the .sqlfluff configuration file into each folder instead of defining it for an entire project.

That's not true. Maybe my comment above wasn't clear, but as SQLFluff supports inheritance of config, you can set it up like this:"

- `sql/.sqlfluff` -- common sqlfluff config (lots of lines)
- `sql/postgres/.sqlfluff` -- a simple, 2-line config file setting the dialect to set it to postgres
- `sql/postgres/postgres-sql-file1.sql`
- `sql/postgres/postgres-sql-file2.sql`
- ...
- `sql/bigquery/.sqlfluff` -- a simple, 2-line config file setting the dialect to bigquery
- `sql/bigquery/postgres-sql-file1.sql`
- `sql/bigquery/bigquery-sql-file2.sql`
- ...

**Comment by anneadb** [comment]
Ah, I guess if you make the split at the very top level of your file structure that is possible. 
But our file structure would be more like this:

* `project1/pipeline1/postgres`
* `project1/pipeline1/bigquery`
* ...
* `project1/pipeline9/postgres`
* `project1/pipeline9/bigquery`
* `project2/pipeline1/postgres`
* `project2/pipeline1/bigquery`
* ...
* `project9/pipeline1/postgres`
* `project9/pipeline1/bigquery`
* ...

**Comment by Clepech** [comment]
In our case, we use Airflow. All our SQL files are located in the same folder as the Airflow dags file they are used. Our project is  split by business domain, and looks like this:

- `project/customers/pipeline1/postgres_stuff.sql`
- `project/customers/pipeline1/dag.py`
- `project/customers/pipeline2/bigquery_stuff.sql`
- `project/customers/pipeline2/dag.py`
- `project/customers/pipeline3/bigquery_stuff.sql`
- `project/customers/pipeline3/dag.py`


- `project/bills/pipeline1/postgres_stuff.sql`
- `project/bills/pipeline1/dag.py`
- `project/bills/pipeline2/bigquery_stuff.sql`
- `project/bills/pipeline2/dag.py`

So it's not really an option to group SQL files by dialect

**Comment by adam-tokarski** [comment]
So apparently basing on directory structure is not enough. Another solution could be to guess dialect by file name prefix (ike `biqguery` for `bigquery_stuff.sql`, `postgres` for `postgres_stuff.sql`, etc., but I guess it may be tedious in longer run to rename (properly) all files. Using specific header in file seems like something more declarative.

@tunetheweb do you think that this proposed
```sql
-- sqlfluff dialect : postgres
```
will be fine solution?

**Comment by LauraRichter** [comment]
+1 on this solution for us too - a header in the file would be great

**Comment by anneadb** [comment]
Thanks for implementing this feature!
In case anyone else comes across this, you can now easily configure a dialect per file: simply add e.g. `-- sqlfluff:dialect:redshift` at the top of your `.sql` file. This will overwrite the default dialect that you have e.g. in `pyproject.toml`.

**Comment by 9128305** [comment]
Is it really working?
I have at the top `-- sqlfluff:dialect:postgres` and `sqlfluff lint|fix|format` fail with `User Error: No dialect was specified.....`

**Comment by KingBain** [comment]
ran into this issue, had -- sqlfluff:dialect:postgresin my sql but was being ignored


For others googling to get here  **cli still requires to provide --dialect option**
