### ISSUE TITLE
Allow trailing comma in the last item on SELECT list

### ISSUE THREAD

**Issue by moseleyi** [sqlfluff/sqlfluff#3586]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### Description

I would like to allow the following:

```
SELECT
  item,
  item2,
  item3,
FROM table
```

So that the last item on the list in SELECT statement can have a trailing comma. How to achieve that?

### Dialect

BigQuery

### Are you willing to work on and submit a PR to address the issue?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by tunetheweb** [comment]
Use this config:

```
[sqlfluff:rules:L038]
# Trailing commas
select_clause_trailing_comma = require
```

Note we currently only have `forbid` or `require` for this rule.

If you want to be more lax about this (i.e. allow it if people use it, but not insist upon it), then just add L038 to your `exclude_rules` list so this is not checked.

Closing this, but let us know if that's not clear.
