### ISSUE TITLE
Blocklisting SQL vendor specific data types

### ISSUE THREAD

**Issue by ericxiao251** [sqlfluff/sqlfluff#361]
Following Simon Holywell's SQL Style Guide, it would be nice to have a lint rule that you can config to check for SQL data types used in the query.

I.e. In BigQuery you can use the keyword `BOOL` or `BOOLEAN` to represent a boolean type, the lint rule could blacklist one of those and enforce only a single keyword.

**Comment by alanmcruickshank** [comment]
I like this rule. I think it would be best if sqlfluff could be opinionated about *which* of the available options is preferred too. From my perspective I would find this really useful with snowflake string types where `STRING`, `TEXT`, `CHAR` and `VARCHAR` are all equivalent.

@ericxiao251 do you expect there is enough consensus for us to come up with the preferred options for the main dialects? If you're able to suggest the preferred versions for bigquery that would be a great.

As a sniff test, if you and @barrywhart can come to an agreement without too much argument for what the preferred set for bigquery is then I'm happy to roll this out in the next release.

**Comment by barrywhart** [comment]
BigQuery may be different in this respect -- it has `STRING` and `BYTES` types, but none of the other types you mention. https://cloud.google.com/bigquery/docs/reference/standard-sql/data-types#string_type

I think Mailchimp data scientists would be open to either option for Boolean columns. I do see that the officlal BigQuery [docs](https://cloud.google.com/bigquery/docs/reference/standard-sql/data-types#boolean_type) list it as `BOOL` without mentioning `BOOLEAN`, so I'd suggest going with `BOOL`.

**Comment by ericxiao251** [comment]
@alanmcruickshank, my initial thoughts are no, and my answer is based on a preliminary look at the data types in:
* BigQuery [data types link](https://cloud.google.com/bigquery/docs/reference/standard-sql/data-types#integer_type)
* Snowflake [data types link](https://docs.snowflake.com/en/sql-reference/data-types-datetime.html)
* Redshift [data types link](https://docs.aws.amazon.com/redshift/latest/dg/c_Supported_data_types.html)
* Presto [data types link](https://prestodb.io/docs/current/language/types.html)
* PostgresSQL [data types link](https://www.postgresql.org/docs/9.5/datatype.html)

I think there is a big difference in naming between `numerical` and `character` types in each SQL dialect.

For example:
* For `numerical` types in BigQuery some of them are suffixed with `64` (i.e. `INT64`, `FLOAT64`).
* For `character` types in BigQuery, there is only a `STRING` type which is equivalent to a `VARCHAR` in other languages.

For `datetime` types I think we might be able to come to a consensus as they are more aligned. They all seem to support at least 2 of 4:
* `DATE`
* `DATETIME`
* `TIME`
* `TIMESTAMP`

Where some support varieties of `TIMESTAMP` such as `TIMESTAMP_ABC` where `ABC` is signifies that there is a timezone component as well. But `TIMESTAMP` is an alias for varieties. So we could make a rule to only use `TIMESTAMP` and not the variants.

**Comment by ericxiao251** [comment]
@barrywhart that is a fair point, but from looking at other SQL dialects (Presto, Snowflake, Redshift) `BOOLEAN` is more commonly used, so I would argue for using `BOOLEAN` actually.

**Comment by barrywhart** [comment]
I wonder if there's much value in having recommended types across databases. Would it be reasonable to have a list per dialect?

**Comment by ericxiao251** [comment]
That's what I am leaning towards as well. If we do come up with a list, it would be a very short list and I don't think there's much value in that.

This would also require some sort of CLI flag to dictate what dialect we are testing against and I am not aware that sqlfluff has that as an option currently? 

Would this also deviate from sqlfluff being a "generic sql linter", I am not sure if that was the intentions or not (still new to sqlfluff).

**Comment by barrywhart** [comment]
There are necessarily parts of the grammar which are specific to certain databases.

My mental model is that it's a generic core that supports db-specific specializations.

**Comment by barrywhart** [comment]
Oh yes -- there is a --dialect command-line option, and you can also set it in the .sqlfluff configuration file.

**Comment by aaronsteers** [comment]
I'm late to this discussion, but I agree strongly with the premise that support for a single explicit preference is generally preferable to ambiguity, and it's preferrable to not have both BOOL and BOOLEAN used in the same codebase (or worse, in the same file).

I actually want to propose another possible guiding principle here, which could be:

* prefer ANSI types and formulas when those are functionally identical to the db-specified type.

I've been similarly considering in my team to disallow the legacy and platform-specific `ISNULL()` and `IFNULL()` functions in preference of the ubiquitous and multi-arg `COALESCE()`. I've just reviewed code today where `IFNULL()` and `COALESCE()` are both used in the same file. My preference would be to be ANSI compliant (and portable to a broader range of developers) unless there's some significant reason not to do so.

Also would prefer the ANSI-compliant CAST(myval as int) over myval::int which is less portable and (imho) not any more readable.

**Comment by alanmcruickshank** [comment]
For the purposes of this issue I think we should focus just on the _datatype_ issue, but follow the thinking of what @aaronsteers suggests. 

...however...

I'm trying to enumerate the actual changes we would enforce, so far I've got:
- `BOOL` -> `BOOLEAN`
- On snowflake, `REAL`, `DOUBLE`, `DOUBLE PRECISION` -> `FLOAT`
- On snowflake, `INT`, `INTEGER`, `BIGINT`, `SMALLINT`, `DECIMAL`, `NUMERIC` -> `NUMBER`
- On snowflake, `CHAR`, `STRING`, `TEXT`, `CHARACTER` -> `VARCHAR`

I realise in this case snowflake is a bit of an oddity in having so few underlying datatypes, but actually a lot of aliases.

I'm scratching my head of other examples though. Any ideas?

**Comment by alanmcruickshank** [comment]
I'm not sure we've got enough clarity on what we want to do here to target this for the 0.4.0 release. I'm going to move this to the pipeline for 0.5.0

**Comment by alanmcruickshank** [comment]
I'm going to suggest we close this issue. I don't think there's enough consensus or a clear aim for how this rule would work.

If anyone disagrees, now would be a good time for suggestions on how we move forward - I'll leave it open for another few weeks and then close it if nobody shouts.

**Comment by tunetheweb** [comment]
Rather than trying to have an opinionated setup of what should be allowed it not, we could just have a new rule which blocks a list of, user configurable, words. So you could configure it to block `BOOL` or `BOOLEAN` (or both if feeling crazy!), or `IFNULL` or whatever. Maybe you want to block a specific table or schema that should be used anymore?

They should be allowed as part of other words (so blocking `BOOL` doesn’t block `BOOLEAN` too).

There’s quite some power to make SQLFluff quite configurable with that. though a bit different than our other rules which are often more opinionated rather than a blank slate like here.

**Comment by alanmcruickshank** [comment]
I like that idea - we'd have to be a little careful on how we set the defaults so that they're dialect aware - but that feels like a nice suggestion on how to implement this.

**Comment by tunetheweb** [comment]
Closed by #2540
