### ISSUE TITLE
Create rule to ignore long Jinja comments

### ISSUE THREAD

**Issue by kieronellis** [sqlfluff/sqlfluff#3618]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### Description

Add rule that long Jinja comments can be ignored.

As indicated [here](https://github.com/sqlfluff/sqlfluff/issues/1439), Jinja comments which are too long cannot be fixed and result in an `unfixable linting violations found` message. As such, it would be great if a rule could be added to ignore these.

There is already a rule `ignore_comment_clauses` so my suggestion would be to add another rule, e.g. `ignore_jinja_comment_clauses`.

### Dialect

I am using BigQuery

### Are you willing to work on and submit a PR to address the issue?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by tunetheweb** [comment]
Personally I think this should just be part of `ignore_comment_clauses` and doesn't necessarily need a separate config or rule.
