### ISSUE TITLE
Standardise `--disable_progress_bar` naming

### ISSUE THREAD

**Issue by tunetheweb** [sqlfluff/sqlfluff#3644]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### What Happened

As noted in https://github.com/sqlfluff/sqlfluff/pull/3610#discussion_r926014745 `--disable_progress_bar` is the only command line option using underscores instead of dashes.

Should we change this?

This would be a breaking change, so do we leave until next major release?
Or do we accept both options?

### Expected Behaviour

We should be standard in out command line option format

### Observed Behaviour

`--disable_progress_bar` is the only non-standard one

### How to reproduce

N/A

### Dialect

N/A

### Version

1.2.1

### Configuration

N/A

### Are you willing to work on and submit a PR to address the issue?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by alanmcruickshank** [comment]
I like the idea (of at least as a transition) or accepting both, but then defaulting to the one consistent with the other options.

**Comment by tunetheweb** [comment]
> So this is about changing option `--disable_progress_bar` to `--disable-progress-bar`, right? I think I can take care of that, it was me who introduced it here :)

Correct and thanks for taking on

> Additionally I would make an attempt to have these two options available, but to nicely inform users that one with underscores is deprecated. What do you think @tunetheweb?

@alanmcruickshank added some functionality that might help in #3874 but not sure if that applies to command lines options too (I’m having less time to work on SQLFluff lately so not following it as closely as I used to). If not maybe it should?

> I see I cannot assign myself to that Issue.

Yeah only maintainers can assign, which is a bit of an annoying restriction of GitHub so we tend not to use that field and commenting (like you’ve done here) is sufficient to claim an issue. Please comment again if to “unassign” yourself if it turns out you won’t be able to work on it after all. Though usually lack of progress is a good indicator of that 😄
