### ISSUE TITLE
partition is not a snowflake reserved keyword.

### ISSUE THREAD

**Issue by kibradley123** [sqlfluff/sqlfluff#3670]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### What Happened

We are using `sqlfluff` with templater `dbt` and dialect `snowflake`. 
Naming a column 'PARTITION' causes a parsing error. 
`PARTITION BY` is a reserved keyword but not the word partition itself see snowflake docs: https://docs.snowflake.com/en/sql-reference/reserved-keywords.html
It is even the suggested column name for partitioning when using external tables. Can this be updated?

### Expected Behaviour

No error is thrown by pre-commit hooks running sqlfluff with templater dbt and dialect snowflake when a column is named partition.

### Observed Behaviour

error is currently  thrown:
<img width="811" alt="Screenshot 2022-07-26 at 11 25 42" src="https://user-images.githubusercontent.com/109590138/181025023-a6245f2d-7c0f-4514-b32c-4d3a97eed5c6.png">
n

### How to reproduce

Using the .sqlfluff below try to create a table with a column named 'partition'

### Dialect

dbt-snowflake

### Version

1.2.1

### Configuration

[sqlfluff]
dialect = snowflake
templater = dbt
exclude_rules = L031, L034, L039,  L036, L044, L013, L014

[sqlfluff:templater:dbt]
project_dir = ./booking/
profiles_dir =./booking/

[sqlfluff:rules]
tab_space_size = 4
max_line_length = 100

[sqlfluff:rules:L010]
# Keywords
capitalisation_policy = upper

[sqlfluff:rules:L030]
# Function names
capitalisation_policy = upper

[sqlfluff:rules:L040]
# Null & Boolean Literals
capitalisation_policy = upper

[sqlfluff:rules:L057]
# Special Characters in Identifiers
allow_space_in_identifier = True
additional_allowed_characters = ['.','(',')','-']

target/
# dbt <1.0.0
dbt_modules/
# dbt >=1.0.0
dbt_packages/
macros/

### Are you willing to work on and submit a PR to address the issue?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by greg-finley** [comment]
Do you have a small complete SQL statement that would reproduce this issue? We should put it in a test file to ensure the proper behavior. i.e.: https://github.com/sqlfluff/sqlfluff/blob/c1e9bce86d52cb600297987a4d9ed36f20d4a6c9/test/fixtures/dialects/snowflake/snowflake_create_table.sql#L12
