### ISSUE TITLE
Indentation after CROSS APPLY is messed up with dialect T-SQL

### ISSUE THREAD

**Issue by borchero** [sqlfluff/sqlfluff#3672]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### What Happened

When formatting a query containing a `CROSS APPLY` expression, all lines after the `CROSS APPLY` expression are wrongly indented by an additional indentation.

### Expected Behaviour

```sql
SELECT
    table1.col,
    table2.col
FROM table1
CROSS APPLY (
    VALUES ((1), (2))
) AS table2(col)
-- Expected: no additional indentation after running `sqlfluff fix`
INNER JOIN table3
    ON table1.col = table3.col;
```

### Observed Behaviour

```sql
SELECT
    table1.col,
    table2.col
FROM table1
CROSS APPLY (
    VALUES ((1), (2))
) AS table2(col)
-- Additional indentation after formatting via `sqlfluff fix`!
    INNER JOIN table3
        ON table1.col = table3.col;
```

### How to reproduce

Format the above query with `sqlfluff fix`.

### Dialect

T-SQL

### Version

- `sqlfluff, version 1.2.1` (installed via homebrew)

### Configuration

```
[sqlfluff]
dialect = tsql
```

### Are you willing to work on and submit a PR to address the issue?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by borchero** [comment]
Happy to submit a PR, but could you provide some support maybe @tunetheweb? 😅

**Comment by tunetheweb** [comment]
This was actually requested by @jpers36 in #2676 and is implemented here:

https://github.com/sqlfluff/sqlfluff/blob/7a40bf6e4dad0d5f80523e077c8a20c0aa9bc987/src/sqlfluff/dialects/dialect_tsql.py#L386-L390

Is there a way of differentiating whether this is a nested join or not? Or is this a nested and you just don't wan't it to indent (in which case we'd need to add a new indent config for this).

**Comment by borchero** [comment]
Mhh I see, didn't know about the nested join statement in T-SQL... as far as I can tell, SQLFluff interprets a JOIN as nested if the previous statement does not have an `ON` clause. However, this does not always make sense, namely for `CROSS JOIN` and `CROSS APPLY` clauses. In these cases, the subsequent JOIN should not be treated as nested.

With the knowledge of nested joins, this issue should rather be about fixing SQLFluff to interpret joins after `CROSS JOIN` and `CROSS APPLY` as nested.

FYI: The example query is not actually a nested join statement so no need to add a new config.

**Comment by tunetheweb** [comment]
OK so it seems `CROSS JOIN` and `CROSS APPLY` are basically the same as `NATURAL joins` since they do not support join conditions?

So here's what I think you need to do:

1. Remove `"CROSS"` as a normal join keyword in T-SQL.

Easiest way to do that is to define this section as a new Grammar (maybe called `PreJoinGrammar`? Or a better phrase you can think of):

https://github.com/sqlfluff/sqlfluff/blob/7a40bf6e4dad0d5f80523e077c8a20c0aa9bc987/src/sqlfluff/dialects/dialect_ansi.py#L1471-L1483

Override this in T-SQL to have the same definition, but without the `"CROSS"` keyword.

2. Add "CROSS" to `NaturalJoinKeywordsGrammar` in T-SQL (currently set to `Nothing()`) so it falls into the second, Natural, section of `JoinClauseSegment`

3. Add a test case (and check none of the current ones fail).

And that should be it.

Here's the diff of when I tried that:

```diff
(.venv) 16:43:59 ~/sources/sqlfluff main $ git diff                                                    
diff --git a/src/sqlfluff/dialects/dialect_ansi.py b/src/sqlfluff/dialects/dialect_ansi.py
index c6362c55..c05d640e 100644
--- a/src/sqlfluff/dialects/dialect_ansi.py
+++ b/src/sqlfluff/dialects/dialect_ansi.py
@@ -546,6 +546,19 @@ ansi_dialect.add(
         "FILTER", Bracketed(Sequence("WHERE", Ref("ExpressionSegment")))
     ),
     FrameClauseUnitGrammar=OneOf("ROWS", "RANGE"),
+    PreJoinKeywordsGrammar=OneOf(
+        "CROSS",
+        "INNER",
+        Sequence(
+            OneOf(
+                "FULL",
+                "LEFT",
+                "RIGHT",
+            ),
+            Ref.keyword("OUTER", optional=True),
+        ),
+        optional=True,
+    ),
     # It's as a sequence to allow to parametrize that in Postgres dialect with LATERAL
     JoinKeywordsGrammar=Sequence("JOIN"),
     # NATURAL joins are not supported in all dialects (e.g. not in Bigquery
@@ -1468,19 +1481,7 @@ class JoinClauseSegment(BaseSegment):
     match_grammar: Matchable = OneOf(
         # NB These qualifiers are optional
         Sequence(
-            OneOf(
-                "CROSS",
-                "INNER",
-                Sequence(
-                    OneOf(
-                        "FULL",
-                        "LEFT",
-                        "RIGHT",
-                    ),
-                    Ref.keyword("OUTER", optional=True),
-                ),
-                optional=True,
-            ),
+            Ref("PreJoinKeywordsGrammar"),
             Ref("JoinKeywordsGrammar"),
             Indent,
             Sequence(
diff --git a/src/sqlfluff/dialects/dialect_tsql.py b/src/sqlfluff/dialects/dialect_tsql.py
index 9e397c35..598dc208 100644
--- a/src/sqlfluff/dialects/dialect_tsql.py
+++ b/src/sqlfluff/dialects/dialect_tsql.py
@@ -384,8 +384,20 @@ tsql_dialect.replace(
         ),
         Sequence(OneOf("IGNORE", "RESPECT"), "NULLS"),
     ),
+    PreJoinKeywordsGrammar=OneOf(
+        "INNER",
+        Sequence(
+            OneOf(
+                "FULL",
+                "LEFT",
+                "RIGHT",
+            ),
+            Ref.keyword("OUTER", optional=True),
+        ),
+        optional=True,
+    ),
     JoinKeywordsGrammar=OneOf("JOIN", "APPLY", Sequence("OUTER", "APPLY")),
-    NaturalJoinKeywordsGrammar=Nothing(),
+    NaturalJoinKeywordsGrammar=Ref.keyword("CROSS"),
     NestedJoinGrammar=Sequence(
         Indent,
         Ref("JoinClauseSegment"),
```

Seems to work, but I don't know T-SQL well enough to know if that's going to address all the needs?

**Comment by borchero** [comment]
Awesome, thanks for your extensive answer @tunetheweb! Regarding tests: where can I add tests related to formatting? It seems like the SQL files in `dialects/...` are only useful for testing the parser.

**Comment by borchero** [comment]
@tunetheweb, I'm not exactly sure why this happens, but simply moving the grammar for the "join type" to a named grammar and referencing it (i.e. your change nr. 1), causes tests to fail: `test/fixtures/dialects/ansi/select_many_join.yml` cannot be parsed anymore. I'm not sure why this happens? I thought that the reference is just replaced with the grammar at runtime.

**Comment by tunetheweb** [comment]
> Awesome, thanks for your extensive answer @tunetheweb! Regarding tests: where can I add tests related to formatting? It seems like the SQL files in `dialects/...` are only useful for testing the parser.

You can add test cases in `test/fixtures/rules/std_rule_cases/L003.yml`

> @tunetheweb, I'm not exactly sure why this happens, but simply moving the grammar for the "join type" to a named grammar and referencing it (i.e. your change nr. 1), causes tests to fail: `test/fixtures/dialects/ansi/select_many_join.yml` cannot be parsed anymore. I'm not sure why this happens? I thought that the reference is just replaced with the grammar at runtime.

Ah my fault. You need to move the `optional=True,`:

```diff
+++ b/src/sqlfluff/dialects/dialect_ansi.py
@@ -546,6 +546,18 @@ ansi_dialect.add(
         "FILTER", Bracketed(Sequence("WHERE", Ref("ExpressionSegment")))
     ),
     FrameClauseUnitGrammar=OneOf("ROWS", "RANGE"),
+    PreJoinKeywordsGrammar=OneOf(
+        "CROSS",
+        "INNER",
+        Sequence(
+            OneOf(
+                "FULL",
+                "LEFT",
+                "RIGHT",
+            ),
+            Ref.keyword("OUTER", optional=True),
+        ),
+    ),
     # It's as a sequence to allow to parametrize that in Postgres dialect with LATERAL
     JoinKeywordsGrammar=Sequence("JOIN"),
     # NATURAL joins are not supported in all dialects (e.g. not in Bigquery
@@ -1468,19 +1480,7 @@ class JoinClauseSegment(BaseSegment):
     match_grammar: Matchable = OneOf(
         # NB These qualifiers are optional
         Sequence(
-            OneOf(
-                "CROSS",
-                "INNER",
-                Sequence(
-                    OneOf(
-                        "FULL",
-                        "LEFT",
-                        "RIGHT",
-                    ),
-                    Ref.keyword("OUTER", optional=True),
-                ),
-                optional=True,
-            ),
+            Ref("PreJoinKeywordsGrammar", optional=True,),
```

If you `Ref` something it needs to match something unless you make it optional.
