### ISSUE TITLE
Enhancement: Deprecate BaseSegment.name in favour of extending types.

### ISSUE THREAD

**Issue by alanmcruickshank** [sqlfluff/sqlfluff#3692]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### Description

This is potentially a controversial one, but I think it makes sense.

The `name` keyword on segments I think is confusing. Sometimes it's used like a type, sometimes it means something else. We have rules that sometimes search by `name` and sometimes by `type`. I think however, that **name is always used as a more specific type**.

The type interface for segments is already much more flexible that when originally designed. `BaseSegment.is_type()` already checks against both the declared type and the types of any parent classes, so we already have the concept of more than one valid `type` for a segment. This presents a dilemma in delivering #3668, because it's not clear how to crawl easily for types **and** for names.

The place where `name` becomes most obvious is in the parse tree where the `name` defines what is shown there.

My proposal is:
- Remove `name` as an attribute.
- Allow (optionally) the `type` of a segment to be given as a tuple of strings rather than just a string.
- When type checking we check against all types declared.
- In all the cases where we need a single `type` for a segment, we get the **last** in the tuple of types.

As an example, we currently have:
```python
PlusSegment=StringParser("+", SymbolSegment, name="plus", type="binary_operator")
```
This would become:
```python
PlusSegment=StringParser("+", SymbolSegment, type=("binary_operator", "plus"))
```

The _functionality_ would remain roughly the same, but rather than checking the `name` or checking `type`, `PlusSegment` would return true for `.is_type("plus")` **and** `istype("binary_operator")`.

In several cases I think this would also simplify code where we're setting the `type` and the `name` to be the same thing at the moment.

### Use case

This simplifies the code and removes some bloat.

### Dialect

all

### Are you willing to work on and submit a PR to address the issue?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by barrywhart** [comment]
I like it! I have often been a bit confused with the current design, having to look at both type and name to figure out which to use (and not really "getting" the distinction).

What you're describing sounds a **lot** like a single-inheritance class hierarchy. Is it worth considering formalizing that a bit? For example, the part about "you can specify type as a tuple of strings" is loosely similar to saying that a segment type can inherit from other type, and it's considered a subtype of all those. Think we might eventually want to require defining a new segment class in order to provide a new type string?

**Comment by alanmcruickshank** [comment]
> Think we might eventually want to require defining a new segment class in order to provide a new type string?

🤦 Yeah that would be much simpler 👍. Looking back at writing this issue I wish I'd seen that too. Great feedback.

Plan then:
- ✅ still get rid of `name`
- ❌ don't use tuples, just actually define the parent segment type. Yes more segment definitions but that's ok because it's cleaner.

Much cleaner and a great idea

**Comment by alanmcruickshank** [comment]
Most of the rules are now refactored with #3701. That at least unblocks #3668.

Remaining work here is to unpick


This PR does not address some of the remaining issues:

- NamedParser still exists which I'd like to remove.
- The link between `...Parser` classes, lexing and segments is really convoluted and relies somewhat on names.
- BaseSegment.name still exists as an attribute and is still used in a few places.

I think first first PR also raises questions about how we reference `type` on segments, which I might revisit too (i.e. when to use `.type` and when to use `.get_type()`).
