### ISSUE TITLE
Add a rule to enforce consistent syntax for SQL type casting

### ISSUE THREAD

**Issue by bolajiwahab** [sqlfluff/sqlfluff#3713]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### Description
Apart from supporting the SQL standard type casting variant `CAST(expression AS type)`, several dialects have other variants for type casting.

The other variants are listed below:

1. PostgreSQL https://www.postgresql.org/docs/current/sql-expressions.html#SQL-SYNTAX-TYPE-CASTS
```
expression::type
```
2. SQL Server https://docs.microsoft.com/en-us/sql/t-sql/functions/cast-and-convert-transact-sql?view=sql-server-ver16
```
CONVERT(type, expression)
```
3. MySQL https://dev.mysql.com/doc/refman/8.0/en/cast-functions.html
```
CONVERT(type, expression)
```
4. Redshift https://docs.aws.amazon.com/redshift/latest/dg/r_CAST_function.html
```
expression::type
CONVERT(type, expression)
```
5. Snowflake https://docs.snowflake.com/en/sql-reference/functions/cast.html
```
expression::type
```
6. Clickhouse https://clickhouse.com/docs/en/sql-reference/functions/type-conversion-functions/#castx-t
```
CAST(type, expression)
expression::type
```
7. Teradata https://docs.teradata.com/r/kmuOwjp1zEYg98JsB8fu_A/BQxvaT7YNqCkkfWB0FaYvA
```
CAST(expression AS type FORMAT expression)
```

Currently, there is no way to enforce consistent type casting in a codebase involving these dialects. We could have a rule specifying the type of casting we want to try to enforce(`STANDARD` or `NON-STANDARD`). This rule should be configurable. 

REF: https://sqlfluff.slack.com/archives/C01GPHR8J0G/p1659570939547909

### Use case

Consistent type casting for the above-listed dialects

### Dialect

postgres, tsql, clickhouse, redshift, mysql, teradata, snowflake

### Are you willing to work on and submit a PR to address the issue?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by fmms** [comment]
I would wish the same for tsql where ine has CONVERT and CAST

**Comment by bolajiwahab** [comment]
> I would wish the same for tsql where ine has CONVERT and CAST

It could easily be extended to cover tsql.

**Comment by fmms** [comment]
@bolajiwahab very much looking forward to your PR. Thanks so much!

Did you consider the style argument for CONVERT in your PR?
Unfortunatley, in T-SQL there are some cases where you cannot replace CONVERT with CAST. 
For details have a look at https://docs.microsoft.com/en-us/sql/t-sql/functions/cast-and-convert-transact-sql?redirectedfrom=MSDN&view=sql-server-ver16 .
That page has the following example:
```
SELECT   
   GETDATE() AS UnconvertedDateTime,  
   CAST(GETDATE() AS NVARCHAR(30)) AS UsingCast,  
   CONVERT(nvarchar(30), GETDATE(), 126) AS UsingConvertTo_ISO8601  ;  
GO  
```

**Comment by bolajiwahab** [comment]
@fmms Thanks for raising that. Indeed, tsql takes an optional styling for CONVERT which cannot be rewritten with CAST.
In that case, the user can ignore the error with noqa and we shouldn't try to fix it. What do you think?

**Comment by fmms** [comment]
@bolajiwahab in my opinion the rule should only consider two-argument-converts. 3-argument-converts should neither raise a warning nor tried to be fixed.

**Comment by bolajiwahab** [comment]
> @bolajiwahab in my opinion the rule should only consider two-argument-converts. 3-argument-converts should neither raise a warning nor tried to be fixed.

Okay. Sounds fair since we cannot rewrite it into CAST in the first place.

**Comment by fmms** [comment]
Awesome tested it on a small code base , it works perfectly 😃. Thanks

**Comment by bolajiwahab** [comment]
> Awesome tested it on a small code base , it works perfectly 😃. Thanks

Great to know that. And thanks for waiting so long for it. Cheers.
