### ISSUE TITLE
Sponsor link is broken

### ISSUE THREAD

**Issue by mtlynch** [sqlfluff/sqlfluff#3715]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### Links or command line

https://github.com/sqlfluff/sqlfluff/blob/6c8d2ab0c5e34b930f902c0e4b84dea51f5b5f0f/.github/FUNDING.yml#L15

http://flattr.com/github/alanmcruickshank

### Issue/Suggested Improvement

The link to sponsor the project currently points to a Flattr page that 404s:

http://flattr.com/github/alanmcruickshank

I'd love to support the project with a financial donation if that's something that would be helpful.

### Are you willing to work on and submit a PR to address the issue?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by alanmcruickshank** [comment]
Yes - this is my bad. I broke the link on the flattr side. Will fix shortly. Thanks for offering a donation!
