### ISSUE TITLE
[dbt] I don't understand how to setup sqlfluff to be compatible with third-party macros

### ISSUE THREAD

**Issue by Tomperez98** [sqlfluff/sqlfluff#3724]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### Issue/Suggested Improvement

I don't understand how to setup sqlfluff to be compatible with third-party macros

### Are you willing to work on and submit a PR to address the issue?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by jaypeedevlin** [comment]
Hey @Tomperez98, I'm not a maintainer here, but I wonder if (assuming you're talking about macros in packages) the `.sqlfluffignore` config mentioned here could resolve your issue?

https://docs.sqlfluff.com/en/stable/configuration.html#installation-configuration

**Comment by barrywhart** [comment]
I'm a maintainer, but I don't think there's enough info here for us to work with. Other people are doing this successfully.

The very short answer is to run `dbt deps` before running SQLFluff.
