### ISSUE TITLE
sqlfluff too slow with pre-commit-config

### ISSUE THREAD

**Issue by antaradas94** [sqlfluff/sqlfluff#3737]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### What Happened

Hi all, SQLFluff imo is a super useful linter at the moment. Have been using it for a while and had not doubts about it up until a point where we had like 100+ files in our DBT. We have SQLFluff in our pre-commit-config and at times, commits with 5+ file with many lines of code are just stuck or process forever at the this linting stage. ( at times have bypassed the sqlfluff stage ) Has anyone also been facing the same? I am assuming this could be a performance issue on SQLFluff side. 
Can there be anyways to improvise on this? Or do you guys already have a way of dealing with the performance speed?
Thanks

### Expected Behaviour

It is expected to work as it does.

### Observed Behaviour

Seems to be really lagging or running forever

### How to reproduce

used it pre-commit-config. 

### Dialect

Snowflake

### Version

1.2.1

### Configuration

default settings

### Are you willing to work on and submit a PR to address the issue?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by barrywhart** [comment]
You can see a list of proposed ideas for improving performance [here](https://github.com/sqlfluff/sqlfluff/issues?q=is%3Aissue+is%3Aopen+performance+label%3Aperformance). The next release will have some significant enhancements to linting performance: see PR #3717. The parser is another area we'd like to improve.

Closing this issue as a duplicate.
