### ISSUE TITLE
Build out different contexts for rules

### ISSUE THREAD

**Issue by alanmcruickshank** [sqlfluff/sqlfluff#3745]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### Description

Based off a discussion from #3743 .

Originally, the functional context was accessible within a rule thus:

```python
class Rule_X(BaseRule):
    def _eval(self, context: RuleContext):
        context.functional.do_functional_things(...)
```

To clean out the `sqlfluff.core` module, I migrated the functional code out to `sqlfluff.utils` (see #3743) and now the way to access the functional context is:

```python
from sqlfluff.utils.functional import FunctionalContext

class Rule_X(BaseRule):
    def _eval(self, context: RuleContext):
        FunctionalContext(context).do_functional_things(...)
```

On slack there was then a discussion about the best path forward. The options presented were:
1. We should have a decorator which provides a pre-hydrated functional context. For the developer that would mean something like this:
   ```python
   from sqlfluff.utils.functional import functional_context, FunctionalContext

   class Rule_X(BaseRule):
       @functional_context
       def _eval(self, context: RuleContext, functional: FunctionalContext):
           functional.do_functional_things(...)
   ```
2. We make `FunctionalContext` a subclass of `RuleContext` so that all the more mundane things (like `dialect`, `segment` and config settings) are still accessible on it and then provide only that, likely triggered by a decorator. For the developer that would mean something like this:
   ```python
   from sqlfluff.utils.functional import functional_context, FunctionalContext

   class Rule_X(BaseRule):
       @functional_context
       def _eval(self, context: FunctionalContext):
           context.do_functional_things(...)
   ```
3. For reflow utils, I'm considering actually having context managers for some utils, and taking the same approach here, we'd perhaps extend this to:
   ```python
   from sqlfluff.utils.functional import FunctionalContext

   class Rule_X(BaseRule):
       def _eval(self, context: RuleContext):
           with FunctionalContext(context) as functional:
               functional.do_functional_things(...)
           # ...mirroring potentially later doing:
           with ReflowContext(context) as reflow:
               reflow.do_reflow_things(...)
   ```
4. Do nothing and continue to get the user to hydrate their own functional context (a la `FunctionalContext(context).do_functional_things(...)`).

### Use case

This is entirely about enabling clearer and easier rule development.

### Dialect

all

### Are you willing to work on and submit a PR to address the issue?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by alanmcruickshank** [comment]
@OTooleMichael @barrywhart - both of you had views on this on slack. Have I represented the options well here?

**Comment by barrywhart** [comment]
Looks good! 👍

**Comment by OTooleMichael** [comment]
Why the context managers for point 3. What is being opened and closed?

**Comment by alanmcruickshank** [comment]
@OTooleMichael, there isn't which I think is a good point. Given how the `ReflowSequence` code is shaping up, I think I might close this issue. Of the options I feel like the current one is the tidiest.
