### ISSUE TITLE
Add mypy in the project ?

### ISSUE THREAD

**Issue by flpezet** [sqlfluff/sqlfluff#378]
Would you agree if we add progressively [mypy](http://mypy-lang.org/)? Static typing documents well the code. 
I'd be glad to do it, it is practical way to dive into the code.

**Comment by alanmcruickshank** [comment]
@flpezet - yes please! I've never really used mypy but I'd love to learn more.

Feel free to add things to the build pipeline and any checks you feel necessary. Some guidance in the `CONTRIBUTING.md` file would also be great.

I'm happy to help on this one too, but I wouldn't know where to start, so if you can get the ball rolling that would be a real help.

**Comment by pwildenhain** [comment]
This definitely interests me as well. I've also heard a lot of good things about [`pydantic`](https://pydantic-docs.helpmanual.io/) which appears to have a `mypy` plugin.

@alanmcruickshank Do you have a preference?

**Comment by pwildenhain** [comment]
We got a good bit of `mypy` in this release, and we can add more as the project continues -- @sqlfluff/sqlfluff-maintainers I'll close this issue for now, but feel free to reopen it if you think we should add more type hints before we close it.
