### ISSUE TITLE
sqlite: PRAGMA statement not parseable

### ISSUE THREAD

**Issue by dr-1** [sqlfluff/sqlfluff#3799]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### What Happened

Parsing of an SQLite PRAGMA statement failed: "PRAGMA FOREIGN_KEYS = ON;"

### Expected Behaviour

Parsing the statement successfully

### Observed Behaviour

```
[L:  1, P:  1]      |file:
[L:  1, P:  1]      |    statement:
[L:  1, P:  1]      |        unparsable:                                           !! Expected: 'StatementSegment'
[L:  1, P:  1]      |            raw:                                              'PRAGMA'
[L:  1, P:  7]      |            whitespace:                                       ' '
[L:  1, P:  8]      |            raw:                                              'FOREIGN_KEYS'
[L:  1, P: 20]      |            whitespace:                                       ' '
[L:  1, P: 21]      |            raw:                                              '='
[L:  1, P: 22]      |            whitespace:                                       ' '
[L:  1, P: 23]      |            raw:                                              'ON'
[L:  1, P: 25]      |    statement_terminator:                                     ';'
[L:  1, P: 26]      |    newline:                                                  '\n'
[L:  2, P:  1]      |    [META] end_of_file:

==== parsing violations ====
L:   1 | P:   1 |  PRS | Line 1, Position 1: Found unparsable section: 'PRAGMA FOREIGN_KEYS
                       | = ON'
```

### How to reproduce

```
echo "PRAGMA FOREIGN_KEYS = ON;" | sqlfluff parse --dialect=sqlite -
```

### Dialect

sqlite

### Version

sqlfluff 1.3.0
python 3.10.6

### Configuration

None

### Are you willing to work on and submit a PR to address the issue?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by alanmcruickshank** [comment]
Confirmed. This is not present in the existing dialect. The sqllite docs for this syntax are here: https://www.sqlite.org/pragma.html

I won't be able to pick this one up myself for a while, I've got quite a lot already queued up for me. Anyone else feel able to take this on any time soon?
