### ISSUE TITLE
Rule: Warn if the overall query (i.e. final query, ignoring CTEs) produces an indeterminate number of columns

### ISSUE THREAD

**Issue by barrywhart** [sqlfluff/sqlfluff#380]
Use of `SELECT *` in production queries is generally considered a bad practice, e.g. [this StackOverflow post](https://stackoverflow.com/questions/3639861/why-is-select-considered-harmful). SQLFluff should warn if a query does this.

In our team, we often allow an exception, i.e.`SELECT *` is okay *if* it's reading from a CTE (i.e. another "table" defined elsewhere in the same query), since in that case, the schema of the CTE may be fixed, so `SELECT *` from a CTE wouldn't allow any new upstream columns from other tables or queries to leak through.

This mistake caused one of our production jobs to fail recently because the query was being used to add new records to an existing table, and it failed in a cryptic way because the `SELECT *` picked up a new column that wasn't present in the existing table being appended to.

**Comment by alanmcruickshank** [comment]
Interesting! Great idea for a rule. I've never adopted this but I probably should.

Happy to accept PRs on this one.

**Comment by barrywhart** [comment]
I'll add to my list. I may have some available time in the next few weeks. 🤞

**Comment by NiallRees** [comment]
What would you think about a warning on an entire query being indeterminate in number of columns produced, as opposed to just one CTE referencing another table with a select *? DBT coding conventions prefer an initial select * from external table CTE, followed by another CTE which specific all columns to capture and any other logic. The motivation is that at a quick glance it is immediately apparent what other tables a model depends on, which can become hard to understand when table references are buried further down the model in joins. You keep the benefit of determinate model 'widths', and quickly identifiable table dependencies.

**Comment by barrywhart** [comment]
That sounds good too. That's what I want to avoid -- creating an output that may break downstream consumers if an input changes.

It'd be a bit more complex to implement, perhaps, but I'm probably thinking too far ahead.

**Comment by NiallRees** [comment]
Definitely more complex, it would take on some query planner like logic. I think that the ground work could be really valuable for other rules though, e.g. it would also allow identification of unused CTE's. 

I wonder if for now to keep things simpler, the logic could just check that out of the final select statement and upstream CTE's, at least one select statement contained no `*`s. That _should_ guarantee a deterministic column output? What do you think @barrywhart ?

**Comment by barrywhart** [comment]
That would be fine. I really like the idea that over time, SQLFluff will do more sophisticated graph/flow analysis of SQL to flag potential issues, something a bit like global optimizing compilers in traditional programming languages.

**Comment by barrywhart** [comment]
Design notes:
* Rule L018 analyzes occurrences of `with_compound_statement`.
* Rule L020 looks at tables and columns in a query.
* Rule L036 detects use of `wildcard_expression` (i.e. passing through all columns from upstream table(s)).

Make sure we detect not only `SELECT *` but also `SELECT t.*`.

**Comment by barrywhart** [comment]
@NiallRees: I updated the issue summary based on your suggestion and hope to start work on this in the next few days. Overall, I like your idea better than the original one.

After thinking about it more, I think there is still some value in the original idea. Why? We're really talking about two different concerns:
* "Indeterminate number of columns in the final query" is a **modeling** issue, because the output table schema can change without warning, without changes to the code.
* "`SELECT *`" from a non-CTE table is a performance/cost issue for some databases.

Why performance/cost? This concern applies mainly to data stores where the data is in a columnar format (e.g. BigQuery, Snowflake, Hive when using ORC or Parquet format, ???). That's because the amount of data read by a query depends on the subset of columns being accessed. In BigQuery, this maps directly to query cost: $5/terabyte read.

I'm thinking about adding a new "set" (i.e. config value) to each dialect reflecting whether it's columnar, and generating this second kind of warning only if that is the case.

What do you think?

Perhaps these should be two different rules (that potentially share code).
