### ISSUE TITLE
1.3.1 did not tag correctly on dockerhub

### ISSUE THREAD

**Issue by WilsonSunBritten** [sqlfluff/sqlfluff#3882]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### What Happened

https://hub.docker.com/layers/sqlfluff/sqlfluff/untagged-d47ee9b0bbcf857a3b4f/images/sha256-aae5463711c70966934a6ae7f0e795cf04f8cbd52952a47314655ad5a0560dfb?context=explore

It seems that sqlfluff 1.3.1 correctly updated the latest image, but instead of having another release tagged as 1.3.1 it was tagged as [untagged-d47ee9b0bbcf857a3b4f](https://hub.docker.com/layers/sqlfluff/sqlfluff/untagged-d47ee9b0bbcf857a3b4f/images/sha256-aae5463711c70966934a6ae7f0e795cf04f8cbd52952a47314655ad5a0560dfb?context=explore). Unclear if this is due to a missed step in release or configuration bug

![image](https://user-images.githubusercontent.com/16767620/192387425-b4d1e7eb-b13d-41f6-9ffc-120639a0191d.png)

### Expected Behaviour

All releases should correctly be tagged as their version in dockerhub

### Observed Behaviour

a tag appeared as [untagged-d47ee9b0bbcf857a3b4f](https://hub.docker.com/layers/sqlfluff/sqlfluff/untagged-d47ee9b0bbcf857a3b4f/images/sha256-aae5463711c70966934a6ae7f0e795cf04f8cbd52952a47314655ad5a0560dfb?context=explore)

### How to reproduce

Check dockerhub https://hub.docker.com/r/sqlfluff/sqlfluff/tags

### Dialect

-

### Version

1.3.1

### Configuration

-

### Are you willing to work on and submit a PR to address the issue?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by barrywhart** [comment]
AFAIK, the SQLFluff maintainers and GitHub organization do not publish a Docker image. That's someone else.

Can you confirm, @alanmcruickshank or @tunetheweb?

I'm going to close this for now. Similar questions sometimes arise for Mac homebrew, for example. I don't know who publishes that, either.

**Comment by barrywhart** [comment]
Also, note that the [Releases](https://github.com/sqlfluff/sqlfluff/releases) page and the latest version on [PyPI](https://pypi.org/project/sqlfluff/) are correct.

**Comment by tunetheweb** [comment]
We do publish that.

Looks to have run successfully to me: https://github.com/sqlfluff/sqlfluff/actions/workflows/publish-sqlfluff-docker-image-to-dockerhub.yaml

But don't know nothing about Docker I'm afraid so maybe @jpy-git can advise as he set up in #1945

**Comment by barrywhart** [comment]
Ah, good to know. Perhaps I did something different (like a different sequence or something) when I published the release?

**Comment by tunetheweb** [comment]
Ah yes I don't think you tagged that release properly initially when you edited the release page. I updated it afterwards IIRC.

Not sure if we can re-tag it now and only include 1.3.1 changes?

Easiest thing would be to just leave until next release.

**Comment by barrywhart** [comment]
Waiting sounds 💯 to me.

**Comment by WilsonSunBritten** [comment]
👍

**Comment by tunetheweb** [comment]
Maybe should add a check and fail the deploy if the tag is not of a specific format to prevent this in future? Or pick up the version from the config file, rather than from the release? @greg-finley is a bit of a wizz at GiHub actions, but probably couldn't do a full test as he (nor I!) don't know Docker that well.
