### ISSUE TITLE
postgre create table why is PRS

### ISSUE THREAD

**Issue by WingDust** [sqlfluff/sqlfluff#3895]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### What Happened

![image](https://user-images.githubusercontent.com/45911286/193172826-8feade14-7c15-4e0c-9fdb-5a584becbf08.png)

### Expected Behaviour

should be right

### Observed Behaviour

error create table

### How to reproduce

```sql
create table  c(
  id serial primary key,
  name text not null,
  );
```

### Dialect

postgre

### Version

web

### Configuration

default

### Are you willing to work on and submit a PR to address the issue?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by adam-tokarski** [comment]
Hi @WingDust 
isn't that by the hanging comma in `name` column definition?

Please check with 
```sql
create table  c(
  id serial primary key,
  name text not null
  );
```

**Comment by WingDust** [comment]
@adam-tokarski  yeh you are right
