### ISSUE TITLE
Failed to generate --new-only YAML parse fixtures

### ISSUE THREAD

**Issue by tomasfarias** [sqlfluff/sqlfluff#3906]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### What Happened

I was contributing a quick fix that required generating some YAML test fixtures. When running `tox -e generate-fixture-yml -- --new-only` an exception was raised:

```
File "tomasfarias/sqlfluff/test/generate_parse_fixture_yml.py", line 48, in _is_matching_new_criteria
    example.dialect,
AttributeError: 'tuple' object has no attribute 'dialect'
ERROR: InvocationError for command tomasfarias/sqlfluff/.tox/generate-fixture-yml/bin/python test/generate_parse_fixture_yml.py --new-only (exited with code 1)
```

### Expected Behaviour

Running `tox -e generate-fixture-yml -- --new-only` should produce new YAML test fixtures without raising any exceptions.

### Observed Behaviour

The function `generate_parse_fixtures_yml.py::_is_matching_criteria` is attempting to access the attribute `dialect` of a tuple object which doesn't exist:

```python
def _is_matching_new_criteria(example: _ParseExample):
    """Is the Yaml doesnt exist or is older than the SQL."""
    yaml_path = _create_yaml_path(example)
    if not os.path.exists(yaml_path):
        return True

    sql_path = os.path.join(
        "test",
        "fixtures",
        "dialects",
        example.dialect, # Here!
        example.sqlfile, # This would fail too.
    )
    return os.path.getmtime(yaml_path) < os.path.getmtime(sql_path)
```

Although the `example` object type hint says it's a `_ParseExample`, subclass of `NamedTuple` (which would support dot notation), the runtime object is just a regular tuple, that doesn't support dot notation as returned by `conftest.py:get_parse_fixtures`.

There are two potential solutions:

1. Using brackets to index the tuple instead of dot notation:
```python
def _is_matching_new_criteria(example: _ParseExample):
    """Is the Yaml doesnt exist or is older than the SQL."""
    yaml_path = _create_yaml_path(example)
    if not os.path.exists(yaml_path):
        return True

    sql_path = os.path.join(
        "test",
        "fixtures",
        "dialects",
        example[0],
        example[1],
    )
    return os.path.getmtime(yaml_path) < os.path.getmtime(sql_path)
```

Although simpler, this solution would still keep the incorrect type hint.

2. Use a namedtuple subclass in `conftest.py:get_parse_fixtures` (and then importing it for type checking in `generate_parse_fixtures_yml.py`):

```python
# In conftest.py
from typing import NamedTuple
...

class _ParseExample(NamedTuple):
    dialect: str
    sqlfile: str


def get_parse_fixtures(fail_on_missing_yml=False):
    """Search for all parsing fixtures."""
    parse_success_examples = []
    parse_structure_examples = []
    # Generate the filenames for each dialect from the parser test directory
    for d in os.listdir(os.path.join("test", "fixtures", "dialects")):
        # Ignore documentation
        if d.endswith(".md"):
            continue
        # assume that d is now the name of a dialect
        dirlist = os.listdir(os.path.join("test", "fixtures", "dialects", d))
        for f in dirlist:
            has_yml = False
            if f.endswith(".sql"):
                root = f[:-4]
                # only look for sql files
                parse_success_examples.append(_ParseExample(d, f)) # Instantiates a new _ParseExample
...
```

If going with this one, the type hints would now match the actual types.

### How to reproduce

1. Clone sqlfluff.
2. Run `tox -e generate-fixture-yml -- --new-only`.

### Dialect

None.

### Version

Main branch.

### Configuration

None.

### Are you willing to work on and submit a PR to address the issue?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by adam-tokarski** [comment]
Hi @tomasfarias I've currently solved that when working on different PR, and then checked that you've raised this issue. Are you going to push PR or can I continue with mine?

**Comment by tomasfarias** [comment]
Hi @adam-tokarski just opened one, thank you!
