### ISSUE TITLE
Support MySQL REPLACE statement

### ISSUE THREAD

**Issue by zhsj** [sqlfluff/sqlfluff#3947]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### Description

https://dev.mysql.com/doc/refman/8.0/en/replace.html

### Use case

Recognize following statement:

``` sql
REPLACE INTO account (
    user_id, username
) VALUES (1, 'admin');
``` 

### Dialect

MySQL

### Are you willing to work on and submit a PR to address the issue?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by adam-tokarski** [comment]
> Can I submit a pr and suggest some changes ???

I think that any PR is more than welcome here. 

Just make sure that if there are some different changes, it would be best to have provided them in separate pull requests - to not block others when any of them need additional work, for example.
