### ISSUE TITLE
SparkSQL: parsing error for : (colon sign) operator (Databricks SQL)

### ISSUE THREAD

**Issue by karabulute** [sqlfluff/sqlfluff#3951]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### What Happened

Colon sign operator extracts content from a JSON string using a JSON path expression. Spark SQL can't parse it, sqlfluff raises a parsing error, and can't fix the file. 

References:

1. [: (colon sign) operator (Databricks SQL)](https://docs.databricks.com/sql/language-manual/functions/colonsign.html)

Solution Suggestion(s):

1. Extend and let Spark SQL to parse it.
2. Create a separate dialect for Databricks SQL instead of an alias.

### Expected Behaviour

```bash
== [C:\query_colon_operator.sql] PASS
==== summary ====
files:             1 violations:        0
clean files:       1 unclean files:     0
avg per file:   0.00 unclean rate:     0%
status:         PASS
All Finished!
```

### Observed Behaviour

```bash
== [C:\query_colon_operator.sql] FAIL
L:   1 | P:  18 |  PRS | Line 1, Position 18: Found unparsable section: ':Detail'
```

### How to reproduce

```sql 
SELECT Log.Record:Detail
FROM App_Logs
```

### Dialect

```bash
dialect:              sparksql 
templater:               jinja
```

### Version

```bash
sqlfluff:                1.3.2 
python:                  3.8.8
```

### Configuration

```text
[sqlfluff]
dialect = databricks
templater = jinja
```

### Are you willing to work on and submit a PR to address the issue?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by alanmcruickshank** [comment]
Interestingly , the same syntax parses fine in the `snowflake` dialect (which uses the same syntax for accessing JSON data`). One good solution might be to port across the same logic from there if you think it's appropriate.

Try running `sqlfluff parse test.sql -d snowflake` and you'll see the results.

**Comment by karabulute** [comment]
Thank you for your feedback. I've already developed some solutions around this. I'll check if the approaches are the same or not.

I'd like to parameterize the `dialect_ansi` and replace the `MatchGrammer` and `TerminateGrammer` in `sparksql`. But, do you suggest keep adding Databricks SQL related improvements to the `Spark SQL` dialect, or create a new dialect for only Databricks? @alanmcruickshank

**Comment by karabulute** [comment]
Here is another example query from [documentation](https://docs.databricks.com/sql/language-manual/functions/colonsign.html#examples) to check, `snowflake` seems to fail with brackets.

```sql 
SELECT c1:['price']::decimal(5,2)
FROM VALUES('{ "price": 5 }') AS T(c1);
```

**Comment by alanmcruickshank** [comment]
ah - that's a different syntax though: ``::decimal(5,2)` is casting it as a different datatype, `Log.Record:Detail` is about JSON access.

**Comment by karabulute** [comment]
> ah - that's a different syntax though: `::decimal(5,2)` is casting it as a different datatype, `Log.Record:Detail` is about JSON access. Are they both supported in databricks?

According to documentation, yes. I'll lookup any examples of that currently in-use but first example is definitely from an in-use query with colon operator.
