### ISSUE TITLE
NOQA not being respected - TMP

### ISSUE THREAD

**Issue by tdstark** [sqlfluff/sqlfluff#3998]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### What Happened

We have a Jinja template field from Airflow which uses a macro. This field is throwing an error because SQLFluff does not yet have the ability to pull in macros from Airflow. When using `-- noqa` or `-- noqa: TMP` on the problematic line, this does not solve the problem.

The problematic sql is:
```
WHERE salesforce_order_id IS NULL
    AND order_number IS NOT NULL
    AND order_start_date IS NOT NULL
    AND (trunc(date_updated) = '{{macros.ds_add(ds, +1)}}' -- noqa: TMP
    OR trunc(date_updated) > nvl(date_successful_sync, '1970-01-01'::date))
```

`sqlfluff lint problematic_sql.sql --config=pyproject.toml --dialect=redshift`

Results in this error:

```
L:   1 | P:   1 |  TMP | Unrecoverable failure in Jinja templating:
                       | <sqlfluff.core.templaters.jinja.JinjaTemplater.process.<locals>.UndefinedRecorder
                       | object at 0x1057766d0> is not safely callable. Have you
                       | configured your variables?
                       | https://docs.sqlfluff.com/en/latest/configuration.html
```

The following configuration is being used in `pyproject.toml`:
```
[tool.sqlfluff.rules]
comma_style = "leading"

[tool.sqlfluff.rules.L010]  # Keywords
capitalisation_policy = "upper"

[tool.sqlfluff.rules.L030]  # Function Names
capitalisation_policy = "upper"

[tool.sqlfluff.rules.L040]  # Null/Boolean Literals
capitalisation_policy = "upper"

[tool.sqlfluff.templater.jinja.context]
execution_date = "2022-01-03 04:14:53,368"
ds_nodash = "20220103T041453"
ts = "2022-01-03T04:14:53,368"
ds = "2022-01-03"
next_ds = "2022-01-03"
tomorrow_ds = "2022-01-03"
```

### Expected Behaviour

The line should be parsed and any linting errors should be skipped.

### Observed Behaviour

The line is not skipped and it throws the following error:
```
L:   1 | P:   1 |  TMP | Unrecoverable failure in Jinja templating:
                       | <sqlfluff.core.templaters.jinja.JinjaTemplater.process.<locals>.UndefinedRecorder
                       | object at 0x1057766d0> is not safely callable. Have you
                       | configured your variables?
                       | https://docs.sqlfluff.com/en/latest/configuration.html
```

### How to reproduce

See Description.

### Dialect

Redshift

### Version

`1.3.2`

### Configuration

See Description.

### Are you willing to work on and submit a PR to address the issue?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by tdstark** [comment]
For what it's worth, this problem still occurs even if the problematic line is commented.

**Comment by alanmcruickshank** [comment]
I think at the moment that problematic lines are only respected _after_ templating, because the flags are extracted from the templated version of the file. Thanks for reporting this.

**Comment by mroy-seedbox** [comment]
Looks like this should have been fixed (a while ago) by the changes to `UndefinedRecorder` in #5786! 🙌

**Comment by tdstark** [comment]
Great, thanks!

**Comment by alanmcruickshank** [comment]
Closing this as resolved.
