### ISSUE TITLE
Indent AS and ON keywords

### ISSUE THREAD

**Issue by kartiktatiparti** [sqlfluff/sqlfluff#4003]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### What Happened

Hi, I am facing an issue with the indents of AS and ON statements.
In my team we follow Mozilla Guide and want use AS and ON clauses with an indent
But sqlfluff lints indents both AS and ON statements to the same level as the table name

### Expected Behaviour

Indent AS and ON on level deeper than the table name:

<img width="561" alt="Screenshot 2022-10-31 at 11 14 53 AM" src="https://user-images.githubusercontent.com/93636303/198939743-59c0ff47-5095-45cc-9ddf-cc30cb7e576c.png">

### Observed Behaviour

SQLFluff indents both on the same level as the table name:

<img width="624" alt="Screenshot 2022-10-31 at 11 15 27 AM" src="https://user-images.githubusercontent.com/93636303/198939806-77a28e1c-456a-4a15-9f97-5f87760938ed.png">

### How to reproduce

import sqlfluff
sql_query = """
SELECT 
a.*,
b.*

FROM
table_a
AS a
JOIN
table_b
AS b
ON a.column_a = b.column_b
"""

print(sqlfluff.fix(sql_query, dialect='ansi', rules=['L003']))

### Dialect

ansi

### Version

Version 1.3.2

### Configuration

[sqlfluff]
rules = L003, L005, L006, L008, L010, L011, L012, L013, L016, L017, L018, L019, L021, L022, L025, L027, L030, L042, L044, L045, L048, L049, L054

dialect = ansi
ignore = parsing

[sqlfluff:indentation]
indented_joins = False

[sqlfluff:rules:L003]
hanging_indents = True

[sqlfluff:rules:L010]
capitalisation_policy = upper

[sqlfluff:rules:L011]
aliasing = explicit

[sqlfluff:rules:L012]
aliasing = explicit

[sqlfluff:rules:L013]
allow_scalar = False

[sqlfluff:rules:L036]
wildcard_policy = multiple

[sqlfluff:rules:L042]
forbid_subquery_in = both

[sqlfluff:rules:L054]
group_by_and_order_by_style = implicit

### Are you willing to work on and submit a PR to address the issue?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by alanmcruickshank** [comment]
Hi @kartiktatiparti - does this existing configuration value solve your issues: https://docs.sqlfluff.com/en/stable/layout.html#configuring-indent-locations

I suspect that setting `indented_joins = True` might be exactly what you want.

**Comment by kartiktatiparti** [comment]
Hi @alanmcruickshank, I had tried indented_joins didn't solve the issue. Later learned that mozilla guide actually indents only 1 level and what we follow is a modified one. So there's no issue here. Thanks for replying.
