### ISSUE TITLE
`insert into ...` in combination with CTE (postgres) does not work

### ISSUE THREAD

**Issue by loxy** [sqlfluff/sqlfluff#4018]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### What Happened

`insert into ...` in combination with CTE (postgres) does not work

### Expected Behaviour

No parsing error should occur, because it is valid SQL (postgres)

### Observed Behaviour

I get following error:

```sh
Line 1, Position 12: Found unparsable section: 'insert into tip as t (
    bettle_id
)
s...'
```

### How to reproduce

Add this to [online tool](https://online.sqlfluff.com/):

```sql
with x as (insert into tip as t (
    bettle_id
)
select
    'myid' as bettle_id
from
    members_not_tipped
on conflict on constraint no_duplicate_tip do
update
set is_winner = false,
stake = min_stake,
outcome = 0,
revenue = -min_stake,
tip_state = 'FINAL'
returning tip_id, member_id, stake, outcome, revenue
)

select * from x;
```

### Dialect

postgres

### Version

1.4.1

### Configuration

See online tool

### Are you willing to work on and submit a PR to address the issue?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by joaostorrer** [comment]
I tested this query with the newer version and is parsed without any error now.

**Comment by loxy** [comment]
Yes. It seems to work now. Thank you!
