### ISSUE TITLE
sqlfluff:templater:jinja:context templater variables with period are not resolved

### ISSUE THREAD

**Issue by andnig** [sqlfluff/sqlfluff#4019]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### What Happened

I've the following templated code ``{{ target.schema }}.article_id_from_url()``.
Adding the "target.schema" variable to the [sqlfluff:templater:jinja:context]
section in ``.sqlfluff``` still results in PRS errors.

```yaml
[sqlfluff:templater:jinja:context]
target.schema = vol-at.dbt_anigg
```

Having variables without period work fine

### Expected Behaviour

We can use variables with period for jinja templating

### Observed Behaviour

Having variables with period in the variable name result in the following linting error:
(If my templated code is ``{{ target.schema }}.article_id_from_url()``):

```
Line 55, Position 17: Found unparsable section: | '.article_id_from_url(cleaned_url),\n ...'
```

### How to reproduce

1. Have ``{{ target.schema }}.article_id_from_url()`` in your sql file
2. Run ``sqlfluff lint <sqlfile.sql> --dialect bigquery``

### Dialect

bigquery

### Version

sqlfluff, version 1.4.0
Python 3.10.4

### Configuration

[sqlfluff]
dialect = bigquery
# Use jinja templater instead of dbt, as the dbt templater is slow
# and does not work with bigquery dialect
templater = jinja
exclude_rules = L034, L032, L024
ignore_templated_areas = True

[sqlfluff:templater:jinja]
# Make dbt default macros available like `ref`
apply_dbt_builtins = true
# Load custom macros from the macro directory
load_macros_from_path = ./macros/
# Allow mocking dbt_utils and other packages through
# python files placed in this dir
library_path = ./sqlfluff_libs/

# Mock variables that are used in dbt
[sqlfluff:templater:jinja:context]
target.schema = vol-at.dbt_anigg

[sqlfluff:rules]
tab_space_size = 4
max_line_length = 100

[sqlfluff:rules:L010]
capitalisation_policy = lower

[sqlfluff:rules:L064]
preferred_quoted_literal_style = double_quotes
----------------------
Ignore
target/
dbt_modules/
dbt_packages/
macros/

### Are you willing to work on and submit a PR to address the issue?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by barrywhart** [comment]
Please read this section of the docs. This is how you need to define templater "variables" with dots in them.

https://docs.sqlfluff.com/en/stable/configuration.html#library-templating

**Comment by andnig** [comment]
Awesome thanks!! 
Thought this only works for functions, not ordinary variables.

**Comment by barrywhart** [comment]
I think it'll work for both. So many people want to do this, perhaps there should be an enhancement (not bug) ticket to make it easier (i.e. so you don't have to create `.py` files.)
