### ISSUE TITLE
Preview rendered SQL via CLI

### ISSUE THREAD

**Issue by dmohns** [sqlfluff/sqlfluff#4020]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### Description

Sometimes when dealing with linting issues it would be helpful to view a rendered version of the SQL in question.

Currently, it is only possible to view the _parsed_ version of a query which can be hard to understand when the query gets larger.

The idea here would be to add a configuration option to `sqlfluff parse -f` that simply outputs the rendered sql.

**For example**

`parse -f sql test.sql` on an sql file like this

```sql
{% set a = true %}
SELECT
    {% if a is true %}
    TRUE
    {% else %}
    FALSE
    {% endif %}
```

should output

```
SELECT
    TRUE
```

### Use case

Viewing the rendered version of an SQL might be more helpful for "users". I.e. people _writing SQL_ with a given SQLFluff rule set. When using complex Jinja statements manual lint fixes needs to be applied, as these are untouched by `sqlfluff fix`.

On the other hand viewing the parsed syntax tree is more suited towards "developers" working on SQLFluff rules.

### Dialect

all

### Are you willing to work on and submit a PR to address the issue?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by alanmcruickshank** [comment]
Thanks for writing this up @dmohns. Two questions to narrow down scope:
1. Do you imagine this would only ever be for single files - or should we also support selecting multiple files or folders like the existing `parse` and `lint` commands.
2. Is this primarily a CLI command, or should we also support output to files as a relatively first class citizen?

**Comment by alanmcruickshank** [comment]
For clarity, I've always imagined doing this as a separate CLI command i.e. `sqlfluff render`, rather than this being a subset of `sqlfluff parse`, but the intent is the same as what you describe.

**Comment by dmohns** [comment]
> 1. Do you imagine this would only ever be for single files - or should we also support selecting multiple files or folders like the existing `parse` and `lint` commands.

I cannot really imagine a scenario right now, where I would need to run this on multiple files. All use cases encountered so far where dealing with rendering issues of individual files. So not having support for multiple files or folders would be completely fine for me.

> 2. Is this primarily a CLI command, or should we also support output to files as a relatively first class citizen?

Hard to say... In my use-case this is primarily a CLI command. However, I am not very familiar with the SQLFluff Python API. I could hypothetically imagine scenarios where having access to the rendered template could be useful for some advanced things. 

>  I've always imagined doing this as a separate CLI command i.e. `sqlfluff render`, rather than this being a subset of `sqlfluff parse`

Hehe, 100% agree. I originally wanted to create this suggesting a  `sqlfluff render` command, but thought that adding another command might increase the complexity.

**Comment by alanmcruickshank** [comment]
@dmohns - check out #4043 and see if that fits what you had in mind? If you're up for reviewing the PR that would also be cool.
