### ISSUE TITLE
Align nullabilities & types in `CREATE/ALTER TABLE`

### ISSUE THREAD

**Issue by svengiegerich** [sqlfluff/sqlfluff#4023]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### Description

Within our company we're used to aligning _types_ & _nullabilities_ - i.e., `NULL`/`NOT NULL` - for every `CREATE` or `ALTER TABLE` statement. This helps us to quickly identify the "design" of the table in our daily work.

### Use case

Desired format:
```
CREATE TABLE tbl (
    foo       VARCHAR(25) NOT NULL,
    barbar    INT         NULL            
)
```

Current format:
```
CREATE TABLE tbl (
    foo VARCHAR(25) NOT NULL,
    barbar INT NULL            
)
```

### Dialect

all

### Are you willing to work on and submit a PR to address the issue?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by spencertollefson** [comment]
Is this in one of the recent minor updates? I'm on v2.0.2 and still don't have this functionality.

**Comment by WillMatthews** [comment]
Hi, I didn't have any luck with the config suggested here, and I've found nothing in the documentation either. I have seen examples of people claiming that this can be done, but I seem unable to replicate it at all.
Please may I have some help? Thanks

**Comment by borchero** [comment]
Yeah, this broke in 2.3.1, any idea why (e.g. @alanmcruickshank)? 🧐

**Comment by alanmcruickshank** [comment]
I'll take a look 👍

**Comment by alanmcruickshank** [comment]
Found the issue - will add your example here as a test case. Thanks for a great bug report!
