### ISSUE TITLE
Plugin example: module not found

### ISSUE THREAD

**Issue by tkachenkomaria244** [sqlfluff/sqlfluff#4024]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### What Happened

It seems some module changes were not applied properly in SQLFluff 1.4.1 (or earlier): in \plugins\sqlfluff-plugin-example\test\rules\rule_test_cases_test.py.
I see an error in this file: module "sqlfluff.testing.rules" is not found, it seems it was replaced with "sqlfluff.utils.testing.rules".

### Expected Behaviour

No errors

### Observed Behaviour

When running plugin tests for my plugin I receive an error:
```
..
from sqlfluff.testing.rules import load_test_cases, rules__test_helper
E   ModuleNotFoundError: No module named 'sqlfluff.testing.rules'
```

### How to reproduce

Run test for plugin rules in embedded plugin example

### Dialect

not applicable

### Version

SQLFluff 1.4.1 (or may be earlier, I didn't tested since 0.13.1), 
Python 3.9.13 

### Configuration

not applicable

### Are you willing to work on and submit a PR to address the issue?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by matthieucan** [comment]
Hello, I'm also experiencing a similar issue. The tests in https://github.com/sqlfluff/sqlfluff/blob/main/plugins/sqlfluff-plugin-example/test/rules/rule_test_cases_test.py are currently failing with the current stable version of sqlfluff.

If I replace `from sqlfluff.testing.rules import load_test_cases, rules__test_helper` with `from sqlfluff.utils.testing.rules import load_test_cases, rules__test_helper`, my rule tests fail with
```
AttributeError: 'Rule_X_L001' object has no attribute 'crawl_behaviour'
```

My configuration is exactly based on `sqlfluff-plugin-example`.

Could you point me to the right direction, or let me know if this plugin example is supposed to support the latest sqlfluff?

Thanks in advance.

**Comment by barrywhart** [comment]
Would you be willing to create a PR to update the example?

**Comment by matthieucan** [comment]
@barrywhart ^ there we go :)
