### ISSUE TITLE
Parser should support flyway style variables embedded in sql

### ISSUE THREAD

**Issue by srjonemed** [sqlfluff/sqlfluff#4025]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### Description

Parser should support flyway style variables embedded in sql. 
SQL's having embedded environment variables written as flyway placeholders should be parsed/ignored by the placeholder templater. For instance, 

> USE ${flyway:database}.test_schema;
> 
> CREATE OR REPLACE STAGE stg_data_export_${env_name}
> URL = 's3://${s3_data_lake_bucket}/${env_name}/exports/stg_data_export'
> STORAGE_INTEGRATION = s3_integ_main;

Above code uses named params: env_name, s3_data_lake_bucket and also flyway variable "flyway:database".
Sqlfluff Parser would fail with any of the built in templaters such as placeholder (dollar?) or jinja

### Use case

sqlfluff parse command should successfully interpret sql's embedded with flyway style placeholders

### Dialect

snowflake (possibly others?)

### Are you willing to work on and submit a PR to address the issue?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by asears** [comment]
This also applies to Databricks/Spark SQL.
