### ISSUE TITLE
Source link on SQLFluff website doesn't lead to the main repository

### ISSUE THREAD

**Issue by imrehg** [sqlfluff/sqlfluff#4065]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### Links or command line

The `Source` link from https://www.sqlfluff.com/ leads to https://github.com/alanmcruickshank/sqlfluff (an apparent fork that is behind in changes) rather than this repository. It is rather confusing behaviour, if one's looking for releases, latest changes, and just in general the repository to contribute to.

Is this behaviour intended?

### Issue/Suggested Improvement

Link to the main repository from the source link.

### Are you willing to work on and submit a PR to address the issue?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by greg-finley** [comment]
Thanks! Could you raise the issue or submit a PR at this repo? https://github.com/sqlfluff/sqlfluff.com

**Comment by imrehg** [comment]
@greg-finley I'd love to, but I cannot see that repository. Is it a typo or private repo?

**Comment by greg-finley** [comment]
Oh, my bad! It’s private. I’ll do the change. Thanks for reporting this. 👍

**Comment by safareli** [comment]
it's still not fixed

**Comment by tunetheweb** [comment]
Reopening this, until we can make that other repo public.

**Comment by pnadolny13** [comment]
Confirming this is still not fixed. I was linked to https://github.com/alanmcruickshank/sqlfluff

**Comment by alanmcruickshank** [comment]
This is now resolved. 👍 

For anyone who cares - the source for the sqlfluff.com site is also now a public repo: https://github.com/sqlfluff/sqlfluff.com
