### ISSUE TITLE
(Postgres) Support CREATE OR REPLACE MATERIALIZED VIEW

### ISSUE THREAD

**Issue by workflow** [sqlfluff/sqlfluff#4069]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### Description

`CREATE OR REPLACE VIEW` is already supported in Postgres, but `CREATE OR REPLACE MATERIALIZED VIEW` leads to:

```
L:   1 | P:   1 |  PRS | Line 1, Position 1: Found unparsable section: 'CREATE OR
                       | REPLACE MATERIALIZED VIEW with...'
```

### Dialect

Postgres (with https://materialize.com/)

### Are you willing to work on and submit a PR to address the issue?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by davetapley** [comment]
Ah, there, is, this issue is specifically the `OR REPLACE` part:

https://github.com/sqlfluff/sqlfluff/blob/5df82444cc94c3628437c8076f57ceb65a7832c9/test/fixtures/dialects/postgres/postgres_create_materialized_view.sql#L1-L7
