### ISSUE TITLE
Multiple processes not used when list of explicit filenames is passed

### ISSUE THREAD

**Issue by xhochy** [sqlfluff/sqlfluff#4077]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### What Happened

When providing a long list of file names to `sqlfluff lint -p -1`, only a single CPU is used. This seems to stem from the fact that https://github.com/sqlfluff/sqlfluff/blob/a006378af8b670f9235653694dbcddd4c62d1ab9/src/sqlfluff/core/linter/linter.py#L1190 is iterating over the list of files. For each listed path there, it would run the found files in parallel. As we are inputting whole filenames here, a path equals a single file and thus `sqlfluff` would only process one file at a time.

The context here is the execution of `sqlfluff lint` inside a `pre-commit` hook.

### Expected Behaviour

All CPU cores are used as `-p -1` is passed on the commandline.

### Observed Behaviour

Only a single CPU core is used.

### How to reproduce

Run `sqlfluff lint -p -1` with a long list of files.

### Dialect

Affects all. 

### Version

1.4.2

### Configuration

None.

### Are you willing to work on and submit a PR to address the issue?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by fmms** [comment]
I have been wondering for some time why sqlfluff never manages to use 100% of CPU. Running it on my Code base takes about 90 minutes. Though never more than 30% of cpu is used…

**Comment by alanmcruickshank** [comment]
Yeah - this looks like an accurate diagnosis. Most of the testing for the multiprocessing feature was done on large projects of multiple files, but _where a single path was passed_ e.g. `sqlfluff lint .`.

This seems like a very sensible improvement for people using the commit hook.

@barrywhart - you did a lot of the original multiprocessing work. Reckon you could take this one on?

**Comment by barrywhart** [comment]
I'll take a look, sure!

**Comment by barrywhart** [comment]
I have a PR which I think will fix this. I don't have access to a SQL project with lots of files. Can one of you test it, @xhochy, @fmms, or @alanmcruickshank?

PR #4084

**Comment by barrywhart** [comment]
I'm seeing some test failures in the PR. Maybe hold off testing this until those are fixed. (Hopefully by Monday!)

**Comment by barrywhart** [comment]
Ok, test failures fixed. I think the fix is good. Status bar output changes slightly, but hopefully for the better. (One less level of nesting.)

**Comment by fmms** [comment]
> I have a PR which I think will fix this. I don't have access to a SQL project with lots of files. Can one of you test it, @xhochy, @fmms, or @alanmcruickshank?

@barrywhart i have tested it today and that is awesome! Thanks!

**Comment by xhochy** [comment]
Thank you, this is working nicely!
