### ISSUE TITLE
diff-qualify to take advantage of multiple processes

### ISSUE THREAD

**Issue by nhrebinka** [sqlfluff/sqlfluff#4094]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### Description

We have compared partial linting (`diff-qualify`) with a full linting (`sqlfluff lint . --processes 4`) on a dbt project with 2200+ models and full linting works faster than `diff-qualify`. More details in this thread https://getdbt.slack.com/archives/CV2KM39KR/p1668983672332239

### Use case

Looking for a faster partial linting. Parallel processing might be a good addition to `diff-qualify`.

### Dialect

snowflake

### Are you willing to work on and submit a PR to address the issue?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by barrywhart** [comment]
`diff-quality` calls SQLFluff one file at a time. In order to take advantage of parallel processing, SQLFluff would need to be passed multiple files at the same time. This will require changes to `diff-quality`.

**Comment by barrywhart** [comment]
I created a PR to the `diff-cover` project to allow plugins to process multiple files in one call.

https://github.com/Bachmann1234/diff_cover/pull/300

If the PR is approved, merged, and released, then the SQLFluff enhancement can be implemented.

**Comment by barrywhart** [comment]
@nhrebinka: I have a PR that works in my tests. Can you try it?

https://github.com/sqlfluff/sqlfluff/pull/4132

I still need to add automated tests before it can be merged and released.
