### ISSUE TITLE
Intellij plugin

### ISSUE THREAD

**Issue by dalgarins** [sqlfluff/sqlfluff#4096]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### Description

Hi, I only wanted let you know I have created a plugin for intellij to use sqlfluff.

https://plugins.jetbrains.com/plugin/20494-sqlfluff-linter-community-edition-

### Dialect

ansi

### Are you willing to work on and submit a PR to address the issue?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by greg-finley** [comment]
Thanks, sounds awesome! 🙌 

In the linked issue, I put a task for someone to document these somewhere.
