### ISSUE TITLE
sqlfluff-lint: error on snowflake exclude keyword

### ISSUE THREAD

**Issue by vaidajakoniene** [sqlfluff/sqlfluff#4102]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### What Happened

Snowflake recently added exclude/rename to the select query syntax. Most likely this syntax is not supported by SQLFluff yet. 

sqlfluff-lint returns error for the below dbt script

reqs_joined as (

    select

        reqs_base.*,
        iso_code.* exclude req_jv_id,
        workforce.* exclude req_jv_id

    from reqs_base

    left join iso_code on reqs_base.req_jv_id = iso_code.req_jv_id
    left join workforce on reqs_base.req_jv_id = workforce.req_jv_id

),

### Expected Behaviour

sqlfluff-lint accepts the above script

### Observed Behaviour

sqlfluff-lint error

== [models/analytics/requisition_hr.sql] FAIL
L: 461 | P:  25 | L012 | Implicit/explicit aliasing of columns.
L: 461 | P:  33 |  PRS | Line 453, Position 33: Found unparsable section:
                       | 'req_jv_id,\n prep_workforce.* excl...'

### How to reproduce

Write a dbt script that is similar to the earlier mentioned script

### Dialect

snowflake

### Version

==== sqlfluff ====
sqlfluff:                1.0.0 python:                 3.11.0
implementation:        cpython verbosity:                   1
dialect:             snowflake templater:               jinja
rules:                                all

dbt version installed: 1.1.1

### Configuration

.sqlfluff

[sqlfluff]
verbose = 1
dialect = snowflake
exclude_rules = L039

[sqlfluff:templater:jinja]
apply_dbt_builtins = True
library_path = sqlfluff_libs

[sqlfluff:rules]
tab_space_size = 4
max_line_length = 120
indent_unit = space
comma_style = trailing

### Are you willing to work on and submit a PR to address the issue?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by moreaupascal56** [comment]
Hey there, I think I'll open a PR for this because even if I don't like the usage of exclude, my team does not agree with me 😭
