### ISSUE TITLE
Rule 34 : SQlfluff doesn't ignore this rule for INSER INTO statements

### ISSUE THREAD

**Issue by KaoutherElhamdi** [sqlfluff/sqlfluff#4105]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### What Happened

Check this [SLACK conversation](https://sqlfluff.slack.com/archives/C01GPHR8J0G/p1669195341860829)
# Context : 
- Templater : Jinja
- Dialect : Snowflake

# What goes wrong ? : 
The rule 34 is meant to order the fields into a select statement : wildcards, simple targets then aggregations
It's a cool feature but this causes a problem when reordering fields during an INSERT INTO statement 

I took a look on your code and I saw that you already thought about something like this
[check code](https://github.com/sqlfluff/sqlfluff/blob/main/src/sqlfluff/rules/L034.py#L86-L88)

But Unfortunately this is not working as it should
Indeed whenever there is a `WITH` clause between the `INSERT INTO` and the `SELECT` 
SQLfluff struggles and doesn't always succeed in detecting it as an INSERT statement to ignore this rule

# How does SQLfluff performs ? : 
We have 2 cases : 
- INSERT INTO directly followed by a SELECT : 
```
INSERT INTO my_table
SELECT ( field1, field2 , ..) FROM ...
```
In this case SQLfluff can understand that it is an `INSERT` statement and it won't reorder the fields based on **L034** in the `SELECT`

- When there is a CTE in between (WITH clause) : 
```
INSERT INTO my_table
WITH my_cte AS (SELECT ...)
SELECT ( field1, field2 , ..) FROM ...
```
OR
```
INSERT INTO my_table
WITH my_cte AS (SELECT ...),
my_second_cte AS (SELECT ...) 
SELECT ( field1, field2 , ..) FROM ...
```

In this case **SQLFLUFF** struggles a lot and sometimes it detects it as an `INSERT` but many times it doesn't and it applied the rule **L034** which causes a lot of problems

### Expected Behaviour

Make sure SQLfluff can always detect an `INSERT` statement to not apply the rule L034

### Observed Behaviour

Whenever there is a `WITH` clause between the `INSERT INTO` and the `SELECT` 
SQLfluff struggles and doesn't always succeed in detecting it as an INSERT statement to ignore this rule

### How to reproduce

`sqlfluff fix` for :
```
INSERT INTO my_table
WITH my_cte AS (SELECT ...)
SELECT ( field1, field2 , ..) FROM ...
```
OR
```
INSERT INTO my_table
WITH my_cte AS (SELECT ...),
my_second_cte AS (SELECT ...) 
SELECT ( field1, field2 , ..) FROM ...
```

### Dialect

Snowflake

### Version

1.4.2

### Configuration

[sqlfluff]
dialect = snowflake
exclude_rules = L029, L031
fix_even_unparsable = False

### Are you willing to work on and submit a PR to address the issue?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by barrywhart** [comment]
Reproduced with this test query:
```
INSERT INTO my_table
WITH my_cte AS (SELECT * FROM t1)
SELECT MAX(field1), field2
FROM t1
```
