### ISSUE TITLE
Snowflake, Postgres: Parse failure on concatention operator `||`

### ISSUE THREAD

**Issue by ixti** [sqlfluff/sqlfluff#4164]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### What Happened

Concatenate operand `||` incorrectly parsed as two pipes. Both Snowflake and Postgres recognize `||` as concatenation operand, thus `'a' || 'b' -- => 'ab'`. SQLFluff blames it's incorrect syntax.

### Expected Behaviour

`'a' || 'b'` should pass linting

### Observed Behaviour

`'a' || 'b'` fails linting with:

> Expected single whitespace between pipe '|' and pipe '|'.

### How to reproduce

echo "SELECT 'a' || 'b' AS c;" | sqlfluff lint --dialect postgres --disable-progress-bar -
echo "SELECT 'a' || 'b' AS c;" | sqlfluff lint --dialect snowflake --disable-progress-bar -

### Dialect

Snowflake
Postgres

### Version

sqlfluff, version 1.4.3
Python 3.10.9

### Configuration

[sqlfluff]
templater = jinja

### Are you willing to work on and submit a PR to address the issue?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by dondupont** [comment]
I am experiencing this as well. The double pipe concatenation operator is being split into two and is causing the query to fail during execution.

**Comment by kyanscienceman** [comment]
Experiencing this as well in BigQuery. Looks like `|` and `||`are both valid BigQuery operators, so makes sense why it's happening, though I'm not sure why this only started being an issue in v1.4.3. For now we disabled L006 in our repo as a workaround.

**Comment by tunetheweb** [comment]
Just go this too. Submitting a fix.

**Comment by tunetheweb** [comment]
SQLFluff 1.4.4 has been released with this fixed in it.

Apologies!

**Comment by ixti** [comment]
@tunetheweb thank you!
