### ISSUE TITLE
Unexpected exception: tuple index out of range

### ISSUE THREAD

**Issue by Jaxing** [sqlfluff/sqlfluff#4184]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### What Happened

One of the lint errors I get is this:
L:  53 | P:  46 | L007 | Unexpected exception: tuple index out of range; Could
                       | you open an issue at
                       | https://github.com/sqlfluff/sqlfluff/issues ? You can
                       | ignore this exception for now, by adding '-- noqa: L007'
                       | at the end of line 53

### Expected Behaviour

To not get it :smile: 

### Observed Behaviour

I got it

### How to reproduce

I have this snippet in my code:
```sql
        tracks_metadata.event_id is not null and  -- line 53
        {% if is_incremental() -%}tracks_metadata.loaded_to_bq_at >= '{{ last_loaded_at }}' and 
        -- filter out events that are more than 3 days delayed. This should be in the hundred or low thousends for the next few years 
        -- it also means that we can filter out some of the current data making the query more effcient.
        (tracks_metadata.sent_at - tracks_metadata.original_timestamp) <= (interval 3 day) and {% endif %}
        true
```

### Dialect

bigquery

### Version

1.4.2

### Configuration

```cfg
[sqlfluff]
templater = dbt
dialect = bigquery
ignore_templated_areas = True

[sqlfluff:indentation]
indented_joins = false
indented_using_on = true
template_blocks_indent = false

[sqlfluff:templater]
unwrap_wrapped_queries = true

[sqlfluff:templater:dbt]
project_dir = dbt-annotell

[sqlfluff:rules]
tab_space_size = 4
indent_unit = space
max_line_length = 140

[sqlfluff:rules:L010]
# Keywords
capitalisation_policy = lower

[sqlfluff:rules:L030]
# Function names
capitalisation_policy = lower
extended_capitalisation_policy = lower

[sqlfluff:rules:L040]
# Null & Boolean Literals
capitalisation_policy = lower


[sqlfluff:rules:L054]
# GROUP BY/ORDER BY column references
group_by_and_order_by_style = implicit
```

### Are you willing to work on and submit a PR to address the issue?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by alanmcruickshank** [comment]
Confirmed that this is still present in `2.0.0a2`. This is a more minimal query and configuration which triggers the same issue:

```sql
select * from foo
where c is not null and  -- comment
    {% if true -%}a >= b and 
    -- comment.
    {% endif %}
    true
```

```cfg
[sqlfluff]
dialect = bigquery

[sqlfluff:indentation]
template_blocks_indent = false
```

The bug is definitely linked to `template_blocks_indent`.
