### ISSUE TITLE
L011 doesn't play nice with dbt jinja tags

### ISSUE THREAD

**Issue by ruben-cit** [sqlfluff/sqlfluff#4244]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### What Happened

Rule L011 isn't working as expecting. Raising an error. Seems related to #4122 but different enough that I'm raising it seperately.

### Expected Behaviour

I expect it to just flag the syntax issue without erroring out.

### Observed Behaviour

dbt model structure of:

```sql
SELECT
    * 
FROM
    {{ source("retool", "incidents_qa") }} qa
```

Raises the following error

```bash
CRITICAL   [L011] Applying rule L011 threw an Exception: 'NoneType' object has no attribute 'working_line_pos'
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/sqlfluff/core/rules/base.py", line 512, in crawl
    res = self._eval(context=context)
  File "/usr/local/lib/python3.9/site-packages/sqlfluff/rules/L011.py", line 92, in _eval
    fixes=ReflowSequence.from_around_target(
  File "/usr/local/lib/python3.9/site-packages/sqlfluff/utils/reflow/sequence.py", line 478, in respace
    new_lint_results, new_point = point.respace_point(
  File "/usr/local/lib/python3.9/site-packages/sqlfluff/utils/reflow/elements.py", line 454, in respace_point
    segment_buffer, results = handle_respace__inline_with_space(
  File "/usr/local/lib/python3.9/site-packages/sqlfluff/utils/reflow/respace.py", line 299, in handle_respace__inline_with_space
    next_block.segments[0].pos_marker.working_line_pos,
AttributeError: 'NoneType' object has no attribute 'working_line_pos'
```

Interestingly, if I include the explicit alias:

```sql
SELECT
    * 
FROM
    {{ source("retool", "incidents_qa") }} AS qa
```

it works fine

### How to reproduce

1. Create `test.sql` file with the above included sql snippets
2. Include `.sqlfluff` and `.sqlfluffignore` files from below
3. Run `sqlfluff lint test.sql`

I don't know if it's needed to setup the dbt python requirements. Can follow-up on that if need be.

### Dialect

BigQuery

### Version

sqlfluff, version 1.4.5

### Configuration

`.sqlfluff`
```yml
[sqlfluff]
dialect = bigquery
templater = dbt

# L032 - Prefer specifying join keys instead of using USING.
#        Excluded because USING works fine in BQ
# L034 - Select wildcards then simple targets before calculations and aggregates.
#        Excluded because of our pattern of leading w/ event_date coercion
exclude_rules = L032, L034

[sqlfluff:rules]
max_line_length = 100

[sqlfluff:rules:L010]
capitalisation_policy = upper

[sqlfluff:rules:L038]
select_clause_trailing_comma = require

[sqlfluff:rules:L051]
fully_qualify_join_types = inner

[sqlfluff:templater:dbt]
project_dir = /root/dbt
profiles_dir = /root/.dbt
profile = default
target = dev
apply_dbt_builtins = True

# From https://docs.sqlfluff.com/en/stable/layout.html#aligned-elements
[sqlfluff:layout:type:alias_expression]
# We want non-default spacing _before_ the alias expressions.
spacing_before = align
# We want to align them within the next outer select clause.
# This means for example that alias expressions within the FROM
# or JOIN clause would _not_ be aligned with them.
align_within = select_clause
# The point at which to stop searching outward for siblings, which
# in this example would likely be the boundary of a CTE. Stopping
# when we hit brackets is usually a good rule of thumb for this
# configuration.
align_scope = bracketed
```

`.sqlfluffignore`

```yml
target/
# dbt >=1.0.0
dbt_packages/
macros/
```

### Are you willing to work on and submit a PR to address the issue?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by alanmcruickshank** [comment]
@ruben-cit - I'm unable to replicate this issue on 1.4.5, however there have been several recent bugfixes on this patch of code. Could you try installing the current alpha release to see if it resolves the issue (`2.0.0a2`)? I understand if you don't want to run an alpha release in production yet, but it would be useful to know if this bug is still outstanding.
