### ISSUE TITLE
'diff-quality --violations sqlfluff' hangs when there's no changed SQL

### ISSUE THREAD

**Issue by StepienTomasz** [sqlfluff/sqlfluff#4256]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### What Happened

When running the below command (either locally or from a Github action) comparing the branches with identical sqlfiles, the command hangs until keyboard interrupt.

```
diff-quality --violations sqlfluff --compare-branch main --fail-under=100
```

This issue prevents us from upgrading Sqlfluff version in our ci/cd pipeline - we want the check to pass with no error when there are no changes. 

### Expected Behaviour

Get the output like this (sqlfluff==1.4.2, diff-cover==7.2.0)

```
$ diff-quality --violations sqlfluff --compare-branch main --fail-under=100
-------------
Diff Quality
Quality Report: sqlfluff
Diff: main...HEAD, staged and unstaged changes
-------------
No lines with quality information in this diff.
-------------
```

### Observed Behaviour

When running the below command (either locally or from a Github action) comparing the branches with identical sqlfiles, the command hangs until keyboard interrupt.

```
diff-quality --violations sqlfluff --compare-branch main --fail-under=100
```

### How to reproduce

```
pip3 install sqlfluff==1.4.5
git checkout -b identical_branch
diff-quality --violations sqlfluff --compare-branch main --fail-under=100
```

### Dialect

Snowflake, but doesn't really matter I guess 

### Version

Python 3.10.6 (main, Aug 10 2022, 11:40:04) [GCC 11.3.0] on linux

sqlfluff, version 1.4.3
sqlfluff, version 1.4.4
sqlfluff, version 1.4.5

### Configuration

no .sqlfluff or .sqlfluffignore files

### Are you willing to work on and submit a PR to address the issue?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by barrywhart** [comment]
Can you test this on the latest version, 2.0.0a2? The `diff-quality` integration has been completely rewritten since 1.4.2.
