### ISSUE TITLE
Support PostGIS operators

### ISSUE THREAD

**Issue by Nate-Wessel** [sqlfluff/sqlfluff#4260]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### Description

Most of our needs are well handled by the PostgreSQL dialect, but there is at least one operator (`<->`) specific to PostGIS that keeps causing parsing to fail. I suspect at least a few of the other operators would cause similar problems, though I just haven't encountered them much in my code yet. 

https://postgis.net/docs/reference.html#Operators

Another issue (https://github.com/sqlfluff/sqlfluff/issues/1290) led to PostGIS data types being included in the postgres dialect, but perhaps it would be better and more accurate to spin off a PostGIS sub-dialect. 

### Use case

I would love for SQLFluff to fully support PostgreSQL's PostGIS extension. 

### Dialect

PostgreSQL

### Are you willing to work on and submit a PR to address the issue?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by mjumbewu** [comment]
@Nate-Wessel Have you started working on a PR for this yet? I was running into this as well, and wondered whether I should start on one.

**Comment by Nate-Wessel** [comment]
@mjumbewu I started looking into the code to see if this would be an easy fix.. but I admit I got a bit overwhelmed for the time and gave it up. It would be great if you could start and I'd be happy to support if you like to the extent that I can.
