### ISSUE TITLE
2.0.0a3: Inline comments confusing `WHERE` indentation and line breaks

### ISSUE THREAD

**Issue by dmohns** [sqlfluff/sqlfluff#4294]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### What Happened

The indentation of a `WHERE` statement (probably affects other areas as well) is getting indented differently based of the existence of an inline comment.

### Expected Behaviour

```sql
SELECT *
FROM table
WHERE 
    TRUE  -- some comment
    AND TRUE
```

This expected behaviour is based on the lint result of the same query without the comment

```sql
SELECT *
FROM table
WHERE
    TRUE
    AND TRUE
```

### Observed Behaviour

```sql
SELECT *
FROM table
WHERE TRUE  -- some comment
AND TRUE
```

### How to reproduce

Run lint/fix on any of the queries above.

### Dialect

BigQuery (but probably applies to all dialects)

### Version

sqlfluff, version 2.0.0a3

### Configuration

default

### Are you willing to work on and submit a PR to address the issue?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by alanmcruickshank** [comment]
I've dug into this issue a little and I think I've clarified the issue:
- *Both* the _Expected_ and _Observed_ query are currently accepted by L003 in 2.0.0a3 (and on `main` as of writing this).
- When the comment is removed, only the indented version is accepted, and the unindented version is fixed to that when `fix` is run.

The question here, is why the comment prevents the detection of the missing indent.

**Comment by the-kevin-kong** [comment]
2.0.0a4 Not sure if this is related but I am getting failures when linting depending on the positioning of the comments
Failure: `P:   5 | L003 | Expected line break and indent of 4 spaces before 'some_table'.`

Offending syntax:
```sql
select
    some_cte.date as date_day
    , some_table.*
from some_table
-- some comment
left join some_cte
    on some_cte.date between some_table.start_date and some_table.end_date
```
Passes:
```sql
-- some comment
select
    some_cte.date as date_day
    , some_table.*
from some_table
left join some_cte
    on some_cte.date between some_table.start_date and some_table.end_date
```
Passes:
```sql
select
    some_cte.date as date_day
    , some_table.*
-- some comment
from some_table
left join some_cte
    on some_cte.date between some_table.start_date and some_table.end_date
```
Passes but unexpected behavior:
```sql
select
    some_cte.date as date_day
    , some_table.*
from
    some_table
-- some comment
left join some_cte
    on some_cte.date between some_table.start_date and some_table.end_date
```

**Comment by alanmcruickshank** [comment]
Yes this is exactly the same issue 👍

**Comment by alanmcruickshank** [comment]
@the-kevin-kong - actually, your issue is more related to #4291 rather than to this one. Both need fixing however.
