### ISSUE TITLE
New dialect: Trino

### ISSUE THREAD

**Issue by efung** [sqlfluff/sqlfluff#4296]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### Description

Support Trino as an SQL dialect.

I did see a [previous discussion](https://github.com/sqlfluff/sqlfluff/issues/2168) and pull request about adding AWS Athena support.  That discussion and the PR looks like a good starting point. 

### Use case

Be able to lint queries in IDEs like IntelliJ IDEA or DataGrip (via sqlfluff plugin).

### Dialect

Trino: https://trino.io/docs/current/language.html

### Are you willing to work on and submit a PR to address the issue?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by efung** [comment]
I would have some time hopefully next month to work on this.

**Comment by greg-finley** [comment]
Cool! I would even recommend shipping a single new operation, just to get the momentum going.

**Comment by efung** [comment]
- [ ] Date/time `INTERVAL` syntax differs from ANSI or Postgres, e.g. `date '2012-08-08' + interval '2' day`
- [ ] `VALUES` lists do not have to be parenthesized, e.g. `VALUES 1, 7, 14, 15, 30`

**Comment by abhiaagarwal** [comment]
@efung are you still working on this, by chance? Willing to take over your work if not.

**Comment by efung** [comment]
> @efung are you still working on this, by chance? Willing to take over your work if not.

Not anymore. I will publish a pull request with what we were able to accomplish a few months ago.

**Comment by wjhrdy** [comment]
I've found a problem with the trino dialect. the `within` keyword in trino is not treated as a keyword.

**Comment by greg-finley** [comment]
@wjhrdy Thanks. Are you willing to attempt a fix? If not, could you please give an example query that doesn't parse correctly? Probably best to do in a new issue.

**Comment by wjhrdy** [comment]
I'll make a new issue with a repeatable example

**Comment by wjhrdy** [comment]
https://github.com/sqlfluff/sqlfluff/issues/5367

**Comment by WittierDinosaur** [comment]
Closing as Trino is live
