### ISSUE TITLE
Rule L067 bug when going from CAST to double-colon (::)

### ISSUE THREAD

**Issue by vicsteiner** [sqlfluff/sqlfluff#4301]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### What Happened

When applying the fix to a query rule Rule_L067 was applied but the output SQL was not equivalent in behaviour and when executed issued an error.

### Expected Behaviour

It went from 

`CAST(calendar_date||' 11:00:00' AS TIMESTAMP) AS calendar_datetime` 

to 

`(calendar_date || ' 11:00:00')::TIMESTAMP AS calendar_datetime`.

### Observed Behaviour

It went from 

`CAST(calendar_date||' 11:00:00' AS TIMESTAMP) AS calendar_datetime` 

to 

`calendar_date || ' 11:00:00'::TIMESTAMP AS calendar_datetime`.

### How to reproduce

```
import sqlfluff

sql = """SELECT id::INT
     , CAST(calendar_date||' 11:00:00' AS TIMESTAMP) AS calendar_datetime
FROM dw.stg_smartbidding
;
"""    

fix_result = sqlfluff.fix(sql, dialect="snowflake", config_path=".sqlfluff")

print(f"Fix output:\n\n{fix_result}\n")
```

### Dialect

snowflake

### Version

1.4.5

### Configuration

[sqlfluff]
dialect = snowflake
exclude_rules = L031,L034,L043

[sqlfluff:layout:type:comma]
line_position = leading

[sqlfluff:rules:L003]
indent_unit = space
tab_space_size = 4

[sqlfluff:rules:L004]
indent_unit = space
tab_space_size = 4

[sqlfluff:rules:L010]
capitalisation_policy = upper

[sqlfluff:rules:L014]
extended_capitalisation_policy = lower

[sqlfluff:rules:L016]
ignore_comment_lines = True
indent_unit = space
max_line_length = 120
tab_space_size = 4

[sqlfluff:rules:L030]
capitalisation_policy = upper

[sqlfluff:rules:L040]
capitalisation_policy = upper

[sqlfluff:rules:L052]
multiline_newline = True

### Are you willing to work on and submit a PR to address the issue?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by fmms** [comment]
@borchero i believe you are the one that knows one of my favorite rules best ...

**Comment by borchero** [comment]
Hmm, I haven't really worked with this rule yet 😅 maybe I can have a look at this though in the next 1-2 weeks

**Comment by fmms** [comment]
Oops sorry that was @bolajiwahab in #3747
