### ISSUE TITLE
New Rule: Prefer CREATE/ALTER/DROP DATABASE than CREATE/ALTER/DROP SCHEMA

### ISSUE THREAD

**Issue by yoichi** [sqlfluff/sqlfluff#4312]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### Description

In MySQL, Hive and SparkSQL, `CREATE/ALTER/DROP SCHEMA` are equivalent to `CREATE/ALTER/DROP DATABASE`.
I'd like to add a rule to prefer using `CREATE/ALTER/DROP DATABASE` on these dialects.

https://dev.mysql.com/doc/refman/8.0/en/create-database.html
https://cwiki.apache.org/confluence/display/hive/languagemanual+ddl#LanguageManualDDL-Create/Drop/Alter/UseDatabase
https://spark.apache.org/docs/latest/sql-ref-syntax-ddl-create-database.html

### Dialect

mysql, hive, sparksql

### Are you willing to work on and submit a PR to address the issue?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by tunetheweb** [comment]
This could be implemented with a block list using [rule L062](https://docs.sqlfluff.com/en/stable/rules.html#sqlfluff.rules.Rule_L062), rather than as a dedicated rule. In that rule description we use the example of `BOOL` over `BOOLEAN` but same applies here no?

**Comment by yoichi** [comment]
> This could be implemented with a block list using [rule L062](https://docs.sqlfluff.com/en/stable/rules.html#sqlfluff.rules.Rule_L062), rather than as a dedicated rule. In that rule description we use the example of `BOOL` over `BOOLEAN` but same applies here no?

Agree. Thank you for your useful information.
