### ISSUE TITLE
Parse error for TSQL function SYSTEM_USER

### ISSUE THREAD

**Issue by DerIltis** [sqlfluff/sqlfluff#4321]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### What Happened

Consider the following valid TSQL statement:

`DECLARE @sys_usr NVARchar(30) = SYSTEM_USER; 
`
When I call sqlfluff via this python code:

```
sql = 'DECLARE @sys_usr NVARchar(30) = SYSTEM_USER;  '
structure = sqlfluff.parse(sql, "tsql")
```

I receive the following error

> Traceback (most recent call last):
>   File "C:\Users\mbechman\PycharmProjects\pythonProject\main.py", line 28, in <module>
>     structure = sqlfluff.parse(sql, "tsql")
>   File "C:\Users\mbechman\PycharmProjects\pythonProject\venv\lib\site-packages\sqlfluff\api\simple.py", line 156, in parse
>     raise APIParsingError(parsed.violations)
> sqlfluff.api.simple.APIParsingError: Found 1 issues while parsing string.
> Line 1, Position 30: Found unparsable section: ' = SYSTEM_USER;  '
> 

### Expected Behaviour

As the SYSTEM_USER function is defined by Microsoft:

https://learn.microsoft.com/en-us/sql/t-sql/functions/system-user-transact-sql?view=sql-server-ver16

and this function was mentioned in an sqlfluff issue that was closed: https://github.com/sqlfluff/sqlfluff/issues/3583

I would have expected that parsing is possible

### Observed Behaviour

See above

### How to reproduce

```
sql = 'DECLARE @sys_usr NVARchar(30) = SYSTEM_USER;  '
structure = sqlfluff.parse(sql, "tsql")
```

### Dialect

tsql

### Version

0.9.0

### Configuration

None

### Are you willing to work on and submit a PR to address the issue?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by AidanHarveyNelson** [comment]
I can see that while it was listed as a keyword it wasn't included as a bare_function.

Have submitted a PR to fix this https://github.com/sqlfluff/sqlfluff/pull/4351
