### ISSUE TITLE
Unexpected exception: Unexpected within constraint: single for frozenset({'base, 'comparison_operator'})

### ISSUE THREAD

**Issue by rramos22** [sqlfluff/sqlfluff#4323]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### What Happened

Ran sqlfluff lint and got this after it compiled
![Screenshot 2023-01-26 at 11 16 22 AM](https://user-images.githubusercontent.com/75861826/214928771-fe02670b-30ac-4a6c-80a7-9161bbb628ce.png)

### Expected Behaviour

For this not to happen?

### Observed Behaviour

Well first of all there is no trailing whitespace in L: 1 P:1 , so this rule shouldn't be erroring out

### How to reproduce

Just ran `sqlfluff lint` on multiple models. 

### Dialect

Snowflake

### Version

sqlfluff, version 1.4.5

### Configuration

[sqlfluff]
templater = dbt
dialect = snowflake
sql_file_exts = .sql
rules = all
exclude_rules = L002, L003, L004, L007, L009, L015, L016, L018, L022, L024, L029, L031, L032, L033, L034, L035, L036, L037, L038, L039, L043, L044, L047, L050, L052, L053, L056, L057, L058, L059, L062, L063, L064, L066
ignore_templated_areas = false
large_file_skip_byte_limit = 0

[sqlfluff:indentation]
indented_ctes = false
indented_joins = false
indented_using_on = true
indented_on_contents = false
template_blocks_indent = true
tab_space_size = 1

[sqlfluff:layout:type:comma]
line_position = leading

[sqlfluff:layout:type:alias_expression]
spacing_before = single

[sqlfluff:layout:type:binary_operator]
spacing_within = single
spacing_after = single

[sqlfluff:layout:type:comparison_operator]
spacing_within = single
spacing_after = single
spacing_before = single

[sqlfluff:layout:type:set_operator]
line_position = alone:strict

[sqlfluff:layout:type:start_bracket]
spacing_before = single
spacing_after = touch

[sqlfluff:layout:type:end_bracket]
spacing_before = touch

[sqlfluff:layout:type:start_square_bracket]
spacing_before = single
spacing_after = single

[sqlfluff:layout:type:end_square_bracket]
spacing_before = single

[sqlfluff:layout:type:casting_operator]
spacing_before = touch
spacing_after = touch

[sqlfluff:layout:type:assignment_operator]
spacing_within = single

[sqlfluff:rules:L010]
capitalisation_policy = lower

[sqlfluff:rules:L011]
aliasing = explicit

[sqlfluff:rules:L012]
aliasing = explicit

[sqlfluff:rules:L013]
allow_scalar = False

[sqlfluff:rules:L014]
extended_capitalisation_policy = lower

[sqlfluff:rules:L026]
force_enable = true

[sqlfluff:rules:L028]
force_enable = true
single_table_references = consistent

[sqlfluff:rules:L030]
capitalisation_policy = lower

[sqlfluff:rules:L040]
capitalisation_policy = lower

[sqlfluff:rules:L042]
forbid_subquery_in = both

[sqlfluff:rules:L051]
fully_qualify_join_types = inner

[sqlfluff:rules:L054]
group_by_and_order_by_style = consistent

[sqlfluff:rules:L067] 
preferred_type_casting_style = shorthand

### Are you willing to work on and submit a PR to address the issue?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by alanmcruickshank** [comment]
Interesting error. That comes from setting the following config value:

```cfg
[sqlfluff:layout:type:comparison_operator]
spacing_within = single
```

What are you expecting the behaviour to be by setting `spacing_within` to `single`? It's not an implemented option yet, but I'm curious as to what your use case is so we can support it effectively.

**Comment by rramos22** [comment]
@alanmcruickshank ohh I didn't know this wasn't supported. I think leaving to the default should be just fine for me. Thank you so much.
