### ISSUE TITLE
Adapt sqlfluff-templater-dbt to latest dbt release 1.4.x

### ISSUE THREAD

**Issue by nicor88** [sqlfluff/sqlfluff#4330]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### What Happened

I bumped to dbt-core 1.4.1 and I started to get this error:
```
ImportError: cannot import name 'CompilationException' from 'dbt.exceptions' (/Users/my-user/venv/lib/python3.9/site-packages/dbt/exceptions.py)
```

### Expected Behaviour

SQL fluff should run as usual.

### Observed Behaviour

The issue is due to the fact that there are breaking changes in dbt -> https://github.com/dbt-labs/dbt-core/releases/tag/v1.4.0

### How to reproduce

install dbt-core 1.4.0

### Dialect

athena

### Version

1.4.5

### Configuration

[sqlfluff]
dialect = athena

[sqlfluff:rules]
tab_space_size = 4
max_line_length = 120

[sqlfluff:layout:type:comma]
spacing_before = touch
line_position = trailing

[sqlfluff:rules:L010]
capitalisation_policy = lower

[sqlfluff:templater:jinja]
apply_dbt_builtins = True
load_macros_from_path=macros

### Are you willing to work on and submit a PR to address the issue?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by GabrielGLevine** [comment]
Relevant PR: https://github.com/dbt-labs/dbt-core/pull/6539

**Comment by greg-finley** [comment]
Fixed [here](https://github.com/sqlfluff/sqlfluff/pull/4317) and it's in sqlfluff `2.0.0a4`. We don't currently plan to cut a release for sqlfluff `1.4.x`.
