### ISSUE TITLE
Error: no such option: --no-safety

### ISSUE THREAD

**Issue by gajus** [sqlfluff/sqlfluff#434]
It is described in the documentation, but it does not seem to be available.

```
❯ sqlfluff fix --no-safety src/migrations/V20200903.0000__baseline.sql
Usage: sqlfluff fix [OPTIONS] [PATHS]...
Try 'sqlfluff fix --help' for help.

Error: no such option: --no-safety

```

https://docs.sqlfluff.com/en/latest/cli.html#sqlfluff-fix

**Comment by alanmcruickshank** [comment]
@gajus - the docs are unfortunately more live than the project! It's coming :).

The work is done, and it will be released in the next version. Keep an eye out for 0.3.6.

**Comment by alanmcruickshank** [comment]
@gajus - this is live now in the most recent release.

https://github.com/sqlfluff/sqlfluff/releases/tag/0.3.6

I'm going to close this issue.
