### ISSUE TITLE
Snowflake ALTER WAREHOUSE SET WAREHOUSE_SIZE='...' unparsable

### ISSUE THREAD

**Issue by rogalski** [sqlfluff/sqlfluff#4342]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### What Happened

```sql
ALTER WAREHOUSE SET WAREHOUSE_SIZE='X-LARGE';
```

Accepted by Snowflake (resizes current cluster), unaccepted by sqlfluff.

### Expected Behaviour

No parse error.

### Observed Behaviour

Parse error.

### How to reproduce

```sql
ALTER WAREHOUSE SET WAREHOUSE_SIZE='X-LARGE';
```

### Dialect

snowflake

### Version

1.4.5

### Configuration

N/A

### Are you willing to work on and submit a PR to address the issue?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by AidanHarveyNelson** [comment]
Hi the syntax you are using is incorrect.

As per the documentation https://docs.snowflake.com/en/sql-reference/sql/alter-warehouse.html when using SET parameter it looks like the following

```
ALTER WAREHOUSE [ IF EXISTS ] <name> SET [ objectProperties ]
                                         [ objectParams ]
```

Name is not an optional parameter when setting Object Properties. I have included examples commands below as well

**Comment by AidanHarveyNelson** [comment]
I can see that while the documentation https://docs.snowflake.com/en/sql-reference/sql/alter-warehouse.html mentions that name is a required field when running the SET command.

After testing the command after running `USE WAREHOUSE` command I can see that Snowflake does not throw a syntax error.

![No Warehouse Specified Command works](https://user-images.githubusercontent.com/79121034/216476915-cb2c8774-00d8-43f0-b931-7c2d671a3f4d.PNG)

Will include a PR to allow name to be optional
