### ISSUE TITLE
`select *` doesn't parse in the new `duckdb` dialect

### ISSUE THREAD

**Issue by holdenmatt** [sqlfluff/sqlfluff#4389]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### What Happened

`select * exclude...` and `select * replace...` queries work, but `select *` does not.

### Expected Behaviour

`select *` queries should parse as valid.

### Observed Behaviour

Parsing raising an error:
```
sqlfluff.api.simple.APIParsingError: Found 1 issues while parsing string.
Line 1, Position 7: Found unparsable section: ' *'
```

### How to reproduce

```
import sqlfluff
sqlfluff.parse("select * from foo", dialect="duckdb")
```

### Dialect

duckdb

### Version

sqlfluff==2.0.0a4
Python 3.10.6

### Configuration

N/A

### Are you willing to work on and submit a PR to address the issue?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by WittierDinosaur** [comment]
Fixed in #4365 - it'll be live in the next release
