### ISSUE TITLE
Single quotes don't parse in duckdb queries

### ISSUE THREAD

**Issue by holdenmatt** [sqlfluff/sqlfluff#4390]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### What Happened

The DuckDB docs/examples often use single quotes around table names. E.g. here's an example query from the DuckDB [shell](https://shell.duckdb.org/):

`SELECT count(*) FROM 'https://shell.duckdb.org/data/tpch/0_01/parquet/lineitem.parquet';`

This works if I change to double quotes, but parsing fails with single quotes.

### Expected Behaviour

Single-quoted tables in the FROM clause should be valid.

### Observed Behaviour

Parsing fails:
```
sqlfluff.api.simple.APIParsingError: Found 1 issues while parsing string.
Line 1, Position 17: Found unparsable section: "FROM 'https://shell.duckdb.org/data/tpch..."
```

### How to reproduce

```
import sqlfluff
sql = "SELECT count(*) FROM 'https://shell.duckdb.org/data/tpch/0_01/parquet/lineitem.parquet';"
sqlfluff.parse(sql, dialect="duckdb")
```

Note that this works if you instead use double-quotes:
```
sql = "SELECT count(*) FROM \"https://shell.duckdb.org/data/tpch/0_01/parquet/lineitem.parquet\";"
```

### Dialect

duckdb

### Version

sqlfluff==2.0.0a4
Python 3.10.6

### Configuration

N/A

### Are you willing to work on and submit a PR to address the issue?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by helloworldrussia** [comment]
I managed to reproduce this error in ansi, athena, bigquery, clickhouse, db2, exasol, hive, materialize, mysql, oracle, postgres, redshift. snowflake, soql, sqlite, teradata, tsql dialects
The error did not occur when using the sparksql dialect.
