### ISSUE TITLE
dbt: ImportError: cannot import name 'CompilationException' from 'dbt.exceptions' 

### ISSUE THREAD

**Issue by coca-alex** [sqlfluff/sqlfluff#4392]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### What Happened

I've tried to use sqlfluff-templater-dbt version =="2.0.0a4" with dbt-core version =="1.4.1"
But I got an Exception even I try to do `sqlfuff version -v `
`ImportError: cannot import name 'CompilationException' from 'dbt.exceptions' (/.../lib/python3.10/site-packages/dbt/exceptions.py)`

It happens because in dbt-core no CompilationException, but CompilationError
https://github.com/dbt-labs/dbt-core/blob/165035692f9d53e6609864f76090df49e8894cd7/core/dbt/exceptions.py#L192

And in SQLFluff-templater-dbt in try block  CompilationException: https://github.com/sqlfluff/sqlfluff/blob/684a30e45f589f7ece4f4ee7ccbf2e6160140f89/plugins/sqlfluff-templater-dbt/sqlfluff_templater_dbt/templater.py#L20

### Expected Behaviour

Not CompilationException -> CompilationError

### Observed Behaviour

I got an unexpected error when I used version of dbt-core later then 1.3.0

### How to reproduce

fix CompilationException -> CompilationError

### Dialect

-

### Version

2.0.0a4

### Configuration

[sqlfluff]
dialect = ansi
templater = dbt
exclude_rules = L031, L030, L014, L034

[sqlfluff:templater:dbt]
project_dir = ./

[sqlfluff:rules]
max_line_length = 140

[indentation]
tab_space_size = 2

[sqlfluff:rules:L010]
# Keywords
capitalisation_policy = upper

[sqlfluff:rules:L029]
ignore_words = name

[sqlfluff:rules:L057]
# Special Characters in Identifiers
allow_space_in_identifier = True
additional_allowed_characters = ['.','(',')','-']

### Are you willing to work on and submit a PR to address the issue?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by pdebelak** [comment]
This was fixed in #4317 . Are you sure you have both sqlfluff 2.0.0a4 and sqlfluff-templater-dbt 2.0.0a4 installed?

**Comment by WittierDinosaur** [comment]
Closing as fixed in #4317
