### ISSUE TITLE
A dead loop to fix this lint issue in 2.0.0

### ISSUE THREAD

**Issue by Hongbo-Miao** [sqlfluff/sqlfluff#4516]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### What Happened

After upgrading sqlfluff to 2.0.0. There is one issue sqlfluff cannot fix, and it is a dead loop.

### Expected Behaviour

No lint issue after fixing.

### Observed Behaviour

A dead loop to fix the lint issue.

### How to reproduce

After upgrading to sqlfluff 2.0.0,

when I run `sqlfluff lint --dialect=postgres my.sql` on

```sql
insert into iot_data (timestamp, temperature, humidity)
select
    ts,
    random() * 50 + 20 as temperature,
    random() * 50 + 50 as humidity
from (
    select generate_series(
            current_timestamp - interval '1 day',
            current_timestamp,
            interval '1 second'
        ) as ts
) as t;
```

It will show
```shell
L:   7 | P:  11 | LT02 | Expected line break and indent of 8 spaces before
                       | 'generate_series'. [layout.indent]
```

After I run `sqlfluff fix --force --dialect=postgres my.sql`, it will change to
```sql
insert into iot_data (timestamp, temperature, humidity)
select
    ts,
    random() * 50 + 20 as temperature,
    random() * 50 + 50 as humidity
from (
    select
        generate_series(
            current_timestamp - interval '1 day',
            current_timestamp,
            interval '1 second'
        ) as ts
) as t;
```

Now when I run `sqlfluff lint --dialect=postgres my.sql` again, it will show
```shell
L:   7 | P:   5 | LT09 | Select targets should be on a new line unless there is
                       | only one select target.
                       | [layout.select_targets]
```

Now if I run `sqlfluff fix --force --dialect=postgres my.sql` again, it will change back to original code again. So it is a dead loop... 🥲

### Dialect

postgres

### Version

2.0.0

### Configuration

[sqlfluff]
exclude_rules = L016

### Are you willing to work on and submit a PR to address the issue?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by dmohns** [comment]
I'm adding more examples, as I _think_ I'm encountering the same issue. But let me know if I should report them in a separate issue.

Consider this SQL

```sql
-- Violates LT02
SELECT SUM(
        1 + SUM(
            2 + 3
        )
    ) AS col
FROM test_table
;
```

is alternating to

```
-- Violates LT09
SELECT
    SUM(
        1 + SUM(
            2 + 3
        )
    ) AS col
FROM test_table
;
```

which violate `LT09` and `LT09` respectively.

**Comment by dmohns** [comment]
There is also a slightly different variation when using STRUCTs

```sql
-- Violates LT02
SELECT ARRAY<STRUCT<
    col1 STRING,
    col2 INT64
>>
    [
        ("abc", 1),
        ("def", 2)
    ] AS values
;
``` 

vs

```sql
-- Violates LT02
SELECT ARRAY<STRUCT<
        col1 STRING,
        col2 INT64
    >>
    [
        ("abc", 1),
        ("def", 2)
    ] AS values
;
```

(also BigQuery dialect)
