### ISSUE TITLE
Handle spaces differently within datatype

### ISSUE THREAD

**Issue by jonyscathe** [sqlfluff/sqlfluff#4521]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### Description

As far as I can tell this is not possible currently, but I could be wrong.

With sqlfluff==2.0.0 the datatype `NUMERIC(3, 1)` gets changed to `NUMERIC (3, 1)`

I would prefer to keep it as `NUMERIC(3, 1)` as per postgresql documentation https://www.postgresql.org/docs/current/datatype-numeric.html#DATATYPE-NUMERIC-DECIMAL

However, I can't see a way to do this other than setting start_bracket's spacing_before to 'touch' which is obviously undesirable.

### Use case

The option of having both `NUMERIC(3, 1)` and `FROM (SELECT` within the same sql file.

I understand that this one is potentially a little bit tricky.
Something similar already works for functions like `SUM(my_field)` is ok without a space before the bracket, I assume because of "sqlfluff:layout:type:function_name" having "spacing_after = touch:inline".
But if there was a sqlfuff:layout:type:data_type or something like that, it couldn't have spacing_after set to "touch:inline" because most of the time there should be a space. It is only when there is something extra like precision (or possible `[]` on the end to indicate an array) where the space isn't desirable.

If there isn't an easy fix, I guess I can live with an odd space in my datatype.

### Dialect

postgresql

### Are you willing to work on and submit a PR to address the issue?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by borchero** [comment]
Uh yes, +100, this is also the first thing I was surprised by in 2.0.0 😬

**Comment by kevinmarsh** [comment]
I also just ran into a similar issue with [declaring array types in Postgres](https://www.postgresql.org/docs/current/arrays.html#ARRAYS-DECLARATION). Going from sqlfluff 1.4.5 to 2.0.0 results in this trying to "fix" it by adding more spaces
```diff
-CREATE TABLE sal_emp (name text, pay_by_quarter integer[], schedule text[][]);
+CREATE TABLE sal_emp (name text, pay_by_quarter integer [], schedule text [] []);
```
