### ISSUE TITLE
exclude rules with new rule names through warnings and doesn't apply them

### ISSUE THREAD

**Issue by christopherekfeldt** [sqlfluff/sqlfluff#4524]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### What Happened

When using "sqlfluff format" or "sqlfluff lint / fix" sqlfluff will through a warning looking like this:

"WARNING    Tried to denylist unknown rules references: ['Rule_CP02', 'Rule_LT05', 'Rule_RF02', 'Rule_CV03', 'Rule_ST05', 'Rule_ST06', 'Rule_ST07']" 

This is my exclude_rules part under [sqlfluff]
exclude_rules = Rule_CP02,Rule_LT05,Rule_RF02,Rule_CV03,Rule_ST05,Rule_ST06,Rule_ST07

Which made it not apply our newly renamed rules to be excluded. When I set them back to use the old aliases of rule names it worked again. This was how it looked previously prior to sqlfluff 2.0.0

exclude_rules = L014,L016,L027,L032,L034,L038,L042

### Expected Behaviour

That the new rule names and aliases would work after being set in .sqlfluff config file.

### Observed Behaviour

As mentioned in "What happened"

### How to reproduce

Add new naming standard for rules and add them to your exclude_rules list. 

Run sqlfluff lint/fix/format. 

### Dialect

bigquery

### Version

sqlfluff, version 2.0.0
Python 3.8.10
sqlfluff-templater-dbt 2.0.0

### Configuration

.sqlfluff
`[sqlfluff]
templater = dbt
dialect = bigquery
verbose = 1
exclude_rules = Rule_CP02,Rule_LT05,Rule_RF02,Rule_CV03,Rule_ST05,Rule_ST06,Rule_ST07
#exclude_rules = L014,L016,L027,L032,L034,L038,L042
encoding = utf-8
#large_file_skip_byte_limit = 32000
ignore_templated_areas = True
processes = 0

[sqlfluff:indentation]
tab_space_size = 4
indent_unit = space

[sqlfluff:layout:type:comma]
line_position = trailing

[sqlfluff:rules:capitalisation.keywords]
# Rule_CP01: capitalisation of keywords
capitalisation_policy = lower

[sqlfluff:rules:capitalisation.functions]
# Rule_CP03: capitalisation of function names
extended_capitalisation_policy = lower

[sqlfluff:rules:capitalisation.literals]
# Rule_CP04: capitalisation of boolean/null literal
capitalisation_policy = lower

[sqlfluff:rules:references.keywords]
# Rule_RF04: keywords should not be used as identifiers.
# The words below are commonly used in BICA models and reports and should be ignored.
ignore_words = week,month,quarter,year,day,date,function,hour,account

[sqlfluff:templater:dbt]
project_dir = .
profiles_dir = .
profile = etlapp
target = tcm

[sqlfluff:templater:jinja]
apply_dbt_builtins = true
`

.sqlfluffignore
`target/
dbt_packages/
macros/
dbt_remote_state/
snapshots/
tests/
.venv/
`

### Are you willing to work on and submit a PR to address the issue?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by alanmcruickshank** [comment]
Hi @christopherekfeldt - you don't need the `Rule_` prefix on your new rules. It should just be `exclude_rules = CP02,LT05,RF02,CV03,ST05,ST06,ST07`. Can you check whether that works?

If you're able to point at where in the migration guide it suggested this layout that would be useful so I can update it in case anyone else falls into this trap.

**Comment by christopherekfeldt** [comment]
Ahh okey! I will close this Issue
