### ISSUE TITLE
Name for Rule_LT07 is incorrect

### ISSUE THREAD

**Issue by deanmorin** [sqlfluff/sqlfluff#4548]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### Links or command line

https://docs.sqlfluff.com/en/latest/rules.html#sqlfluff.rules.sphinx.Rule_LT07

The name for this rule is showing as `layout.functions`, which is actually the name for Rule_LT06

### Issue/Suggested Improvement

Replace with the correct name

### Are you willing to work on and submit a PR to address the issue?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by alanmcruickshank** [comment]
Good catch! thanks. 👍
