### ISSUE TITLE
Implicit indents are not allowed within WHERE clauses

### ISSUE THREAD

**Issue by borchero** [sqlfluff/sqlfluff#4559]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### What Happened

When setting `allow_implicit_indents = true` in the SQLFluff configuration, the option is not honored in `WHERE` clauses when running `sqlfluff fix`.

_Note:_ This is likely related to #4539. Thus, I believe this issue concerns clauses other than `WHERE` and `GROUP BY`.

### Expected Behaviour

The query should not be modified.

### Observed Behaviour

The query is modified to disallow implicit indents:

```sql
SELECT t.col1
FROM t
WHERE
    t.col2 = 'foo'
    AND t.col3 = 'bar'
```

### How to reproduce

Use the following SQL script:

```sql
SELECT t.col1
FROM t
WHERE t.col2 = 'foo'
    AND t.col3 = 'bar'
```

### Dialect

`tsql`

### Version

SQLFluff version 2.0.1

### Configuration

```
[sqlfluff]
dialect = tsql

[sqlfluff:indentation]
allow_implicit_indents = true
```

### Are you willing to work on and submit a PR to address the issue?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by alanmcruickshank** [comment]
I think this is a `tsql` specific bug, due to that dialect having it's own implementation of some clauses. This should be an easy fix.
