### ISSUE TITLE
Snowflake `double precision` Data Type and Space

### ISSUE THREAD

**Issue by murat-cetinkaya** [sqlfluff/sqlfluff#4572]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### What Happened

When I run SQLFluff v2.0.1 fix command it converts `double precision` data type to `doubleprecision`.

### Expected Behaviour

I expected that the code:

`someColumn AS double precision`

will be untouched.

### Observed Behaviour

With 2.0.1 with the extra space fixed within data types I now get

`someColumn AS doubleprecision`

`doubleprecision` is not going to work so well.

### How to reproduce

Have any valid Snowflake code with a double precision datatype

### Dialect

Snowflake

### Version

v2.0.1

### Configuration

-- here's what I use in my .sqlfluff config file. The rest of the configuration uses default values.

[sqlfluff]
templater = jinja
dialect = snowflake
ignore = templating

rules = layout.spacing

[sqlfluff:templater:jinja]
load_macros_from_path = macros

### Are you willing to work on and submit a PR to address the issue?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by alanmcruickshank** [comment]
Thanks for raising this bug - I can see why this is happening. I'll see if I can come up with a fix shortly.
