### ISSUE TITLE
2.0.1 - Multi-line comment causes LT02 violation on preceding line

### ISSUE THREAD

**Issue by fredriv** [sqlfluff/sqlfluff#4582]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### What Happened

In SQL with multi-line comments using `/* ... */`, SQLFluff v2.0.1 reports an LT02 indent/line break error on the preceding line.

### Expected Behaviour

I expect the SQL to validate OK. SQLFluff v1.4.5 reports no issues with the same SQL code.

### Observed Behaviour

Output from SQLFluff:
```
L:   1 | P:   7 | LT02 | Expected line break and indent of 4 spaces before 'a'.
                       | [layout.indent]
L:   8 | P:   5 | LT02 | Expected line break and indent of 4 spaces before 'a'.
                       | [layout.indent]
```

### How to reproduce

SQL file to reproduce:
```
select a.col

/*
Multi
line
comment 1
*/
from a

/*
Multi
line
comment 2
*/
inner join b
    on a.id = b.id;



select a.col

/* Single line comment 1 */
from a

/* Single line comment 2 */
inner join b
    on a.id = b.id
```

### Dialect

`ansi`

### Version

```
> sqlfluff --version
sqlfluff, version 2.0.1

> python --version
Python 3.9.9
```

### Configuration

```
[sqlfluff]
dialect = ansi
```

### Are you willing to work on and submit a PR to address the issue?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by alanmcruickshank** [comment]
Thanks for such a complete example. This is a very interesting bug. I'll pick this up.
