### ISSUE TITLE
Specify join keys - do not use using

### ISSUE THREAD

**Issue by NiallRees** [sqlfluff/sqlfluff#467]
'Certain warehouses have inconsistencies in using results (specifically Snowflake).'

Taken from the [dbt coding conventions](https://github.com/fishtown-analytics/corp/blob/master/dbt_coding_conventions.md#ctes)

**Comment by dmateusp** [comment]
Interesting! Do you know what the inconsistencies are in Snowflake ? I wasn't able to find more information

**Comment by NiallRees** [comment]
Good question, I found this:

https://community.snowflake.com/s/question/0D50Z00008WRZBBSA5/bug-with-join-using-

and

https://docs.snowflake.com/en/sql-reference/constructs/join.html

specifically 'The following example shows non-standard usage' section. It seems like it can be dangerous to use 'using' in particular situations, and I imagine an unexpected outcome as a result would be really hard to debug.

**Comment by NiallRees** [comment]
Resolved by #487
