### ISSUE TITLE
Configuring max_line_length is unclear

### ISSUE THREAD

**Issue by jamesowers-roo** [sqlfluff/sqlfluff#4670]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### Links or command line

This may be a bug, but I would like to check I'm doing things correctly. I am in a project where sqlfluff is configured inside a `pyproject.toml`, I have

```
[tool.sqlfluff]
max_line_length = 88
```

however, I keep getting LT05s:

```
L:  60 | P:  13 | LT05 | Line is too long (85 > 80).
                       | [layout.long_lines]
```

This implies that my max line length is not being respected.

### Issue/Suggested Improvement

This is probably a very common one to want to configure - please may we add a minimal working example of this configuration to the docs? I notice that there is text which says ["This is (of course) configurable"](https://docs.sqlfluff.com/en/stable/layout.html#:~:text=This%20is%20(of%20course)%20configurable): this section could link to that example!

### Are you willing to work on and submit a PR to address the issue?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by tunetheweb** [comment]
I believe it should be this [as per the docs](https://docs.sqlfluff.com/en/latest/configuration.html#:~:text=For%20the%20pyproject.toml%20file%2C%20all%20valid%20sections%20start%20with%20tool.sqlfluff):

```
[tool.sqlfluff.core]
max_line_length = 88
```
