### ISSUE TITLE
Question and ask for information about release dates.

### ISSUE THREAD

**Issue by ItamarShalev** [sqlfluff/sqlfluff#4715]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### What Happened

Thanks for all the support and quick response.
Is it possible to know when you upload the release version? 
And for now, is it possible to do it now to rebase my code and take all the bug fixes?
Since the dialect of MySQL has been fixed thanks to @yoichi.

Also,  is it possible to turn on the flag "ignore_unparsble_sections" or something like that?

### Expected Behaviour

.

### Observed Behaviour

.

### How to reproduce

.

### Dialect

mysql

### Version

.

### Configuration

.

### Are you willing to work on and submit a PR to address the issue?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by WittierDinosaur** [comment]
We are likely doing a release today or tomorrow. Generally, we release once a month of so. When we're doing bigger changes, it's less frequent, when many people commit smaller changes it's more frequent. To keep on top of all SQLFluff news, it's best to join our Slack community - we are generally pretty responsive, and we broadcast our releases there
sqlfluff.slack.com
