### ISSUE TITLE
Add dialect of OSS Spark SQL

### ISSUE THREAD

**Issue by jingyi-dd** [sqlfluff/sqlfluff#4750]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### Description

The current spark dialect contains all dialects. Can we have one purely for OSS Spark sql so that we can use it to check if there is any vendor specific syntax?

### Use case

With the new dialect of OSS Spark, we can check if the query is compatible with any Spark vendors.

### Dialect

sparksql

### Are you willing to work on and submit a PR to address the issue?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by bmorck** [comment]
Could you elaborate on what you mean by the current spark dialect containing all dialects. From my understanding the SparkSQL dialect is meant to match with the OSS. There are definitely gaps in its parsing abilities but I believe it's grammar should eventually match the OSS.

**Comment by jingyi-dd** [comment]
Hi @bmorck, thank you for the reply. SparkSQL dialect is meant to match with the OSS and it might introduce some syntax extensions. for example, in dialect_sparksql, it has some databricks-specfic syntax like colon sign casting operator which is not inherited from OSS Spark and it might not work if we run it in vendors other than databricks

**Comment by greg-finley** [comment]
Thanks for the idea, but SQLFluff is aiming to lint the SQL you have instead of raise errors for SQL that is invalid. We intentionally make some invalid SQL lintable to ease our development.
