### ISSUE TITLE
editorconfig support?

### ISSUE THREAD

**Issue by kapitanluffy** [sqlfluff/sqlfluff#4785]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### Description

I am just wondering whether sqlfluff supports editorconfig. For example if the editor config says

```editorconfig
[*.sql]
indent_size = 2
```

Will sqlfluff use the same indent size?

### Dialect

All

### Are you willing to work on and submit a PR to address the issue?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by tunetheweb** [comment]
The project uses editorconfig for our own code, but sqlfluff config (for linting) needs to be picked up from one of the [supported config file options](https://docs.sqlfluff.com/en/stable/configuration.html#configuration-files) and editorconfig is not one of those and would only allow limited support so don't think it's worth adding support for that.
