### ISSUE TITLE
`ROLLUP` Support

### ISSUE THREAD

**Issue by kazimanil** [sqlfluff/sqlfluff#4878]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### Description

My dear friend @dmohns has searched for this and only could find a similar issue [here](https://github.com/sqlfluff/sqlfluff/pull/4862) but for another dialect.

For my recent changes in the codes, I decided to use `ROLLUP` functionality of Bigquery. `AM06` rule is being raised even though all of my `GROUP BY` and `GROUP BY ROLLUP()` statements only use numerical column identifiers. I think `sqlfluff` is confused with the text of `ROLLUP()`.

### Use case

Can the linting for `bigquery` dialect be aware of `ROLLUP` and similar functions too?

### Dialect

Bigquery. @dmohns might have a specific ruleset.

### Are you willing to work on and submit a PR to address the issue?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by tunetheweb** [comment]
Yup. Because to be honest to don’t really fancy trawling through 1400+ lines of code to try to understand the issue. A minimal reproducible sample code please!

**Comment by tunetheweb** [comment]
Yes. It see's `ROLLUP(1, 2, 3, 5)` as an expression which is counts as an `explicit` reference rather than a numeric `implict` reference. Hence inconsistent. Have raised #4892 to resolve.
