### ISSUE TITLE
Improve code coverage

### ISSUE THREAD

**Issue by pwildenhain** [sqlfluff/sqlfluff#488]
Since I'm trying to make sure I don't decrease code coverage with my PRs, I've been checking out the coverage report by running `coverage html`

I noticed that most of the untested lines have to do with error handling (both for the user and developer) which, while not the most important feature, is still worth being tested.

I'm up for doing this ✅ since it will help me familarize myself more with the codebase

**Comment by alanmcruickshank** [comment]
@pwildenhain I'm considering closing this issue because of the success of your quest! https://codecov.io/gh/sqlfluff/sqlfluff

Code coverage is now ~96% across the codebase which is a pretty good place for us to be.

**Comment by pwildenhain** [comment]
Agreed! It was a noble quest indeed ⚔️
