### ISSUE TITLE
New Rule on aliasing being "useful"

### ISSUE THREAD

**Issue by JackWolverson** [sqlfluff/sqlfluff#4895]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### Description

 we wanted to enforce table aliasing to be a 'useful' alias. so if a table name is 'users' we can have 'u' as an alias but not 'a'. i dont think there is a rule that could work here as there is only using as and alias length 

### Use case

an alias like this will pass the rule 

FROM users u 
or
FROM products AS p

and an alias like this will fail 

FROM users a 

FROM products AS a 

### Dialect

all ? 

### Are you willing to work on and submit a PR to address the issue?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by fmms** [comment]
Not sure if that is really possible,
We often alias fact tables with an f. Or dimensions with the name of the entity Dim_Material m.

**Comment by greg-finley** [comment]
I appreciate the idea, but I don't think it's something we plan to support.
