### ISSUE TITLE
Parse error when using PostgreSQL positional params

### ISSUE THREAD

**Issue by ayoisaiah** [sqlfluff/sqlfluff#4899]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### What Happened

A query using positional params like this:

```sql
SELECT id FROM users WHERE username = $1;
```

Gives the following error:

```
L:   1 | P:  33 |  PRS | Line 1, Position 33: Found unparsable section: ' = $1;'
L:   1 | P:  36 |  LXR | Unable to lex characters: '$1;'
```

### Expected Behaviour

Wasn't expecting an error. Am I missing something?

### Observed Behaviour

L:   1 | P:  33 |  PRS | Line 1, Position 33: Found unparsable section: ' = $1;'
L:   1 | P:  36 |  LXR | Unable to lex characters: '$1;'

### How to reproduce

Any query containing a positional parameter:

SELECT id FROM users WHERE username = $1;

### Dialect

postgres

### Version

sqlfluff, version 2.1.1
Python 3.11.3

### Configuration

none

### Are you willing to work on and submit a PR to address the issue?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by pdecat** [comment]
Hi, you need to specify a templater for this, see https://docs.sqlfluff.com/en/stable/configuration.html#placeholder-templater

**Comment by ayoisaiah** [comment]
@pdecat Thanks a lot!
