### ISSUE TITLE
Initial SQLFluff invocation loads many unnecessary plugins

### ISSUE THREAD

**Issue by boazwasserman** [sqlfluff/sqlfluff#4917]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### What Happened

I am using sqlfluff.parse to perform validations on LLM generated SQL statements. Seems like on the first time it is called it is taking too long to run.

### Expected Behaviour

sqlfluff.parse should not take over 2 seconds on first invocation

### Observed Behaviour

The first time parse is called, it takes quite long (2-3 seconds) while following executions are much much shorter (around 1/10 of second).
This is obviously better than all invocation taking that long, but I wonder if there is a way to reduce the time of the first call as well, or maybe even know what's causing it to take so long.
I further tested this behavior by adding sqlfluff.parse("") after module load, which took the initial long time and afterwards later invocations were fast again.

### How to reproduce

Wrap each invocation of sqlfluff.parse with something simple like:
start_time = timeit.default_timer()
sqlfluff.parse("")
end_time = timeit.default_timer()
print(f"1 - The function took {end_time - start_time} seconds to complete.")

start_time = timeit.default_timer()
sqlfluff.parse("")
end_time = timeit.default_timer()
print(f"2 - The function took {end_time - start_time} seconds to complete.")

And we'll be able to see that the second time works much faster

### Dialect

ansi

### Version

sqlfluff, version 2.1.1
Python 3.9.16

### Configuration

Using default

### Are you willing to work on and submit a PR to address the issue?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by alanmcruickshank** [comment]
Hi @boazwasserman - would you be able to run one of the profiling tools (snakeviz or similar) on both of the runs to identify the biggest difference between the two? My theory is that this is driven by dialect loading, but I'd love to confirm that.

Thanks for taking the time to investigate this - I think this could help a lot of users if we can get to the bottom of it.

**Comment by alanmcruickshank** [comment]
I've done some digging using snakeviz (on just `sqlfluff.parse("")`, and this is all setup time - in particularly loading plugins. For example, even just the presence of the dbt templater as a plugin - even thought this script isn't _using_ the plugin - drastically increases runtimes. Rule plugins also add significant overhead (which given this is a _parsing_ example), feels unexpected.

I'm going to relabel this issue and see if I can reduce this one myself.
