### ISSUE TITLE
TSQL: `DROP EXTERNAL TABLE` unparsable

### ISSUE THREAD

**Issue by keen85** [sqlfluff/sqlfluff#4918]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### What Happened

Microsoft SQL Server 2016 and later supports `DROP EXTERNAL TABLE` statement:
https://learn.microsoft.com/en-us/sql/t-sql/statements/drop-external-table-transact-sql

This example from the [official TSQL documentation](https://learn.microsoft.com/en-us/sql/t-sql/statements/drop-external-table-transact-sql?view=sql-server-ver16#examples) is not parsable:
```sql
DROP EXTERNAL TABLE SalesPerson;  
DROP EXTERNAL TABLE dbo.SalesPerson;  
DROP EXTERNAL TABLE EasternDivision.dbo.SalesPerson;  
```

### Expected Behaviour

Above example should be parsable.

### Observed Behaviour

`Found unparsable section`

### How to reproduce

[see example above](https://online.sqlfluff.com/fluffed?sql=H4sIAE47h2QC_3MJ8g9QcI0IcQ3yc_RRCHF08nFVCE7MSS0OSC0qzs-zVlDg5XLBoiYlKV-PGHWuicUlqUV5LpllmcWZ-Xl6mPoA88oEUoIAAAA%3D&dialect=tsql)

### Dialect

tsql

### Version

2.1.1

### Configuration

not applicable

### Are you willing to work on and submit a PR to address the issue?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by greg-finley** [comment]
Closed via https://github.com/sqlfluff/sqlfluff/pull/4919
