### ISSUE TITLE
ST03 parsing error with a single unused CTE

### ISSUE THREAD

**Issue by llz22** [sqlfluff/sqlfluff#4923]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### What Happened

When running SQLfluff lint with dialect sparksql on the following query:

`WITH test_query AS (
    SELECT a
    FROM tableA
    LIMIT 10
)`

I would expect it to throw a "ST03: unused CTE" error. However, it instead fails to parse. 

Adding the following at the end allows it to parse, suggesting the un-parsable error stems from the unused CTE:
`SELECT * FROM test_query`

### Expected Behaviour

I would expect it to return a ST03 error, and any other applicable lint errors.

### Observed Behaviour

Running lint on the query returns an unparsable error on the first line, and does not return any other applicable linting errors. 

### How to reproduce

Running:
`sqlfluff lint test_query.sql --dialect sparksql`

on the following query:
`WITH test_query AS (
    SELECT a
    FROM tableA
    LIMIT 10
)`

Produces the parsing error.

### Dialect

sparksql

### Version

sqlfluff 2.1.1 
python 3.8.13

### Configuration

default configuration

### Are you willing to work on and submit a PR to address the issue?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by fmms** [comment]
Is that really valid sparksql?

At least for T-SQL the behaviour would be correct:
![image](https://github.com/sqlfluff/sqlfluff/assets/908734/110d3360-e94e-418e-b3a5-3f91e1432a04)

**Comment by llz22** [comment]
Would we still expect SQLfluff to catch it as an unused CTE even if the query is invalid? It is not valid sparkSQL but it is necessary to exclude the last line in our specific instance. If not, I can make a simple workaround on my end.
