### ISSUE TITLE
`extract_macros_from_config` after `extract_macros_from_path` instead of before

### ISSUE THREAD

**Issue by Ofir-Purple** [sqlfluff/sqlfluff#493]
### High level summary

Suggestion: Change the loading order of macros so that macros defined in the config file will be loaded after macros defined in path (`load_macros_from_path`). That way, macros defined in the config will take precedence and will allow the user to override macros defined in the path. 

To illustrate the point, let's consider the following `.sqlfluff` config:

```
...
[sqlfluff:templater:jinja:macros]
my_specific_macro_def = {% macro my_macro(...) %}...{% endmacro %}

[sqlfluff:templater:jinja]
load_macros_from_path=some/path/to/macros/dir
...
```

Now let's say `my_macro` is also defined somewhere in `some/path/to/macros/dir`. With the current loading order, `my_macro` will be equal to the macro defined in `some/path/to/macros/dir`. If the suggestion above is accepted, then `my_macro` will equal the definition in the section `[sqlfluff:templater:jinja:macros]`

### Reasoning

In our dbt project we use a lot of macros for all sorts of use cases and we include them with `load_macros_from_path`. When integrating sqlfluff, we wanted to override some of these default macros, but keep the rest as they are. This new behavior will allow that. This is especially useful given #335 , this helps "neutralize" problematic macros without foregoing all of the macro implementations.

### Suggested change

In https://github.com/sqlfluff/sqlfluff/blob/master/src/sqlfluff/templaters.py, in the function `process`, the code for loading macros is:

```
        # Load config macros
        ctx = self._extract_macros_from_config(config=config, env=env, ctx=live_context)
        # Load macros from path (if applicable)
        macros_path = config.get_section((self.templater_selector, self.name, 'load_macros_from_path'))
        if macros_path:
            ctx.update(self._extract_macros_from_path(macros_path, env=env, ctx=live_context))
        live_context.update(ctx)
```
 This change will have the code organized more like:

```
        ctx = {}
        # Load macros from path (if applicable)
        macros_path = config.get_section((self.templater_selector, self.name, 'load_macros_from_path'))
        if macros_path:
            ctx.update(self._extract_macros_from_path(macros_path, env=env, ctx=live_context))
        # Load config macros
        ctx.update(self._extract_macros_from_config(config=config, env=env, ctx=live_context))
        live_context.update(ctx)
```

**Comment by NiallRees** [comment]
I believe this to be resolved by #508, even though the solution is different to the one proposed here. This will be fixed in release 0.4.0
