### ISSUE TITLE
Add requirements_dev.txt for formatting/linting checks

### ISSUE THREAD

**Issue by pwildenhain** [sqlfluff/sqlfluff#496]
@pwildenhain fyi I just hit a minor issue with black, where my outdated version wasn't formatting all the files the same way that the `tox` environment did

what do you think about either having a `requirements_dev.txt` which specifies the version of black to use, or adding `pre-commit` ?

_Originally posted by @dmateusp in https://github.com/sqlfluff/sqlfluff/pull/486#issuecomment-713629122_

**Comment by alanmcruickshank** [comment]
I think I'd prefer `requirements_dev.txt` rather than a pre-commit. I've found pre-commits to be harder to maintain in the past. 👍

**Comment by pwildenhain** [comment]
sure thing 👍
