### ISSUE TITLE
Docs Aesthetics: Fork me on GitHub link - icon rendering incomplete

### ISSUE THREAD

**Issue by arnoldmashava** [sqlfluff/sqlfluff#4987]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### Links or command line

[Latest](https://docs.sqlfluff.com/en/latest/) and [Stable](https://docs.sqlfluff.com/en/stable/) Versions: the icon rendering for the [`Fork me on GitHub`](https://github.com/sqlfluff/sqlfluff) link points to an inadmissible `*.png` component: https://s3.amazonaws.com/github/ribbons/forkme_right_darkblue_121621.png - where the resultant visual stimulus emanating from that cited component in the [Docs](https://readthedocs.org/projects/sqlfluff/) is **NOT** salacious and alluring enough for the wandering eye.

![Screenshot_20230720_091908](https://github.com/sqlfluff/sqlfluff/assets/5759101/fae5dcbe-d39b-4e04-aaef-f44b7173a3ae)

### Issue/Suggested Improvement

For a quick fix, depending on the admissibility and preferences of the Author(s), incorporate into the [Documentation Builds](https://readthedocs.org/projects/sqlfluff/builds/) `source code` any of these hacks as a replacement:

1. [GitHub Ribbons](https://github.blog/2008-12-19-github-ribbons/) according to [Tom Preston-Werner](https://github.blog/author/mojombo/)

2. [GitHub Corners](https://github.com/tholman/github-corners) according to [Tim Holman](https://github.com/tholman)

3. [GitHub Animated Corners](https://github.com/eugena/github-animated-corners) according to [Eugena Mikhaylikova](https://github.com/eugena)

I am of the conviction that the Author(s) might have desired specifications in tweaking the code snippets in these hacks so that the existing visual theming in the [Docs](https://readthedocs.org/projects/sqlfluff/) is sustained.

### Are you willing to work on and submit a PR to address the issue?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by greg-finley** [comment]
Thanks! Any of them is better than a broken picture. 🙂 

I personally like option 1. Feel free to have a shot at it.
