### ISSUE TITLE
postgres dont have any useful info about fail 

### ISSUE THREAD

**Issue by zhajingzhaxi** [sqlfluff/sqlfluff#4995]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### What Happened

i am certain that sql execution in the  file was successful  , i just want to format and output for others, unfortunately, ,command line is fail to output ,I  want to extract useful infomation from messages, but there are really too many outputs, and I don't know which important ones I should focus on.

### Expected Behaviour

just want to succeed and output result success

### Observed Behaviour

F:\〉sqlfluff format pg.sql -x newc --dialect postgres                                                                                                                                                                  07/24/2023 03:23:15 下午
==== finding fixable violations ====
== [pg.sql] FAIL
L:   1 | P:   7 | LT01 | Unnecessary trailing whitespace.
                       | [layout.spacing]
L:   2 | P:   1 | LT02 | Expected indent of 4 spaces.
                       | [layout.indent]
L:   3 | P:   1 | LT02 | Expected indent of 4 spaces.
                       | [layout.indent]
L:   3 | P:   1 | LT04 | Found leading comma ','. Expected only trailing near
                       | line breaks. [layout.commas]
L:   3 | P:   2 | LT01 | Expected single whitespace between comma ',' and
                       | function name identifier. [layout.spacing]
L:   3 | P:  10 | LT01 | Unexpected whitespace before naked identifier.
                       | [layout.spacing]
L:   5 | P:   1 | LT02 | Expected indent of 4 spaces.
                       | [layout.indent]
L:   5 | P:   7 | LT01 | Unnecessary trailing whitespace.
                       | [layout.spacing]
L:   6 | P:   1 | LT02 | Expected indent of 8 spaces.
                       | [layout.indent]
L:   6 | P:   2 | LT01 | Unnecessary trailing whitespace.
                       | [layout.spacing]
L:   7 | P:   1 | LT02 | Expected indent of 8 spaces.
                       | [layout.indent]
L:   7 | P:   1 | LT04 | Found leading comma ','. Expected only trailing near
                       | line breaks. [layout.commas]
L:   7 | P:   2 | LT01 | Expected single whitespace between comma ',' and
                       | function name identifier. [layout.spacing]
L:   8 | P:   1 | LT02 | Expected indent of 12 spaces.
                       | [layout.indent]
L:   9 | P:   1 | LT02 | Expected indent of 12 spaces.
                       | [layout.indent]
L:   9 | P:   1 | LT04 | Found leading comma ','. Expected only trailing near
                       | line breaks. [layout.commas]
L:   9 | P:   2 | CP03 | Function names must be consistently lower case.
                       | [capitalisation.functions]
L:   9 | P:   2 | LT01 | Expected single whitespace between comma ',' and
                       | function name identifier. [layout.spacing]
L:   9 | P:   2 | LT05 | Line is too long (153 > 80).
                       | [layout.long_lines]
L:   9 | P:   8 | CP02 | Unquoted identifiers must be consistently lower case.
                       | [capitalisation.identifiers]
L:   9 | P:  17 | CP01 | Keywords must be consistently lower case.
                       | [capitalisation.keywords]
L:   9 | P:  21 | LT01 | Expected single whitespace between 'over' keyword and
                       | start bracket '('. [layout.spacing]
L:   9 | P:  22 | CP01 | Keywords must be consistently lower case.
                       | [capitalisation.keywords]
L:   9 | P:  32 | CP01 | Keywords must be consistently lower case.
                       | [capitalisation.keywords]
L:   9 | P:  37 | CP02 | Unquoted identifiers must be consistently lower case.
                       | [capitalisation.identifiers]
L:   9 | P:  50 | CP03 | Function names must be consistently lower case.
                       | [capitalisation.functions]
L:   9 | P:  50 | LT01 | Expected single whitespace between binary operator '-'
                       | and function name identifier.
                       | [layout.spacing]
L:   9 | P:  54 | CP01 | Keywords must be consistently lower case.
                       | [capitalisation.keywords]
L:   9 | P:  59 | CP01 | Keywords must be consistently lower case.
                       | [capitalisation.keywords]
L:   9 | P:  66 | CP02 | Unquoted identifiers must be consistently lower case.
                       | [capitalisation.identifiers]
L:   9 | P:  79 | CP01 | Keywords must be consistently lower case.
                       | [capitalisation.keywords]
L:   9 | P:  86 | CP02 | Unquoted identifiers must be consistently lower case.
                       | [capitalisation.identifiers]
L:   9 | P:  94 | CP01 | Keywords must be consistently lower case.
                       | [capitalisation.keywords]
L:   9 | P: 104 | CP01 | Keywords must be consistently lower case.
                       | [capitalisation.keywords]
L:   9 | P: 109 | CP01 | Keywords must be consistently lower case.
                       | [capitalisation.keywords]
L:   9 | P: 113 | LT01 | Expected single whitespace between 'over' keyword and
                       | start bracket '('. [layout.spacing]
L:   9 | P: 114 | CP01 | Keywords must be consistently lower case.
                       | [capitalisation.keywords]
L:   9 | P: 124 | CP01 | Keywords must be consistently lower case.
                       | [capitalisation.keywords]
L:   9 | P: 129 | CP02 | Unquoted identifiers must be consistently lower case.
                       | [capitalisation.identifiers]
L:   9 | P: 140 | LT01 | Unexpected whitespace before end bracket ')'.
                       | [layout.spacing]
L:   9 | P: 141 | LT02 | Expected line break and indent of 4 spaces before ')'.
                       | [layout.indent]
L:  10 | P:   1 | LT02 | Expected indent of 4 spaces.
                       | [layout.indent]
L:  11 | P:   1 | LT02 | Expected indent of 8 spaces.
                       | [layout.indent]
L:  11 | P:   7 | LT01 | Unnecessary trailing whitespace.
                       | [layout.spacing]
L:  12 | P:   1 | LT02 | Expected indent of 12 spaces.
                       | [layout.indent]
L:  12 | P:   1 | LT05 | Line is too long (86 > 80).
                       | [layout.long_lines]
L:  12 | P:   5 | CP02 | Unquoted identifiers must be consistently lower case.
                       | [capitalisation.identifiers]
L:  12 | P:  68 | CP02 | Unquoted identifiers must be consistently lower case.
                       | [capitalisation.identifiers]
L:  13 | P:   1 | LT02 | Expected indent of 12 spaces.
                       | [layout.indent]
L:  13 | P:   1 | LT04 | Found leading comma ','. Expected only trailing near
                       | line breaks. [layout.commas]
L:  13 | P:   2 | LT01 | Expected single whitespace between comma ',' and star
                       | '*'. [layout.spacing]
L:  14 | P:   1 | LT02 | Expected indent of 8 spaces.
                       | [layout.indent]
L:  14 | P:   6 | CP02 | Unquoted identifiers must be consistently lower case.
                       | [capitalisation.identifiers]
L:  15 | P:   1 | LT02 | Expected indent of 4 spaces.
                       | [layout.indent]
L:  15 | P:   4 | LT01 | Unexpected whitespace before end bracket ')'.
                       | [layout.spacing]
L:  15 | P:   5 | LT02 | Expected line break and no indent before ')'.
                       | [layout.indent]
L:  16 | P:  22 | LT12 | Files must end with a single trailing newline.
                       | [layout.end_of_file]
  [1 templating/parsing errors found]
==== no fixable linting violations found ====
All Finished �📜🎉🎉!
  [57 unfixable linting violations found]

### How to reproduce

windows10
nushell or any shell as the same output

============================
my pg.sql content is follow:
`select 
b.playername
,min(abs(  b.date_part)) 时间
from (
select 
* 
,date_part(
'day'
,MIN(a.LOGTIME) OVER(PARTITION BY a.PLAYERNAME) -MIN(CASE WHEN a.CUMSUM >= 20 THEN a.LOGTIME ELSE NULL END) OVER(PARTITION BY a.PLAYERNAME) )
from (
select 
sum(AMOUNT) over (partition by playername order by logtime asc) as CUMSUM
,*
from F1019
) a ) b
group by b.playername`      

### Dialect

sqlfluff format pg.sql -x new --dialect postgres         

### Version

lasted version 

### Configuration

default configuration

### Are you willing to work on and submit a PR to address the issue?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by zhajingzhaxi** [comment]
**### i find this is  a chinese  characters problem ,it can be executed successfully while removing chinese  str in sql file .but the terminal output also rendering fail message, confusing!!!**


>
F:\〉sqlfluff format pg.sql -x newc --dialect postgres                                                                                                                                                                  07/24/2023 02:30:35 下午
==== finding fixable violations ====
== [pg.sql] FAIL
L:   1 | P:   7 | LT01 | Unnecessary trailing whitespace.
                       | [layout.spacing]
L:   2 | P:   1 | LT02 | Expected indent of 4 spaces.
                       | [layout.indent]
L:   3 | P:   1 | LT02 | Expected indent of 4 spaces.
                       | [layout.indent]
L:   3 | P:   1 | LT04 | Found leading comma ','. Expected only trailing near
                       | line breaks. [layout.commas]
L:   3 | P:   2 | LT01 | Expected single whitespace between comma ',' and
                       | function name identifier. [layout.spacing]
L:   3 | P:  10 | LT01 | Unexpected whitespace before naked identifier.
                       | [layout.spacing]
L:   5 | P:   1 | LT02 | Expected indent of 4 spaces.
                       | [layout.indent]
L:   5 | P:   7 | LT01 | Unnecessary trailing whitespace.
                       | [layout.spacing]
L:   6 | P:   1 | LT02 | Expected indent of 8 spaces.
                       | [layout.indent]
L:   6 | P:   2 | LT01 | Unnecessary trailing whitespace.
                       | [layout.spacing]
L:   7 | P:   1 | LT02 | Expected indent of 8 spaces.
                       | [layout.indent]
L:   7 | P:   1 | LT04 | Found leading comma ','. Expected only trailing near
                       | line breaks. [layout.commas]
L:   7 | P:   2 | LT01 | Expected single whitespace between comma ',' and
                       | function name identifier. [layout.spacing]
L:   8 | P:   1 | LT02 | Expected indent of 12 spaces.
                       | [layout.indent]
L:   9 | P:   1 | LT02 | Expected indent of 12 spaces.
                       | [layout.indent]
L:   9 | P:   1 | LT04 | Found leading comma ','. Expected only trailing near
                       | line breaks. [layout.commas]
L:   9 | P:   2 | CP03 | Function names must be consistently lower case.
                       | [capitalisation.functions]
L:   9 | P:   2 | LT01 | Expected single whitespace between comma ',' and
                       | function name identifier. [layout.spacing]
L:   9 | P:   2 | LT05 | Line is too long (153 > 80).
                       | [layout.long_lines]
L:   9 | P:   8 | CP02 | Unquoted identifiers must be consistently lower case.
                       | [capitalisation.identifiers]
L:   9 | P:  17 | CP01 | Keywords must be consistently lower case.
                       | [capitalisation.keywords]
L:   9 | P:  21 | LT01 | Expected single whitespace between 'over' keyword and
                       | start bracket '('. [layout.spacing]
L:   9 | P:  22 | CP01 | Keywords must be consistently lower case.
                       | [capitalisation.keywords]
L:   9 | P:  32 | CP01 | Keywords must be consistently lower case.
                       | [capitalisation.keywords]
L:   9 | P:  37 | CP02 | Unquoted identifiers must be consistently lower case.
                       | [capitalisation.identifiers]
L:   9 | P:  50 | CP03 | Function names must be consistently lower case.
                       | [capitalisation.functions]
L:   9 | P:  50 | LT01 | Expected single whitespace between binary operator '-'
                       | and function name identifier.
                       | [layout.spacing]
L:   9 | P:  54 | CP01 | Keywords must be consistently lower case.
                       | [capitalisation.keywords]
L:   9 | P:  59 | CP01 | Keywords must be consistently lower case.
                       | [capitalisation.keywords]
                       | [capitalisation.identifiers]
L:   9 | P:  79 | CP01 | Keywords must be consistently lower case.
                       | [capitalisation.keywords]
L:   9 | P:  86 | CP02 | Unquoted identifiers must be consistently lower case.
                       | [capitalisation.identifiers]
L:   9 | P:  94 | CP01 | Keywords must be consistently lower case.
                       | [capitalisation.keywords]
L:   9 | P: 104 | CP01 | Keywords must be consistently lower case.
                       | [capitalisation.keywords]
L:   9 | P: 109 | CP01 | Keywords must be consistently lower case.
                       | [capitalisation.keywords]
L:   9 | P: 113 | LT01 | Expected single whitespace between 'over' keyword and
                       | start bracket '('. [layout.spacing]
L:   9 | P: 114 | CP01 | Keywords must be consistently lower case.
                       | [capitalisation.keywords]
L:   9 | P: 124 | CP01 | Keywords must be consistently lower case.
                       | [capitalisation.keywords]
L:   9 | P: 129 | CP02 | Unquoted identifiers must be consistently lower case.
                       | [capitalisation.identifiers]
L:   9 | P: 140 | LT01 | Unexpected whitespace before end bracket ')'.
                       | [layout.spacing]
L:   9 | P: 141 | LT02 | Expected line break and indent of 4 spaces before ')'.
                       | [layout.indent]
L:  10 | P:   1 | LT02 | Expected indent of 4 spaces.
                       | [layout.indent]
L:  11 | P:   1 | LT02 | Expected indent of 8 spaces.
                       | [layout.indent]
L:  11 | P:   7 | LT01 | Unnecessary trailing whitespace.
                       | [layout.spacing]
L:  12 | P:   1 | LT02 | Expected indent of 12 spaces.
                       | [layout.indent]
L:  12 | P:   1 | LT05 | Line is too long (86 > 80).
                       | [layout.long_lines]
L:  12 | P:   5 | CP02 | Unquoted identifiers must be consistently lower case.
                       | [capitalisation.identifiers]
L:  12 | P:  68 | CP02 | Unquoted identifiers must be consistently lower case.
                       | [capitalisation.identifiers]
L:  13 | P:   1 | LT02 | Expected indent of 12 spaces.
                       | [layout.indent]
L:  13 | P:   1 | LT04 | Found leading comma ','. Expected only trailing near
                       | line breaks. [layout.commas]
L:  13 | P:   2 | LT01 | Expected single whitespace between comma ',' and star
                       | '*'. [layout.spacing]
L:  14 | P:   1 | LT02 | Expected indent of 8 spaces.
                       | [layout.indent]
L:  14 | P:   6 | CP02 | Unquoted identifiers must be consistently lower case.
                       | [capitalisation.identifiers]
L:  15 | P:   1 | LT02 | Expected indent of 4 spaces.
                       | [layout.indent]
L:  15 | P:   4 | LT01 | Unexpected whitespace before end bracket ')'.
                       | [layout.spacing]
L:  15 | P:   5 | LT02 | Expected line break and no indent before ')'.
                       | [layout.indent]
L:  16 | P:  22 | LT12 | Files must end with a single trailing newline.
                       | [layout.end_of_file]
== [pg.sql] FIXED
57 fixable linting violations found

**Comment by WittierDinosaur** [comment]
It looks like you just need to run `sqlfluff fix`, which will auto-fix a lot of these for you. This is the product working as intended
