### ISSUE TITLE
Comparison operators with space between don't parse

### ISSUE THREAD

**Issue by joaostorrer** [sqlfluff/sqlfluff#5059]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### Description

The following query is not parsed by sqlfluff:

`select 1 from dual where 3 < = 4`

### Dialect

oracle

### Are you willing to work on and submit a PR to address the issue?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by alanmcruickshank** [comment]
This is supported on TSQL, so you can probably steal the implementation from there 👍
