### ISSUE TITLE
Support ignoring specific rules in specific files

### ISSUE THREAD

**Issue by dmateusp** [sqlfluff/sqlfluff#507]
## Problem

I have a case where stakeholders ask us to name columns using some reserved keywords, which has us breaking a specific rule in a View.

There might be a few cases where this feature can be useful:
- the rule hits an edge case in a file but works fine on the rest of the project
- you explicitly want to break a rule in a specific file, maybe fixing the rule would require a big refactoring you do not want to commit to just yet

## Proposal

I'd like to suggest parsing the following comment as special syntax 

```
-- sqlfluffignore: L001,L002,L003

select a from table_1...
...
```

The rules would then be ignored for the specific file

**Comment by pwildenhain** [comment]
Do you know about `--noqa:` comments? That would be the current workaround
for your use case

**Comment by dmateusp** [comment]
Didn't realize it was supported already! I'll close that issue then thanks

**Comment by pwildenhain** [comment]
Is this feature in the documentation anywhere @alanmcruickshank ? I also remember learning about it in an issue I filed...
