### ISSUE TITLE
Unable to parse ALTER POLICY 

### ISSUE THREAD

**Issue by nathancahill** [sqlfluff/sqlfluff#5075]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### What Happened

```sql
ALTER POLICY sales_rep_is_self ON invoices
  WITH CHECK (sales_rep = CURRENT_USER AND CURRENT_USER IN (
    SELECT name FROM allowed_users
  ));
```

### Expected Behaviour

Should parse `ALTER POLICY`

### Observed Behaviour

`Found unparsable section: 'ALTER POLICY`

### How to reproduce

Run `sqlfluff parse` with the example query.

### Dialect

postgres

### Version

2.2.0

### Configuration

Default

### Are you willing to work on and submit a PR to address the issue?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by fnimick** [comment]
I believe the fix in #5138 is not complete. This still fails on e.g.:
`alter policy "policy_name" on table_name to authenticated using (condition);` - which is a legal postgres syntax to alter both the using_expression and the role target in the same command.

See: https://www.postgresql.org/docs/current/sql-alterpolicy.html

It passes fine if either `to authenticated` or `using (condition)` are removed.
