### ISSUE TITLE
Detect, but not fix or prompt for, fixable violations

### ISSUE THREAD

**Issue by ewan-escience** [sqlfluff/sqlfluff#5083]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### Description

I'd like to detect, using `sqlfluff fix`, if there are any auto fixable errors, but not have them fixed and not be blocked by the prompt asking to fix it. Using `--ignore linting` will alway report no fixable issues to be found, even if they are present. Piping 'n' into the program doesn't work for me, e.g. `echo 'n' | sqlfluff fix` or  `yes 'n' | sqlfluff fix` will still display the blocking prompt if there are any fixable issues found.

If there is another way to do this using the shell only, so without adding a new feature to SQLFluff, I'd be happy as well.

### Use case

I'm trying to detect in a build pipeline if there were any auto fixable issues and fail the build in that case, so that the contributor of that code can use SQLFluff to fix the issue.

### Dialect

none

### Are you willing to work on and submit a PR to address the issue?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by alanmcruickshank** [comment]
I don't think this feature exists right now, but it almost sounds like a
`--dry-run` feature, where we go as far as asking for fixes but then always
abort (basically the opposite of `--force`).

It would be fairly easy to add. 👍

**Comment by alanmcruickshank** [comment]
@ewan-escience - I'm thinking about this. When we talk about `fixable` violations here, we mean ones that SQLFluff is automatically able to fix. _all_ of them are fixable if you're displaying them to a human. Why would you want to exclude the ones which are fixable by a human, but not by the machine if you're displaying it to a human?

**Comment by ewan-escience** [comment]
What I'm trying to do is to use SQLFluff as a formatting (but not linting) check in a CI/CD pipeline. My assumption would be that if there are any auto fixable problems, the code isn't formatted properly and the pipeline should reject it. But non auto fixable problems would be linting errors instead of formatting errors, and I don't want the pipeline to fail on those.

But if this is not how SQLFluff works and/or it would be hard to implement this, no problem.

**Comment by alanmcruickshank** [comment]
@ewan-escience , I'm not sure I understand yet. Can you explain what you would see as the difference between a _linting_ issue and a _formatting_ issue is? I see the two terms as fairly interchangable.

**Comment by ewan-escience** [comment]
I'm looking at https://prettier.io/docs/en/comparison for those definitions, so `formatting` is only about how the code looks without changing the syntax or behaviour and `linting` also includes changing the syntax or behaviour. I'd like to catch formatting issues, as they are objectively wrong. Linting issues are subjective though and always need a human to look at.

**Comment by alanmcruickshank** [comment]
I understand what you mean - and I think this is possible through careful rule selection. There's a grey area here because depending on your dialect, some thing could be either `linting` or `formatting` (by your definitions), for example casing: in snowflake the difference between `SELECT FOO` and `select foo` is not a functional one, but in clickhouse it is (because clickhouse is case sensitive in how it resolves unquoted identifiers).

My suggestion would be to work through the (rule docs)[https://docs.sqlfluff.com/en/stable/reference/rules.html] and pick out the rules that you feel are the ones you want to keep, and then only run with those specific rules.
