### ISSUE TITLE
Type hints break cli on an older click version: NameError

### ISSUE THREAD

**Issue by bitkeen** [sqlfluff/sqlfluff#5105]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### What Happened

Type hints break cli on an older click version.
https://github.com/sqlfluff/sqlfluff/blob/main/src/sqlfluff/cli/autocomplete.py#L16
```
Traceback (most recent call last):
  File "/usr/bin/sqlfluff", line 5, in <module>
    from sqlfluff.cli.commands import cli
  File "/usr/lib/python3.11/site-packages/sqlfluff/cli/commands.py", line 23, in <module>
    from sqlfluff.cli.autocomplete import shell_completion_enabled, dialect_shell_complete
  File "/usr/lib/python3.11/site-packages/sqlfluff/cli/autocomplete.py", line 16, in <module>
    def dialect_shell_complete(ctx, param, incomplete) -> List[completion.CompletionItem]:
                                                               ^^^^^^^^^^
NameError: name 'completion' is not defined
```
click 7.1.2

### Expected Behaviour

No NameError is raised.

### Observed Behaviour

NameError is raised.

### How to reproduce

Run sqlfluff cli with click 7.1.2

### Dialect

Any

### Version

sqlfluff 2.2.1
Python 3.11.3

### Configuration

None

### Are you willing to work on and submit a PR to address the issue?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by greg-finley** [comment]
Hey sorry, we don't plan to support older versions. See this issue: https://github.com/pallets/click/issues/2558
