### ISSUE TITLE
Postgres: deferrable in create table statement

### ISSUE THREAD

**Issue by David-Briffa** [sqlfluff/sqlfluff#5106]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### What Happened

When adding deferrable to a constraint within a create statement, it is marked as unparsable due to not being recognized.

Keywords:
- NOT DEFERRABLE INITIALLY DEFERRED
- NOT DEFERRABLE INITIALLY IMMEDIATE
- NOT DEFERRABLE
- DEFERRABLE INITIALLY IMMEDIATE
- DEFERRABLE

### Expected Behaviour

CREATE TABLE sample (
id int NOT NULL,
sample_column varchar (50) NOT NULL, 

CONSTRAINT sample_column UNIQUE (first_name) DEFERRABLE INITIALLY DEFERRED
);

The statement should not be marked as unparsable as the syntax is valid, executing the statement regardless of the highlighted error works as intended.

### Observed Behaviour

Line 1, Position 1: Found unparsable section: 'CREATE TABLE sample (/n  id int NOT NU...'

### How to reproduce

$ echo 'CREATE TABLE sample_table(id int NOT NULL, testField int NOT NULL CONSTRAINT test_id_constraint UNIQUE (testField) DEFERRABLE INITIALLY DEFERRED);'  | sqlfluff lint

### Dialect

Postgres

### Version

2.0.0

### Configuration

[sqlfluff]
dialect = postgres
sql_file_exts = .sql,.pgsql
max_line_length = 150

### Are you willing to work on and submit a PR to address the issue?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by greg-finley** [comment]
Hello! It works in newer versions of sqlfluff: https://online.sqlfluff.com/fluffed?sql=H4sIAMV96WQC_3MOcnUMcVUIcXTycVUoTswtyElV0ODlUgCCzBSFzLwSBT__EAW_UB8fHYgoRE18cn5OaW6eQlliUXJGYpGGqYEmskKIUmd_v-CQIEdPvxA0XaF-noGhrgoaaZlFxSXxeYm5qZoKLq5urkFBYGd4-nmGeDr6-ERCBV1deLk0rXm5ACtWHW6sAAAA&dialect=postgres
