### ISSUE TITLE
Rules page in documentation is broken.

### ISSUE THREAD

**Issue by a-litvinov** [sqlfluff/sqlfluff#511]
I've got an impression that this page was supposed to list all implemented lint rules, but it is empty: https://docs.sqlfluff.com/en/latest/rules.html#ruleref

If my impression is incorrect, is there a page where I can see all rules description besides looking directly into the code?

**Comment by alanmcruickshank** [comment]
@a-litvinov - thanks for raising. Your assumption is correct and you have found a bug with that docs page. I'm looking at why it's happening now...

**Comment by alanmcruickshank** [comment]
@a-litvinov  - this is fixed! Check out the same link now.

**Comment by a-litvinov** [comment]
Thanks for the quick reaction! :+1:
