### ISSUE TITLE
PRs from outside contributors cannot run coverage comment job

### ISSUE THREAD

**Issue by greg-finley** [sqlfluff/sqlfluff#5188]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### What Happened

`RequestError [HttpError]: Resource not accessible by integration`

https://github.com/sqlfluff/sqlfluff/actions/runs/6133068338/job/16644639081?pr=5185

### Expected Behaviour

The job can run from outside PRs

### Observed Behaviour

It fails

### How to reproduce

See link

### Dialect

n/a

### Version

n/a

### Configuration

n/a

### Are you willing to work on and submit a PR to address the issue?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by alanmcruickshank** [comment]
I think this is now solved (after a lot of "testing in production")
