### ISSUE TITLE
Break up standard rules into separate files

### ISSUE THREAD

**Issue by pwildenhain** [sqlfluff/sqlfluff#519]
> What about
> 
> 1. A new `std` directory in `rules` where all standard rules live
> 2. Each standard rule has it's own file

I like this.

> One thing I'm still not clear on with this though is how would you register and document_configuration on the rules? Import the std_rule_set into each of the rule files? Seems like a little much 🤷‍♂️

I also agree that this is totally the tricky part. I'm not sure either. Very open to suggestions! Want to make a new issue for this if you're merging this PR?

_Originally posted by @alanmcruickshank in https://github.com/sqlfluff/sqlfluff/pull/515#issuecomment-719502293_

**Comment by NiallRees** [comment]
Yes please. And also let's get the tests for each rule in the same file as the rule itself. I don't think importing the std_rule_set into each file is a big deal to be honest. Happy to work on this one if no one else does before me

**Comment by pwildenhain** [comment]
Oh getting the test with it sounds cool! I'm excited to see how this turns out -- I say go for it @NiallRees

**Comment by alanmcruickshank** [comment]
> And also let's get the tests for each rule in the same file as the rule itself

@NiallRees I'm not sure about this last bit. I'm up for splitting test files out and somehow being more accessible, but at the moment the tests aren't included with the packaged library when shipped, and if we're going to move the tests into the main codebase, then we will need to revisit which files are included and which not.

If we can find a tidy way of doing it, then I'm open to suggestions, but if it's a real pain I'm happy to keep `test` separate to `src`.

**Comment by barrywhart** [comment]
Can this issue be closed?
