### ISSUE TITLE
Public API to build nested configs

### ISSUE THREAD

**Issue by golergka** [sqlfluff/sqlfluff#5207]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### Description

I want to have a public API to be able to build `FluffConfig` instance from several config files which override one another, replicating the behaviour with nested `.sqlfluff` configs in the filesystem.

### Use case

I'm building a lint functionality which uses SQLFluff. I want the user to be able to provide nested `.sqlfluff` config files in the service's virtual filesystem, so I need to build the config in my own code.

I have tried using `nested_combine` like this:

```Python
class LintConfigFile:
    content: str

def build_config(config_files: Optional[List[LintConfigFile]]) -> FluffConfig:
    if not config_files:
        return None

    loader = ConfigLoader.get_global()
    config_dicts = [
        loader.load_config_string(config_file.content)
        for config_file in config_files
    ]
    config = nested_combine(*config_dicts)
    return FluffConfig.from_kwargs(config=config)
```

However, this fails to combine contents of two different config files with this simple unit test:

```
        def test_build_config_multiple(self):
            config = build_config(
                [
                    LintConfigFile(
                        content="""
    [sqlfluff]
    dialect = duckdb
    """
                    ),
                    LintConfigFile(
                        content="""
    [sqlfluff]
    max_line_length = 120
    """
                    ),
                ]
            )
>           assert config.get("dialect") == "duckdb"
E           AssertionError: assert None == 'duckdb'
```

So I ended up using this:

```Python
def build_config(
    config_files: Optional[List[LintConfigFile]],
) -> Optional[FluffConfig]:
    if not config_files:
        return None

    # We build a temporary directory with the config files to replicate sqlfluff
    # nesting config behavior
    with tempfile.TemporaryDirectory(dir=TMP_DIR) as temp_dir_path:
        cur_path = temp_dir_path
        for i, config_file in enumerate(config_files):
            cur_path = cur_path + f"/config-{i}"
            os.makedirs(cur_path)
            config_path = f"{cur_path}/.sqlfluff"
            with open(config_path, "w") as f:
                f.write(config_file.content)
        return FluffConfig.from_path(cur_path)
```

Which behaves exactly as I expect, but looks to be very unoptimal.

### Dialect

not related to particular dialect

### Are you willing to work on and submit a PR to address the issue?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by MasterOdin** [comment]
With some experimentation, was able to find a way to achieve creating a config from multiple strings, though still relies on undocumented internals:

```python
class LintConfigFile:
    content: str


def build_config(
    config_files: Optional[List[LintConfigFile]],
) -> Optional[FluffConfig]:
    loader = ConfigLoader.get_global()
    configs = nested_combine(*[
        loader.load_config_string(config_file.content) for config_file in config_files
    ])
    return FluffConfig(configs=configs)
```

would still be nice to have a method off `FluffConfig` that does this for us.

**Comment by alanmcruickshank** [comment]
@golergka & @MasterOdin - thanks both for posting a great issue here. I think this should be fairly easy to do. So that I understand what you're thinking, would you imagine a nested combination of strings (i.e. nested combine of unparsed config files) or a nested combine of `FluffConfig` objects?

I think the former is slightly easier, and that seems to be more like what you're suggesting in the example test cases, but I thought I should check.

**Comment by MasterOdin** [comment]
The former, where given a list of strings, we get back a `FluffConfig` with them parsed/combined.

Rewriting my example function with a proposed API:

```
class LintConfigFile:
    content: str


def build_config(
    config_files: List[LintConfigFile],
) -> FluffConfig:
    return FluffConfig.from_strings(config_strings=[config_file.content for config_file in config_files])
```

**Comment by alanmcruickshank** [comment]
@MasterOdin @golergka - PR with a solution to this is live. Should be merged and released soon.
