### ISSUE TITLE
Snowflake: Stored procedure are not parsable

### ISSUE THREAD

**Issue by robin-alphasophia** [sqlfluff/sqlfluff#5239]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### What Happened

I am using SQLFluff with the Snowflake dialect, however it seems to be struggling with every single stored procedure we have (and we have quite a lot).

For example, in this stored procedure, it is already having an issue with the first line:

```
CREATE OR REPLACE PROCEDURE HEALTHCARE.INPUT.AS_GET_CSV_HEADER_PATTERN(SOURCE_DIR VARCHAR, PATTERN VARCHAR, MAX_COL NUMBER(38,0), IS_GZIP BOOLEAN)
RETURNS ARRAY
LANGUAGE SQL
AS
BEGIN
  -- Construct the statement
  -- 1. Start the SQL statement
  LET HEADER_STMT VARCHAR := 'SELECT ARRAY_CONSTRUCT_COMPACT(';
  -- 2. Iterate through the columns and add them to the statement
  FOR i IN 1 TO MAX_COL DO
    HEADER_STMT := HEADER_STMT || 't.$' || i;
    IF (i < MAX_COL) THEN
        HEADER_STMT := HEADER_STMT || ',';
    END IF;
  END FOR;
  -- 3. Finish the statement
  LET FILE_FORMAT VARCHAR := (SELECT CASE WHEN :IS_GZIP THEN 'HEALTHCARE.INPUT.DEFAULT_CSV_GZIP_NO_HEADER' ELSE 'HEALTHCARE.INPUT.DEFAULT_CSV_NO_HEADER' END);
  HEADER_STMT := HEADER_STMT || ') FROM \'@s3_stage/' || :SOURCE_DIR || '/\' (FILE_FORMAT => ' || :FILE_FORMAT || ', PATTERN => \'' || :PATTERN || '\') t LIMIT 1;';

  -- Execute the statement
  LET RESULT RESULTSET := (EXECUTE IMMEDIATE HEADER_STMT);

  -- Fetch the result and return it
  LET c CURSOR FOR RESULT;
  LET RESULT_ARRAY ARRAY;
  OPEN c;
  FETCH c INTO RESULT_ARRAY;

  -- Return
  RETURN RESULT_ARRAY;
END;
```

Error:
`Line 1, Position 1: Found unparsable section: 'CREATE OR REPLACE PROCEDURE HEALTHCARE.I...'sqlfluff(PRS)`

### Expected Behaviour

This should be parsable, as far I know

### Observed Behaviour

It just means that we can basically do no syntax testing whatsoever within Snowflake stored procedures (which is around 60% of our code basis).

### How to reproduce

Simply try to save the file above with the .sqlfluff configuration as described.

### Dialect

Snowflakie

### Version

sqlfluff, version 2.3.2
Python 3.11.4

### Configuration

[sqlfluff]

# Supported dialects https://docs.sqlfluff.com/en/stable/dialects.html
# Or run 'sqlfluff dialects'
dialect = snowflake

# Affect only .sql files in the current directory and below
sql_file_exts = .sql

# One of [raw|jinja|python|placeholder]
templater = raw

# Comma separated list of rules to exclude, or None
# See https://docs.sqlfluff.com/en/stable/configuration.html#enabling-and-disabling-rules
# AM04 (ambiguous.column_count) and ST06 (structure.column_order) are
# two of the more controversial rules included to illustrate usage.
exclude_rules = ambiguous.column_count, structure.column_order, references.keywords

# The standard max_line_length is 80 in line with the convention of
# other tools and several style guides. Many projects however prefer
# something a little longer.
# Set to zero or negative to disable checks.
max_line_length = 120

# CPU processes to use while linting.
# The default is "single threaded" to allow easy debugging, but this
# is often undesirable at scale.
# If positive, just implies number of processes.
# If negative or zero, implies number_of_cpus - specified_number.
# e.g. -1 means use all processors but one. 0 means all cpus.
processes = 1 # default -1

# If using the dbt templater, we recommend setting the project dir.
[sqlfluff:templater:dbt]
project_dir = ./

[sqlfluff:indentation]
# While implicit indents are not enabled by default. Many of the
# SQLFluff maintainers do use them in their projects.
allow_implicit_indents = True
tab_space_size = 2

# The default configuration for aliasing rules is "consistent"
# which will auto-detect the setting from the rest of the file. This
# is less desirable in a new project and you may find this (slightly
# more strict) setting more useful.
[sqlfluff:rules:aliasing.table]
aliasing = explicit
[sqlfluff:rules:aliasing.column]
aliasing = explicit
[sqlfluff:rules:aliasing.length]
min_alias_length = 1

# The default configuration for capitalisation rules is "consistent"
# which will auto-detect the setting from the rest of the file. This
# is less desirable in a new project and you may find this (slightly
# more strict) setting more useful.
# Typically we find users rely on syntax highlighting rather than
# capitalisation to distinguish between keywords and identifiers.
# Clearly, if your organisation has already settled on uppercase
# formatting for any of these syntax elements then set them to "upper".
# See https://stackoverflow.com/questions/608196/why-should-i-capitalize-my-sql-keywords-is-there-a-good-reason
[sqlfluff:rules:capitalisation.keywords]
capitalisation_policy = upper
[sqlfluff:rules:capitalisation.identifiers]
capitalisation_policy = upper
[sqlfluff:rules:capitalisation.functions]
extended_capitalisation_policy = upper
[sqlfluff:rules:capitalisation.literals]
capitalisation_policy = upper
[sqlfluff:rules:capitalisation.types]
extended_capitalisation_policy = upper

### Are you willing to work on and submit a PR to address the issue?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by robin-alphasophia** [comment]
I just realized the snowflake dialect supports stored procedures. The error seems to be, that sqlfluff has actually harder parsing restrictions than actual snowsql, i.e.

in between

AS and BEGIN must come for example `$$` as such:

```
CREATE OR REPLACE PROCEDURE HEALTHCARE.INPUT.AS_DEPLOY_TO_ENV(ENV VARCHAR)
RETURNS BOOLEAN
LANGUAGE SQL
AS
$$
BEGIN
```

Snowflake SQL actually does not need that, when the stored procedure is in SQL as supposed to JavaScript etc. Now I have to go back and add the $$ to all scripts. Not perfect, but should work for now.

Could we make this optional in the future, or are there inherent problems with that?

**Comment by robin-alphasophia** [comment]
Trying to fix it myself by introducing a new BEGIN...END block in the Snowflake dialect:

```
class CreateScriptingBlockStatementSegment(BaseSegment):
    """A snowflake `BEGIN ... END` statement for SQL scripting.
    
    https://docs.snowflake.com/en/sql-reference/snowflake-scripting/begin
    """

    type = "create_scripting_block_statement"
    match_grammar = Sequence(
        "BEGIN",       
        AnyNumberOf(
            Ref("StatementSegment"),
        ),
        "END",
    )
```
 
 Trying to match 
 
 ```
 BEGIN
  SELECT 5 FROM HEALTHCARE.INPUT.USERS;
END;
 ```
    
Unfortunately I am running into issues, as the parser seems to always want to identify any BEGIN as transaction statement (which is rather weakly parsed, if you look into it, does not actually require a proper sequence, BEGIN; BEGIN; BEGIN; BEGIN; COMMIT; is still considered valid)

**Comment by DT-jd** [comment]
Hi @robin-alphasophia followed your PR and you added support for the stored procedure without qualifying a schema or database. I see other examples in the same file with the differing variations. Could this affect the parser if i'm using database and schema, because i'm still getting the same error you reported here. running on the latest version. Want to confirm before opening an issue.

@alanmcruickshank not sure if you could share some insight here.

**Comment by DT-jd** [comment]
@robin-alphasophia is it possible to share your config files/settings for parsing a snowflake procedure, please?
