### ISSUE TITLE
Support native "format" capability to apply fixes in VS Code

### ISSUE THREAD

**Issue by aaronsteers** [sqlfluff/sqlfluff#525]
I wanted to cross-post my ticket on the VS Code extension, in case there is ability here to support that project. The [SQLFLuff extension](https://marketplace.visualstudio.com/items?itemName=dorzey.vscode-sqlfluff) in VS Code by @dorsey is _fantastic_ for adding linting support but doesn't yet support the "format" option. Getting both linting and also auto-formatting working in VS Code goes a long way to making SQL a "first class language" in VS Code.

Upvotes and/or contributions towards this enhancement would be much appreciated:
- https://github.com/sqlfluff/vscode-sqlfluff/issues/6

Also - for anyone interested, check that linked issue for a description of my workaround which leverages the **Run on Save** extension.

**Comment by alanmcruickshank** [comment]
@aaronsteers - I think we should keep the discussion on the outcome on the original issue, but once we've got clarity on what kind of api would need to be exposed by sqlfluff to support that feature, let's update this issue to track that.

There's a *VERY* simple example of how fixing can work with the public api at the moment here: https://github.com/sqlfluff/sqlfluff/blob/master/examples/basic_api_usage.py

If we could lay out a rough example script that had the right hooks then we can work on sqlfluff supporting an interface that can work with that.

**Comment by aaronsteers** [comment]
Sounds great! Thanks, Alan!

**Comment by aaronsteers** [comment]
@alanmcruickshank (et al):  @dorzey has been does amazing work over here (https://github.com/sqlfluff/vscode-sqlfluff/pull/9) on the auto-formatting feature in VS Code. Once this releases, it'll bring first-class IDE programming support to the SQL language into VS Code. Linting has been in place for a while but this now adds "document format" capabilities, including on-demand formatting from the VS Code IDE and/or "Format on save" if the user has that feature turned on within VS Code.

Thanks @alanmcruickshank and especially @dorzey for making this possible.

Once that resolves, I think this ticket will be resolved as well.

@alanmcruickshank - Is there anywhere you think we should post about these new integration capabilities with VS Code?

**Comment by barrywhart** [comment]
From the comment above, it sounds like we can close this issue as well? Closing.
