### ISSUE TITLE
Fields starting with 'sql' unparsable with alias

### ISSUE THREAD

**Issue by dmgdotnet** [sqlfluff/sqlfluff#5250]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### What Happened

Field names beginning with 'sql' are not parsable when referenced using an alias unless name is escaped using []

### Expected Behaviour

SQL Should be parsable without escaping with [].

### Observed Behaviour

Following syntax works:

SELECT sqldate
FROM Marketing m

SELECT m.[sqldate]
FROM Marketing m

Following syntax does not work:

SELECT m.sqldate
FROM Marketing m

== [C:\temp\sqlFluff\test.sql] FAIL
L:   1 | P:   1 |  PRS | Line 1, Position 1: Found unparsable section: 'SELECT
                       | m.sql_Test_SQLDate\nFROM Marketing...'
WARNING: Parsing errors found and dialect is set to 'tsql'. Have you configured your dialect correctly?

### How to reproduce

sqlfluff lint $file -d tsql

SELECT m.sqldate
FROM Marketing m

### Dialect

tsql

### Version

sqlfluff, version 2.3.0

### Configuration

default configuration

### Are you willing to work on and submit a PR to address the issue?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by WittierDinosaur** [comment]
This was fixed a while ago, and works on the current release. Closing this issue
