### ISSUE TITLE
noqa: PRS emits ignored parsing erros on stdout

### ISSUE THREAD

**Issue by ahirner** [sqlfluff/sqlfluff#5327]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### What Happened

Using `sqlfluff` as auto formatter, requires `-` to be clean. Right now, a log line is included with or without colored output and no verbosity. 

### Expected Behaviour

Log line is emitted on stderr.

### Observed Behaviour

Observe "  [0 templating/parsing errors remaining after "ignore" & "warning"]" on the first line of `formatted-noqa-psr.sql`:

```sql
  [0 templating/parsing errors remaining after "ignore" & "warning"]
select
  create_time as last,
  (
    count(
      *) over
    (
      order by create_time desc -- noqa: PRS
      range between current row and '10 seconds' following  -- noqa: PRS
    )
  ) * 0.1
  as count
from foo_bar
where create_time > '2023-01-12T00:00:00'
order by create_time
limit 1000
```

### How to reproduce

`noqa-psr.sql`:
```sql
select
  create_time as last,
  (
    count(
      *) over
    (
      order by create_time desc -- noqa: PRS
      range between current row and '10 seconds' following  -- noqa: PRS
    )
  ) * 0.1
  as count
from foo_bar
where create_time > '2023-01-12T00:00:00'
order by create_time
limit 1000
```

Format from stdin:
```
cat noqa-psr.sql | sqlfluff format --ignore-local-config -d postgres - > formatted-noqa-psr.sql
```

### Dialect

postgres

### Version

2.3.3 (same on 2.3.2)

### Configuration

default

### Are you willing to work on and submit a PR to address the issue?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by alanmcruickshank** [comment]
Thanks for the issue report. I've confirmed the bug locally on my system and found the issue. PR should be coming soon.
