### ISSUE TITLE
"Nothing else in FileSegment." with multiple statements in file.

### ISSUE THREAD

**Issue by AndLut** [sqlfluff/sqlfluff#5330]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### What Happened

I tried linting a file with multiple `CREATE OR REPLACE FUNCTION` statements, but it always fails after the first statement ("Found unparsable section"). If I enable debug logs (`-vvvv`), I can see, that there is a line reading "unparsable: !! Expected: 'Nothing else in FileSegment.'".

### Expected Behaviour

The file is linted and syntax errors are printed out for all of the code in the file.

### Observed Behaviour

Only the first function gets linted, the rest is omitted. Linting with `fix_even_unparsable = True` doesn't really work as well.

### How to reproduce

Have a file with the following content:

~~~
CREATE EXTENSION IF NOT EXISTS hstore;

-------------------------------------------------------------------------------
-- Time Series Generation Function
-------------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION time_bucket(
    _time timestamp without time zone,
    _from timestamp without time zone,
    _to timestamp without time zone,
    _buckets integer DEFAULT 200,
    _offset integer DEFAULT 0
)
RETURNS timestamp without time zone
IMMUTABLE PARALLEL SAFE
BEGIN ATOMIC
SELECT date_bin(((_to - _from) / greatest((_buckets - 1), 1)), _time, _from) + ((_to - _from) / greatest((_buckets - 1), 1)) * (_offset + 1);
END;

CREATE OR REPLACE FUNCTION time_bucket_limited(_time timestamp, _from timestamp, _to timestamp, _buckets int = 200)
    RETURNS timestamp
    IMMUTABLE PARALLEL SAFE
BEGIN ATOMIC
    RETURN CASE WHEN _time <= _from THEN _from
      WHEN _time >= _to THEN _to
      ELSE DATE_BIN((_to - _from) / GREATEST(_buckets - 1, 1), _time, _from) + ((_to - _from) / GREATEST(_buckets - 1, 1))
    end;
END;

CREATE OR REPLACE FUNCTION time_series(
    _from timestamp without time zone,
    _to timestamp without time zone,
    _buckets integer DEFAULT 200
)
RETURNS TABLE ("time" timestamp without time zone)
IMMUTABLE PARALLEL SAFE
BEGIN ATOMIC
-- ATTENTION: use integer to generate series, since with timestamps there are rounding issues
SELECT time_bucket(_from, _from, _to, _buckets, g.ofs - 1)
FROM generate_series(0, greatest((_buckets - 1), 1)) AS g (ofs);
END;
~~~

and try to run `sqlfluff lint <file-name> --dialect postgres` with it.

### Dialect

postgres

### Version

sqlfluff, version 2.3.3
Python 3.11.4

### Configuration

~~~
[sqlfluff]
# Supported dialects https://docs.sqlfluff.com/en/stable/dialects.html
# Or run 'sqlfluff dialects'
dialect = postgres
~~~

### Are you willing to work on and submit a PR to address the issue?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by anneadb** [comment]
Hi,
did you ever find a solution?
I am running into the same error with dialect "exasol".

**Comment by AndLut** [comment]
Unfortunately not. We went with another solution in the end.

**Comment by anneadb** [comment]
> Unfortunately not. We went with another solution in the end.

Too bad. Thanks for the reply. Maybe someone else will have a solution.

**Comment by WittierDinosaur** [comment]
@anneadb Can you raise a separate issue for your problem. I've found the issue and raised a PR to fix it in Postgres, but that won't affect Exasol
