### ISSUE TITLE
Public API to get individual fixes

### ISSUE THREAD

**Issue by golergka** [sqlfluff/sqlfluff#5353]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### Description

I want to have a public API to get a list of errors with fixes for them, which could be displayed in an IDE.

I've been writing code that would use internal, undocumented APIs to achieve this, but I've ran into some problems.

I can get a list of errors with fixes like this:

```Python
from sqlfluff.core.linter import Linter

# ...some many lines later...

linter = Linter(config=config)
result = linter.lint_string_wrapped(args.content)
violations = result.paths[0].files[0].violations
for error in violations:
    if isinstance(error, SQLLintError):
        fixes: List[SQLFluffLintFix] = error.fixes
        # TODO Convert fixes
    else:
        logger.trace("Not SQLLintError")
```

And I was trying to come up with a function that would convert a LintFix instance to a serialisable representation, which could then be used in a code editor:

```Python
from sqlfluff.core.rules.base import LintFix as SQLFluffLintFix


# These data classes map to Monaco or other potential editor's types

class Range:
    start_line_number: int
    start_column: int
    end_line_number: int
    end_column: int


class LintFixEdit:
    range: Range
    text: str


class LintFix:
    title: str
    edits: List[LintFixEdit]


def sqlfluff_to_editor_lint_fix(
    sqlfluff_lint_fix: SQLFluffLintFix,
) -> Optional[LintFix]:
    popsql_edits: List[LintFixEdit] = []

    # PROBLEM
    # Position marker doesn't always exist
    anchor_pos = sqlfluff_lint_fix.anchor.pos_marker
    if not anchor_pos:
        raise ValueError(
            f"Anchor position not found for fix: {sqlfluff_lint_fix}"
        )

    range_start_line = anchor_pos.line_no
    range_start_column = anchor_pos.line_pos

    edit_text = ""

    if sqlfluff_lint_fix.edit_type == "delete":
        # Nothing to do, text stays empty and range defines the segment to delete
        pass
    elif sqlfluff_lint_fix.edit_type in [
        "create_before",
        "create_after",
        "replace",
    ]:
        if not sqlfluff_lint_fix.edit:
            raise ValueError(
                f"Edit segments are missing for a non-delete operation: {sqlfluff_lint_fix}"
            )

        for edit_segment in sqlfluff_lint_fix.edit:
            edit_text += edit_segment.raw

            # PROBLEM
            # How to get a range end position?

```

The core of the problem with this approach is that `BaseSegment` class is not actually a position in source code, but some kind of very representation. This makes sense for a parser, but I didn't understand how to convert `BaseSegment` to a pair of start and end line and column numbers.

### Use case

I want to display sqlfluff fixes as "quick fixes" in a code editor, and be able to instantly apply those edits when user selects one (without running sqlfluff again).

<img width="456" alt="Screenshot 2023-10-25 at 12 47 27" src="https://github.com/sqlfluff/sqlfluff/assets/929735/029a6a9a-e9e1-4520-92b6-982f74fab08e">

(In my particular case, I will use Monaco editor).

### Dialect

Not specific to any dialect

### Are you willing to work on and submit a PR to address the issue?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by alanmcruickshank** [comment]
Great idea. I've actually just made some progress toward this _already_. You might want to check out what I've just done in #5348.

The important method here is `sqlfluff.core.rules.fix.iter_patches()`, which yields an iterable of `FixPatch` objects. This will form the backbone of what we need for this. The one potential issue here is that these are in the "templated" space (i.e. there will be duplicates in here in the case of jinja loops). The logic which currently applies those fixes and builds up the final linted string is in `sqlfluff.core.linter.linted_file.LintedFile.fix_string()`, which is bundled into a few private methods which first run some de-duplication and the builds up the final file step by step.

The logic is all there, but we'll need some work to expose this properly.

The big question is is how we reference the location of fixes in the source file. We can generate all the patches, but as soon as any are applied, the references to any _later_ patches are then inaccurate. I'll try to illustrate...

Lets say we have an original file like this:

```sql
SELECT abc FROM def
```

And two fixes which are designed to edit `abc` to `ABCABC` and `def` to `DEFDEF`, these would reference the location of `7:10 -> "ABCABC"` and `16:19 -> "DEFDEF"`. If we apply the first one, the resulting file would be this:

```sql
SELECT ABCABC FROM def
```

Now we have one remaining fix "left in the buffer", but the positioning of it is _no longer accurate_, and if we apply it without any adjustments, then we would end up with:

```sql
SELECT ABCABC FRDEFDEFdef
```

...which is now an invalid query.

@golergka - for your use case, do you have a sense of how you'd like to keep the references for un-applied fixes accurate as the earlier ones are applied?

**Comment by alanmcruickshank** [comment]
🤔 - the more I think about it, the adjustments should just be adding the length difference to later locations (in the example above, we just need to add 3 to the positions of any later fixes). Would you be up for that solution? You'd have to apply that logic within your tooling, but it would allow you to apply SQLFluff patches fairly simply (and it might be logic we could use internally within SQLFluff to simplify things too, but even easier because by applying the fixes in reverse order we never need to do any of the adjustments).

**Comment by golergka** [comment]
> for your use case, do you have a sense of how you'd like to keep the references for un-applied fixes accurate as the earlier ones are applied?

In my use case, I would never apply the patches while the python code is running — it would be a completely one-off operation, like running a regular lint and getting results back. If user would choose to apply some of the patches, he would do so in the editor, a completely separate application, after these patches would be translated to it's format.
