### ISSUE TITLE
Release timeline for 0.5.0

### ISSUE THREAD

**Issue by alanmcruickshank** [sqlfluff/sqlfluff#542]
Following on from #470 , this tracks the release schedule for 0.5.0.

As at writing, there are no major items planned for this release, but I'm sure they'll filter through. Project for that are here: https://github.com/sqlfluff/sqlfluff/projects/3.

If there are any big features we'd like to target, then let the discussion begin!

**Comment by pwildenhain** [comment]
The biggest feature request that I've seen on GitHub and slack is skipping linting for templated sql. I think this should be the default behavior, with the option to turn it back on.

From what I understand this could get pretty hairy with the current state of the linting infrastructure 😬 but I'm looking forward to us figuring it out 🧠 ⚡ 

Another big feature that I'm excited for is #201 to add severity levels to our lint violations, allowing users to downgrade certain lints to "warnings" if they aren't that concerned about them. I feel like this will give the project more flexibility, and also make the VSCode plugin better as well.

Lastly (for now) I think 0.5 should have some common sense jinja linting rules in it, some of which have already had issues filed.

**Comment by alanmcruickshank** [comment]
There are a few big changes which mean that I think we should publish 0.5.0 as the next release:

- #825: Extracts dialects out. This isn't a breaking change in itself, but it does introduce a breaking change to the API with the renaming of `sqlfluff.dialects()` and `sqlfluff.rules()` (although they were only introduced in #809 so it shouldn't cause too much pain). The scale of the change to the codebase alone might also warrant a major release.
- #882: Renames a lot elements in the parse tree and changes the structure of the FROM clause. Given the scale of the change this has the potential to be a breaking change.
- #880: Could be a breaking change for anyone defining custom rules.
- #826: Isn't a breaking change, but means that the docs for the last major release might be broken.

The issues that I'd definitely like to get merged before release are:
- #825 
- #882 
- #868 
- #838 

Bonus points for any others we can also merge before that point.

@sqlfluff/sqlfluff-maintainers - any other issues or PRs which we think are particularly pressing to get into the next release? I'm thinking particularly about any bugs which are causing major headaches.

**Comment by NiallRees** [comment]
I'm going to attempt https://github.com/sqlfluff/sqlfluff/issues/464 this week too. Have an idea about how we can implement it in a relatively straightforward way.

**Comment by alanmcruickshank** [comment]
@NiallRees - I realise I said I would have a go at #586 a while back. I assume that would be a helpful stub to work from?

**Comment by NiallRees** [comment]
> @NiallRees - I realise I said I would have a go at #586 a while back. I assume that would be a helpful stub to work from?

The idea I currently have means we won't need to understand the jinja, and we can go off compiled SQL. That said I think there are potentially two sources of overlap though in #464 and #586:

- The rules will need to to raise an error even though the anchor segment is templated. 
- We should extend the current linting rule yml test cases to support jinja

**Comment by barrywhart** [comment]
#833 looks like a good bug to fix: An unexpected case in L003 (auto indent) causing a runtime error.

**Comment by pwildenhain** [comment]
I would also like to see issues like #845 and #831 addressed. If no one feels like they have time to pick it them up I can try to find time to dive in to the templating stuff 😬😅

**Comment by alanmcruickshank** [comment]
So I think #833 might already be solved. I've posted on that thread to confirm.

- I'll pick up #586 and #831 which I think have some overlap and will need more than just some extra rule logic.
- @NiallRees is going to pick up #464 . Could you also handle getting #868 sorted and merged? I think you and @dmateusp have been the main reviewers so far.
- I think #845 could be an interesting one for @pwildenhain to pick up. I haven't assigned it to you, but if you want to have a go I think it could be fun. You might run into something that you can't solve - but if you do then It's likely that I might solve that for you when I've done the other two.

Any more for any more?

**Comment by alanmcruickshank** [comment]
Anyone fancy taking on #201? It's an oldie - but it looks like we've got enough clarity on it to make progress now.

**Comment by pwildenhain** [comment]
@alanmcruickshank I've taken #845. Should I wait until you've addressed #586 and #831 before tackling that?

**Comment by alanmcruickshank** [comment]
> @alanmcruickshank I've taken #845. Should I wait until you've addressed #586 and #831 before tackling that?

Check out my pr for #586 (#892). It might be a good starting point for #845.

**Comment by barrywhart** [comment]
#610 would be another good one to look at. It's been open since December, and it's a case where the automated lint "fix" actually **breaks** existing code.

**Comment by alanmcruickshank** [comment]
I'm going to close this now we've released 0.5.0, we've closed of _most_ of these issues and the remaining ones can probably come out as minor releases.
