### ISSUE TITLE
Prefer CTE's over subqueries

### ISSUE THREAD

**Issue by NiallRees** [sqlfluff/sqlfluff#545]
https://discourse.getdbt.com/t/why-the-fishtown-sql-style-guide-uses-so-many-ctes/1091

**Comment by pwildenhain** [comment]
This resonates with me, I could definitely see implementing this as a lower-level lint (shout out to #201)

**Comment by alanmcruickshank** [comment]
Do you think that #782 addresses this enough. That PR is designed to address #89, but I realise comes close to this.

**Comment by NiallRees** [comment]
> Do you think that #782 addresses this enough? That PR is designed to address #89, but I realise comes close to this.
> 
> I'm tempted to say yes.

Just added a comment on the PR 👍

**Comment by alanmcruickshank** [comment]
I'm going to close this now that #782 is merged. I think the configurable elements of it solve this issue.
