### ISSUE TITLE
Add lint rule for no whitespace around shorthand cast

### ISSUE THREAD

**Issue by pwildenhain** [sqlfluff/sqlfluff#548]
> The code changes look good, but what's the reasoning for allowing gaps? For example, in the test case that you added, I would think the first line `'1' :: INT as id1,` should result in a lint, though definitely not a parsing error.

This is just to fix the parsing error that's all 👍 it should probably have a lint rule associated at some point though as you say.

_Originally posted by @NiallRees in https://github.com/sqlfluff/sqlfluff/pull/544#issuecomment-725655566_

**Comment by jpy-git** [comment]
This would be handy to have so I've extended L039 to account for this.
I currently have another PR affecting L039 in review atm so will push the PR for this once that's resolved 😄
