### ISSUE TITLE
Add support for pivot and unpivot statements for databricks

### ISSUE THREAD

**Issue by snkekorfus** [sqlfluff/sqlfluff#5483]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### Description

Add support for the pivot and unpivot statements from databricks looking like this:

Pivot:
```sql
SELECT year, region, q1, q2, q3, q4
  FROM sales
  PIVOT (sum(sales) AS sales
    FOR quarter
    IN (1 AS q1, 2 AS q2, 3 AS q3, 4 AS q4));
```

Unpivot:
```sql
SELECT *
  FROM sales UNPIVOT INCLUDE NULLS
    (sales FOR quarter IN 
    (q1       AS `Jan-Mar`,
     q2       AS `Apr-Jun`,
     q3       AS `Jul-Sep`,
     sales.q4 AS `Oct-Dec`)
);
```

Ref Pivot: https://docs.databricks.com/en/sql/language-manual/sql-ref-syntax-qry-select-pivot.html
Ref Unpivot: https://docs.databricks.com/en/sql/language-manual/sql-ref-syntax-qry-select-unpivot.html

### Dialect

databricks

### Are you willing to work on and submit a PR to address the issue?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by pp-gborodin** [comment]
Hi! Spark also has PIVOT and UNPIVOT
https://spark.apache.org/docs/latest/sql-ref-syntax-qry-select-pivot.html
https://spark.apache.org/docs/latest/sql-ref-syntax-qry-select-unpivot.html
