### ISSUE TITLE
Deprecate built-in dbt macros

### ISSUE THREAD

**Issue by NiallRees** [sqlfluff/sqlfluff#554]
Once #508 is released and stable, remove the build-in stub dbt macros from the codebase. This is a breaking change so communication and documentation should be part of the pull request and release.

**Comment by alanmcruickshank** [comment]
I'm not sure we should **remove** them. I agree that they're not as important once the dbt templater is in place, but I think they should be moved to a separate plugin. They definitely shouldn't be part of the standard install, but I suspect that the JinjaTemplater will always be faster than the DBTTemplater, so some users may prefer to use it.

Thoughts @NiallRees, @dmateusp  ?

**Comment by pwildenhain** [comment]
So are you suggesting that the `JinjaTemplater` should also be spun out to a plugin, and that it would come pre-packaged with a few key built-in `dbt` macros?
