### ISSUE TITLE
Cannot follow the documentation to configure files for pyproject.toml

### ISSUE THREAD

**Issue by iamtodor** [sqlfluff/sqlfluff#5578]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### Links or command line

I'm trying to configure https://docs.sqlfluff.com/en/stable/configuration.html#configuration-files `sqlfluff` thru `pyproject.toml` config file and if I copy the code from the doc it simply does not work.

# First example

```toml
[tool.sqlfluff.core]
templater = "jinja"
sql_file_exts = ".sql,.sql.j2,.dml,.ddl"
```

This block does not work: it raises the following error: 

```
Traceback (most recent call last):
  File "/Users/user/programming/freshbooks/code/data-pipelines/.venv/bin/sqlfluff", line 8, in <module>
    sys.exit(cli())
  File "/Users/user/programming/freshbooks/code/data-pipelines/.venv/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/user/programming/freshbooks/code/data-pipelines/.venv/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/user/programming/freshbooks/code/data-pipelines/.venv/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/user/programming/freshbooks/code/data-pipelines/.venv/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/user/programming/freshbooks/code/data-pipelines/.venv/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/user/programming/freshbooks/code/data-pipelines/.venv/lib/python3.8/site-packages/sqlfluff/cli/commands.py", line 603, in lint
    config = get_config(
  File "/Users/user/programming/freshbooks/code/data-pipelines/.venv/lib/python3.8/site-packages/sqlfluff/cli/commands.py", line 416, in get_config
    return FluffConfig.from_root(
  File "/Users/user/programming/freshbooks/code/data-pipelines/.venv/lib/python3.8/site-packages/sqlfluff/core/config.py", line 906, in from_root
    return cls(
  File "/Users/user/programming/freshbooks/code/data-pipelines/.venv/lib/python3.8/site-packages/sqlfluff/core/config.py", line 800, in __init__
    self._configs = nested_combine(
  File "/Users/user/programming/freshbooks/code/data-pipelines/.venv/lib/python3.8/site-packages/sqlfluff/core/helpers/dict.py", line 37, in nested_combine
    raise ValueError(
ValueError: Key 'templater' is a dict in one config but not another! PANIC: 'jinja'
```

Instead of `[tool.sqlfluff.core]` I have to use `[sqlfluff.code]`:

```toml
[sqlfluff.core]
templater = "jinja"
sql_file_exts = ".sql,.sql.j2,.dml,.ddl"
```

# Second example where dialect is being ignored

I cannot specify dialect in the `pyproject.toml` file:

```toml
[sqlfluff]
templater = "jinja"
sql_file_exts = ".sql, .sql.j2, .dml,.ddl"
dialect = "bigquery"
```

```
>>> sqlfluff lint my_model.sql

User Error: No dialect was specified. You must configure a dialect or specify one on the command line using --dialect after the command. Available dialects:
ansi, athena, bigquery, clickhouse, databricks, db2, duckdb, exasol, greenplum, hive, materialize, mysql, oracle, postgres, redshift, snowflake, soql, sparksql, sqlite, teradata, trino, tsql
```

It simply does not read the provided configuration.

What am I missing in this particular case?

I have the `sqlfluff==2.3.5` version installed

### Issue/Suggested Improvement

Under the discussion

### Are you willing to work on and submit a PR to address the issue?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by emmagan** [comment]
for the second example, you can change the dialect if you switch the pyproject.toml section name to `[tools.sqlfluff.core]`. i had the same issue specifying dialect using `[tools.sqlfluff]`

**Comment by iamtodor** [comment]
@emmagan if I follow you correctly, this one does not work :(

```
[sqlfluff]
templater = "dbt"
sql_file_exts = ".sql, .sql.j2, .dml,.ddl"

[tools.sqlfluff.core]
dialect = "bigquery"
```

**Comment by jonathanunderwood** [comment]
It's `tool` not `tools` that you need. E.g.

```yaml
[tool.sqlfluff.core]
dialect = "snowflake"
templater = "dbt"
runaway_limit = 10
max_line_length = 100
indent_unit = "space"

[tool.sqlfluff.templater.dbt]
project_dir = "./proj"

[tool.sqlfluff.indentation]
tab_space_size = 4

[tool.sqlfluff.layout.type.comma]
spacing_before = "touch"
line_position = "trailing"
```

The docs are quite unclear on all this though, for sure.

**Comment by iamtodor** [comment]
@jonathanunderwood thank you for pointing it out!

**Comment by Madsfvk** [comment]
@jonathanunderwood  @iamtodor can you help me understand why the ```max_line_length``` doesn't seem to take effect?

I have this configured in my ```pyproject.toml``` file.

`[tool.sqlfluff.core]
dialect = "snowflake"
templater = "jinja"
processes = -1
max_line_length = 100`

And still get this output when linting in dBt:
![image](https://github.com/sqlfluff/sqlfluff/assets/49226961/5b980f1f-1090-4b0b-ae32-46e39c93566e)

**Comment by alanmcruickshank** [comment]
I'm going to close this issue unless someone has an idea on how the make the docs clearer on this.

I've tested the file example given:
```toml
[tool.sqlfluff.core]
templater = "jinja"
sql_file_exts = ".sql,.sql.j2,.dml,.ddl"
```

And it's formatted correctly and does load without error on the current SQLFluff release.

As others have pointed out, using `tools` or just `[sqlfluff]` in the `toml` config files won't work as described here in the docs: https://docs.sqlfluff.com/en/stable/configuration/setting_configuration.html#configuration-files

> For the [pyproject.toml file](https://www.python.org/dev/peps/pep-0518/), all valid sections start with `tool.sqlfluff` and subsections are delimited by a dot. For example the jinjacontext section will be indicated in the section started with `[tool.sqlfluff.jinjacontext]`.
