### ISSUE TITLE
Support `.sqlfluffignore` configuration in `pyproject.toml`

### ISSUE THREAD

**Issue by aaaaahaaaaa** [sqlfluff/sqlfluff#5596]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### Description

In the spirit of reducing the number of config files required, it would be great if the `sqlfluffignore` configuration could be supported in `pyproject.toml`.

### Dialect

`pyproject.toml` configuration

### Are you willing to work on and submit a PR to address the issue?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by aaaaahaaaaa** [comment]
Sounds perfect

**Comment by frehoy** [comment]
> This is definitely possible, and would also open up the option of specifying ignore options in the `.sqlfluff` file too. By setting up one we would do almost all of the work to set up the other.
> 
> My initial suggestion is that this would be it's actually just a new key in the top line config, something like:
> 
> ```ini
> [sqlfluff]
> ignore_files =
>     foo.sql
>     bar.sql
> ```
> 
> or
> 
> ```toml
> [tool.sqlfluff.core]
> ignore_files = [
>     "foo.sql",
>     "bar.sql",
> ]
> ```
> 
> How does that sound?

In our project we ignore entire directories like
```
#.sqlfluffignore
dbt_modules/
dbt_packages/
```
so calling it `ignore_files` files could be a bit confusing. How about `ignore_paths`?
