### ISSUE TITLE
Allow downgrading errors coming from templated code to "warnings"

### ISSUE THREAD

**Issue by dmateusp** [sqlfluff/sqlfluff#563]
Raised in #363 by @azhard 

The work in #541 would allow us to know if an error comes from a templated block. From there we could introduce another "class" of issues which do not cause the `sqlfluff lint` command to fail, but are still returned (for libraries interacting with sqlfluff directly) and displays them (for the CLI)

**Comment by alanmcruickshank** [comment]
Rules must now specify whether they are suitable for templated code or not. I think that addresses this use case, so I'm going to close this as stale.
