### ISSUE TITLE
Escape is unparseable

### ISSUE THREAD

**Issue by gnilrets** [sqlfluff/sqlfluff#564]
Hi, I'm  using SQLFluff 0.3.6 with the Snowflake dialect and found that when I use ESCAPE, I get an unparsable error:
```
SELECT *
FROM
  x
WHERE
  z LIKE '^_f' ESCAPE '^'
```

gives:
```
L:   5 | P:  15 |  PRS | Found unparsable section: " ESCAPE '^'"
```

**Comment by pwildenhain** [comment]
Strange: looks like it exists in the [`ansi_keywords.py`](https://github.com/sqlfluff/sqlfluff/blob/master/src/sqlfluff/core/dialects/ansi_keywords.py#L244) module as an "unreserved" keyword so I'm not sure why it would have trouble recognizing it
