### ISSUE TITLE
EPOCH not recognized as a keyword

### ISSUE THREAD

**Issue by gnilrets** [sqlfluff/sqlfluff#565]
Hi, I'm using SQLFluff 0.3.6 with the Snowflake dialect and found that when I try to extract the epoch from a timestamp, I get an error about an unqualified reference, which leads me to believe that it's not recognizing the `EPOCH` keyword:

```
SELECT
  EXTRACT(EPOCH FROM t1.sometime) AS myepoch
FROM
  t1
INNER JOIN
  t2 ON t1.pk = t2.pk
```

gives:
```
L:   2 | P:  11 | L027 | Unqualified reference 'EPOCH' found in select with more
                       | than one referenced table/view.
```

**Comment by pwildenhain** [comment]
I'm not sure if this is a snowflake specific issue, I use netezza at work, a postgre fork, which also has the `epoch` keyword.

**Comment by pwildenhain** [comment]
confirmed that this is just for the postgres dialect (which snowflake inherits from). PR incoming 🚀
