### ISSUE TITLE
mysql SET NAMES statement is not supported

### ISSUE THREAD

**Issue by ergohack** [sqlfluff/sqlfluff#5663]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### What Happened

== [test.sql] FAIL                                                                                             
L:   4 | P:   1 |  PRS | Line 4, Position 1: Found unparsable section: "SET NAMES
                       | 'utf8';"
WARNING: Parsing errors found and dialect is set to 'mysql'. Have you configured your dialect correctly?

### Expected Behaviour

As the statement matches the MySQL 8 documentation for [SET NAMES](https://dev.mysql.com/doc/refman/8.0/en/set-names.html), this line should have had no error.

### Observed Behaviour

Instead, all processing of the file stopped.

### How to reproduce

Add a legitimate `SET NAMES` statement to your .sql file.  e.g. `SET NAMES 'utf8';` or `SET NAMES DEFAULT;`

### Dialect

mysql

### Version

sqlfluff, version 2.3.5

### Configuration

[sqlfluff]
dialect = mysql
large_file_skip_byte_limit = 0

[sqlfluff:indentation]
tab_space_size = 4

### Are you willing to work on and submit a PR to address the issue?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by greg-finley** [comment]
Hey! It's done here: https://github.com/sqlfluff/sqlfluff/pull/5374

You can get it in [3.0 pre-release](https://github.com/sqlfluff/sqlfluff/releases/tag/3.0.0a6) or wait for the [3.0 release](https://github.com/sqlfluff/sqlfluff/pull/5660) soon.
