### ISSUE TITLE
Update to the "About"

### ISSUE THREAD

**Issue by dmateusp** [sqlfluff/sqlfluff#567]
The about isn't very descriptive ^^, what about

> A modular SQL linter and auto-formatter with support for multiple dialects and templated code

**Comment by NiallRees** [comment]
I like this

**Comment by pwildenhain** [comment]
I think @alanmcruickshank is the only who can update this. You're talking about the GitHub "About" right?

**Comment by alanmcruickshank** [comment]
Done :)

Only took me 2 yrs.

**Comment by pwildenhain** [comment]
To be fair, I see now that I can modify it, since you changed our repo permissions....anyway, better late than never 🤷🏻 
Thanks!
