### ISSUE TITLE
BigQuery GROUP BY ALL parsing violation

### ISSUE THREAD

**Issue by mzouvelos** [sqlfluff/sqlfluff#5671]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### What Happened

sqlfluff throughs parsing violation when finding line with command GROUP BY ALL in BigQuery dialect file.
This causes sqlfluff to report back these as templating/parsing errors found and return only unfixable linting violations for all other occurences without linting anything.

### Expected Behaviour

sqlfluff to not detect GROUP BY ALL in BigQuery dialect as a parsing violation and continue to lint the file as normal

### Observed Behaviour

![sqlfluff_group_by_all](https://github.com/sqlfluff/sqlfluff/assets/85908602/90ec5cfe-762b-4b62-af83-1b65319ba46a)

### How to reproduce

any .sql file with GROUP BY ALL command from BigQuery dialect

### Dialect

bigquery

### Version

sqlfluff 2.3.5

### Configuration

[sqlfluff]
verbose=0
dialect = bigquery
templater = dbt
max_line_length = 160
exclude_rules = CP02, LT01, L034, ST07, LT08, LT11, RF04

[sqlfluff:templater:dbt]
profiles_dir = ./profiles

[tool.sqlfluff.templater.jinja]
apply_dbt_builtins = True

[sqlfluff:indentation]
indented_joins = False
indented_ctes = False
indented_then = False
template_blocks_indent = False
tab_space_size = 4
indent_unit = space
comma_style = trailing
indented_using_on = False
allow_implicit_indents = True

[sqlfluff:rules]
allow_scalar = True
single_table_references = consistent
only_aliases = True

[sqlfluff:rules:capitalisation.keywords]
capitalisation_policy = upper

[sqlfluff:rules:layout.long_lines]
ignore_comment_lines = True

[sqlfluff:rules:layout.select_targets]
wildcard_policy = single

[sqlfluff:layout:type:comma]
spacing_before = touch
line_position = trailing

[sqlfluff:layout:type:keyword]
line_position = alone:strict

[sqlfluff:layout:type:select_clause]
line_position = alone:strict

[sqlfluff:layout:type:where_clause]
line_position = alone:strict

[sqlfluff:layout:type:from_clause]
line_position = alone:strict

[sqlfluff:layout:type:join_clause]
line_position = alone:strict

[sqlfluff:layout:type:groupby_clause]
line_position = alone:strict

[sqlfluff:rules:capitalisation.functions]
capitalisation_policy = upper

[sqlfluff:rules:convention.select_trailing_comma]
select_clause_trailing_comma = forbid

[sqlfluff:rules:capitalisation.literals]  # Null & Boolean Literals
capitalisation_policy = upper

[sqlfluff:rules:structure.subquery]
forbid_subquery_in = both

[sqlfluff:rules:convention.quoted_literals]
preferred_quoted_literal_style = double_quotes

[sqlfluff:rules:ambiguous.column_references]  # Number in group by
group_by_and_order_by_style = implicit

### Are you willing to work on and submit a PR to address the issue?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by WittierDinosaur** [comment]
This is fixed in the current version of main, it's also fixed in the latest release 3.0.0a6 - we'll be releasing 3.0.0 at some point over the next day or so, and we consider the latest alpha as stable
