### ISSUE TITLE
Sql FLuff VScode extension on formatting adding a debug line to the top of the sql file

### ISSUE THREAD

**Issue by alexandreczg** [sqlfluff/sqlfluff#5679]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### What Happened

For some reason the VScode extension is adding the following line:
```
The -f/--force option is deprecated as it is now the default behaviour.
```

to the top of any sql file I format on save.  It seems to be running the command:
```
sqlfluff fix --force -
```

### Expected Behaviour

To no add that line on top.

### Observed Behaviour

![image](https://github.com/sqlfluff/sqlfluff/assets/131292734/3319627e-aef1-4a28-ba61-621453363cc8)

### How to reproduce

Install the VScode extension `v2.4.4` and save a SQL file. 

### Dialect

Postgres

### Version

```
$ sqlfluff --version
sqlfluff, version 3.0.1
$ python --version
Python 3.12.2
```

### Configuration

pyproject.toml
```
[tool.sqlfluff.core]
# Supported dialects https://docs.sqlfluff.com/en/stable/dialects.html
# Or run 'sqlfluff dialects'
dialect = 'postgres'
```

### Are you willing to work on and submit a PR to address the issue?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by alanmcruickshank** [comment]
OOooh good catch. Yep this isn't the intended functionality. I'll sort this in the next few days.
