### ISSUE TITLE
Add better test case names to these old std rules tests

### ISSUE THREAD

**Issue by pwildenhain** [sqlfluff/sqlfluff#574]
Right now the standard rules test cases have names like `test_1`, `test_2`, etc. These names should be updated to be more descriptive, and potentially adding a longer test case description with the `desc:` yaml key.

_Originally posted by @pwildenhain in https://github.com/sqlfluff/sqlfluff/pull/553#discussion_r528269346_

**Comment by linchun3** [comment]
@pwildenhain I'll give this a shot if you've not started on it?

**Comment by pwildenhain** [comment]
Yup, go for it!

**Comment by pwildenhain** [comment]
@linchun3 any progress on this? It's ok if you didn't get to all of them, progress is progress 👍🏻 and we could still merge

**Comment by linchun3** [comment]
Hey! Yeah I was halfway through it, I'll commit what I have in a PR and tag you for review in awhile.

**Comment by ttomasz** [comment]
Hi, it seems there was not much going on in this issue recently so I'll go ahead and try to improve some of the names that remain
