### ISSUE TITLE
sqlfluff deletes dbt query and replaces with "15:25:23  Registered adapter: redshift=1.7.0"

### ISSUE THREAD

**Issue by hblauth** [sqlfluff/sqlfluff#5750]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### What Happened

When I save a abt SQL query in vscode, with sqlfluff set to run on save file, sqlfluff overwrites the whole query with "15:25:23  Registered adapter: redshift=1.7.0"

### Expected Behaviour

Linting and fixing the query in accordance with the rules

### Observed Behaviour

When I save a abt SQL query in vscode, with sqlfluff set to run on save file, sqlfluff overwrites the whole query with "15:25:23  Registered adapter: redshift=1.7.0"

### How to reproduce

sqlfluff settings:

[sqlfluff]
dialect = redshift
templater = dbt
max_line_length = 120

[sqlfluff:rules:capitalisation.keywords]
capitalisation_policy = upper

[sqlfluff:rules:capitalisation.identifiers]
extended_capitalisation_policy = lower

[sqlfluff:layout:type:comma]
spacing_before = touch
line_position = leading

[sqlfluff:layout:type:alias_expression]
spacing_before = align
align_within = select_clause
align_scope = bracketed

[sqlfluff:rules:convention.casting_style]
preferred_type_casting_style = shorthand

[sqlfluff:templater:dbt]
project_dir = ./
profiles_dir = ./
profile = default
target = dev

Query:
{{
config(
materialized='table'
)
}}

SELECT
    jt.eventid AS event_id
    , jt.eventtype AS event_type
    , jt.eventtimestamp AS event_timestamp
    , jt.jobid AS job_id
    , jt.title AS job_title
    , jtjt.tags.level AS level
    , ms_level.score AS level_score
    , jtjt.tags.activity AS activity
    , ms_activity.score AS activity_score
    , jtjt.tags.specialism AS specialism
    , ms_specialism.score AS specialism_score
    , jt.dhimetadata.schemaid::varchar(150) AS dcs_schema_id
    , jt.dhimetadata.schemaversion::varchar(10) AS dcs_schema_version
    , RANK() OVER (PARTITION BY jt.jobid ORDER BY jt.eventtimestamp DESC)
FROM
    dcs_job_tags_spectrum.job_tags_v2 AS jt
    , jt.job_tags AS jtjt
    , jt.model_score.level AS ms_level
    , jt.model_score.activity AS ms_activity
    , jt.model_score.specialism AS ms_specialism
WHERE
    ISNULL(jt.dhimetadata.issystemtest, FALSE) = FALSE

    {% if is_incremental() %}
        AND jt.ingest_date >= TO_CHAR(sysdate - 3, 'YYYYMMDD')
    {% endif %}

### Dialect

redshift

### Version

sqlfluff, version 2.3.5
Python 3.7.13

### Configuration

[sqlfluff]
dialect = redshift
templater = dbt
max_line_length = 120

[sqlfluff:rules:capitalisation.keywords]
capitalisation_policy = upper

[sqlfluff:rules:capitalisation.identifiers]
extended_capitalisation_policy = lower

[sqlfluff:layout:type:comma]
spacing_before = touch
line_position = leading

[sqlfluff:layout:type:alias_expression]
spacing_before = align
align_within = select_clause
align_scope = bracketed

[sqlfluff:rules:convention.casting_style]
preferred_type_casting_style = shorthand

[sqlfluff:templater:dbt]
project_dir = ./
profiles_dir = ./
profile = default
target = dev

### Are you willing to work on and submit a PR to address the issue?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by keraion** [comment]
Also note sqlfluff/vscode-sqlfluff#132
