### ISSUE TITLE
Maintainers pre 0.4.0 get together

### ISSUE THREAD

**Issue by NiallRees** [sqlfluff/sqlfluff#582]
Hey everyone, it would be great to get a chance to meet and chat about the 0.4.0 release now that we're almost there. Thanks to some big contributions in the last week, we now have full dbt templating support thanks to @dmateusp, and @alanmcruickshank's improvement of lintfix application means fixes are now 'instant' vs the old 2 mins+ for some files.

From what I can see we're all either GMT or EST timezones, how would 17:00 GMT Tuesday the 1st of December work for everyone? If you could comment with an email address I can send a calendar invite to that would be great 👍

**Comment by dmateusp** [comment]
Sounds good! I might arrive a few minutes late depending on the meeting I have right before

 dmateusp@gmail.com

**Comment by barrywhart** [comment]
barrywhart@yahoo.com

**Comment by pwildenhain** [comment]
I might have to leave early (dentist 🦷 ) but I can be on at 12!

pwildenhain@gmail.com

**Comment by nolanbconaway** [comment]
I'll pop in! nolanbconaway@gmail.com

**Comment by pwildenhain** [comment]
I haven't gotten an invite -- did you send something out @NiallRees ?

**Comment by NiallRees** [comment]
Just sent the invites!

**Comment by NiallRees** [comment]
@dorzey ?

**Comment by dorzey** [comment]
Yep. I can make it dorzey@gmail.com

**Comment by NiallRees** [comment]
invite sent @dorzey
