### ISSUE TITLE
MariaDB into existing MySQL, or new dialect for CREATE/DROP [OR REPLACE] ?

### ISSUE THREAD

**Issue by Xemptuous** [sqlfluff/sqlfluff#5840]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### Description

MariaDB has some small syntactic differences compared to MySQL, but for the most part should be very similar. I have run into issues where the linter throws `unparsable section` errors because of the presence of `CREATE OR REPLACE TABLE` statements, because MySQL doesn't support the OR REPLACE syntax. 

There are many more instances where parsing errors happen due to small differences between these dialects. 

Would it be preferrable to add to the existing MySQL syntax, or to create a whole new dialect specifically for the small MariaDB changes?i

### Use case

`mariadb` dialect added that borrows heavily from `mysql` but with syntax differences accounted for.

### Dialect

MySQL

### Are you willing to work on and submit a PR to address the issue?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by WittierDinosaur** [comment]
I think a new dialect, based off of MySQL is the way to go here. Do you fancy drafting the initial implementation?

**Comment by Xemptuous** [comment]
> I think a new dialect, based off of MySQL is the way to go here. Do you fancy drafting the initial implementation?

Yes, I can try and draft a PR linking to this. It might take me a bit to understand how to get it done, but I can get working on a branch soon.

**Comment by WittierDinosaur** [comment]
Great! For pointers on how to do it: #5640 added Vertica, and #5741 added a couple of bits that the first PR missed

**Comment by Xemptuous** [comment]
> Great! For pointers on how to do it: #5640 added Vertica, and #5741 added a couple of bits that the first PR missed

Thanks, that's helpful! Since MariaDB is so similar to MySQL just with small differences, would you suggest I copy-paste mysql and make small changes as needed, or do the mariadb dialect file from scratch but using the mysql one as reference?
