### ISSUE TITLE
New rule. Jinja tag content should be surrounded by whitespace.

### ISSUE THREAD

**Issue by alanmcruickshank** [sqlfluff/sqlfluff#586]
The basic machinery for doing this is now in place with #541, however some structural changes will probably still be required.

This would be a rule which lints jinja tags (`{{ }}`, `{# #}` & `{% %}`) in templated queries and ensures that there is at least a single whitespace between the delimiters of the tag and the content.

Bad: `{{ref()}}`, `{{my_variable}}`, `{{1+2}}`, `{%else%}`

Good: `{{ ref() }}`, `{{ my_variable }}`, `{{ 1+ 2 }}`, `{% else %}`.

Note: I don't think we should attempt to lint or parse the _content_ of the tag significantly beyond the edges as this would involve us effectively building a whole new sub-language within sqlfluff which feels like significant scope creep!

**Comment by dmateusp** [comment]
love this! I'm pretty sure my eye twitches every time I don't see the spaces
