### ISSUE TITLE
Comment after table name in a WITH clause break layout.spacing (LT01)

### ISSUE THREAD

**Issue by Stefan-Data** [sqlfluff/sqlfluff#5897]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### What Happened

In a WITH statement you cannot put a comment in between the table name and the AS. This would be valid if the comment is followed by a newline, but sqlfluff wants to rmove the line break and in doing so adds it to the comment.

Given the following SQL:
```
WITH bug_base_table -- Putting a comment here to prove that sqlfull will misplace the AS seen on the line below. 
AS (
  SELECT 1 AS col1
)

SELECT * FROM bug_base_table
```

### Expected Behaviour

I would like to either retain the original SQL or fix it to something such as:
```
-- Putting a comment here to prove that sqlfull will misplace the AS seen on the line below. 
WITH bug_base_table AS (
  SELECT 1 AS col1
)

SELECT * FROM bug_base_table
```

### Observed Behaviour

Unfortunately the SQL is "fixed" to the following invalid SQL:
```
WITH bug_base_table -- Putting a comment here to prove that sqlfull will misplace the AS seen on the line below. AS (
  SELECT 1 AS col1
)

SELECT * FROM bug_base_table
```

### How to reproduce

Create a CTE with a comment after the table name, followed by a newline.

### Dialect

Databricks

### Version

sqlfluff, version 3.0.6
Python 3.10.11

### Configuration

```
[sqlfluff]
dialect = databricks
```

### Are you willing to work on and submit a PR to address the issue?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by keraion** [comment]
Fixed by #6140
