### ISSUE TITLE
SQL translation?

### ISSUE THREAD

**Issue by PenelopeFudd** [sqlfluff/sqlfluff#5902]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### Description

Since SqlFluff is generating an abstract syntax tree from the input, could it be used to translate from one dialect to another?

### Use case

I'd like to be able to convert SQL syntax from one dialect (e.g. SQLite) to another (e.g. Postgres).  

Some features may not be available in the target dialect, and that's ok, as long as it's clear when a statement couldn't be translated.

Partial translations would be ok too, again, making it clear that statement should not be used as-is.

### Dialect

all

### Are you willing to work on and submit a PR to address the issue?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by greg-finley** [comment]
I think we probably wouldn’t attempt it given that is hard to add and covered well by sqlglot already. Check it out: https://github.com/tobymao/sqlglot?tab=readme-ov-file#formatting-and-transpiling

**Comment by PenelopeFudd** [comment]
'kay, thanks!
