### ISSUE TITLE
Got the error "Undefined jinja template variable: 'dbt_utils'" after ugrading to dbt 1.8

### ISSUE THREAD

**Issue by splat-ef** [sqlfluff/sqlfluff#5904]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### What Happened

I am using dbt in Snowflake and after switching to dbt v1.8, I'm now seeing the following error message:

`TMP | Undefined jinja template variable: 'dbt_utils'`

when using `dbt_utils` macros like this one:

`select {{ dbt_utils.generate_surrogate_key([xxx]) }} from <my_table>`.

Note that:

- I also got new errors for custom macros but that got fixed once I added `load_macros_from_path = macros` to my `.sqlfluff` file.
- adding `apply_dbt_builtins = True` does not solve the issue.

### Expected Behaviour

SQLFluff successfully parses dbt_utils macros.

### Observed Behaviour

SQLFluff throws two errors:

- a TMP error and, because of this, 
- also throws a PRS error: `PRS | Line xx, Position xx: Found unparsable section`.

### How to reproduce

This simple code generates a surrogate key from a constant string:

```
select {{ dbt_utils.generate_surrogate_key(["'my_constant_string'"]) }} as my_sk
```

The SQLFluff linter returns:

```
L:   1 | P:  11 |  TMP | Undefined jinja template variable: 'dbt_utils'
L:   1 | P:  73 |  PRS | Line 1, Position 9: Found unparsable section: 'as my_sk'
```

### Dialect

snowflake

### Version

Python version:
- Python 3.11.9

dbt packages:
- dbt-adapters: 1.2.1
- dbt-common: 1.1.0
- dbt-core: 1.8.0
- dbt-extractor: 0.5.1
- dbt-semantic-interfaces: 0.5.1
- dbt-snowflake: 1.8.1

SQLFluff packages:
- sqlfluff: 3.0.7
- sqlfluff-templater-dbt: 3.0.7

### Configuration

```
[sqlfluff]
dialect = snowflake
runaway_limit = 10

[sqlfluff:templater:jinja]
load_macros_from_path = macros
apply_dbt_builtins = True
```

### Are you willing to work on and submit a PR to address the issue?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by alanmcruickshank** [comment]
This is unrelated to the upgrade. The `dbt_utils` macros aren't included with the jinja templater (and haven't been pre 1.8 either), and instead I'd recommend using the dbt templater instead.

https://pypi.org/project/sqlfluff-templater-dbt/
