### ISSUE TITLE
False positive on SET CONSTRAINTS ALL DEFERRED

### ISSUE THREAD

**Issue by IttayWeiss** [sqlfluff/sqlfluff#5926]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### What Happened

Gives false positive on valid SQL with SET CONSTRAINTS

### Expected Behaviour

Parsing as valid SQL.

### Observed Behaviour

Parsing violations reported.

### How to reproduce

sqlfluff parse test.sql --dialect postgres

where test.sql is:
SET CONSTRAINTS ALL DEFERRED;

### Dialect

Postgres

### Version

3.0.5

### Configuration

None

### Are you willing to work on and submit a PR to address the issue?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by IttayWeiss** [comment]
Possibly the same sort of false positive when running on:

CREATE CONSTRAINT TRIGGER "some_trigger"
   AFTER INSERT ON "some_table" DEFERRABLE
   FOR EACH ROW
   EXECUTE PROCEDURE some_procedure();

**Comment by WittierDinosaur** [comment]
Closing as this is fixed as of the latest release
