### ISSUE TITLE
Not Working under python 3.12.x

### ISSUE THREAD

**Issue by StevenGrzybowski** [sqlfluff/sqlfluff#5945]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### What Happened

Under python 3.12 (currently needed for dbt 1.8) 
attempting to install  sqlfluff 3.0.7 & run sqlfluff--version results in the following :
```
ModuleNotFoundError: No module named 'imp'
```

### Expected Behaviour

To get the sqlfluff version back

### Observed Behaviour

```
Traceback (most recent call last):
  File "/usr/local/bin/sqlfluff", line 5, in <module>
    from sqlfluff.cli.commands import cli
  File "/usr/local/lib/python3.12/site-packages/sqlfluff/__init__.py", line 6, in <module>
    import pytest
  File "/usr/local/lib/python3.12/site-packages/pytest.py", line 7, in <module>
    from _pytest.assertion import register_assert_rewrite
  File "/usr/local/lib/python3.12/site-packages/_pytest/assertion/__init__.py", line 12, in <module>
    from _pytest.assertion import rewrite
  File "/usr/local/lib/python3.12/site-packages/_pytest/assertion/rewrite.py", line 8, in <module>
    import imp
ModuleNotFoundError: No module named 'imp'
```

### How to reproduce

under python 3.12.x  , install sqlfluff 3.0.7. Then Try to run sqlfluff --version 

### Dialect

sqlfluff-templater-dbt

### Version

3.0.7

### Configuration

[sqlfluff:core]
dialect = snowflake
templater = dbt
exclude_rules = CP02, LT05, AL06, RF04, ST06
large_file_skip_byte_limit = 0

[sqlfluff:templater:dbt]
project_dir = ./analytics
profiles_dir = ./analytics

[sqlfluff:templater:jinja:macros]
select_event_meta_macro = {% macro select_event_meta(prefix='', except=[]) %}{% endmacro %}
source_events_select_macro = {% macro select_event_source(source_name, source_table, flatten=False, quoted_cols=False) %} {% endmacro %}

[jinja]
padding = true

[sqlfluff:aliasing]
column = explicit
expression = explicit
table = explicit

[sqlfluff:rules:capitalisation.keywords]
capitalisation_policy = lower

[sqlfluff:rules:capitalisation.identifiers]
capitalisation_policy = lower

[sqlfluff:rules:capitalisation.functions]
extended_capitalisation_policy = lower

[sqlfluff:rules:capitalisation.literals]
capitalisation_policy = lower

[sqlfluff:rules:capitalisation.types]
extended_capitalisation_policy = lower

[sqlfluff:convention]
coalesce = true
left_join = true
not_equal = true
select_trailing_comma = forbid

[sqlfluff:indentation]
allow_implicit_indents = true
indented_joins = false
indent_using_on = true
indented_on_contents = false
indented_then = true
indented_ctes = false
tab_space_size = 4

[sqlfluff.layout]
spacing = true
cte_bracket = true
cte_newline = true
end_of_file = true
functions = true
select_targets = true
select_modifiers = true
set_operator = true
start_of_file = true

[sqlfluff.layout.comma]
line_position = trailing
spacing_before = touch

[sqlfluff.references]
consistent = true
from = true
qualification = true

[sqlfluff:structure]
else_null = true
join_condition_order = earlier
nested_case = true
simple_case = true
unused_cte = true

### Are you willing to work on and submit a PR to address the issue?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by WittierDinosaur** [comment]
I think this may be an issue with pytest, not sqlfluff. Python 3.12 dropped `imp` as a module, so all packages that called it needed an update. We don't import `imp` directly anywhere, but `pytest` does. Can you try upgrading your version of `pytest`, and seeing if this error persists? We don't pin `pytest` at all in our dependencies

**Comment by alanmcruickshank** [comment]
I'm going to close this one. Python 3.12 is supported as part of our test suite and so is confirmed as running fine. I'm assuming that the comment above is the solution to this one.

Do re-open the issue if not.
