### ISSUE TITLE
Extend support L033 for more sqlfluff dialects

### ISSUE THREAD

**Issue by Battiloni** [sqlfluff/sqlfluff#5964]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### Description

The rule `ambiguous.union` from the ambiguous bundle is only set for the following dialects:
- `ansi`, `hive`, `mysql`, and `redshift`

Details of the rule
```text
- ambiguous.union
- Code AM02
- Alias L033
- UNION [DISTINCT ALL] is preferred over just UNION.
- https://docs.sqlfluff.com/en/3.0.7/rules.html#rule-ambiguous.union
```

This makes the rule only usable for the above dialects - it could also be used for other modern dialects such as:
- `bigquery`, `snowflake`, `databricks`, `clickhouse`
- most of them support also `UNION DISTINCT`, see docs of RDBMS below
   - [bigquery](https://cloud.google.com/bigquery/docs/reference/standard-sql/query-syntax#set_operators)
   - [snowflake](https://docs.snowflake.com/en/sql-reference/operators-query)
   - [databricks](https://docs.databricks.com/en/sql/language-manual/sql-ref-syntax-qry-select-setops.html)
   - [clickhouse](https://clickhouse.com/docs/en/sql-reference/statements/select/union)

### Use case

I would like to add support for other dialects:
- `bigquery`
- `snowflake`
- `databricks`
- `clickhouse`

This would be a big enhancement to this rule - as when developing SQL statements using `UNION` clauses, it's very important to specify `DISTINCT` or `ALL` to be sure about the final output of the unioned dataset
- it's good practice to declare `UNION DISTINCT` or `UNION ALL` as they don't produce the same result

### Dialect

- `bigquery`
- `snowflake`
- `databricks`
- `clickhouse`

### Are you willing to work on and submit a PR to address the issue?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by GabrielBoehme13** [comment]
Please also enable this rule for the `db2` dialect. [(IBM documentation)](https://www.ibm.com/docs/en/db2-for-zos/13?topic=queries-fullselect)

**Comment by WittierDinosaur** [comment]
Per the docs, snowflake doesn't support distinct. Happy to add for the others though

**Comment by Battiloni** [comment]
> Per the docs, snowflake doesn't support distinct. Happy to add for the others though

Indeed per the docs, it seems not supported. However being an avid Snowflake user, ANSI SQL is supported on Snowflake and `UNION DISTINCT`syntax works on its query engine

```sql
WITH union_distinct_cte AS (
    SELECT 1 AS value
    UNION DISTINCT
    SELECT 1 AS value
)

, union_cte AS (
    SELECT 1 AS value
    UNION
    SELECT 1 AS value
)

SELECT 'union_distinct_cte' AS cte_name, * FROM union_distinct_cte
UNION ALL
SELECT 'union_cte' AS cte_name, * FROM union_cte
;
````


CTE_NAME | VALUE
-- | --
union_distinct_cte | 1
union_cte | 1

Hence IMO, it should also be added to this rule

**Comment by kchi0do** [comment]
Can this also be extended to Trino?

**Comment by alanmcruickshank** [comment]
I've discussed with @mchen-codaio who's going to enable support for Snowflake and Trino.

**Comment by Battiloni** [comment]
Thanks for implementing the rule for new dialects 😄

Just tested it with release 3.2.5 and seems to be working great!

Closing this issue now then.
