### ISSUE TITLE
Support Higher-Level Functions (Snowflake)

### ISSUE THREAD

**Issue by coolbeans201** [sqlfluff/sqlfluff#5977]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### Description

We're currently trying to utilize higher-order functions in Snowflake for views we're creating off our semistructured data: https://docs.snowflake.com/en/user-guide/querying-semistructured.

Any way we can get the missing keywords supported? We have a query that's failing sqlfluff parsing currently that is runnable within Snowflake (needed to overcome for CI/CD purposes). Thank you!

### Use case

Support for higher-order functions is there so we can leverage this while sqlfluff stays green

### Dialect

Snowflake

### Are you willing to work on and submit a PR to address the issue?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by WittierDinosaur** [comment]
Can you give examples of what's failing?

**Comment by coolbeans201** [comment]
Sorry, just noticed this. We've been seeing an issue for a view we've created utilizing ARRAY_DISTINCT, as an example.

**Comment by elcorbs** [comment]
Similar to this, I'm seeing a parsing error from sqlfluff when using the higher order functions [filter](https://docs.snowflake.com/en/sql-reference/functions/filter) and [transform](https://docs.snowflake.com/en/sql-reference/functions/transform).

**Comment by amardatar** [comment]
Hey @WittierDinosaur - I've put in a PR for this (#6136), hopefully shows the syntax that has been introduced. Just as a point of reference, below screenshot is the parse issue I'm having at present on a working query.

![Screenshot 2024-09-02 at 14 40 06](https://github.com/user-attachments/assets/e2e6452f-bc3d-48ef-9672-216e801e19e3)
