### ISSUE TITLE
Add more information to  "WARNING    Indent balance test failed for 'file.sql'. Template indents will not be linted for this file."

### ISSUE THREAD

**Issue by NiallRees** [sqlfluff/sqlfluff#599]
I'm getting this a lot in my work codebase when testing the latest changes. It would be helpful if this warning gave some actionable feedback or at least a link to the docs to explain what this means.

**Comment by sdepablos** [comment]
:+1:

**Comment by alanmcruickshank** [comment]
I wonder whether #643 is causing this to appear more than it should 🤔

**Comment by alanmcruickshank** [comment]
Now that this is silenced with #885 I'm going to close this issue.
