### ISSUE TITLE
RF03: Unable to fix qualified reference in single table select within CTE

### ISSUE THREAD

**Issue by mison6** [sqlfluff/sqlfluff#6014]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### What Happened

I have rule RF03 (references.consistent) set to single_table_references = unqualified. With a simple select statement, it is able to auto-fix issues like the following:

```sql
select
  my_table.first,
  second
from my_table
```

Correctly changing it to 

```sql
select
    first,
    second
from my_table
```

However, the same query modified to be within a CTE, it indicates that the issue is unfixable and the query has to be updated manually.

```sql
with

final as (
    select
        my_table.first,
        second
    from my_table
)

select *
from final
```

### Expected Behaviour

Similar to the query without CTEs, sqlfluff `fix` changes the query to

```sql
with

final as (
    select
        first,
        second
    from my_table
)

select *
from final
```

### Observed Behaviour

`sqlfluff fix --show-lint-violations` outputs the following

```bash
==== finding fixable violations ====
==== no fixable linting violations found ====                                                                                            
All Finished 📜 🎉!
  [1 unfixable linting violations found]
==== lint for unfixable violations ====
== [models/marts/test.sql] FAIL
L:   5 | P:   9 | RF03 | Qualified reference 'my_table.first' found in single table select.
                       | [references.consistent]
```

### How to reproduce

With the below `.sqlfluff` configuration, create a file containing the above sql with a single CTE. Run `sqlfluff fix --show-lint-violations` and observe that it cannot be fixed.

### Dialect

snowflake

### Version

3.0.6

### Configuration

[sqlfluff]
dialect = snowflake

[sqlfluff:rules:references.consistent]
single_table_references = unqualified

### Are you willing to work on and submit a PR to address the issue?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by marcelolima** [comment]
Having same issue, have you found a solution for it?
