### ISSUE TITLE
Instantiate FluffyConfig using dict instead of INI/Toml file or strings

### ISSUE THREAD

**Issue by eirnym** [sqlfluff/sqlfluff#6038]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### Description

I'd like to have ability to specify a single configuration parameter programmatically without passing a file or using `from_string` or `from_strings` (which are very similar)

I understand that configuration has this nice structure of INI/TOML and in most cases it's worth a while to read it from a file, but sometimes I prefer to change parameters as I please without using toml/ini parser to create a proper config.

### Use case

I'd like to override a single or few parameters using dict structure. Something like an example below. dict covers everything I need. I agree that it may not cover every single case, but in most cases it will do the job.

```python
config = {
	"sqlfluff:rules:capitalisation.keywords": {
        "capitalisation_policy": "lower"
	}
}

fluffy_config = FluffyConfig.from_kwargs(..., extra_config=config)
```

### Dialect

sqlite, doesn't matter though

### Are you willing to work on and submit a PR to address the issue?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by alanmcruickshank** [comment]
@eirnym - I think this is already possible using the `configs` kwarg on `FluffConfig`. e.g.

```python
configs = {
	"rules":{
            "capitalisation.keywords": {
                "capitalisation_policy": "lower"
            }
        }
}

fluff_config = FluffConfig.from_kwargs(configs=configs)
```

I agree that it's not very well documented however. Does this solution work for you? I'm happy to improve the docs if it's going to get used.

**Comment by eirnym** [comment]
This looks like what I was looking for. 

I'd like to ask for documentation for it and configuration overview: how you can configure and understanding why naming is different and how to move from one option to another
