### ISSUE TITLE
Select targets should be on a new line unless there is only one select target

### ISSUE THREAD

**Issue by NiallRees** [sqlfluff/sqlfluff#605]
I imagine the logic being something like

If number of select targets == 1, ensure no newline between `select` and select target.
If number of select target > 1, ensure newline before select target and whitespace segment.
The fix would need to introduce the required whitespace according to tab_space_size and indent_unit.

Pass
```
select * from x
```

```
select * 
from x
```

Fail
```
select
    *
from x
```

Pass
```
select
    a,
    b,
    c
from x
```

Fail
```
select a, b, c
from x
```

**Comment by dorzey** [comment]
I'll take this one and attempt to make it my first contribution to the main project.
