### ISSUE TITLE
Snowflake AT(time travel) parsing error

### ISSUE THREAD

**Issue by twice154** [sqlfluff/sqlfluff#6070]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### What Happened

If I use Snowflake AT(time travel) in query and run `sqlfluff lint`, parsing error happens.

### Expected Behaviour

No parsing error happens because it's official function of Snowflake.

### Observed Behaviour

```
L:  16 | P:  12 |  PRS | Line 16, Position 12: Found unparsable section:
                       | "(TIMESTAMP => TO_TIMESTAMP(DATEADD('DAY'..."
```

### How to reproduce

Using Snowflake's time travel query like below.
`AT (TIMESTAMP => TO_TIMESTAMP(DATEADD('DAY', -1, DATEADD('MONTH', -1, DATEADD('DAY', -1, CURRENT_DATE)))))`

### Dialect

Snowflake

### Version

3.1.0

### Configuration

[sqlfluff]
dialect = snowflake
templater = jinja
exclude_rules = ambiguous, structure, references, aliasing, layout, capitalisation

### Are you willing to work on and submit a PR to address the issue?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by keraion** [comment]
closed by #6230
