### ISSUE TITLE
Not all ALTER TABLE operations are recognized in the Databricks dialect

### ISSUE THREAD

**Issue by nicolb2305** [sqlfluff/sqlfluff#6087]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### What Happened

Certain ALTER TABLE operations such as SET TAGS are not implemented. For a full list of possible ALTER TABLE operations see: https://docs.databricks.com/en/sql/language-manual/sql-ref-syntax-ddl-alter-table.html

From my limited testing it seems that the following operations result in a parsing error:
- [ ] [ SET ] OWNER TO
- [ ] SET TAGS
- [ ] UNSET TAGS
- [ ] CLUSTER BY

### Expected Behaviour

That valid SQL statements are parsed correctly.

### Observed Behaviour

That valid SQL statements are marked as unparsable.

### How to reproduce

None of these SQL statements are parsed correctly:
```sql
ALTER TABLE test OWNER TO a_group;
ALTER TABLE test SET TAGS ("tag" = "val");
ALTER TABLE test UNSET TAGS ("tag")
ALTER TABLE test CLUSTER BY (col1, col2);
```

### Dialect

Databricks

### Version

3.1.0

### Configuration

No extra configuration other than setting the dialect to databricks

### Are you willing to work on and submit a PR to address the issue?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by sousaherbert** [comment]
Working on a PR for this...

**Comment by sousaherbert** [comment]
I need permission to push a PR.

**Comment by pahunter90** [comment]
> I need permission to push a PR.

I also ran into this issue and just submitted a PR.

**Comment by sousaherbert** [comment]
But your PR does not solve the issue with ALTER VIEW and ALTER TABLE right?

**Comment by pahunter90** [comment]
As of now it does not. Do you have code for that? It appears the ALTER TABLE statements are relying on the sparksql dialect, which differs quite a bit from what is allowed in databricks. We hit the issue when attempting to parse ALTER DATABASE, and I noticed similar statements missing from ALTER CATALOG. I'd really prefer to not have to write all of the databricks cases for ALTER TABLE myself. Could take some time.

**Comment by sousaherbert** [comment]
I have the code... I am not being able to push the PR... because I get the message I am not allowed to do so and Idk if I need to be allowed to do so.

**Comment by pahunter90** [comment]
Odd. I'd be happy to submit it tomorrow if you want to send over the code.
