### ISSUE TITLE
Improve architecture docs

### ISSUE THREAD

**Issue by NiallRees** [sqlfluff/sqlfluff#621]
In particular I find the parser section really hard to understand. It is the most complicated part by nature, and I think providing some examples of the difference between match grammar and parse grammar would be helpful. An example parse tree too I think could help. As a contributor this was (and still is) a really scary part of the codebase, and I think it could help us improve the frequency of contributions.

https://docs.sqlfluff.com/en/stable/architecture.html

**Comment by alanmcruickshank** [comment]
I assume I should pick this one up? 🤣

**Comment by NiallRees** [comment]
I was actually going to suggest I do! As someone who didn't write it I thought it might be easier to know what the subtler parts are. Also no better way of learning something than explaining to someone else - if I have a go I'll get you to check what I've said is right? Might take a couple of goes.
