### ISSUE TITLE
[Snowflake] Add support for `GRANT MONITOR ON USER ...`

### ISSUE THREAD

**Issue by mroy-seedbox** [sqlfluff/sqlfluff#6308]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### Description

Add support for `GRANT MONITOR ON USER ...`.

See documentation [here](https://docs.snowflake.com/en/user-guide/security-access-control-privileges#all-privileges-alphabetical) and [here](https://docs.snowflake.com/en/sql-reference/sql/grant-privilege#syntax).

![image](https://github.com/user-attachments/assets/f5e960da-921a-4aac-8168-f80b9e909575)

![image](https://github.com/user-attachments/assets/c6d6fb4a-a000-4080-a1b4-14e0098ff79d)

### Dialect

Snowflake

### Are you willing to work on and submit a PR to address the issue?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by mroy-seedbox** [comment]
I believe this is only a matter of adding `USER` in the list of permissionable objects [here](https://github.com/fpsebastiam/sqlfluff/blob/main/src/sqlfluff/dialects/dialect_snowflake.py#L2908).

But I'm not sure if over changes or tests would also need to be added. 🤷‍♂️ 

![image](https://github.com/user-attachments/assets/65ec5e40-7d93-4273-acb5-7b98bb983130)

**Comment by greg-finley** [comment]
Hello! I think the change you proposed sounds like it would fix the issue.

Do you want to give it a shot to make a PR? Just throw one more statement into `test/fixtures/dialects/snowflake/grant_revoke.sql` and generate the fixture via the tox command found here: https://github.com/sqlfluff/sqlfluff/wiki/Contributing-Dialect-Changes#testing-your-changes

**Comment by mroy-seedbox** [comment]
I'll give it a try!

**Comment by mroy-seedbox** [comment]
@greg-finley: fix is in PR #6322! 🙌 🚀
