### ISSUE TITLE
Parsing error when using Snowflake single or double-colon syntax for semi-structured data traversal and casting

### ISSUE THREAD

**Issue by emekdahl** [sqlfluff/sqlfluff#634]
When linting queries like the following using Snowflake's double-colon casting syntax:

`SELECT 
  ID :: VARCHAR as id, 
  OBJ : userId :: VARCHAR as user_id, 
  OBJ : offerId :: VARCHAR as offer_id, 
  redemptions.value : awardedReceiptId :: VARCHAR as awarded_receipt_id, `

There is the following error: `L:   7 | P:  20 |  PRS | Found unparsable section: ' : awardedReceiptId ::
                       | VARCHAR as awarde...'`

https://docs.snowflake.com/en/sql-reference/functions/cast.html
https://docs.snowflake.com/en/user-guide/querying-semistructured.html#traversing-semi-structured-data

**Comment by emekdahl** [comment]
Thanks to the help of a colleague, I realized this issue can be resolved by removing the white space around the colons. I am closing it out, however, it may help someone else troubleshoot their sqlfluff implementation. Happy linting! :)

**Comment by pwildenhain** [comment]
@NiallRees you added this functionality recently right? Should we support the whitespace in a shorthand cast?
