### ISSUE TITLE
--threads argument for sqlfluff lint

### ISSUE THREAD

**Issue by jars** [sqlfluff/sqlfluff#642]
Hey sqfluff devs! :sheep: 

Are all files linted in isolation? I suspect they have no dependencies on each other. Seems ripe for concurrency?

The `dbt` bin supports a `--threads` argument for this. Could be a huge optimization tweak?

For context, we are using sqlfluff with dbt and we have hundreds of models.
I don't have an accurate runtime estimate for our entire project because of #641, but I suspect it's several hours right now.

**Comment by barrywhart** [comment]
We might want to call it `--parallel` in case we decided use processes instead.

**Comment by barrywhart** [comment]
I'm experimenting with this in #1013. We'll see how it goes.

**Comment by alanmcruickshank** [comment]
@barrywhart - I think this should be possible again now. All of the dynamic class construction has been removed as part of #1019

**Comment by barrywhart** [comment]
@alanmcruickshank: Yes, I updated my original PR today, based on your changes. It is now much simpler and cleaner. It works and is ready for review. 

#1013
