### ISSUE TITLE
Showing progress of `sqlfluff lint` and `sqlfluff fix`

### ISSUE THREAD

**Issue by dclong** [sqlfluff/sqlfluff#645]
It helps since `sqlfluff fix` runs slowly.

**Comment by joellabes** [comment]
I agree with this, but would also say it makes sense for other commands as well, especially when linting using the dbt compiler is so slow (#651)

**Comment by dclong** [comment]
I installed sqlfluff from the master branch but I don't see a progress bar when running sqlfluff fix.
