### ISSUE TITLE
Are we optionally bracketing where we should be, and should we add an OptionallyBracketed segment?

### ISSUE THREAD

**Issue by NiallRees** [sqlfluff/sqlfluff#650]
From https://github.com/sqlfluff/sqlfluff/pull/648#discussion_r549768093:

> This should be a pattern which exists elsewhere, but I couldn't find it, so just went with a OneOf with one bracketed and one not bracketed. We could make an 'OptionallyBracketed' segment for this purpose to be used in group by, partition by and other clauses which I assume are also currently unparsable with brackets. Have I missed something here @alanmcruickshank ?

**Comment by barrywhart** [comment]
Should we close this? We now have `OptionallyBracketed`, although there are likely places where it could/should be used but isn't.

**Comment by alanmcruickshank** [comment]
I've found *one* location which I think this applies to but everything else is good. Will make PR.
