### ISSUE TITLE
`sqlfluff lint` for a single file performs 10x slower with dbt templater than Jinja

### ISSUE THREAD

**Issue by joellabes** [sqlfluff/sqlfluff#651]
Running `sqlfluff lint  models/staging/classes/classes__academic_years.sql` takes >20 seconds when using the dbt templater, versus <2 seconds when using the Jinja templater. The model's code is: 
```sql
with src as (
    select * from {{source('classes', 'academicyear')}}
),

renamed as (
    select
        id as academic_year_id,
        name as academic_year_name,
        hemisphereid as hemisphere_id,
        startdate as start_date,
        enddate as end_date,
        startdate < date_trunc('day', getdate())
            and enddate >= date_trunc('day', getdate())
            as is_currently_active
    from src
)

select *
from renamed
```

**Comment by NiallRees** [comment]
Hey @joellabes. I understand that this is annoyingly slow - unfortunately it's not something we can improve on, as the bottleneck is the dbt compilation time. Investigations are taking place over in https://github.com/fishtown-analytics/dbt/issues/2862 to speed this up in future dbt releases. Until then, the only alternative is to use the jinja templater with stub macro definitions in the .sqlfluff file per https://docs.sqlfluff.com/en/stable/configuration.html#macro-templating.

**Comment by joellabes** [comment]
No worries - @pwildenhain just asked for a copy of it in the [dbt slack](https://getdbt.slack.com/archives/CV2KM39KR/p1609277674169700?thread_ts=1608708938.159900&channel=CV2KM39KR&message_ts=1609277674.169700) and figured I should write up the context instead of randomly dumping a query

**Comment by jars** [comment]
@NiallRees, I'm currently having issues using your alternative. Are you able to shed some light on https://sqlfluff.slack.com/archives/C01GX4L213J/p1608169058075100 ?

**Comment by jpy-git** [comment]
Going to close this as this is a dbt limitation not sqlfluff and dbt speed has likely improved since this issue was raised (although obvs will still be longer than Jinja, given it connects to a database).
