### ISSUE TITLE
Add a command-line option for file encoding (was: File encoding is not respected)

### ISSUE THREAD

**Issue by sti0** [sqlfluff/sqlfluff#654]
When fixing a file the encoding is maybe not respected and the fixed code is written with default system encoding. This leads in losing special chars etc.

E.g. the original file is a UTF-8 file, with the fix the code is written in CP1252 on Windows. 

This happens because prior Python 3.9 `open()` uses the system default codepage, e.g. windows = cp1252. With Python 3.9 it's opened with UTF-8 encoding if no encoding is set (which even could lead to false results, if the file is with CP1252 encoded).

[Python 3.8 docs](https://docs.python.org/3.8/library/functions.html#open):

> encoding is the name of the encoding used to decode or encode the file. This should only be used in text mode. The default encoding is platform dependent (whatever locale.getpreferredencoding() returns), but any text encoding supported by Python can be used. See the codecs module for the list of supported encodings.

This happens here:
https://github.com/sqlfluff/sqlfluff/blob/ce673c5c7731c3c7e0fff76f77d49bc8e362d7f2/src/sqlfluff/core/linter.py#L471

Possible solutions:
1. auto detect
2. configurable encoding
3. passing encoding as command line parameter
4. writing a new file, instead of overwritting the current file

I would prefer to make the encoding configurable (pt. 2 or 3) to take the full control over it because even auto-detection could fail.

**Comment by alanmcruickshank** [comment]
I think this issue also address #372 which talks explicitly about this issue with UTF-8-BOM.

I think going for option 1 & 3 is a good idea. That means:
- Being able to configure in the CLI and in the config file, the encoding to use when writing files. The config file part of this is easy. Adding it to the CLI is more work, but similar functionality exists for a couple of other config options already.
- We should try and autodetect the file if no explicit encoding has been set (and I suggest that the default parameter in the config file is still present but set to `autodetect`). In this mode we should use [chardet](https://pypi.org/project/chardet/) (which I'm pretty sure is in our dependency tree already) to detect the encoding of a file on read, store that in the `LintedFile` object and then use the same value to set the encoding on write.

**Comment by barrywhart** [comment]
This was mostly implemented in #899 and #1177, but the CLI portion has yet to be implemented.
