### ISSUE TITLE
T-SQL dialect (Microsoft SQL Server Transact-SQL)

### ISSUE THREAD

**Issue by davidwales** [sqlfluff/sqlfluff#660]
T-SQL support would be great for those of us stuck in MS Land! 😄

**Comment by KimchaC** [comment]
+1 for me.

Is there a guide on how this could be implemented?

**Comment by barrywhart** [comment]
I don't know about a guide, but if you look at existing files like dialect_bigquery.py or dialect_postgres.py, it'd be pretty similar. Essentially, each dialect is a Python module that specializes an existing"base" dialect module. In most cases, the base dialect is dialect_ansi.py, which is sort of the ANSI SQL standard with a few db-specific bits that may someday be moved to other dialects if needed.
