### ISSUE TITLE
Unexpected exception: tuple index out of range (L019)

### ISSUE THREAD

**Issue by justinwagg** [sqlfluff/sqlfluff#661]
## Expected Behaviour

Including configuration
```
[sqlfluff:rules:L019]
comma_style = leading
```
does not lead to critical exception.

## Observed Behaviour

Running `sqlfluff lint models/dwh/best_model.sql` with the config below causes exception. 

```bash
(venv) ➜  ✗ sqlfluff lint models/dwh/best_model.sql
CRITICAL   [L019] Applying rule L019 threw an Exception: tuple index out of range
Traceback (most recent call last):
  File "/Users/justinwagg/Documents/data/venv/lib/python3.8/site-packages/sqlfluff/core/rules/base.py", line 282, in crawl
    res = self._eval(
  File "/Users/justinwagg/Documents/data/venv/lib/python3.8/site-packages/sqlfluff/core/rules/std.py", line 2218, in _eval
    last_seg = self._last_code_seg(raw_stack)
  File "/Users/justinwagg/Documents/data/venv/lib/python3.8/site-packages/sqlfluff/core/rules/std.py", line 2133, in _last_code_seg
    if raw_stack[idx].is_code or raw_stack[idx].is_type("newline"):
IndexError: tuple index out of range
CRITICAL   [L019] Applying rule L019 threw an Exception: tuple index out of range
Traceback (most recent call last):
  File "/Users/justinwagg/Documents/data/venv/lib/python3.8/site-packages/sqlfluff/core/rules/base.py", line 282, in crawl
    res = self._eval(
  File "/Users/justinwagg/Documents/data/venv/lib/python3.8/site-packages/sqlfluff/core/rules/std.py", line 2218, in _eval
    last_seg = self._last_code_seg(raw_stack)
  File "/Users/justinwagg/Documents/data/venv/lib/python3.8/site-packages/sqlfluff/core/rules/std.py", line 2133, in _last_code_seg
    if raw_stack[idx].is_code or raw_stack[idx].is_type("newline"):
IndexError: tuple index out of range
== [models/dwh/best_model.sql] FAIL
L:   1 | P:   1 | L019 | Unexpected exception: tuple index out of range; Could
                       | you open an issue at
                       | https://github.com/sqlfluff/sqlfluff/issues ? You can
                       | ignore this exception for now, by adding '--noqa: L019'
                       | at the end of line 1
L:   2 | P:   1 | L019 | Unexpected exception: tuple index out of range; Could
                       | you open an issue at
                       | https://github.com/sqlfluff/sqlfluff/issues ? You can
                       | ignore this exception for now, by adding '--noqa: L019'
                       | at the end of line 2
L:   4 | P:   1 | L003 | Indent expected and not found compared to line #3
L:   5 | P:   1 | L003 | Indent expected and not found compared to line #3
```

Removing 

 ```
[sqlfluff:rules:L019]
comma_style = leading
```

fixes the issue.

## Steps to Reproduce

Model:
```sql
-- models/dwh/best_model.sql
{{
  config(
    materialized='incremental',
    unique_key='field_1'
  )
}}

select field_1
,field_2
,field_3
from my_great_table
```

```bash
(venv) ➜ ✗ sqlfluff lint models/dwh/best_model.sql
```

## Version
Include the output of `sqlfluff --version` along with your Python version
```bash
(venv) ➜ ✗ python -V
Python 3.8.0
(venv) ➜ ✗ sqlfluff --version
sqlfluff, version 0.4.0a3
```

## Configuration
```
[sqlfluff]
templater = dbt
dialect = bigquery
exclude_rules = L036,L009,L008

[sqlfluff:indentation]
indented_joins = False

[sqlfluff:rules:L019]
comma_style = leading

[sqlfluff:rules:L003]
lint_templated_tokens = False

```

**Comment by drewmcdonald** [comment]
I came across this, as well -- I think this is an interaction between the `comma_style = leading` configuration and the presence of whitespace at the head of a file.

This applies when the whitespace is hard coded and when it's left behind by templating (as in @justinwagg's example), but not when jinja whitespace removal is used.

### Statements

#### Fails:
```

SELECT
    field_1
    , field_2
FROM my_dataset.my_table
```

#### Fails:
```
{% set my_var = 5 %}
SELECT
    field_1
    , field_2
FROM my_dataset.my_table
```

#### Succeeds:
```
{% set my_var = 5 -%}
SELECT
    field_1
    , field_2
FROM my_dataset.my_table
```

#### Succeeds:
```
SELECT
    field_1
    , field_2
FROM my_dataset.my_table
```

### Configuration

```
[sqlfluff]
templater = jinja

[sqlfluff:rules]
comma_style = leading
```

**Comment by MinchoG** [comment]
@drewmcdonald I have removed all whitespaces and continue to receive such an error. I would like to share with you the code snipet in slack and reconsider options to see what the issue is.

**Comment by NiallRees** [comment]
Hi both - would either of you feel confident in having a go at writing a failing test for this issue? It would really help in being able to solve it - I had a go with your first query @drewmcdonald but was unable to reproduce the error.

**Comment by MinchoG** [comment]
I was just about to write my code snippet when I compiled it and decided to lint my target/compiled model. I did not mention that I am running dbt via docker where on the container I do not have sqlfluff installed.(When I linted the target/compiled file I received log of rules violations and when I decided to do fix --no-safety I got this error:
```
==== fixing violations ====
1856 fixable linting violations found
Are you sure you wish to attempt to fix these? [Y/n] ...
Attempting fixes...
Persisting Changes...
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/bin/sqlfluff", line 33, in <module>
    sys.exit(load_entry_point('sqlfluff==0.3.6', 'console_scripts', 'sqlfluff')())
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/sqlfluff/cli/commands.py", line 272, in fix
    success = do_fixes(lnt, result, verbosity=verbose, types=SQLLintError,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/sqlfluff/cli/commands.py", line 193, in do_fixes
    res = result.persist_changes(output_func=lnt.output_func, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/sqlfluff/linter.py", line 524, in persist_changes
    *[
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/sqlfluff/linter.py", line 525, in <listcomp>
    path.persist_changes(verbosity=verbosity, output_func=output_func, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/sqlfluff/linter.py", line 408, in persist_changes
    buffer[file.path] = file.persist_tree(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/sqlfluff/linter.py", line 332, in persist_tree
    write_buff, success = self.fix_string(verbosity=verbosity)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/sqlfluff/linter.py", line 174, in fix_string
    raise NotImplementedError(
NotImplementedError: A equal template block remains with no more diff_fix_codes left
```

**Comment by NiallRees** [comment]
> I was just about to write my code snippet when I compiled it and decided to lint my target/compiled model. I did not mention that I am running dbt via docker where on the container I do not have sqlfluff installed.(When I linted the target/compiled file I received log of rules violations and when I decided to do fix --no-safety I got this error:
> 
> ```
> ==== fixing violations ====
> 1856 fixable linting violations found
> Are you sure you wish to attempt to fix these? [Y/n] ...
> Attempting fixes...
> Persisting Changes...
> Traceback (most recent call last):
>   File "/Library/Frameworks/Python.framework/Versions/3.9/bin/sqlfluff", line 33, in <module>
>     sys.exit(load_entry_point('sqlfluff==0.3.6', 'console_scripts', 'sqlfluff')())
>   File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/click/core.py", line 829, in __call__
>     return self.main(*args, **kwargs)
>   File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/click/core.py", line 782, in main
>     rv = self.invoke(ctx)
>   File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/click/core.py", line 610, in invoke
>     return callback(*args, **kwargs)
>   File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/sqlfluff/cli/commands.py", line 272, in fix
>     success = do_fixes(lnt, result, verbosity=verbose, types=SQLLintError,
>   File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/sqlfluff/cli/commands.py", line 193, in do_fixes
>     res = result.persist_changes(output_func=lnt.output_func, **kwargs)
>   File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/sqlfluff/linter.py", line 524, in persist_changes
>     *[
>   File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/sqlfluff/linter.py", line 525, in <listcomp>
>     path.persist_changes(verbosity=verbosity, output_func=output_func, **kwargs)
>   File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/sqlfluff/linter.py", line 408, in persist_changes
>     buffer[file.path] = file.persist_tree(
>   File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/sqlfluff/linter.py", line 332, in persist_tree
>     write_buff, success = self.fix_string(verbosity=verbosity)
>   File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/sqlfluff/linter.py", line 174, in fix_string
>     raise NotImplementedError(
> NotImplementedError: A equal template block remains with no more diff_fix_codes left
> ```

This looks like an old version of sqlfluff - can you check?

**Comment by drewmcdonald** [comment]
Hi @NiallRees -- see the draft PR here for a failing test case: #689

**Comment by MinchoG** [comment]
sqlfluff, version 0.3.6

**Comment by NiallRees** [comment]
> sqlfluff, version 0.3.6

OK cool. The part that's failing in your stack trace has been totally changed in 0.4.0 - can you try it with 0.4.0a3?

**Comment by MinchoG** [comment]
Oh LOL
```
==== fixing violations ====
1983 fixable linting violations found
Are you sure you wish to attempt to fix these? [Y/n] ...
Attempting fixes...
Persisting Changes...
== [5_WAREHOUSE/F_MIXPANEL_EVENTS.sql] PASS
Done. Please check your files to confirm.
```
Thanks a bunch!!!
