### ISSUE TITLE
dbt templater stdout print to sqlfluff stdout

### ISSUE THREAD

**Issue by cnolanminich** [sqlfluff/sqlfluff#682]
Just started testing the `0.4.0a3` on our primary data project (which we use and ❤️  sqlfluff for! Minus an issue around raw jinja tags, everything is looking excellent.

One UX improvement that would I think help is to pass all dbt stdout into the sqlfluff stdout. That way, a user would know that dbt is "working" on the dbt steps. This is especially nice when the compilation of the models takes a while to complete.

**Comment by alanmcruickshank** [comment]
@cnolanminich - would you expect this to a be a default regardless of the current verbosity or something that would only show if someone wanted to view logs? i.e. with `-v`.

Currently we've tried to mimic `flake8` such that in the default config nothing is output if there are no issues. I would be tempted to to either show the dbt logs if the verbosity level is high - or perhaps if there was an explicit config value to display the logs?

**Comment by cnolanminich** [comment]
> @cnolanminich - would you expect this to a be a default regardless of the current verbosity or something that would only show if someone wanted to view logs? i.e. with -v.

I think as dbt gets faster and faster at parsing (a major focus of that project), this will become less of a frustrating UX for sqlfluff. So I think having it as `-v` option would work perfectly

**Comment by alanmcruickshank** [comment]
I'm going to close this issue given I think it was sufficiently addressed in #942 and there's not been further requests for this feature. Our team works with the dbt plugin on a fairly large project now and the UX is ok at that level.
