### ISSUE TITLE
Class OrderByColumnInfo appears in rule docs: https://docs.sqlfluff.com/en/latest/rules.html

### ISSUE THREAD

**Issue by NiallRees** [sqlfluff/sqlfluff#685]
The addition of the class OrderByColumnInfo by #678 has resulted in the class being added to the rule documentation. It should be removed (easiest way is probably to filter the class names by `Rule_` prefix)

**Comment by barrywhart** [comment]
I don't see `OrderByColumnInfo` anymore in the latest docs. Has this been fixed, @NiallRees?

**Comment by barrywhart** [comment]
Closing this, as I think it's been fixed (possibly accidentally, e.g. when we split the rules into individual files).

**Comment by NiallRees** [comment]
Yep thank you @barrywhart 👍
