### ISSUE TITLE
EXASOL: Ambiguous `{{ ... }}` from Jinja vs LUA

### ISSUE THREAD

**Issue by dmateusp** [sqlfluff/sqlfluff#690]
> How to turn off Jinja templating? In LUA language its possible to use {{}}. this is parsed as Jinja

_Originally from @sti0 in #684_ 

I think if a user was using EXASOL + Jinja, that user would have to [Jinja escape](https://jinja.palletsprojects.com/en/2.11.x/templates/#escaping) the section that includes `{{ ... }}`.

Otherwise do we have the option today of having _no templater_, maybe that is something we want to support ?

**Comment by sti0** [comment]
> I think if a user was using EXASOL + Jinja, that user would have to [Jinja escape](https://jinja.palletsprojects.com/en/2.11.x/templates/#escaping) the section that includes `{{ ... }}`.

But that will only work if using sqlfluff. If I parse a given LUA script it's not parsable or ended up in a wrong result. I strongly recommend to turn off templating Exasol scripts. As it's lua/ python/java there could be templating code inside.

**Comment by dmateusp** [comment]
I'm not familiar with EXASOL, but I imagine you could be using Jinja templating for the rest of your EXASOL scripts:

like

```sql
select ... {{ some jinja }}
from ... 
```

and in your CREATE FUNCTION scripts:
```sql
{% raw %}
CREATE FUNCTION ...
(some stuff that includes `{{ ... }}`)
{% endraw %}
```

My understanding of the {% raw %} tag is that it would prevent Jinja from trying to template that section

**Comment by sti0** [comment]
As I said. This only works if I use sqlfluff / Jinja engine. If I simply like to parse a given script for validating and automatic deployment (which is my use case) than the script don't need Jinja. The script maybe needs to be processed in plain definition in some case with no need to parse it in sqlfluff first.

**Comment by dmateusp** [comment]
ah yes @sti0 I think we are on the same page. There are two points I wanted to get across on the description of the issue:
* EXASOL users which use Jinja as a templater (not your case), might run into the issue you ran into, and could work around it by using `{% raw %}`
* Not sure we support having "no templating today", but it is worth supporting IMO

**Comment by sti0** [comment]
> ah yes @sti0 I think we are on the same page. There are two points I wanted to get across on the description of the issue:
> 
> * EXASOL users which use Jinja as a templater (not your case), might run into the issue you ran into, and could work around it by using `{% raw %}`
> * Not sure we support having "no templating today", but it is worth supporting IMO

I have nothing to add. That describes the request clearly. Thanks 👍🏻

**Comment by alanmcruickshank** [comment]
> * Not sure we support having "no templating today", but it is worth supporting IMO

This *does* exist. Set your templater to `raw` (either with `--templater=raw` or set `templater = raw` in your config file) and no pre-processing will happen. This isn't used much, so if you looked in the docs and couldn't find it then coudl you suggest where we should make this clearer? I think it's a docs fail here that nobody knows about it 😬
