### ISSUE TITLE
Optional brackets

### ISSUE THREAD

**Issue by sti0** [sqlfluff/sqlfluff#693]
-- Please add any additional labels that are related to the issue before submitting! --
On some case it's possible that a segment or grammar could be within brackets but it don't have to.

One example:

```
CREATE VIEW test_view AS
SELECT * FROM another_table;

----OR

CREATE VIEW test_view AS (
SELECT * FROM another_table
);
```
In such a case it's necessary to define it in the dialect like this:
```
OneOf(
            Ref("MainTableExpressionGrammar"),
            Bracketed(Ref("MainTableExpressionGrammar")),
        ),
```

I suggest to add a option to `Bracketed` which makes the **brackets** optional (not the whole definition like `optional=` does).

**Comment by NiallRees** [comment]
See also https://github.com/sqlfluff/sqlfluff/issues/650

**Comment by alanmcruickshank** [comment]
This would also be quite an impactful but not-too-difficult issue for a first timer too!

**Comment by barrywhart** [comment]
Closing this now -- see the linked PR.
