### ISSUE TITLE
Rule docs for latest version are broken

### ISSUE THREAD

**Issue by NiallRees** [sqlfluff/sqlfluff#694]
https://docs.sqlfluff.com/en/latest/rules.html

Caused by https://github.com/sqlfluff/sqlfluff/pull/688

The rule classes appear in the docs when I build them locally, but aren't in prod!

**Comment by NiallRees** [comment]
If anyone can confirm they're seeing the same thing locally that would be helpful - just to rule out some kind of caching issue

**Comment by NiallRees** [comment]
Would you mind checking out the readthedocs build dash @alanmcruickshank ? https://stackoverflow.com/questions/29246562/sphinx-automodule-works-offline-but-not-through-readthedocs-org

**Comment by barrywhart** [comment]
@NiallRees: I ran `make html` locally, and the generated `rules.html` looks correct to me. It's a pretty long file, and I confirm that I see the newest rule class (`Rule_L037`) in it. I'm happy to upload the actual file if that would be helpful.

**Comment by NiallRees** [comment]
Resolved by #703
