### ISSUE TITLE
Single CLI command for lint & fix

### ISSUE THREAD

**Issue by nvuillam** [sqlfluff/sqlfluff#697]
Usually, linters have a --fix option, that auto-apply fixes after linting.
I see that for sqlfluff is it separated into 2 distinct commands: `sqlfluff lint` and `sqlfluff fix`

- Is there a way to lint & fix in the same sqlfluff CLI command ?
- If not, would it be possible to implement it ? 

It would help a lot for sqlfluff [Mega-Linter](https://nvuillam.github.io/mega-linter/descriptors/sql_sqlfluff/) integration :) (Mega-Linter core architecture manages to run a single command)

Many thanks !

**Comment by alanmcruickshank** [comment]
@nvuillam can you give an example of what you mean? The current `fix` command includes a linting step and so can be called by itself. What features would we need to add to the current `fix` command to fulfil this use case?

**Comment by nvuillam** [comment]
If fix includes also what does a lint, it's ok for what I need, thanks :)

**Comment by alanmcruickshank** [comment]
Awesome. I'm going to close this issue for now 👍
