### ISSUE TITLE
Named WINDOW clause not recognized (BigQuery)

### ISSUE THREAD

**Issue by MartinNowak** [sqlfluff/sqlfluff#698]
## Expected Behaviour

Proper parsing of [WINDOW clauses](https://cloud.google.com/bigquery/docs/reference/standard-sql/query-syntax?hl=en#window_clause).

## Observed Behaviour

```
L:   1 | P:  17 |  PRS | Found unparsable section: 'OVER(win)'
L:   1 | P:  44 |  PRS | Found unparsable section: ' win AS (PARTITION BY date)'
```

## Steps to Reproduce

```sh
echo 'SELECT AVG(col) OVER(win) FROM table WINDOW win AS (PARTITION BY date)' | sqlfluff parse --dialect=bigquery -
```

## Version
sqlfluff, version 0.3.6
Python 3.8.7

## Configuration
No additional/default config.

**Comment by barrywhart** [comment]
BigQuery [docs](https://cloud.google.com/bigquery/docs/reference/standard-sql/query-syntax) on named windows

Syntax (from the same page). Named windows may be added to the end of a `SELECT`, following the optional `WHERE`, `GROUP BY`, and `HAVING`:
```
select:
    SELECT [ AS { STRUCT | VALUE } ] [{ ALL | DISTINCT }]
        { [ expression. ]* [ EXCEPT ( column_name [, ...] ) ]
            [ REPLACE ( expression [ AS ] column_name [, ...] ) ]
        | expression [ [ AS ] alias ] } [, ...]
    [ FROM from_item  [, ...] ]
    [ WHERE bool_expression ]
    [ GROUP BY { expression [, ...] | ROLLUP ( expression [, ...] ) } ]
    [ HAVING bool_expression ]
    [ WINDOW named_window_expression AS { named_window | ( [ window_definition ] ) } [, ...] ]
```

**Comment by barrywhart** [comment]
@MartinNowak: I have a draft PR which I believe adds parsing support for named windows. Would you like to test or review it? #728

**Comment by MartinNowak** [comment]
Will give it a try.

**Comment by barrywhart** [comment]
I made some fixes this morning and marked the PR ready for review. 🤞🏽
