### ISSUE TITLE
Create abstraction and pattern for parsing tests

### ISSUE THREAD

**Issue by NiallRees** [sqlfluff/sqlfluff#699]
Does anyone else feel like the current parsing test pattern isn't as complete as it could be? I'd love an easy way to assert a string against a nested set of segments in an easy way, like you get from `sqlfluff parse`. Any ideas?

--edit https://github.com/sqlfluff/sqlfluff/blob/master/test/core/dialects/snowflake_test.py#L15

**Comment by barrywhart** [comment]
Can you post a URL to a test using the current pattern? Not sure I know what you're referring to.

**Comment by NiallRees** [comment]
> Can you post a URL to a test using the current pattern? Not sure I know what you're referring to.

Ah sorry - this is what I'm referring to: https://github.com/sqlfluff/sqlfluff/blob/master/test/core/dialects/snowflake_test.py#L15
