### ISSUE TITLE
Is there a way to specify a custom template placeholder?

### ISSUE THREAD

**Issue by iBalag** [sqlfluff/sqlfluff#714]
Hi,
In our company, we use psycopg2 for dealing with databases. For building SQL queries we use [named arguments](https://www.psycopg.org/docs/usage.html#passing-parameters-to-sql-queries) (like **%(name)s**) and built-in SQL query [formating abilities](https://www.psycopg.org/docs/sql.html#psycopg2.sql.SQL.format). An example of our SQL Template:

```
SELECT user_id
FROM users
WHERE created_date >= %(startDate)s
    AND created_date <= %(endDate)s
    AND {dynamicFilter}
```
When I try to use sqlfluff linter for checking this SQL template I will get the following issues:
```
L:   3 | P:  19 |  PRS | Found unparsable section: ' >= %(startDate)s\n AND
                       | created_date <...'
L:   3 | P:  23 |  LXR | Unable to lex characters: ''%(startDat'...'
L:   4 | P:  25 |  LXR | Unable to lex characters: ''%(endDate)'...'
L:   5 | P:   9 |  LXR | Unable to lex characters: ''{dynamicFi'...'
```

So, the question is: can I specify a custom template placeholder? Or just disable this issue?

Thanks!

**Comment by iBalag** [comment]
I found how to disable parsing and lexing issues with --ignore flag:

`sqlfluff lint test.sql --ignore parsing,lexing`

It looks like a temporary solution for now.

**Comment by alanmcruickshank** [comment]
Thanks for raising the issue @iBalag . I notice you've got dbapi style templating in your query (e.g. `%(startDate)s`) *and* you've got some other templating (`{dynamicFilter}`).

What are you use to generate the other templating?

Making an alternate templating engine to handle the `%` fields would be relatively straightforward, but at the moment we don't have support for multiple different kinds of templaters on top of eachother. I could imagine having the ability to "chain" templaters, but that would be a bigger job to implement.

**Comment by iBalag** [comment]
> What are you use to generate the other templating?

@alanmcruickshank Just a custom python parser which parses GET request params (`api.example.com/users?name='John'&age=18`) to SQL code (with SQL injection checking) - `name = 'John' AND age = 18`. Not a perfect solution, I know :)

**Comment by WittierDinosaur** [comment]
@alanmcruickshank @barrywhart this is up and running now, correct?

**Comment by barrywhart** [comment]
There is a "placeholder" templater now. It supports several placeholder syntaxes natively, and you can configure your own as well.

**Comment by barrywhart** [comment]
I think this has been addressed.
