### ISSUE TITLE
Enforce accompanying .yml for all .sql parsing fixtures

### ISSUE THREAD

**Issue by NiallRees** [sqlfluff/sqlfluff#730]
Off the back of https://github.com/sqlfluff/sqlfluff/pull/729, should we add a test to ensure that all `.sql` parse test fixtures have an associated `.yml` file?

**Comment by barrywhart** [comment]
Related: I have created a [pre-commit hook](https://gist.github.com/barrywhart/868446ba70e47ea792c2a6475b6aaa47) which creates the `.yml` file automatically.
