### ISSUE TITLE
Update sqlfluff version placeholder in example plugin to first release including #705

### ISSUE THREAD

**Issue by dmateusp** [sqlfluff/sqlfluff#764]
More of a note to self! 

This [install_requires](https://github.com/sqlfluff/sqlfluff/pull/705/files#diff-0ab7043f471d48de4c9b3e3aec77c0cc1e3884f1e15d366a017004675cd3ed56R13) line in the example plugin will need to point to the first release that includes the pluggy work (#705)

**Comment by barrywhart** [comment]
@dmateusp: Does this need to happen for the upcoming 0.5.0 release?

**Comment by dmateusp** [comment]
@barrywhart I think it does, AFAIK no minor release includes the plugin work right?

**Comment by barrywhart** [comment]
I think you're right. 👍

**Comment by tunetheweb** [comment]
@dmateusp / @barrywhart can this be closed now?

**Comment by barrywhart** [comment]
Ah yes. Closing.
