### ISSUE TITLE
Consider updating "Development Status" from "Alpha" to "Beta"?

### ISSUE THREAD

**Issue by barrywhart** [sqlfluff/sqlfluff#765]
In `setup.py`, the project status is set to `"Development Status :: 3 - Alpha"`. With the 0.4.0 release, I think we're approaching a certain level of completeness and stability. Should we change this to "Beta" for the next big release? Some things to consider (probably not a complete list):
* Parsing stability, especially for the more popular dialects
* API stability: How likely are we to make breaking changes?
* `dbt` stability: This is a very popular feature. How well is it working?
* Documentation: What's the quality and completeness of the docs?

**Comment by alanmcruickshank** [comment]
Apart from plugins I'm not expecting any more major architecture changes any time soon. That means that serious bugs should either already be occurring or we're relatively safe.

Of the bugs already raised, I think we need to solve #780, #715, #669 & #641 first - but then I'd be happy to move the project to `beta`.

On the API - I think that might be in more alpha status but lets revisit whether to explicitly call that out as different when we upgrade the rest of the project. Unless we get bug reports on it then I'd be tempted to upgrade that to beta too.

**Comment by alanmcruickshank** [comment]
The last of these bugs now has a PR in place. I suggest we move to beta in the next release. I'll add that to the PR.
