### ISSUE TITLE
[snowflake] TRANSIENT command not parsing

### ISSUE THREAD

**Issue by DavidJohnQuinlan** [sqlfluff/sqlfluff#768]
Hi all,

Just wanted to say I am a big fan of the project. 

## Observed Behaviour
I am having a parsing issue related to a snowflake SQL query. Please see the query below: 

```
CREATE OR REPLACE TRANSIENT TABLE MY_DB.NEW_TABLE AS
SELECT
    UNIQUE_ID,
    ACCT_ID
FROM MY_DB.TABLE;
```

This query obtains the following parsing error when running the `sqlfluff lint` command: 

```
L:   1 | P:   1 |  PRS | Found unparsable section: 'CREATE OR REPLACE TRANSIENT
                       | TABLE MY_DB....'
```
After some further investigation I believe the issue is related to the `TRANSIENT` command not being parsed. 

## Version

I am using `sqlfluff, version 0.4.0` and `Python, version 3.7.4`

## Configuration
```
[sqlfluff]
verbose = 0
nocolor = False
dialect = snowflake
templater = jinja
rules = None
exclude_rules = None
recurse = 0
output_line_length = 80
runaway_limit = 10
ignore_templated_areas = True
```

Thanks in advance for your help.

**Comment by alanmcruickshank** [comment]
This would be a great issue for any newcomers. The `snowflake` dialect gets the `CREATE TABLE` segment from the `ansi` dialect. To add this in we should just at an optional `TRANSIENT` keyword to `CreateTableStatementSegment` in `dialect_ansi.py`.

**Comment by DavidJohnQuinlan** [comment]
Thanks Alan, I will give it a go.
