### ISSUE TITLE
Ignore unparseable DML/DDL in script files

### ISSUE THREAD

**Issue by aaronsteers** [sqlfluff/sqlfluff#775]
Caveat: I recognize that script files are not the primary target for SQLFLuff but I think it would be good to see if we can gracefully handle such files.

Could we add a rule where we do not try to parse DML/DDL commands such as `ALTER`, `CREATE`, `USE`, and `DESCRIBE`?

As of today, these each throw an `unparsable section` error. While I don't want to stop parsing errors from being thrown on SELECT statements within the same file, I do think it's totally fair and understood for SQLFluff to not attempt parsing every variant of `non-SELECT` DML/DDL statements.

Thoughts?

**Comment by alanmcruickshank** [comment]
I think most of the `CREATE` statements have reasonable coverage, but I agree we shouldn't try and lint all of the other statements precisely. We should be specific enough to be useful and then use some of the more liberal grammar elements (like `GreedyUntil` or `Anything`) to allow some reasonable flexibility within that.

@aaronsteers - have you got a few examples for us to work with?

**Comment by tunetheweb** [comment]
Closing as not heard anything back. Can reopen if we get feedback.
