### ISSUE TITLE
Provide a template to plugin developers

### ISSUE THREAD

**Issue by dmateusp** [sqlfluff/sqlfluff#794]
I wonder if it may be easier for folks to develop plugins if we provided the example plugin as a separate "GitHub Template Repository" that they could fork, maybe with some templating to replace the word "example", etc.

https://github.blog/2019-06-06-generate-new-repositories-with-repository-templates/
https://rclayton.silvrback.com/templatizing-github-template-repos

_Originally posted by @barrywhart in https://github.com/sqlfluff/sqlfluff/pull/705#discussion_r579690988_

**Comment by alanmcruickshank** [comment]
I'm going to close this as we've got a good example plugin in the repo and we've not seen any activity on this issue for a while.
