### ISSUE TITLE
What does `_target_elems` do? A few rules define that property but only L010 seems to use it

### ISSUE THREAD

**Issue by dmateusp** [sqlfluff/sqlfluff#795]
What does `_target_elems` do? I see it in several of the rules, but I can't find any core code or documentation referencing it. 🤔

_Originally posted by @barrywhart in https://github.com/sqlfluff/sqlfluff/pull/705#discussion_r579691841_

**Comment by alanmcruickshank** [comment]
It defines which types of segments L010 and any rules that inherit from it are looking for.

https://github.com/sqlfluff/sqlfluff/blob/master/src/sqlfluff/core/rules/std/L010.py#L57

L012, L012, L014, L030 & L040 all define it, but they all inherit the same linting logic from L010.

**Comment by barrywhart** [comment]
Thanks! Could it be worth adding a comment about it in the places where it is used? No big deal, but I was halfway convinced it must be a core feature for rules which I couldn't find the source for. 🤦‍♂️
