### ISSUE TITLE
API .get_tables_references() Snowflake Dialect Bug

### ISSUE THREAD

**Issue by kgpayne** [sqlfluff/sqlfluff#801]
## Expected Behaviour
```python
parsed = sqlfluff.parse("select * from my_schema.my_table", dialect="snowflake")
external_tables = parsed.tree.get_table_references()
print(external_tables)
# outputs: {'my_schema.my_table'}
```

## Observed Behaviour
SQLFluff throws an ```AttributeError: 'StatementSegment' object has no attribute 'get_table_references'```

## Steps to Reproduce
parsed = sqlfluff.parse("select * from my_schema.my_table", dialect="snowflake")
external_tables = parsed.tree.get_table_references()
print(external_tables)

## Version
sqlfluff 0.4.0, tested with py36, py37, py38, py39

## Configuration
N/A

**Comment by alanmcruickshank** [comment]
I think this is solved
