### ISSUE TITLE
New Slack link?

### ISSUE THREAD

**Issue by qbatten** [sqlfluff/sqlfluff#802]
Any chance we could get a new Slack invite link again? Looks like the one in the README & Docs has expired. (As a sidenote, this is basically a re-up of #656.)

If you wanted to create a link that never expires, I believe you can do that via the "Edit link settings" button in the Slack UI! [Here's a link to the relevant Slack doc](https://slack.com/help/articles/201330256-Invite-new-members-to-your-workspace#share-an-invitation-link).

Thanks so much!

**Comment by fernandobrito** [comment]
This has been closed, but isn't the link in the README and latest docs still broken?

**Comment by qbatten** [comment]
Yep, link still doesn't work, as far as I can tell. 

Hope they take a look at this again, I'd love to join the Slack and I believe the solution I suggested will fix the issue where the link expires every month.

**Comment by fernandobrito** [comment]
@qbatten I was able to find a link that works by going to the #tools-sqlfluff channel in the dbt Slack community. You can use it: https://join.slack.com/t/sqlfluff/shared_invite/zt-o1f4x0e8-pZzarAIlQmKj_6ZwD16w0g
