### ISSUE TITLE
Expose supported dialects for import

### ISSUE THREAD

**Issue by kgpayne** [sqlfluff/sqlfluff#805]
As a developer using SQLFluff in other projects, it would be helpful to have a list of supported dialects available for import.

Currently I maintain a list of dialects inferred from the project source:

```python
supported_dialects = [
    "bigquery", "mysql", "teradata", "postgres", "snowflake", "exasol", "exasol_fs"
]
```

It would be great to replace this with:

```python
from sqlfluff import SUPPORTED_DIALECTS
```

**Comment by nolanbconaway** [comment]
This is also what's done in sqlfluff-online! https://github.com/sqlfluff/sqlfluff-online/blob/master/src/app/config.py
