### ISSUE TITLE
Add testing for docs in CI

### ISSUE THREAD

**Issue by NiallRees** [sqlfluff/sqlfluff#808]
Let's add some testing on the actual sphinx output?

**Comment by alanmcruickshank** [comment]
The rule docs are now fixed (thanks to #817). I agree that some testing on the sphinx docs makes a lot of sense though. I've update the issue to be an enhancement as a result.

**Comment by dmateusp** [comment]
The [Great Expectations project](https://github.com/great-expectations/great_expectations) does something quite nice:

For each PR they generate docs on CI and these are available to see for reviewers.

Check [my PR](https://github.com/great-expectations/great_expectations/pull/1662), if you see the details of CI there's a [link to the docs](https://great-expectations--1662.org.readthedocs.build/en/1662/)

I think they use [this feature](https://docs.readthedocs.io/en/stable/pull-requests.html)

**Comment by tunetheweb** [comment]
@zhongjiajie added some tests in #1335 and  integrated them into CI in #1393 

Given that going to close this for now but feel free to reopen if we have more specifics.

**Comment by zhongjiajie** [comment]
> The [Great Expectations project](https://github.com/great-expectations/great_expectations) does something quite nice:
> 
> For each PR they generate docs on CI and these are available to see for reviewers.
> 
> Check [my PR](https://github.com/great-expectations/great_expectations/pull/1662), if you see the details of CI there's a [link to the docs](https://great-expectations--1662.org.readthedocs.build/en/1662/)
> 
> I think they use [this feature](https://docs.readthedocs.io/en/stable/pull-requests.html)

This CI is really good, maybe we could add it to our CI
