### ISSUE TITLE
Rules whose docs need rationales (or improvements to existing ones)

### ISSUE THREAD

**Issue by barrywhart** [sqlfluff/sqlfluff#812]
A few rules seem to lack a clear rationale or explanation why they are part of SQLFluff or why SQLFluff considers them "recommended practices". It's important to be clear, because if someone finds a rule annoying, they may want to just disable it. That's fine if they understand the pros and cons of the rule. SQLFluff owes them a description of the pros; if it's unclear, they shouldn't have to go and research the practice on their own. (They are free to do so, but we're building credibility and helping our users _if they don't have to_.)
- L031: The docs don't provide a rationale why this is a best practice. They mention accidental self joins, but a self join may be deliberate. If we added a config option instead to *always* use aliases in join conditions, would that serve the same purpose while also making the code shorter?
- L032: I believe during development of this rule, there was a clear rationale involving corner cases with incorrect behavior. Let's dig this up and add it to the docs. Also, was it specific to certain databases or applicable to all?
- L020, L029: These seem like they detect things that will literally just *fail", don't they? If so, does it make sense for a linter to check for them? Let's explain why" in their docs.

**Comment by tunetheweb** [comment]
Added explanations to #2542:

![image](https://user-images.githubusercontent.com/10931297/152214012-8863ddff-327f-4849-ab4f-aae082a96e66.png)

![image](https://user-images.githubusercontent.com/10931297/152214059-eff7ec3a-50b3-4f5c-86c1-c99244bceda6.png)

![image](https://user-images.githubusercontent.com/10931297/152214115-36dc3941-244f-4be9-81b8-3c61d953550f.png)

![image](https://user-images.githubusercontent.com/10931297/152215182-e47d2393-0b30-4de0-a210-c4c60c354233.png)
