### ISSUE TITLE
Please create conda package!

### ISSUE THREAD

**Issue by abalter** [sqlfluff/sqlfluff#815]
Please create conda package in conda-forge channel.

**Comment by alanmcruickshank** [comment]
@abalter - I'm curious. most conda pacakages are first available on pypi, and in my experience I usually use conda where binaries are involved - but as sqlfluff is pure-python I wasn't expecting people to want a conda package. Can you elaborate a bit more on your use case on why a conda package is preferable to pypi?

**Comment by abalter** [comment]
Conda _started_ as a way to install python packages on pypi. But it grew into a universal package manager. Python keeps all the versions of your various software (R, python, java, c, node, ...) harmonized. It also allows you to export environment specifications so you can build the same environment elsewhere. Conda also tracks pip installs.

Conda is really just pip++, and I'm hoping everything in pip gets migrated. Almost everything is.

**Comment by abalter** [comment]
Information:

https://stackoverflow.com/questions/54834579/specific-reasons-to-favor-pip-vs-conda-when-installing-python-packages

https://www.anaconda.com/blog/understanding-conda-and-pip

https://towardsdatascience.com/pipenv-vs-conda-for-data-scientists-b9a372faf9d9

https://www.earthdatascience.org/courses/intro-to-earth-data-science/python-code-fundamentals/use-python-packages/introduction-to-python-conda-environments/

**Comment by alanmcruickshank** [comment]
@abalter - do you have any documentation on how to publish a conda package? I'm not familiar with the process. If it's relatively straightforward then I would be happy to add it to our standard release pipeline.

**Comment by abalter** [comment]
I think these are good docs. I would love to take this on myself, but my life simply has no room for rabbit holes at this time.

Building conda packages from scratch — conda-build 3.21.4+2.gfa451287.dirty documentation
https://docs.conda.io/projects/conda-build/en/latest/user-guide/tutorials/build-pkgs.html

Conda-build recipes — conda-build 3.21.4+2.gfa451287.dirty documentation
https://docs.conda.io/projects/conda-build/en/latest/concepts/recipe.html

Building conda packages with conda skeleton — conda-build 3.21.4+2.gfa451287.dirty documentation
https://conda.io/projects/conda-build/en/latest/user-guide/tutorials/build-pkgs-skeleton.html

Building a conda package and uploading it to Anaconda Cloud | by Qiusheng Wu | Medium
https://medium.com/@giswqs/building-a-conda-package-and-uploading-it-to-anaconda-cloud-6a3abd1c5c52

**Comment by barrywhart** [comment]
We attempted to do this awhile back and gave up. AFAIK, there haven't been any other requests for this. Think we should close it?

**Comment by abalter** [comment]
Hi @barrywhart . By chance, what problems did you run into? I've never done it before myself, but I would try to help if I can. Maybe send me the code you used to try, and I'll see if I can get it to work?

**Comment by barrywhart** [comment]
@abalter: See the PR linked above (#956). Someone else did the work, and I don't know what the issues were, but that may provide some clues.

**Comment by alanmcruickshank** [comment]
@abalter - the challenge was primarily building the package. At the time that I tried this - not all of our dependencies had conda packages - which made it very hard for the package builder to successfully package the tool.

If you're able to successfully put together the configuration which builds a sqlfluff conda package that would be  a very helpful first step.

**Comment by RoyalTS** [comment]
Seems this has been resolved and a feedstock now exists? https://github.com/conda-forge/sqlfluff-feedstock

**Comment by tunetheweb** [comment]
Cool. Thanks for letting us know.
