### ISSUE TITLE
sqlfluff[dbt] on official python 3.8 image only works with dbt==0.18

### ISSUE THREAD

**Issue by jnoynaert** [sqlfluff/sqlfluff#818]
Relates to #789, #715.

Maybe not a truly sqlfluff problem, but worth noting that if you start fresh with the official `python:3.8` or `python:3.8-buster` images, sqlfluff essentially refuses to install with dbt 19.0.

I'd bet a decent number of sqlfluff users are using the python:3.8 image or an equivalent environment.

```bash
docker run -i -t python:3.8-buster /bin/bash # same results with python:3.8
```

```bash
pip install --upgrade pip # non-op
pip install sqlfluff # works
pip install sqlfluff[dbt] # pip resolver falls over and dies, taking several packages back through most of their version history and then stalling out
pip install pre-commit && pre-commit install-hooks # with sqlfluff configured to include dbt support, stalls indefinitely for the same reason
```
alternatively, though:

```bash
pip install sqlfluff[dbt] dbt==0.18 # happy times
```

**Comment by jnoynaert** [comment]
Works if you start from ubuntu:20.04, aside from throwing the following incompatibility errors (I haven't actually tested the functionality):

```
ERROR: requests 2.23.0 has requirement chardet<4,>=3.0.2, but you'll have chardet 4.0.0 which is incompatible.
ERROR: dbt-core 0.19.0 has requirement colorama<0.4.4,>=0.3.9, but you'll have colorama 0.4.4 which is incompatible.
ERROR: dbt-core 0.19.0 has requirement Jinja2==2.11.2, but you'll have jinja2 2.11.3 which is incompatible.
```

**Comment by jnoynaert** [comment]
Okay, seems to do with the version of pip packaged with certain images? At this point I have a working build pipeline s I'm probably done digging.

This works (still with the above incompatibility errors):

```bash
docker run -i -t python:3.8.5 /bin/bash
pip install sqlfluff[dbt]
```
This does *not* work:
```bash
docker run -i -t python:3.8.5 /bin/bash
pip install --upgrade pip
pip install sqlfluff[dbt] #fails
pip install sqlfluff[dbt] --use-feature=2020-resolver #fails
```

**Comment by dwallace0723** [comment]
We are also experiencing this issue. `python:3.8.6-slim-buster` image.

**Comment by alanmcruickshank** [comment]
Thanks @pvonglehn . I'm assuming that at present we won't attempt to fix this within SQLFluff, as it looks like an upstream issue with pip. The recommended workaround is to specify the dbt version at the same time:

```bash
pip install sqlfluff[dbt] dbt==0.18 # happy times
```

If anyone has suggestions on things we can do to mitigate or solve this within the project then I'm all ears.

**Comment by dlogozz0** [comment]
We are experiencing an issue probably related to this.. Inside our Pipfile we have 

```
sqlfluff = {extras = ["dbt"], index="pypi", version = "*"}
dbt = "*"
``` 

Error thrown when running `sqlfluff lint` 

```    
from dbt.parser.manifest import (
ImportError: cannot import name 'load_macro_manifest' from 'dbt.parser.manifest' 
```

This looks to be where the issue arises: https://github.com/sqlfluff/sqlfluff/blob/master/src/sqlfluff/core/templaters/dbt.py#L107

I suppose I can specify a lower version of dbt in the pipfile but I would think this should just work.

**Comment by jnoynaert** [comment]
@dlogozz0 we don't have this issue anymore on the latest versions of sqlfluff and dbt. I'm going to go ahead and close this to keep from mixing up the issues
