### ISSUE TITLE
Enforce indent_unit rule on all files

### ISSUE THREAD

**Issue by will-misslin** [sqlfluff/sqlfluff#837]
-- Please add any additional labels that are related to the issue before submitting! --
The `.sqlfluff` config section for `[sqlfluff:rules]` contains an `indent_unit` option which allows for selection of `space` or `tab` for indenting. While this rule appears to be followed for lines modified by sqlfluff, it would be awesome if this rule could also be checked and enforced for existing files that have no other rule violations.

**Comment by tunetheweb** [comment]
Rule L004 enforces this doesn't it?
