### ISSUE TITLE
Lint rules should have access to the file path of the file being linted

### ISSUE THREAD

**Issue by barrywhart** [sqlfluff/sqlfluff#839]
I'm working on an organization-specific rule (a plug-in) and realized that it could be very useful for rules to have access to the path of the file that is currently being linted.

Context: The SQL files in our projects fall into two categories, similar to dbt:
* Model files (These create output tables)
* Pre- or post-conditions (These enforce constraints on the data but do not create output tables.) These are typically found in a directory named `constraints/`, `postconditions/`, something like that.

The rule I'm developing should only apply to model files, so having access to the path is a pragmatic (admittedly org-specific and not 100% guaranteed) way to deduce the category.

Other rules may use this in other ways; this is just one real-world use case to justify the enhancement.

**Comment by dmateusp** [comment]
makes total sense, thanks for the context

**Comment by dmateusp** [comment]
Would you mind sharing a small snippet of how you're using the file name inside the rule just as reference for folks trying to do this in their own rules in the future?

**Comment by barrywhart** [comment]
Here's an example:
```
    def _eval(self, segment, dialect, path, **_):
        if "constraints" in path.parts[:-1]:
            # Don't analyze constraints, only "model" files.
            return
```
