### ISSUE TITLE
Rename BaseCrawler class as BaseRule to be clearer, avoid confusion with analysis helper classes, e.g. SelectCrawler

### ISSUE THREAD

**Issue by barrywhart** [sqlfluff/sqlfluff#840]
Discussed here:
https://github.com/sqlfluff/sqlfluff/pull/779#pullrequestreview-604167034

**Comment by alanmcruickshank** [comment]
Yes. The fact that it's called a crawler is a historic artifact when I thought that the crawlers and rules might be separate. Given they're not, this makes total sense.
