### ISSUE TITLE
Clean up AliasedTableReferenceSegment grammar

### ISSUE THREAD

**Issue by barrywhart** [sqlfluff/sqlfluff#876]
This is a tech debt issue; nothing of concern to users.

In working on #865, Niall and I noticed something a bit odd about `AliasedTableReferenceSegment`. In order to add support for using table aliases in `UPDATE` statements, I had changed `UpdateStatementSegment` from:

```
Ref("TableReferenceSegment")
```

to:

```
Ref("AliasedTableReferenceSegment")
```

This worked, and all tests (new and old) passed because the match grammar for `AliasedTableReferenceSegment` specifies that the alias part is optional:

```
Ref("TableReferenceSegment"), Ref("AliasExpressionSegment", optional=True)
```

But... this resulted in the parse tree looking odd. (Note the nested `table_reference` nodes.)
```
    update_statement:
      keyword: UPDATE
      table_reference:
        table_reference:
          identifier: table_name
```

To avoid this, we updated my change to instead be:
```
OneOf(Ref("TableReferenceSegment"), Ref("AliasedTableReferenceSegment"))
```

This avoids the nesting, but it'd be better if we didn't have to specify `OneOf()` to make the parse tree look reasonable.  `AliasedTableReferenceSegment` supports the exact SQL syntax we want. Can we refactor the ANSI dialect a bit so the parse tree looks okay if we do this?

Another (more minor) question: The name `AliasedTableReferenceSegment` suggests that there's an alias present, but it's actually optional. Should we consider renaming it to make this clearer?

**Comment by barrywhart** [comment]
@NiallRees: I created this after our discussion. How does this look?

**Comment by NiallRees** [comment]
Nice @barrywhart . I think that the real solve here is in your last question, and that `AliasedTableReferenceSegment` should only match on aliased tables references per its title.

**Comment by barrywhart** [comment]
@alanmcruickshank: That makes sense to me.
