### ISSUE TITLE
On macos: Respect XDG base dirs.

### ISSUE THREAD

**Issue by shawnohare** [sqlfluff/sqlfluff#889]
Apropos to #405, a large number of developer tools (especially those with a cli) respect XDG base dirs in both macos and linux. Those that insist on using `~/Library` on macos are outliers, as it creates unnecessary headaches for anyone that (a) maintains their own user configurations and / or (b) frequently switches between macos and linux. 

Can `sqlfluff` at least first look for configuration in `${XDG_CONFIG_HOME:-~/.config}` first on macos? Obviously `~/Library` can be used as a fallback if desired for some reason, though I think it becomes irrelevant for configuration / data if the XDG base dir spec is followed. (As indicated in https://stackoverflow.com/questions/3373948/equivalents-of-xdg-config-home-and-xdg-data-home-on-mac-os-x caching is a little more subtle).

**Comment by dmateusp** [comment]
Since we use `appdirs` to resolve those directories, this `appdirs` [issue](https://github.com/ActiveState/appdirs/issues/78) is the source of the problem. We could try going with [this patch](https://github.com/ActiveState/appdirs/issues/78#issuecomment-366947045).
