### ISSUE TITLE
Rule: No nested selects within join clauses.

### ISSUE THREAD

**Issue by barrywhart** [sqlfluff/sqlfluff#89]
This is a pretty general, high-level quality check. I often see this issue with SQL written by new data scientists or engineers -- they'll deliver a working query, but it's monolithic and 50+ lines long. Even with proper indentation, it's hard to grasp what going on.

When this occurs, SQLFluff should suggest breaking the query into two or more logical chunks, with some of these chunks written as (descriptively named) CTEs.

**Comment by alanmcruickshank** [comment]
I like this as an idea. Do you think it's about nested `SELECT` statements here? That would be the easiest to put a rule around: i.e. More than 3 nested select statements raises a linting error.

What I'm not sure about is whether that catches all the cases that you're thinking about. @barrywhart  Anything else you think we might need to do?

**Comment by barrywhart** [comment]
I'll review some our earlier queries and get back with you. My main memory is the number of physical lines. I don't recall whether it was mostly nesting or something else.

This reminds me of another thing -- I think some queries were JOINing with a nested SELECT for no reason -- the nested query was trivial and they could've simply written it as a JOIN. Once I find some of these queries, I'll share them here and we can think about whether this should be one issue or several.

**Comment by barrywhart** [comment]
This is one query I inherited. It's hard to point to any one single area where it is overly complex. It's just... large. 🙂 

```
SELECT
users_info.user_id AS user_id,
users_info.member_since AS member_since, 
orders_mth.paid_time AS order_date,
orders_mth.amount AS amount,
users_info.country AS country
FROM 
(SELECT ui.user_id as user_id, 
cohort.first_order_date as first_order_date,
ui.member_since AS member_since,
MAX(uv.name) AS country
FROM
(select user_id, user_type , min(date(member_since)) as member_since
from users_info
group by 1,2
having user_type != 'internal'
  ) as ui
LEFT JOIN users_contact uc
ON ui.user_id = uc.user_id
LEFT JOIN countries uv
ON uc.country=uv.country_id
left join 
(select user_id, min(date(time_stamp)) as first_order_date 
from orders
where (internal = 'N' and successful = 'Y' and monthly_order_type != 0) 
group by 1) as cohort 
ON (ui.user_id = cohort.user_id)
WHERE ( ui.member_since <= '", cohort_end_date, "' 
and ui.member_since >='", cohort_start_date, "'
and ui.user_id not in (72410650, 72458194, 72418426, 72447882)
and NOT REGEXP_CONTAINS(LOWER(uc.email), r'@mailchimp.com')
and NOT REGEXP_CONTAINS(LOWER(uc.email), r'@rsglab.com')
AND ui.user_type != 'internal'
AND cohort.first_order_date is not null 
and uc.email is not null)
GROUP BY 1,2,3) AS users_info
left join 
(select tl.user_id as user_id, date(tl.paid_time) as paid_time,
sum(tl.amount) - sum(coalesce(tl_ad.ad_amount, 0)) as amount
from  
(select time_stamp as paid_time, 
user_id as user_id,
sum(case when tax_amount > 0 and amount > 0 and amount > tax_amount
and amount = coalesce(pre_tax_amount, 0) + coalesce(tax_amount, 0) - coalesce(credits_used, 0)
then amount - tax_amount
else amount end) as amount
from orders
where (internal = 'N' and successful = 'Y' 
and monthly_order_type != 0 )
group by 1, 2) as tl
left join 
(select o.user_id as user_id, time_stamp as paid_time, 
sum(oi.discounted_amount) as ad_amount
from orders`as o
inner join order_items as oi
on (oi.order_id = o.order_id
and oi.source_database = o.source_database)
where (o.successful = 'Y'
and o.internal = 'N'
and oi.type in ('fb_ad','fb_ad_reup','google_ad','google_ad_reup','postcards_automation_credits','postcards_prepaid_postage',
'postcards_prepaid_printing')
and monthly_order_type != 0)
group by 1,2) as tl_ad 
on tl.user_id = tl_ad.user_id
and tl.paid_time = tl_ad.paid_time  
group by 1,2) AS orders_mth
on users_info.user_id = orders_mth.user_id
```

**Comment by barrywhart** [comment]
Query with unnecessary nested SELECTs:
```
SELECT
    *
  FROM (
    SELECT
      user_id,
      campaign_id,
      unique_opens,
      opens
    FROM
      `{{bi_user_campaigns_stats}}`
    JOIN (
      SELECT
        user_id,
        campaign_id
      FROM
        `{{bi_user_campaigns_contents}}`
      WHERE
        track_opens="Y")
    USING
      (user_id,
        campaign_id))
  JOIN (
    SELECT
      user_id,
      campaign_id,
      recipients_click,
      unsubs
    FROM
      `{{bi_user_campaigns_stats}}`
    JOIN (
      SELECT
        user_id,
        campaign_id
      FROM
        `{{bi_user_campaigns_content}}`
      WHERE
        track_clicks_html="Y")
    USING
      (user_id,
        campaign_id))
  USING
    (user_id,
      campaign_id)
  )
```

**Comment by barrywhart** [comment]
Another query with unnecessary nesting (FWIW, I think it's a later version of the previous one).

Perhaps SQLFluff could detect at least some of these cases automatically. In fact, is there *ever* a reason to `SELECT FROM` a nested `SELECT`? Offhand, I can't think so.

```
SELECT
  user_id,
  campaign_id,
  start_time,
  end_time,
  emails_sent,
  unique_opens,
  opens,
  recipients_click,
  unsubs
FROM
(SELECT
  c.user_id as user_id,
  c.campaign_id,
  c.start_time,
  c.end_time,
  c.emails_sent,
  s.unique_opens,
  s.opens,
  s.recipients_click,
  s.unsubs
FROM
  `{{bi_user_campaigns}}` AS c
LEFT JOIN `mc-business-intelligence.mailchimp.users_compliance` AS compliance
USING (user_id, campaign_id)
JOIN `{{bi_user_campaigns_stats}}` AS s
USING (user_id, campaign_id)
JOIN `{{bi_user_campaigns_content}}` AS content
ON (s.user_id = content.user_id
      AND s.campaign_id = content.campaign_id
      -- We only want to include campaigns that had tracking for clicks AND opens enabled
      AND track_opens="Y"
      AND track_clicks_html="Y")
WHERE
  c.type = 'regular'
  AND compliance.user_id IS NULL
  AND compliance.campaign_id IS NULL)
-- Note: At this time, campaign date filtering is only for use by tests. We
-- filter campaigns by start_date, which could have issues, e.g. including
-- stats for campaigns that are still ongoing.
WHERE TRUE {{user_filter}} {{campaign_date_filter}}
```

**Comment by alanmcruickshank** [comment]
I think your suggestion for #37 is actually a great idea for *this* potential issue. I'm not yet sold on #37 because I think it can be quite useful to have logic in joins, but I'm definitely sold on this one, and using [Halstead Complexity Measures](https://en.wikipedia.org/wiki/Halstead_complexity_measures), sounds like a great idea.

I'm assuming this is just for select statements for now?

**Comment by barrywhart** [comment]
I agree, #37 is tricky. There are cases where a `JOIN` condition belongs in a `WHERE` instead, but I don't know if it's possible to automatically identify such cases.

Yes, I am just thinking of select statements.

**Comment by aaronsteers** [comment]
In regards to recommending CTEs based on complexity, what about a rule to recommend a CTE for any subqueries that are not the first relation in the FROM clause.

Essentially, this is okay:

```
SELECT
    tbl_a.a,
    tbl_b.b
FROM (
    SELECT *
    FROM tbl_c
) AS tbl_a
LEFT JOIN tbl_b
    USING (keycol)
```

But this is not:

```
SELECT
    tbl_a.a,
    tbl_b.b
FROM tbl_a
LEFT JOIN (
    SELECT *
    FROM tbl_c
) AS tbl_b
    USING (keycol)
```

The logic is that whatever comes first in your query _should_ be the thing primarily determining its granularity. But once we begin our joins, the extra verbosity discourages readability and spreads out the code so that the full joins cannot be viewed in a single screen height.

**Comment by alanmcruickshank** [comment]
@aaronsteers I like your suggestion! I think there might be other potential rules that could also be useful here, but your suggestion would be a really good starting point, 👍
