### ISSUE TITLE
Carriage returns add extra characters to fix results?

### ISSUE THREAD

**Issue by nolanbconaway** [sqlfluff/sqlfluff#906]
This is a weird one y'all. Maybe someone who knows more about string encoding knows what's going on?

This bug was surfaced to me by some users of sqlfluff-online:

![image](https://user-images.githubusercontent.com/1770896/112768906-58cfcf80-8fec-11eb-9490-0e73e2ee7bfd.png)

Notice the extra "urns" at the end of the fixed sql. How did that get there?

Towards remedying the situation, I isolated the carriage return, `\r\n` as the culprit. The fixed SQL seems to repeat one character at the end of the string for each carriage return.

## Steps to Reproduce

```py
from sqlfluff.api import fix

sql = """select *\r\nfrom table"""
print(fix(sql))

"""
select *
from table
e
"""
# ^^^ PROBLEM!

sql = """select *\nfrom table"""
print(fix(sql))
"""
select *
from table
"""

sql = """select *
from table"""
print(fix(sql))
"""
select *
from table
"""
```

It appears that this also affects the CLI, so the problem is somewhat deeper than the public API.

```py
sql = """select *\r\nfrom table"""
with open("test.sql", "w") as f:
    f.write(sql)
```

```sh
$ cat test.sql | sqlfluff fix -
select *
from table
e%                                                                                                                
```

I have not investigated further though! Would love to hear if anyone has any clue about what's up here. Is it possible that all strings need to run through the preprocessing implemented for sqlfluff-online? https://github.com/sqlfluff/sqlfluff-online/pull/19

If so, i'll happily submit the fix! If its something more involved than you might want to put an adult in the room.

## Version

Fluff 0.4.1
Python 3.8.7

## Configuration

No configs, out the box fluff here!

**Comment by barrywhart** [comment]
My intuition is that somewhere, SQLFluff is tracking the location of elements within the SQL as byte offsets from the start, but carriage returns are getting accidentally removed so the offsets are incorrect. I would look for a place where the SQL is being read or written using a file-like object, as that's where these things often happen.

**Comment by barrywhart** [comment]
Running the CLI example in verbose mode yields some apparent clues near the end of the output.
```
cat test.sql | sqlfluff fix -vvvvvv -
...
DEBUG      Original Tree: 'select *\nfrom table'
DEBUG      Fixed Tree: 'select *\nfrom table\n'
DEBUG      ### Templated File.
DEBUG          File slice: 0 TemplatedFileSlice(slice_type='literal', source_slice=slice(0, 19, None), templated_slice=slice(0, 19, None))
DEBUG          			templated: 'select *\nfrom table'	source: 'select *\r\nfrom tabl'
DEBUG      Source-only slices: []
DEBUG      ### Beginning Patch Iteration.
DEBUG        0 Yielded patch: FixPatch(templated_slice=slice(0, 19, None), fixed_raw='select *\nfrom table\n', patch_type='literal')
DEBUG              Templated Hint: ...'' <> ''...
INFO             * Keeping patch on literal-only section: EnrichedFixPatch(source_slice=slice(0, 19, None), templated_slice=slice(0, 19, None), fixed_raw='select *\nfrom table\n', patch_type='literal', templated_str='select *\nfrom table', source_str='select *\r\nfrom tabl')
DEBUG      Final slice buffer: [slice(0, 19, None), slice(19, 20, None)]
DEBUG      Appending literal Patch:          slice(0, 19, None)    'select *\r\nfrom tabl' > 'select *\nfrom table\n'
DEBUG      Appending Raw:                    slice(19, 20, None)     'e'
```

I see several odd-looking things...

Here, `source` is truncated:
```
DEBUG          			templated: 'select *\nfrom table'	source: 'select *\r\nfrom tabl'
```

Similarly, `source_str` is truncated here:
```
INFO             * Keeping patch on literal-only section: EnrichedFixPatch(source_slice=slice(0, 19, None), templated_slice=slice(0, 19, None), fixed_raw='select *\nfrom table\n', patch_type='literal', templated_str='select *\nfrom table', source_str='select *\r\nfrom tabl')
```

And this is apparently where the extraneous `e` at the end of the fixed query comes from:
```
DEBUG      Appending Raw:                    slice(19, 20, None)     'e'
```

I'm not familiar with this area of the code, but hopefully this provides some good hints for others who are.

**Comment by jpy-git** [comment]
@nolanbconaway so I tried this again now and don't see the issue anymore on 0.9.0:
![image](https://user-images.githubusercontent.com/80432516/146284294-0162191e-f2c0-4b6f-87f1-e0265bed151d.png)
Could you confirm if you still see this?

@barrywhart don't think this is related to the other newline issue I mentioned earlier. So will keep investigating that and update on #797.

**Comment by nolanbconaway** [comment]
Lemme give it a go!

**Comment by nolanbconaway** [comment]
Looks OK to me!

```
➜ python                       
Python 3.8.7 (default, Jan 24 2021, 16:06:25) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from sqlfluff.api import fix
>>> 
>>> sql = """select *\r\nfrom table"""
>>> print(fix(sql))
select *
from table

>>> import sqlfluff
>>> sqlfluff.__version__
'0.9.0'

```
