### ISSUE TITLE
Lint output is referencing line and character positions from the compiled file

### ISSUE THREAD

**Issue by fernandobrito** [sqlfluff/sqlfluff#910]
When I run `sqlfluff lint` on a file using the dbt templater, the results are referencing the line numbers from the compiled file, and not from the source file.

## Observed Behaviour

On the left hand side you can see my original source file and on the right hand side the compiled file.

![image](https://user-images.githubusercontent.com/196840/113009267-14713a80-9178-11eb-9a6e-8f391ee00607.png)

In the results in the terminal, sqlfluff is using the line numbers from the compiled file (the one in the right).

## Expected Behaviour

Given that sqlfluff supports source mapping, I would expect it to use the line numbers from the source file (9, 10, 12 and 13 in my screenshot).

## Steps to Reproduce

My toy file:
```
{{
    config(
        schema='core',
        alias='test',
        materialized='view'
    )
}}

select 1,
    2,

    3
FROM {{ source('dbexp', 'account') }}
```

## Version

sqlfluff, version 0.4.1
Python 3.7.6
dbt 0.18.1

## Configuration
```
[sqlfluff]
dialect = snowflake
templater = dbt

# dbt templating does not keep trailing new lines (L009)
exclude_rules = L009,L031,L034,L041

[sqlfluff:rules]
max_line_length = 100

[sqlfluff:rules:L010] # keywords
capitalisation_policy = lower

[sqlfluff:rules:L030] # function names
capitalisation_policy = lower

[sqlfluff:rules:L040] # boolean/null literals
capitalisation_policy = lower
```

**Comment by fernandobrito** [comment]
Moving here some of my findings that I posted on [Slack](https://sqlfluff.slack.com/archives/C01GX4L213J/p1616938160015700).

When [format_violation()](https://github.com/sqlfluff/sqlfluff/blob/959f216249afb7ab3829875f00234aca89b03f1c/src/sqlfluff/cli/formatters.py#L50) is called to format the output, there's a call to [violation.get_info_tuple()](https://github.com/sqlfluff/sqlfluff/blob/959f216249afb7ab3829875f00234aca89b03f1c/src/sqlfluff/core/errors.py#L99) which calls [self.line_no()](https://github.com/sqlfluff/sqlfluff/blob/959f216249afb7ab3829875f00234aca89b03f1c/src/sqlfluff/core/errors.py#L57). Here `line_no` is retrieved from `pm` `PositionMarker`, but there's also an attribute called `pm.source_pos_marker` which has the `line_no` in the source, and I don't understand why this one is not called instead.

Also good to keep in mind that when this is fixed, we should also be consistent and use the source line number in error descriptions that reference other lines/positions (such as `Line over-indented compared to line #XXX`).

**Comment by fernandobrito** [comment]
Or actually, all `line_no()`, `line_pos()` and `char_pos()` will call [self.pos_marker()](https://github.com/sqlfluff/sqlfluff/blob/959f216249afb7ab3829875f00234aca89b03f1c/src/sqlfluff/core/errors.py#L81). Should this method maybe return `self.segment.pos_marker.source_pos_marker` if that's available?

**Comment by alanmcruickshank** [comment]
@fernandobrito - can you test this with the new release which has just come out (0.5.0)? I think I might have fixed some of this - but would love to check which bits I have and haven't.

My guess is that I haven't yet fixed the `Line over-indented compared to line #XXX` part, but I'm hoping that's the only issue left.

**Comment by fernandobrito** [comment]
Awesome, I confirm that 0.5.0 behaves as I expect (line numbers refer to source code), but as you mentioned, the line number in the violation messages still refers to the row number in the compiled file.

Thanks for the fix and update! I'm very excited to start plugging sqlfluff into my CI workflow 🤩 
I guess I can close this issue?

![image](https://user-images.githubusercontent.com/196840/113610364-4d645000-964d-11eb-9a42-8cb5ce02af06.png)
