### ISSUE TITLE
L044: Max Recursion Depth

### ISSUE THREAD

**Issue by dwallace0723** [sqlfluff/sqlfluff#930]
Came across this `CRITICAL` error when linting a few models in our dbt project using sqlfluff `0.5.0`:

#### Steps to reproduce:
```
$ sqlfluff lint models/sales/hubspot_engagement_calls.sql
CRITICAL   [L044] Applying rule L044 threw an Exception: maximum recursion depth exceeded while calling a Python object 
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/sqlfluff/core/rules/base.py", line 290, in crawl
    res = self._eval(
  File "/usr/local/lib/python3.8/site-packages/sqlfluff/core/rules/std/L044.py", line 138, in _eval
    return self._analyze_result_columns(select_info, dialect, queries)
  File "/usr/local/lib/python3.8/site-packages/sqlfluff/core/rules/std/L044.py", line 106, in _analyze_result_columns
    self._analyze_result_columns(
  File "/usr/local/lib/python3.8/site-packages/sqlfluff/core/rules/std/L044.py", line 106, in _analyze_result_columns
    self._analyze_result_columns(
  File "/usr/local/lib/python3.8/site-packages/sqlfluff/core/rules/std/L044.py", line 106, in _analyze_result_columns
    self._analyze_result_columns(
  [Previous line repeated 976 more times]
  File "/usr/local/lib/python3.8/site-packages/sqlfluff/core/rules/std/L044.py", line 90, in _analyze_result_columns
    for wildcard in select_info.get_wildcard_info():
  File "/usr/local/lib/python3.8/site-packages/sqlfluff/core/rules/analysis/select_crawler.py", line 119, in get_wildcard_info
    WildcardInfo(
  File "<string>", line 1, in __new__
RecursionError: maximum recursion depth exceeded while calling a Python object
```

#### SQLFluff Verbose Output
[sqlfluff_verbose_out.txt](https://github.com/sqlfluff/sqlfluff/files/6268014/sqlfluff_verbose_out.txt)

#### Version

```sh
$ sqlfluff --version
sqlfluff, version 0.5.0
```

#### Configuration
```
[sqlfluff]
dialect = snowflake
templater = dbt
# dbt templating does not keep trailing new lines (L009)
exclude_rules = L007,L009,L031,L033,L034

[sqlfluff:rules]
max_line_length = 120
comma_style = trailing

[sqlfluff:rules:L010]
capitalisation_policy = upper
```

#### SQL

```sql
{{
    config(
        materialized = 'table'
    )
}}

with
    hubspot__engagement_calls as (
        select * from {{ ref('hubspot__engagement_calls') }}
    )

select * from hubspot__engagement_calls
```

#### Compiled SQL

```sql

with
    hubspot__engagement_calls as (
        select * from ANALYTICS_DWALLACE.PUBLIC_intermediate.hubspot__engagement_calls
    )

select * from hubspot__engagement_calls
```

**Comment by alanmcruickshank** [comment]
Great bug report, thanks! This looks very interesting. Do I correctly understand that this is only happening on this model?

@barrywhart , you worked on this rule relatively recently - reckon you could take a look at how to avoid the infinite recursion? I can see the recursion in here https://github.com/sqlfluff/sqlfluff/blob/master/src/sqlfluff/core/rules/std/L044.py#L106 but I'm not sure on the best way to avoid it given the design you had in mind.

Unless it's a massive fix, I assume we should publish a new release as soon as it's fixed.

**Comment by barrywhart** [comment]
I think it'll be a very simple fix. OTOH, that SQL looks like it couldn't do anything useful. Is there a more realistic, useful query that it's based on, @dwallace0723?

**Comment by dwallace0723** [comment]
> Is there a more realistic, useful query that it's based on,

@barrywhart Happy to provide additional information as needed, but I'm not totally sure what you're implying here since this is indeed a real production query that gets run via dbt. OOC, why would it matter if the query doesn't seem "realistic"? Is the rule checking how realistic the query is?

**Comment by dwallace0723** [comment]
@barrywhart here is another SQL query where this rule is choking:

**SQL**
```sql
{{
    config(
        materialized = 'table'
    )
}}

with
    hubspot__contacts as (
        select * from {{ ref('hubspot__contacts') }}
    ),

    final as (
        select
            *
        from
            hubspot__contacts
        where
            not coalesce(_fivetran_deleted, false)
    )

select * from final
```

**Compiled SQL**
```sql


with
    hubspot__contacts as (
        select * from ANALYTICS_DWALLACE.PUBLIC_intermediate.hubspot__contacts
    ),

    final as (
        select
            *
        from
            hubspot__contacts
        where
            not coalesce(_fivetran_deleted, false)
    )

select * from final
```

**Comment by barrywhart** [comment]
The rule shouldn't have infinite recursion. My confusion is that the test query queries itself, so I was wondering what this actually does when you run it. I have a PR up now -- could you test this and see if it addresses the problems you're seeing?

**Comment by dwallace0723** [comment]
>My confusion is that the test query queries itself,

@barrywhart no, it doesn't. Take another look at the compiled SQL:

```sql
with
    hubspot__engagement_calls as (
        select * from ANALYTICS_DWALLACE.PUBLIC_intermediate.hubspot__engagement_calls
    )

select * from hubspot__engagement_calls;
```

This is perfectly valid SQL and runs just fine.

**Comment by barrywhart** [comment]
I think L044 has a more subtle bug that is not addressed by my PR. I think it is mistakenly interpreting `ANALYTICS_DWALLACE.PUBLIC_intermediate.hubspot__engagement_calls` as if it were the same as the CTE `hubspot__engagement_calls`. It thinks the CTE is querying itself, when it is actually querying an external table. I'll take a closer look at this.

The current PR avoids the infinite recursion and accidentally returns the correct result, so it may be worth merging as is, but I definitely want to dig into this more (I can create a new issue if needed).

**Comment by barrywhart** [comment]
Ok, I think I have a full fix now, handling both _actual_ recursive CTEs as well as the other bug, which was making the mistake described above.

Until the fix is available, I believe you can work around this issue by changing the CTE name so it doesn't match the base table name of the underlying table it's querying from.
