### ISSUE TITLE
Resolve whitespace interdependencies between rules.

### ISSUE THREAD

**Issue by alanmcruickshank** [sqlfluff/sqlfluff#946]
This issue tracks the conversation initially raised in #905 and #934 . Several rules move around sections of code, and either end up recreating sections of L003, or they disregard configuration and let L003 pick up the pieces.

My intent so far has been the latter, in the interest of keeping dependencies clean, *however* I think we need to revisit what the rules are here because it leads to a few odd cases.

As far as I see it we have a few options:
1. *The simple option*: Only L003 deals with indentation and only L039 deals with excess whitespace, other rules may also add additional functionality, but rules should assume that these rules will pick up and enforce any configuration. If we choose this option I think we should document this choice more clearly and potentially have some warnings around any configuration values which detail the implications of disabling some of these "catchall" rules.
2. *The DRY option*: Whitespace and indentation logic should be made generic and then can be called by other rules more specifically. While rules like L003 and L039 might apply that logic fairly broadly, other rules may apply exactly the same logic on specific lines or regions when reformatting code so that it remains consistent. This option results in the cleanest tests, and the least duplication. It's probably the most complex to achieve tidily, and also runs the risk of some quite subtle bugs being introduced by that underlying logic if it misbehaves in some cases.
3. *The Deluxe option*: We require that any rule which modifies positioning *also* manages it's own whitespace. This could lead to significant duplication, but does keep rules more separate and potentially keeps the whitespace logic simpler in each place that it exists. It does lead to probably some boilerplate code.

Based on conversations so far, I feel like people are leaning toward option 2? Any more viewpoints which we need to take into account on this?

@pwildenhain @barrywhart @NiallRees

**Comment by alanmcruickshank** [comment]
While I was pondering this, I had a potentially neat idea on how to implement option 2 without adding a load of extra cruft to rules which want to edit code. We could add an additional kwarg to `LintFix` called `reflow`. It defaults to `False` but if set to `True` it would reflow all the whitespace _within the segment where the fix was applied_.

We might have to deal with a few edge cases, but I think this could mostly allow rules to do things like _"insert a thing here"_ or _"swap these two items"_ and not need to worry about whitespace in doing so.

This could even simplify L003 and L039, when then only have to **detect** issues, leaving `reflow` to selectively sort out whitespace if it's found not up to scratch. Thoughts?

**Comment by pwildenhain** [comment]
`reflow` sounds neat, I'm up to see what that looks like 💪🏻 I agree that option 2 is most desirable and sustainable

**Comment by barrywhart** [comment]
I like 1 or 2. 2 is definitely better if we can figure out how to do it and do it well. I like the `reflow` idea because it appears to sidestep my biggest worry: that if lots of rules are **explicitly** doing their own formatting, even if they're using the same code, could cause conflicts or other issues when multiple rules are touching the same area of SQL.

One way to think of `reflow` is that it moves formatting from being implemented in rules to being a core behavior, which I think is a justifiable change. 👍🏽

**Comment by NiallRees** [comment]
> I like 1 or 2. 2 is definitely better if we can figure out how to do it and do it well. I like the `reflow` idea because it appears to sidestep my biggest worry: that if lots of rules are **explicitly** doing their own formatting, even if they're using the same code, could cause conflicts or other issues when multiple rules are touching the same area of SQL.
> 
> One way to think of `reflow` is that it moves formatting from being implemented in rules to being a core behavior, which I think is a justifiable change. 👍🏽

I've been wondering more about how we can avoid this interdependency issue when it comes to non-code linting (new lines, indentation).

**Comment by NiallRees** [comment]
Oops, ignore ^
