### ISSUE TITLE
[L016] Applying rule L016 threw an Exception: tuple index out of range 

### ISSUE THREAD

**Issue by upretip** [sqlfluff/sqlfluff#967]
No errors during `sqlfluff parse` only error during `lint` and `fix`
I do not have a sql script that I can share (hopefully I can create a script that i can share). However the detail is as follows:

- Had CTE (with blocks and alias)
- Long sql statements (select, where, order by, etc.)
- Sql selected one column per line

## Expected Behaviour
`L:  1 | P: 177 | L016 | Line is too long`
## Observed Behaviour
Error 

```python
CRITICAL   [L016] Applying rule L016 threw an Exception: tuple index out of range 
Traceback (most recent call last):
  File "/Users/<username>/.local/pipx/venvs/sqlfluff/lib/python3.9/site-packages/sqlfluff/core/rules/base.py", line 290, in crawl
    res = self._eval(
  File "/Users/<username>/.local/pipx/venvs/sqlfluff/lib/python3.9/site-packages/sqlfluff/core/rules/std/L016.py", line 437, in _eval
    fixes = self._eval_line_for_breaks(this_line)
  File "/Users/<username>/.local/pipx/venvs/sqlfluff/lib/python3.9/site-packages/sqlfluff/core/rules/std/L016.py", line 274, in _eval_line_for_breaks
    self.logger.info("    {0}: {1!r}".format(idx, sec))
  File "/Users/<username>/.local/pipx/venvs/sqlfluff/lib/python3.9/site-packages/sqlfluff/core/rules/std/L016.py", line 56, in __repr__
    pos=self.segments[0].get_start_pos_marker(),
IndexError: tuple index out of range
== [views/v_gre_susp.sql] FAIL
```

`L:  1 | P: 177 | L016 | Unexpected exception: tuple index out of range; Could you open an issue at https://github.com/sqlfluff/sqlfluff/issues ? You can  ignore this exception for now, by adding '--noqa: L016' at the end of line 15`
## Version
sqlfluff, version 0.5.0

## Configuration
```
No custom configuration. Running out of the box with ansi dialect
```

**Comment by barrywhart** [comment]
@upretip: I created a PR (#980) which should avoid the run-time "tuple index out of range" error. Since I don't have a way to reproduce the error you're seeing, could you please test this change and tell me what you see? It's possible this is:
* A true fix
* A change that avoids the runtime error but the resulting SQL still has "line too long" issues
* Something else

**Comment by upretip** [comment]
@barrywhart I installed your code to a fresh venv using 
`➜ pip install  git+ssh://git@github.com/barrywhart/sqlfluff.git@bhart-issue_967_L016_tuple_index_out_of_range` 

I can confirm that the error is no longer there. No more python trackback. 
`sqlfluff --version ==0.5.2`

Here is the terminal output
```
➜ sqlfluff lint v_gre_susp.sql
== [v_gre_susp.sql] FAIL
L:  12 | P:  25 | L018 | WITH clause closing bracket should be aligned with WITH
                       | keyword.
L:  23 | P: 126 | L016 | Line is too long
L:  52 | P: 126 | L016 | Line is too long
L:  53 | P: 126 | L016 | Line is too long
L:  73 | P: 118 | L016 | Line is too long
L:  97 | P: 118 | L016 | Line is too long
L:  99 | P:  70 |  PRS | Found unparsable section: '+'
L:  99 | P: 113 | L016 | Line is too long
WARNING: Parsing errors found and dialect is set to 'ansi'. Have you configured your dialect?


➜ sqlfluff fix v_gre_susp.sql 
==== finding fixable violations ====
==== no fixable linting violations found ====
  [7 unfixable linting violations found]
```

Let me know what needs to be done next.

**Comment by barrywhart** [comment]
@upretip: You can ignore my earlier question -- I hadn't seen your detailed response yet. I need to ask a maintainer to review the PR before merging it.

Thanks for the bug report and for testing this!
