### ISSUE TITLE
Join statement indent

### ISSUE THREAD

**Issue by wissamimad** [sqlfluff/sqlfluff#973]
Hello all!,i'm new to the sqlfluff and trying to make this work on my dbt code
below is sample of a left join on multiple keys and every time i run the sqlfluff fix i get a different indentation on the conditions and if put all the condition on the same line it doesn't break line on the "and" example (on cte1.cid = cte2.cid and cte1.sid = cte2.sid and cte1.customer = cte2.customer) it stays the same please help how to make indentation vertically aligned and break line on the "and" clause
![image](https://user-images.githubusercontent.com/79839344/115037353-0db42880-9ed7-11eb-9dbb-177d0ee31241.png)

**Comment by barrywhart** [comment]
Thanks for creating the issue. Could you please SQL example as a text comment here? That will make it easier for someone to reproduce the issue. Also, can you provide your `.sqlfluff` file as well?

**Comment by wissamimad** [comment]
{{
    config(
        materialized='incremental',
        dist='even'
    )
}}

    select
        cte1.cid,
        cte1.sid,
        cte1.customer

    from cte1
    left join cte2
        on cte1.cid = cte2.cid and cte1.sid = cte2.sid and cte1.customer = cte2.customer
    left join cte3
        on cte1.cid = cte3.cid and
            cte1.sid = cte3.sid and
            cte1.customer = cte3.customer


This is the SQL Example along with my .sqlfluff config below:

[sqlfluff]
verbose = 0
nocolor = False
dialect = ansi
templater = dbt
rules = None
exclude_rules = None
recurse = 0
output_line_length = 80
runaway_limit = 10
ignore_templated_areas = True
# Comma separated list of file extensions to lint.

# NB: This config will only apply in the root folder.
sql_file_exts = .sql,.sql.j2,.dml,.ddl

[sqlfluff:indentation]
indented_joins = False
template_blocks_indent = True

[sqlfluff:templater]
unwrap_wrapped_queries = True

[sqlfluff:templater:jinja]
apply_dbt_builtins = True

[sqlfluff:templater:jinja:macros]
# Macros provided as builtins for dbt projects
dbt_ref = {% macro ref(model_ref) %}{{model_ref}}{% endmacro %}
dbt_source = {% macro source(source_name, table) %}{{source_name}}_{{table}}{% endmacro %}
dbt_config = {% macro config() %}{% for k in kwargs %}{% endfor %}{% endmacro %}
dbt_var = {% macro var(variable) %}item{% endmacro %}
dbt_is_incremental = {% macro is_incremental() %}True{% endmacro %}

# Some rules can be configured directly from the config common to other rules.
[sqlfluff:rules]
tab_space_size = 4
max_line_length = 80
indent_unit = space
comma_style = trailing
allow_scalar = True
single_table_references = consistent
unquoted_identifiers_policy = all

# Some rules have their own specific config.
[sqlfluff:rules:L003]
lint_templated_tokens = True

[sqlfluff:rules:L010]  # Keywords
capitalisation_policy = consistent

[sqlfluff:rules:L014]  # Unquoted identifiers
extended_capitalisation_policy = consistent

[sqlfluff:rules:L016]
ignore_comment_lines = False

[sqlfluff:rules:L029]  # Keyword identifiers
unquoted_identifiers_policy = aliases

[sqlfluff:rules:L030]  # Function names
capitalisation_policy = consistent

[sqlfluff:rules:L038]
select_clause_trailing_comma = forbid

[sqlfluff:rules:L040]  # Null & Boolean Literals
capitalisation_policy = consistent

[sqlfluff:rules:L042]
# By default, allow subqueries in from clauses, but not join clauses.
forbid_subquery_in = join

[sqlfluff:rules:L047]  # Consistent syntax to count all rows
prefer_count_1 = False

**Comment by pwildenhain** [comment]
@wissamimad what if you being the new lines with the `and` condition? I think that's more in line with what SQLFluff expects.

If this is something that it very important to your team's sql style, might I suggest implementing [a custom rule plugin](https://docs.sqlfluff.com/en/stable/developingplugins.html)?

**Comment by tunetheweb** [comment]
@wissamimad 0.6.3 added the featured I believe you are looking for.

You will need to add this config so say you prefer your `AND`s before the newlines, rather than the default of after.

```
[sqlfluff:rules:L007]
operator_new_lines = before
```
