### ISSUE TITLE
Add rule identifier to the diff_cover output

### ISSUE THREAD

**Issue by fernandobrito** [sqlfluff/sqlfluff#975]
We just started using sqlfluff in our organization, and our first streamlined usage is through the `diff_cover` plugin, which is used to write a comment on the PR:

![image](https://user-images.githubusercontent.com/196840/115050974-997c8380-9edc-11eb-86d1-2c59fdbc3291.png)

Since we are just getting started, there will be a lot of tweaking of rules as we use it "in the wild". Something that would really help would be to have the rule identifier on the output. Is there any particular reason why this is not included?

For context, this is the PR on `sqlfluff` adding itself as a `diff_cover` plugin: https://github.com/sqlfluff/sqlfluff/pull/90.

(amazing to see that you folks were the ones adding a plugin system to `diff_cover` 🙌 )

**Comment by fernandobrito** [comment]
I guess the same question also applies to character positions (why they are not displayed).

For reference, the documentation states it clearly on https://docs.sqlfluff.com/en/latest/production.html#adding-diff-quality-to-your-builds (but doesn't give the reason)
> These messages are basically the same as those provided directly by SQLFluff, although the format is a little different. Note that diff-quality only lists the line _numbers_, not the character position. If you need the character position, you will need to run SQLFluff directly.

**Comment by barrywhart** [comment]
The reason character position is not included is that diff-quality formats the messages, not SQLFluff. I think we could include the rule identifier in the error string -- that seems like a good idea. I'll work on this.

**Comment by fernandobrito** [comment]
That was a quick response and action. Thanks a lot!

**Comment by barrywhart** [comment]
@fernandobrito: No problem! It's a quiet Saturday waiting for my kid to finish an online competition. 🙏🏽
