### ISSUE TITLE
More robust parsing API

### ISSUE THREAD

**Issue by dclong** [sqlfluff/sqlfluff#984]
`sqlfluff.parse` throws exceptions when it encounters unparsable sections. This makes it inconvenient for users to call `sqlfluff.parse`. Is it possible to add an option to suppress exceptions and return whatever sqlfluff can parse and with the sections that it cannot understand? The command API is such an example but I'm looking for an analogue Python API.

**Comment by adam-tokarski** [comment]
@dclong are you able to provide a minimal reproducible example for that? It would allow to be on the same page for all of us. 
* please provide example of statement which throws an exception
* do you have any idea how it should look like - especially that "_the sections that it cannot understand_"?

**Comment by jpy-git** [comment]
@tunetheweb given that the API has been switched to JSON output now I think this can be closed?

**Comment by tunetheweb** [comment]
Well either way we've got no feedback so happy to close.
