### ISSUE TITLE
Failing to parse BigQuery array literals

### ISSUE THREAD

**Issue by defonzie** [sqlfluff/sqlfluff#989]
## Expected Behaviour

No parsing errors for `SELECT [] AS foo` with BigQuery dialect. Should also support an explicit type like `SELECT ARRAY<string>[] AS foo`.

## Observed Behaviour

`Found unparsable section: '[] AS foo'`

## Steps to Reproduce

http://sqlfluff-online.herokuapp.com/fluffed?sql=H4sIAH95gmAC_wt29XF1DlGIjlVwDFZIy88HANgBUWYQAAAA&dialect=bigquery

## Version
0.5.2

## Configuration
```
dialect = bigquery
```

**Comment by barrywhart** [comment]
I'll try and look at this one soon. It may interact with issue #991 and the proposed fix, #997.

**Comment by barrywhart** [comment]
When we address this issue, I suggest the following extended test case, which tests both string and numeric array types and literal values inside the square brackets.

```
SELECT
    ['a'] AS strcol1,
    ARRAY<string>['b'] AS strcol2,
    [1.0] AS numcol1,
    ARRAY<NUMERIC>[1.4] AS numcol1
```

**Comment by barrywhart** [comment]
Interestingly, this works already, so part of the issue may be that **empty** array literals are not supported:
```
SELECT [1.0]
```
