### ISSUE TITLE
Failing to parse number literals with exponent

### ISSUE THREAD

**Issue by defonzie** [sqlfluff/sqlfluff#990]
## Expected Behaviour

No parsing errors for `SELECT 1e-9 AS foo` with BigQuery dialect. `1e-9` should be parsed as a number literal.

## Observed Behaviour

`Found unparsable section: '-9 AS foo'`

## Steps to Reproduce

http://sqlfluff-online.herokuapp.com/fluffed?sql=H4sIAG97gmAC_wt29XF1DlEwTNW1VHAMVkjLz-flAgDfCwtlFAAAAA%3D%3D&dialect=bigquery

## Version
0.5.2

## Configuration
```
dialect = bigquery
```

**Comment by barrywhart** [comment]
Other dialects probably need this as well, so let's fix this in the ANSI dialect if there are no objections.
* Snowflake [docs](https://docs.snowflake.com/en/sql-reference/data-types-numeric.html#numeric-constants) on floating-point literals and exponents
* Postgres docs [here](https://www.postgresql.org/docs/10/sql-syntax-lexical.html#SQL-SYNTAX-CONSTANTS) (see section 4.1.2.6, "Numeric Constants")
